### ISSUE TITLE
Prisma2 + next.js + now

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#1170] opened 2019-12-17 15:25 UTC
Prisma 2 within a next.js project deployed on now fails with `EROFS` (see error)

![image](https://user-images.githubusercontent.com/746482/71008932-bedf5e80-20e9-11ea-9f6a-f605e7afd62e.png)

Reproduction: https://github.com/divyendu-test/p2-1170

To reproduce (https://github.com/divyendu-test/p2-1170), 

1. add `PG_URL` to your now secrets. 
2. `now`
3. open the deployed URL (date section won't load)
4. see logs in zeit console

**Comment by timsuchanek** [comment] 2019-12-18 17:26
I added a minimal reproduction here: https://github.com/timsuchanek/p2-1170

**Comment by medelman17** [comment] 2019-12-27 15:45
I just ran into the above, too. 

Interestingly, moving the photon-depedendent graphql lambda from within Next (i.e., `pages/api/graphql.ts`) to outside Next (e.g., `api/graphql.ts`) solves it without further configuration.

**Comment by medelman17** [comment] 2019-12-27 23:28
Here's a new twist... 

If I separate the Next app and Prisma-related code into separate packages/yarn-workspaces... it also works like a charm (i.e., without having to use the standalone `api` directory outside of `pages`). 

Deployment: https://fonts-edelman215.fabulas.now.sh/
Repo: https://github.com/medelman17/typography-data

**Comment by shrugs** [comment] 2020-01-11 17:24
for clarity, since this took me a while to figure out: the workaround is to use the `now`-specific `/api` routes instead of the next.js `pages/api` routes

**Comment by yuyao17** [comment] 2020-01-12 02:43
Hi @shrugs , I've bumped into this problem as well, can you elaborate on your solution a bit more?

**Comment by shrugs** [comment] 2020-01-12 03:03
@yuyao17 sure!

it seems like the problem stems from how next.js is handling executables like photon. the attached issue and reproducible example have more info but the gist is that the `//pages/api` files are bundled by next.js, which is then handled by the `now` next.js builder.

a workaround is to, instead of letting next.js bundle the serverless functions, use `now`'s automatic handling of `//api` routes to bundle and deploy your functions for you. in my simple project, moving my serverless function from `//pages/api/test.ts` to `//api/test.ts` solved the problem. `now` also happens to deploy api routes at the same path, so they're available at `deploymenturl.example.com/api/test` as before

**Comment by asciant** [comment] 2020-01-12 06:46
@shrugs does this fix use `now-node` instead of `now-next`? 

I assume it would? Which may mean that the files contained within the `/api` directory (previously `/pages/api`) won't be pre-compiled with babel (for us JS users, not sure how TS works in this case)?

**Comment by shrugs** [comment] 2020-01-12 14:10
@asciant not sure what builder is being used for those functions - i'm currently configuration-less - though things seem to work out of the box. but it's certainly a different builder than the primary next.js builder. 

https://zeit.co/docs/v2/serverless-functions/introduction has more info, plus a link to next+now specific details

**Comment by timsuchanek** [comment] 2020-01-14 13:53
This is the tracking issue on the now side: https://github.com/zeit/now/issues/3503

**Comment by timsuchanek** [comment] 2020-01-30 14:31
This has been fixed on the Zeit side. In case this doesn't work for you yet, please let us know!

**Closed** 2020-01-30 14:31 UTC
Labels: bug/2-confirmed, kind/bug, topic: deployment-platforms, topic: framework
