### ISSUE TITLE
`Upsert` causes random self-referencing 1:1 relations to break

### ISSUE THREAD

**Issue by m-rots** [prisma/prisma2#622] opened 2019-09-27 16:10 UTC
Reproduction: https://github.com/m-rots/prisma2-upsert-bug-reproduction

Updating an existing entity with the `upsert` operation causes other, random entities to break their relation. I've provided a minimal reproduction which shows this unexpected behaviour.

I am trying to create a tree-like file structure within a SQLite database, and updating random files within this database caused other files and folders to lose their parent-connection.

Prisma model:
```
model File {
  id        String  @default(cuid()) @id @unique
  folder    Boolean
  name      String
  parent    File?   @relation(onDelete: CASCADE)
}
```
I am aware that CASCADE behaviour has not been implemented yet, and this reproduction produces the same results with and without specifying onDelete behaviour.

System used: Darwin, MacOS 10.15
Node version: 12.9.0
Prisma version: 2.0.0-preview-12, 2.0.0-preview-13

**Comment by divyenduz** [comment] 2019-10-01 08:53
I am able to reproduce, thanks for the detailed reproduction.

**Comment by divyenduz** [comment] 2019-10-11 08:38
Internal note: Re-test it after query engine rewrite work, on Divy's plate to raise again.

**Comment by divyenduz** [comment] 2020-01-10 14:23
The original reproduction is still reproducible with preview 19

**Comment by tomhoule** [comment] 2020-01-30 14:29
Status update: there are big changes ongoing in the query engine. I haven't worked on this.

**Comment by tomhoule** [comment] 2020-02-11 11:08
I updated the repro example to the latest release (alpha 756) and this seems to be fixed, so I'll close the issue. Feel free to reopen if you manage to reproduce the bug with an up-to-date version of prisma2 :)

**Closed by tomhoule** 2020-02-11 11:08 UTC
Labels: bug/1-repro-available, kind/bug
