### ISSUE TITLE
Error running lift up for the first time with sqlite

### ISSUE THREAD

**Issue by zigomir** [prisma/prisma2#256] opened 2019-07-27 19:22 UTC
Version: `prisma2@2.0.0-preview-3, binary version: 5f361e08f59d0d21e5510e6c3e65cc8052dca4f7`

I get

```
Error: Error in lift engine for rpc migrationProgress:
  thread 'main' panicked at 'Could not load migration from database. Migration name was: 20190727151522-init', src/libcore/option.rs:1034:5
```

when running `prisma2 lift up`

Although `dev.db` now has (`Post`, `User` and `_Migration`) tables.

If I then re-run `prisma2 lift up` – probably a separate issue – I get

```
thread 'main' panicked at 'The model User already exists in this Datamodel. It is not possible to create it once more.', migration-engine/core/src/migration/datamodel_calculator.rs:59:9
stack backtrace:
```

Looks like `lift` is not picking up latest migration version from `_Migration` table (although there's a record in it) correctly.

**Comment by timsuchanek** [comment] 2019-07-29 12:59
Duplicate of https://github.com/prisma/lift/issues/74

**Closed** 2019-07-29 15:36 UTC
Labels: bug/2-confirmed, release/preview4
