### ISSUE TITLE
Multiple data sources on a single data model? (stripe + db)

### ISSUE THREAD

**Issue by FrankSandqvist** [prisma/prisma2#106] opened 2019-07-06 15:41 UTC
Will it be possible in Prisma 2 to have multiple data sources on a single data model?

Given a user object with both MySQL & Stripe data sources;
(this is obviously pseudocode)

```
model User (data-source MySQL) {
  firstName: String!
  lastName: String!
  email: String!
  stripeCustomer: StripeCustomer!
}

model StripeCustomer (data-source Stripe) {
  id: String!
  email: String!
  billingAddress: StripeBillingAddress!
  source: StripeSource!
  etc. etc.
}
```

**Comment by FrankSandqvist** [comment] 2019-07-06 15:44
I suppose Stripe is a bit of a weird example, since the data model for that is already defined. Somehow an ability to import pre-made data models of Stripe into Prisma?

**Comment by 2color** [comment] 2020-02-06 15:21
Currently, we don't support multiple data sources in a single Prisma schema.

We originally designed the schema to support multiple data sources. But the scope of this feature is very vast and it will take us quite some time to support this.

We are focusing on the stability of the current feature set right now.

Closing this as a duplicate of #265

**Closed by 2color** 2020-02-06 15:21 UTC
Labels: kind/feature, topic: multiple datasources

**Comment by oussamabouchareb** [comment] 2020-04-29 23:35
if we can't use multiple data sources on the same schema then how can you work around doing this? multiple schemas each with its own data source?
