### ISSUE TITLE
Prisma init is not connecting mysql 8 database 

### ISSUE THREAD

**Issue by shoaibsharif** [prisma/prisma2#497] opened 2019-09-05 03:27 UTC
I was trying to connect my exist mysql database using prisma init but it is not working
![prisma2](https://user-images.githubusercontent.com/29075110/64309836-bc9a2f80-cf52-11e9-943a-4464824eeee7.gif)

The error I get:
```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `Step4SelectDatabase`. See https://fb.me/react-warning-keys for more information.
    in Unknown (created by Step4SelectDatabase)
    in Step4SelectDatabase
    in Unknown
    in Unknown
    in TabIndexProvider
    in div (created by Box)
    in Box
    in App
The above error occurred in one of your React components:
    in Unknown (created by Step4SelectDatabase)
    in div (created by Box)
    in Box (created by BorderBox)
    in div (created by Box)
    in Box (created by BorderBox)
    in BorderBox (created by Step4SelectDatabase)
    in div (created by Box)
    in Box (created by Step4SelectDatabase)
    in Step4SelectDatabase
    in Unknown
    in Unknown
    in TabIndexProvider
    in div (created by Box)
    in Box
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, App.
Warning: App: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.
The above error occurred in one of your React components:
    in Unknown (created by Step4SelectDatabase)
    in div (created by Box)
    in Box (created by BorderBox)
    in div (created by Box)
    in Box (created by BorderBox)
    in BorderBox (created by Step4SelectDatabase)
    in div (created by Box)
    in Box (created by Step4SelectDatabase)
    in Step4SelectDatabase
    in Unknown
    in Unknown
    in TabIndexProvider
    in div (created by Box)
    in Box
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, App.
Warning: App: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.
The above error occurred in one of your React components:
    in Unknown (created by Step4SelectDatabase)
    in div (created by Box)
    in Box (created by BorderBox)
    in div (created by Box)
    in Box (created by BorderBox)
    in BorderBox (created by Step4SelectDatabase)
    in div (created by Box)
    in Box (created by Step4SelectDatabase)
    in Step4SelectDatabase
    in Unknown
    in Unknown
    in TabIndexProvider
    in div (created by Box)
    in Box
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, App.
Warning: App: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.
The above error occurred in one of your React components:
    in Unknown (created by Step4SelectDatabase)
    in div (created by Box)
    in Box (created by BorderBox)
    in div (created by Box)
    in Box (created by BorderBox)
    in BorderBox (created by Step4SelectDatabase)
    in div (created by Box)
    in Box (created by Step4SelectDatabase)
    in Step4SelectDatabase
    in Unknown
    in Unknown
    in TabIndexProvider
    in div (created by Box)
    in Box
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, App.
Warning: App: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.
(node:951) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by pantharshit00** [comment] 2019-09-05 09:36
Thanks for reporting this @shoaibsharif. But this issue is a duplicate of https://github.com/prisma/prisma2/issues/46, please comment on that issue so that we can have discussion on a single place 🙂

**Closed** 2019-09-05 09:36 UTC
