### ISSUE TITLE
can't run init- error with <TabIndexProvider>

### ISSUE THREAD

**Issue by nboltn** [prisma/prisma2#1207] opened 2019-12-22 00:15 UTC
As the title says, I can't get past `prisma2 init`.

```
$ prisma2 init psd
The above error occurred in the <TabIndexProvider> component:
    in TabIndexProvider
    in div (created by Box)
    in Box
    in Unknown
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, App.
```

Any ideas?

**Comment by janpio** [comment] 2019-12-22 00:16
What OS?
What command line?
What Prisma version? (`prisma2 -v`)

**Comment by nboltn** [comment] 2019-12-23 23:37
I got it working using a different terminal emulator. I was running `prisma2@2.0.0-preview019` under windows using the mingw terminal.

**Comment by janpio** [comment] 2019-12-26 00:33
Thanks @nbolt, then it seems mingw terminal is also a non interactive terminal, which makes this a duplicate of https://github.com/prisma/prisma2/issues/554

I will close this issue now, implementation of non interactive versions of these commands will be tracked in https://github.com/prisma/prisma2/issues/554.

**Closed by janpio** 2019-12-26 00:33 UTC
Labels: topic: cli-init
