### ISSUE TITLE
Subselect with UUID key

### ISSUE THREAD

**Issue by kroleek** [prisma/prisma2#1506] opened 2020-02-01 22:10 UTC
I found strange bug when using UUID as primary key.

- postgres "11.5 (Debian 11.5-1.pgdg90+1)"
- @prisma/client "2.0.0-preview021"
- prisma2 "2.0.0-preview021"

My schema
```
model TravelInsurancePerson {
  id String @id @default(uuid())

  name String
}

model TravelInsurance {
  id         String @id @default(uuid())
  externalId Int    @unique

  persons TravelInsurancePerson[]

}
```
(I use Prisma to create DB)

I create data first and then try to get data back from DB with findOne API.
```
  const get = await prismaClient.travelInsurance.findOne({
    where: { id },
    select: {
      id: true,
      persons: {
        select: {
          id: true
        }
      }
    }
  });
```
(Note that data are correctly stored in DB.)

Selecting related data (Persons) somehow depends on data in id column in main table (TravelInsurance). 
- when it's used UUID string as id then persons return empty array
- if I use some simple string (like '1234') it returns valid related data

You can try it in my test repo https://github.com/kroleek/prisma_test1 (just run `yarn` and `yarn test`)

**Comment by johnsjulander** [comment] 2020-02-02 08:12
Also have this issue. Tests failing after have updated and migrated from preview017 to preview021. Not getting data joined from foreign tables when using include, even though foreign key is present in main table and data present in foreign table.

**Comment by malekjaroslav** [comment] 2020-02-03 09:35
The same issue with uuid

**Comment by pantharshit00** [comment] 2020-02-03 11:21
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma-client-js/issues/434

**Closed by pantharshit00** 2020-02-03 11:21 UTC
