### ISSUE TITLE
Instrospection does not use indexes to find @unique fields

### ISSUE THREAD

**Issue by Errorname** [prisma/prisma2#1032] opened 2019-11-29 10:50 UTC
To reproduce:
1. `prisma2 init test` and choose `postgresql`
2. `prisma2 dev` to create the tables in the database
3. User has a @unique field on email
4. `prisma2 init test2`, choose `postgresql` and choose the created database/schema for introspection
5. Observe that the @unique is not present in the introspected schema

**Comment by divyenduz** [comment] 2019-12-02 15:24
Thank you for raising this. 

Internal note: This is the result produced by the new introspection engine, the unique issue is fixed, we need to address this `@default("")` directive from a product perspective. 

![image](https://user-images.githubusercontent.com/746482/69971386-198c8e00-1520-11ea-8246-e3f5444d7f42.png)

**Comment by divyenduz** [comment] 2020-01-09 14:29
@Errorname We [rewrote introspection](https://github.com/prisma/prisma2/releases) recently. Can you please see if this issue still exists in the latest alpha or preview?

**Comment by pantharshit00** [comment] 2020-01-11 15:46
Unable to reproduce this now, schema is correct now. I used version `prisma2@2.0.0-alpha.520, binary version: 89e9a32e88c127726a79da89b638c4bab2840095`

Closing, comment here if you can still reproduce this.

**Closed by pantharshit00** 2020-01-11 15:46 UTC
Labels: bug/2-confirmed, kind/bug, topic: old-introspection
