### ISSUE TITLE
Failed to delete many to many on SQLite

### ISSUE THREAD

**Issue by tristancaron** [prisma/prisma2#138] opened 2019-07-10 15:16 UTC
Getting this error:
```
ConnectorError(QueryError(SqliteFailure(Error { code: ConstraintViolation, extended_code: 787 }, Some("FOREIGN KEY constraint failed"))
```

When having this scenario
```
model Course {
  id @id
  name String

  students Student[]
}

model Student {
  id @id 
  name String

  courses Course[]
}
```

```js

const student = await photon.students.create({
  data: {
    name: "Toto",
  }
})
// Later
const course = await photon.courses.create({
  data: {
    name: "Photon",
    students: {
        connect: [{ connect: {id: student.id} }]
    }
  }
})
// Later
const course = await photon.courses.delete({
  where: {
    id: course.id
  }
})
```

I expect it to remove the relationship.

**Comment by pantharshit00** [comment] 2019-07-18 13:58
Closing as a duplicate of https://github.com/prisma/prisma2/issues/166

**Closed by pantharshit00** 2019-07-18 13:58 UTC
