### ISSUE TITLE
prisma2 migrate save --experimental throws Error in migration engine.

### ISSUE THREAD

**Issue by tmhrbr** [prisma/prisma2#1485] opened 2020-01-30 13:35 UTC
>  ERROR  Oops, an unexpected error occured!
Error in migration engine.

> report id 1542.

prisma.schema
```
datasource postgresql {
  provider = "postgresql"
  url      = env("DB_ENDPOINT")
}

generator client {
  provider = "prisma-client-js"
}

model User {
    id String @id @default(cuid())
    name String?
    email String @unique
    password String
    createdAt DateTime @default(now())
    updatedAt DateTime @updatedAt
}

model List {
    id String @id @default(cuid())
    user User
    name String
    items ListItem[]
    createdAt DateTime @default(now())
    updatedAt DateTime @updatedAt
}

model ListItem {
    id Int @id
    user User
    name String
    done Boolean @default(false)
}
```

**Comment by pantharshit00** [comment] 2020-01-30 13:49
@tmhrbr 

I am unable to reproduce this. I was able to deploy this schema successfully. 

Can you please tell if this is the initial schema, or you added any additional field which caused this issue?

**Comment by tmhrbr** [comment] 2020-01-30 13:53
I was using `2.0.0-preview019` version with lift and it worked fine. If I run `prisma2 introspect` on my DB with similar schema and then try to save migration with this generated schema, it will crash as well.

**Comment by tmhrbr** [comment] 2020-01-30 15:36
Solved. I tried different versions and on version `prisma2@2.0.0-preview015` I got a meaningful error: 

> Error: There are more migrations in the database than locally. This must not happen. 

So after resetting my database I was able to migrate succesfuly.

**Comment by pantharshit00** [comment] 2020-01-30 15:54
I am going to close this then. Feel free to comment if you are facing any more trouble.

**Closed by pantharshit00** 2020-01-30 15:54 UTC
Labels: bug/0-needs-info, kind/bug
