### ISSUE TITLE
Telemetry prompt options don't work on Windows (cursor keys do nothing)

### ISSUE THREAD

**Issue by jferrettiboke** [prisma/prisma2#617] opened 2019-09-27 13:35 UTC
Telemetry prompt options don't work on Windows after using `prisma2 dev`. Windows users are not able to continue working due to this bug.

All I can see is this static message:

```
 ERROR  Oops, an unexpected error occured!
Please help us improve Prisma 2 by submitting an error report.
Error reports never contain personal or other sensitive information.
Learn more: https://pris.ly/d/telemetry.md

    Yes            Send error report once
    No             Don't send error report
```

P.S. The "Learn more" link doesn't work.

---

- Windows 10
- Node.js: `v10.15.3`
- `nexus`: `0.12.0-beta.9`
- `nexus-prisma`: `0.4.2`
- `prisma2`: `2.0.0-preview-13`

**Comment by divyenduz** [comment] 2019-09-27 16:35
@jferrettiboke Can you not move back and forth between the yes and no options using the up/down key? 

Also, which terminal are you using on windows?

**Comment by janpio** [comment] 2019-09-27 16:47
Any way to force a crash/error?

**Comment by jferrettiboke** [comment] 2019-09-28 00:29
>Can you not move back and forth between the yes and no options using the up/down key?

@divyenduz Exactly. I am not able to select an option. It looks like a static message.

>Also, which terminal are you using on windows?

I am using Bash from VSC. I just checked Command Prompt (default terminal in Windows), and it doesn't work either.

>Any way to force a crash/error?

@janpio I can't do anything. Just `Ctrl + c` to exit.

**Comment by janpio** [comment] 2019-09-28 08:40
Ha, I was asking if there is a simple way to _reproduce_ the behavior of getting an error that triggers the telemetry prompt - so I can confirm this bug maybe.

**Comment by divyenduz** [comment] 2019-09-28 14:53
@janpio Delete your binaries maybe or do `echo "" > <binary path>` to make it invalid! And try do run lift commands then!

**Comment by janpio** [comment] 2019-09-28 15:31
Unfortunately not @divyenduz: Removing the migration engine binary in the global `prisma2`'s `node_modules` folder gave me a different error: https://github.com/prisma/prisma2/issues/629#issue-499785281, as did replacing the migration binary content with an empty string: https://github.com/prisma/prisma2/issues/629#issuecomment-536199210

**Comment by janpio** [comment] 2019-09-30 09:19
I can confirm the behavior on Windows in all consoles I tested (Cmder, cmd.exe, PowerShell):

- Create project with `prisma2 init foo`: `Blank project > SQLite > Confirm > Javascript > Demo script`
- Open `prisma/schema.prisma` and replace `provider = "sqlite"` with `provider = "postgres"`
- Run `prisma2 dev`

Gives you the reported static message with no way to select Yes or No.

Additional observations: While one window (console) was in that state, `prisma2 dev` could not be started in another window - it just did nothing until I killed the first unresponsive process.

**Comment by janpio** [comment] 2019-09-30 10:02
(I just promoted this issue to be worked on in the _current_ sprint. There will be a hotfix before that happens though, that will at least output the error message so you can copy/paste that into GitHub issues or google for it - then the only "problem" of not being able to select Yes/No is not that bad any more.)

**Comment by janpio** [comment] 2019-09-30 11:51
(`preview-13.1` was released and outputs the stacktrace again - so you can learn about the error now. The "can not select Yes/No" problem will be fixed during this sprint.)

**Comment by timsuchanek** [comment] 2019-10-18 08:44
Fixed in latest alpha.
You can try it out with `npm i -g prisma2@alpha`.

**Closed by timsuchanek** 2019-10-18 08:44 UTC
Labels: bug/2-confirmed, kind/bug

**Comment by janpio** [comment] 2019-10-18 11:43
Can still reproduce the problem with `prisma2@2.0.0-alpha.254, binary version: 332b3baf392a718cffaccff674ebea649d05fcbd` in Cmder (which uses `cmd.exe` under the hood). It seems to work in `cmd.exe` directly or Powershell though, which is super strange. Any idea why this might be the case?

**Comment by pantharshit00** [comment] 2019-10-18 13:04
Cmder uses [Conemu](https://conemu.github.io/) under the hood. That might be the cause of this.

**Comment by janpio** [comment] 2019-10-18 15:52
(Just noticed that box around the prompt is also missing in Cmder, which is now there in Powershell and cmd.exe)

I will create a follow up issue as the main command lines now work.
