### ISSUE TITLE
@@unique with @relation

### ISSUE THREAD

**Issue by vitaliytv** [prisma/prisma2#1257] opened 2019-12-31 06:16 UTC
When i use @@unique with @relation field, i get error. 

Example:
```
model Staff {
  id        Int           @id @default(autoincrement())
  staffId   Int       
  monthId     WorktimeMonth @relation(references: [id]) @map("month_id")

  @@unique([monthId, staffId], name: "month_staff")
}
```

Error:
```
$ prisma2 generate 
Error: Schema parsing
thread 'main' panicked at 'Unable to resolve scalar field 'monthId'', src/libcore/option.rs:1190:5
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::continue_panic_fmt
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::option::expect_failed
  10: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  11: prisma_models::index::IndexTemplate::build
  12: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  13: prisma_models::model::ModelTemplate::build
  14: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  15: prisma_models::internal_data_model::InternalDataModelTemplate::build
  16: prisma::cli::CliCommand::execute
  17: <std::future::GenFuture<T> as core::future::future::Future>::poll
  18: tokio::runtime::enter::Enter::block_on
  19: std::thread::local::LocalKey<T>::with
  20: std::thread::local::LocalKey<T>::with
  21: tokio::runtime::spawner::Spawner::enter
  22: tokio::runtime::time::variant::with_default
  23: std::thread::local::LocalKey<T>::with
  24: prisma::main
  25: std::rt::lang_start::{{closure}}
  26: std::panicking::try::do_call
  27: __rust_maybe_catch_panic
  28: std::rt::lang_start_internal
  29: main

```

**Comment by pantharshit00** [comment] 2020-01-06 10:04
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of #1177

**Closed by pantharshit00** 2020-01-06 10:04 UTC
