### ISSUE TITLE
CLI output for `generate` when generator is not defined still says I can use Prisma Client in my code now

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2#1723] opened 2020-02-28 08:31 UTC
I have this Prisma schema (without a `generator`):

```prisma
datasource sqlite {
  provider = "sqlite"
  url      = "file:./dev.db"
}

model User {
  id   Int    @id @default(autoincrement())
  name String
  emai String @unique
}
```

Now I run `prisma2 generate`:

~~~
$ yarn prisma2 generate
yarn run v1.22.0
$ /Users/nikolasburk/Desktop/types/node_modules/.bin/prisma2 generate

info You don't have defined any generator in your schema.prisma, so nothing will be generated.
You can define them like this:

generator client {
  provider = "prisma-client-js"
}

You can now start using Prisma Client in your code:

```
import { PrismaClient } from '@prisma/client'
// or const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient()
```      

Explore the full API: http://pris.ly/d/client

✨  Done in 1.03s.
~~~

After the note that I don't have a `generator` defined I see the code snippet that explains how to import and instantiate Prisma Client which shouldn't be there.

**Comment by pantharshit00** [comment] 2020-02-28 09:39
Closing as a duplicate of https://github.com/prisma/prisma2/issues/1643

**Closed by pantharshit00** 2020-02-28 09:39 UTC
