### ISSUE TITLE
Prisma-client returns null

### ISSUE THREAD

**Issue by pallemach2** [prisma/prisma2#1579] opened 2020-02-11 23:58 UTC
Hey, first, here is a part of my schema:

````
model Lobby {
  id         String    @default(uuid()) @id
  maxPlayers Int
  name       String    @unique
  password   String?
  started    Int
  cardpack   Cardpack
  gamestate  Gamestate
  members    User[]
}

model User {
  id       String     @default(uuid()) @id
  nickname String     @unique
  lobby    Lobby?
  cards    Usercard[]
}
````

And here is a code-snippet where i try to create a lobby:

```
await prisma.lobby.create({
    data: {
      cardpack: { connect: { id: cardpack.id } },
      maxPlayers: 5,
      name: "TestLobby",
      started: 0,
      members: { connect: { id: member.id } },
      gamestate: {
        create: {
          state: "test_state",
          zar: {
            connect: {
              id: zar.id
            }
          },
          zarcard: {
            connect: {
              id: zarcard.id
            }
          }
        }
      }
    }
  });
```

My problem is, that even if i connect the "member" to the "members"-field in lobby, the "members"-field is empty/an empty array when i search for the lobby with prisma:

```
  let lobbies = await prisma.lobby.findMany({
    select: { id: true, members: true, name: true }
  });
```

And the lobby-field in the user is also null, but when i look in the database, the right lobby-id is saved in the lobby-field of the user. But why does Prisma return null then?

**Comment by pantharshit00** [comment] 2020-02-13 13:52
I think this is a duplicate of https://github.com/prisma/prisma-client-js/issues/434 which is related to uuids. 

It was fixed in the recent alpha. So can you please install the alpha version `npm install -g prisma2@alpha && prisma2 generate` and try this again.

Closing as a duplicate of https://github.com/prisma/prisma-client-js/issues/434

**Closed by pantharshit00** 2020-02-13 13:52 UTC
