### ISSUE TITLE
Error: Error in lift engine:

### ISSUE THREAD

**Issue by heavenkiller2018** [prisma/prisma2#119] opened 2019-07-03 07:57 UTC
https://nexus.js.org/docs/database-access-with-prisma-v2

i followed the instruction, but error appeared when the step "prisma2 lift save --name="init"":

**$ prisma2 lift save --name="init"**

[migration-engine] error: Error: spawn C:\Users\Administrator\AppData\Roaming\npm\node_modules\prisma2\migration-engine ENOENT
Error: Error in lift engine:

what's the problem?

**Comment by pantharshit00** [comment] 2019-07-09 16:37
Windows is currently isn't supported.

Closing as a duplicate of https://github.com/prisma/prisma2/issues/4

**Comment by greguintow** [comment] 2019-07-10 01:50
Is giving the same error in Linux, my operating system is Ubuntu 18.04

**Comment by pantharshit00** [comment] 2019-07-10 09:44
@greguintow  Can you please provide me with the output of `uname -a`?

**Comment by goof03** [comment] 2019-07-10 10:08
Do you have try npm install in your prisma project ? Solve for me on archlinux
But all my lift command are very slow :
rocket Done with 1 migration in 661.14s.

Sorry for the closed bug :-(

**Comment by xiaoyu-tamu** [comment] 2019-07-11 19:26
Same here, 


Lift just created your migration 20190711142305-init in

~/Workspaces/project-name master* **5m 13s**

**Comment by xiaoyu-tamu** [comment] 2019-07-11 22:46
it only happens in postgresql ( maybe mysql ). it's really fast if I switch to sqlite.

**Comment by tvvignesh** [comment] 2019-07-14 18:46
@pantharshit00 I am facing the same error too in Ubuntu 19.04 with Postgres. Screenshot below.

![Screenshot from 2019-07-15 00-11-40](https://user-images.githubusercontent.com/1165845/61187904-42a5a280-a695-11e9-8691-8807d60568ed.png)

After this error, I even tried creating an empty database and schema in Postgres, still does not work.

Also, this is my distribution details:
```
Linux vignesh-desktop 5.0.0-21-generic #22-Ubuntu SMP Tue Jul 2 13:27:33 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
Any idea how to solve this?

**Comment by cassv24** [comment] 2019-07-14 22:27
Same issue here 🐧:

![Screenshot from 2019-07-14 18-24-41](https://user-images.githubusercontent.com/23457150/61190106-de6aea80-a664-11e9-9064-acf01826da76.png)

`Linux worlds 5.0.0-20-generic #21-Ubuntu SMP Mon Jun 24 09:32:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by pantharshit00** [comment] 2019-07-15 15:33
I was unable to reproduce this. 

![image](https://user-images.githubusercontent.com/22195362/61228469-f8c7c580-a743-11e9-96aa-b457b22db6e6.png)


I think in all of the above cases the binary is not downloaded because of npm not allowing binary installation without a flag in a root location.

Can you please try install prisma2 again with the following command and trying this again:

```sh
npm install -g --unsafe-perm prisma2
```

**Comment by tvvignesh** [comment] 2019-07-16 16:11
@pantharshit00 Yup! When I try with --unsafe-perm it works properly for postgres. Thanks. But, is this the long term solution as well?

**Comment by pantharshit00** [comment] 2019-07-16 16:42
Yes, this is how npm is designed. If you need to install prisma2 globally, you will need to use that flag on linux.

This is one time only though(only at installation).

**Comment by cassv24** [comment] 2019-07-21 21:48
Ok, now it's giving me the fallowing error with  `prisma2 lift save --name 'init'` (🐧Ubuntu 19.04)

```
server-v2 ±|master ✗|→ prisma2 lift save --name 'init'
Error: Error in lift engine for rpc listMigrations:
  thread 'main' panicked at 'loading the connector failed.: DataModelErrors { code: 1001, errors: ["Field declarations don\'t require a `:`.", "Field declarations don\'t require a `:`.", "Field declarations don\'t require a `:`."] }', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
   9: migration_core::migration_engine::MigrationEngine::init
  10: <F as jsonrpc_core::calls::RpcMethodSimple>::call
  11: <F as jsonrpc_core::calls::RpcMethod<T>>::call
  12: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
  13: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  14: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  15: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  16: futures::task_impl::std::set
  17: std::thread::local::LocalKey<T>::with
  18: futures::future::Future::wait
  19: jsonrpc_core::io::IoHandler<M>::handle_request_sync
  20: migration_core::rpc_api::RpcApi::handle
  21: migration_engine::main
  22: std::rt::lang_start::{{closure}}
  23: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  24: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  25: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  26: main
  27: __libc_start_main
  28: _start
```

**Comment by pantharshit00** [comment] 2019-07-25 11:01
@cassv24 

From the error it looks like you are using a wrong syntax for the datamodel.
Can you please share your datamodel?

**Comment by timsuchanek** [comment] 2019-07-29 12:50
As the problem described in https://github.com/prisma/prisma2/issues/119#issuecomment-513590348 is unrelated to the original issue, we close this for now.
@cassv24 please open a separate issue for the datamodel parsing error you described.

**Closed by timsuchanek** 2019-07-29 12:50 UTC
Labels: bug/0-needs-info, kind/bug
