### ISSUE TITLE
Which folders should go in .gitignore?

### ISSUE THREAD

**Issue by kitze** [prisma/prisma2#607] opened 2019-09-26 10:09 UTC
It's a bit confusing:
- `generated` (no idea how this one got generated)
-  `prisma/migrations` (I'm assuming it shouldn't be ignored)
- `src/schema.graphql` (it's generated by nexus, but it's not going in `generated` or `prisma` for some reason)
- `@node_modules/@generated` (which is ignored by default) 

Can anyone please clarify?

**Comment by jasonkuhrt** [comment] 2019-09-27 00:53
Hey @kitze 

> generated (no idea how this one got generated)

Not sure what this one is, could you share more?

> prisma/migrations (I'm assuming it shouldn't be ignored)

Yeah these should be committed. Any feelings about it? 

> src/schema.graphql

Is optional and I think we should disable its being generated by default. Working on an issue that would include such a change here https://github.com/prisma-labs/nexus/pull/230.

> @node_modules/@generated

This part is working as intended. Any feelings about it?

**Comment by jasonkuhrt** [comment] 2019-09-27 00:55
> Not sure what this one is, could you share more?

I suspect this might be from nexus generation (yes, there is generation at prisma and nexus level). If so, note, and again this wip pr https://github.com/prisma-labs/nexus/pull/230 will change things so that by default the generation goes into `node_modules/@types/...` which will 1) remove a decision from the user's plate and 2) align with how prisma generates things and 3) Just Work with TypeScript system (will pick up the generated TS types).

**Comment by kitze** [comment] 2019-09-27 06:10
Thanks @jasonkuhrt. If the `generated` folder goes in `@types` that will be less confusing and one less decision to make. Also the generated `schema.graphql` file can be hidden somewhere just so it follows the rule that *all* generated files are hidden and not committed to git.

This can be closed 👍️

**Comment by jasonkuhrt** [comment] 2019-09-27 14:19
Thanks for the feedback @kitze

**Closed by jasonkuhrt** 2019-09-27 14:19 UTC
Labels: kind/discussion
