### ISSUE TITLE
[Windows] `prisma init` can't install dependencies, continues happily anyway

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#239] opened 2019-07-25 10:23 UTC
```
C:\Users\Jan>prisma2 init

 Which parts of Prisma do you want to use?

 Learn more about the tools at prisma.io/docs
 ──────────────────────────────────────────────────

>  From Scratch        Basic Prisma setup + simple script
>  GraphQL boilerplate GraphQL server example
>  REST boilerplate    REST API example (using express.js)
>  gRPC boilerplate    gRPC API example (client + server)

 ──────────────────────────────────────────────────

<  Back                (Language selection)
√ Downloading starter from https://api.github.com/repos/prisma/photonjs/tarball/master
√ Extracting content to C:\Users\Jan
× Installing dependencies 👩‍🚀

  Your template has been successfully set up!

  Here are the next steps to get you started:
    1. Run prisma2 lift save --name init to create a migration.
    2. Run prisma2 lift up to apply the migration.
    3. Run yarn seed to seed the database.
    4. Run yarn start (Runs the default script)
    5. That's it !


C:\Users\Jan>
```

Not sure if anything really broke, or if that was a false negative for "Installing dependencies".

(preview-2)

**Comment by pantharshit00** [comment] 2019-07-25 14:16
Currently, prisma2 is unable to fetch the binary for windows as we haven't released that yet. That is why it is failing at install step as npm is exiting with an exit code of 1.

I am closing this as a duplicate of #4

**Closed by pantharshit00** 2019-07-25 14:16 UTC
