### ISSUE TITLE
Blocked `prisma2 dev` process also blocks `prisma2 dev` in other terminal

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#675] opened 2019-10-07 10:17 UTC
While investigating https://github.com/prisma/prisma2/issues/641 I encountered a thing that I was told would not be possible, so I created a gif to show it:

1. Tab 1: I use `init` to create a project using MySQL and run `prisma2 dev` to show it usually works.
2. Tab 2: Then I `init` a project using SQLite, which then fails on `prisma2 dev` because of #641 
3. Tab 3: Then I `init` another project with MySQL, and this time `prisma2 dev` also hangs - probably because of the still running but broken `dev` from 2)

![blocking_processes](https://user-images.githubusercontent.com/183673/66303714-e5b83200-e8fb-11e9-915f-1d7964193d0d.gif)

**Comment by pantharshit00** [comment] 2019-10-08 11:47
I can't reproduce this anymore after #641 was fixed. Closing this for now, reopen if you can still reproduce this.

**Comment by janpio** [comment] 2019-10-08 12:56
The underlying problem still probably exists - one hanging process still will block the other one, we currently just don't have a reproduction to block a process. But as I was told this blocking would not be possible, I think this is still valid.

**Closed** 2020-02-20 20:36 UTC
Labels: bug/0-needs-info, kind/bug, topic: dev
