### ISSUE TITLE
starterkit -> javascript -> graphql + auth -> postgres -> prisma2 dev

### ISSUE THREAD

**Issue by tmfprlt1234** [prisma/prisma2#1001] opened 2019-11-27 00:45 UTC
<Anything that helps us reproduce the error goes here>

**Error dump**
Cannot destructure property `dmmf` of 'undefined' or 'null'.

**Stacktrace**
TypeError: Cannot destructure property `dmmf` of 'undefined' or 'null'.
    at connect (/usr/local/lib/node_modules/prisma2/build/photon-worker.js:44:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by janpio** [comment] 2019-11-27 10:13
Where exactly do you get this error message - in your console or Prisma Studio?

**Comment by pantharshit00** [comment] 2019-11-27 12:44
I think this might be a duplicate of https://github.com/prisma/prisma2/issues/999

**Comment by tmfprlt1234** [comment] 2019-11-27 13:57
> Where exactly do you get this error message - in your console or Prisma Studio?

i got this message in terminal and localhost:5555

**Comment by pantharshit00** [comment] 2019-11-27 14:26
Yup, this is indeed a duplicate of #999. Thanks for reporting this though.

Going to close this now

**Closed by pantharshit00** 2019-11-27 14:26 UTC
Labels: bug/0-needs-info, kind/bug
