### ISSUE TITLE
"prisma2 dev" encounters error when a model is missing an id field 

### ISSUE THREAD

**Issue by infoverload** [prisma/prisma2#500] opened 2019-09-05 16:01 UTC
I introspected an existing database schema.  When I run "prisma2 dev" against this generated model:

```
model Category {
  id                     Int                      @id
  name                   String
  postCategoriesCategory PostCategoriesCategory[]

  @@map("category")
}

model Post {
  id                     Int                      @id
  postCategoriesCategory PostCategoriesCategory[]
  text                   String
  title                  String

  @@map("post")
}

model PostCategoriesCategory {
  categoryId Category
  postId     Post

  @@map("post_categories_category")
}
```
 
I encounter this error:
`Error: QueryError(Generic("Model PostCategoriesCategory does not have an id field")`

The workaround is to manually add an id field to the PostCategoriesCategory model.

**Comment by pantharshit00** [comment] 2019-09-05 16:41
This is a known limitation as mentioned in the [limitations.md](https://github.com/prisma/prisma2/blob/master/docs/limitations.md) file, point no 6.

Closing as a duplicate of https://github.com/prisma/prisma2/issues/175

**Closed by pantharshit00** 2019-09-05 16:41 UTC
