### ISSUE TITLE
Defining db field type for model fields

### ISSUE THREAD

**Issue by mzygmunt** [prisma/prisma2#1800] opened 2020-03-10 09:45 UTC
It would be good to be able to define field type in db eg. varchar, text, longtext for Strings in the model.
In some cases, I need to store very long text in String and default type like VARCHAR (191) IMC is not enough.
Maybe a good solution would be to add the parameter @dbType (VARCHAR (x), ... TEXT, .... LONGTEXT)?

**Comment by pantharshit00** [comment] 2020-03-12 15:53
Hi @mzygmunt 


Right now you should be able to introspect an existing database that is using these types and it will be mapped to `String` or appropriate representation according to the type.

We will support native database types in the schema in the future via https://github.com/prisma/prisma2/issues/446

So I am going to close this is a duplicate of https://github.com/prisma/prisma2/issues/446

**Closed by pantharshit00** 2020-03-12 15:53 UTC
