### ISSUE TITLE
Error: Command failed with exit code 13

### ISSUE THREAD

**Issue by cstffx** [prisma/prisma2#935] opened 2019-11-13 18:58 UTC
OS: Ubuntu 16.04

Steps: 

yarn global add prisma2 

git clone https://github.com/prisma/prisma-examples.git
cd prisma-example/javascript/graphql
yarn

And get 

Error: Error: Command failed with exit code 13 (EACCES): /home/user/prisma-examples/javascript/graphql/node_modules/prisma2/query-engine-linux-glibc-libssl1.1.0 cli --dmmf
spawn /home/user/prisma-examples/javascript/graphql/node_modules/prisma2/query-engine-linux-glibc-libssl1.1.0 EACCES
error Command failed with exit code 1

**Comment by pantharshit00** [comment] 2019-11-14 13:03
I am unable to reproduce this. 


Also, I noticed something weird that you are not getting the right binary for ubuntu 16.04 that we ship. In the screenshot below, the binary for ubuntu 16.04 is named `query-engine-linux-glibc-libssl1.0.2-ubuntu1604` but your binary is named `query-engine-linux-glibc-libssl1.1.0 `

![image](https://user-images.githubusercontent.com/22195362/68859268-e8812080-070c-11ea-83e5-e0e63a658c8e.png)

Can you please paste the output of `lsb_release -a`, ` openssl version` and `uname -a` here?

**Comment by cstffx** [comment] 2019-11-14 15:02
Hi, 

>> lsb_release -a 
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

>> openssl version
OpenSSL 1.1.0h  27 Mar 2018 (Library: OpenSSL 1.1.1a  20 Nov 2018)

>> uname -a
Linux desarrollo 4.4.0-157-generic #185-Ubuntu SMP Tue Jul 23 09:17:01 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by pantharshit00** [comment] 2019-11-15 12:28
Interesting, you have openssl version 1.1 while you are on Ubuntu 16.04 which I think should have openssl 1.0.1

Are you using the desktop version or a server? Also, I think this would probably be fixed by https://github.com/prisma/prisma-engine/issues/37

**Comment by cstffx** [comment] 2019-11-18 16:47
I'm using the desktop version.

**Comment by pantharshit00** [comment] 2019-11-19 08:46
Well, can you please try to install this with npm?

```
sudo npm install -g --unsafe-perm prisma2
```

**Comment by cstffx** [comment] 2019-11-19 18:10
Continue downloading query-engine-linux-glibc-libssl1.1.0

**Comment by cstffx** [comment] 2019-11-21 21:23
I get the next: 

/home/user/node/bin/prisma2 -> /home/user/node/lib/node_modules/prisma2/build/index.js

> prisma2@2.0.0-preview016.2 install /home/user/node/lib/node_modules/prisma2
> node download-build/index.js || echo ""

> Downloading linux-glibc-libssl1.1.0 binary for query-engine and migration-engine [                    ] 0%

Then the process fail with

request to https://s3-eu-west-1.amazonaws.com/prisma-native/master/b72fd0a786adc77ba6c61d0a9637ff0371e433b0/linux-glibc-libssl1.1.0/migration-engine.gz failed, reason: connect ETIMEDOUT 52.218.52.154:443'

I am accessing the internet through a proxy, however I have no problems installing other packages with npm and yarn. I can also download this package using the browser through the same proxy. I am investigating other causes and considering upgrading to ubuntu 18.04

**Comment by pantharshit00** [comment] 2019-11-22 09:02
Hi @cstffx 

We host our binaries in amazon s3. Our CLI downloads it in postinstall scripts. Can you please make sure that S3 is not blocked by your proxy?

**Comment by cstffx** [comment] 2019-11-22 21:27
Yes, I thought about it from the beginning, but the fact is that I can download the same binaries from my browser. So my proxy is not blocking this site. I can also download other packages from npm.
I am investigating whether the post-installation script is able to correctly detect my proxy settings. I am using the HTTP_PROXY and HTTPS_PROXY environment variables specifying the username and password: 
HTTPS_PROXY="user@password:ip:port"

**Comment by aleccool213** [comment] 2019-12-17 18:49
@pantharshit00 Why is `--unsafe-perm` necessary?

**Comment by pantharshit00** [comment] 2019-12-18 15:57
It is not necessary anymore after #944 is fixed(it is in alpha now)

Previously unsafe perm was necessary as it would overcome a security feature of npm if you run npm as root on linux(which is a bad idea anyways). So it would'nt let our script download the prisma binary. So to overcome this, either you need to use `--unsafe-perm` or execute npm as a non-root user.

https://docs.npmjs.com/misc/config#unsafe-perm

Its usage is common for packages that install a binary(for example electron: https://github.com/electron/electron/blob/8a4c76d6558cffa53400e54317f0f9b1da22f7ef/docs/tutorial/installation.md#troubleshooting) but we have figured out a way to download the binary on the first run instead if our postinstall fails for some reason.

**Comment by divyenduz** [comment] 2020-01-09 15:37
@aleccool213 After #944, is this issue still relevant for you?

**Comment by aleccool213** [comment] 2020-01-09 15:39
@divyenduz All good 👍

**Comment by divyenduz** [comment] 2020-01-09 15:40
Thank you, closing this one then 🙌

**Closed by divyenduz** 2020-01-09 15:40 UTC
Labels: bug/0-needs-info, kind/bug
