### ISSUE TITLE
Error when running lift save following tutorial

### ISSUE THREAD

**Issue by tommarmstrong** [prisma/prisma2#372] opened 2019-08-18 08:36 UTC
Hi there,

I followed the guide [here](https://github.com/prisma/prisma2/blob/master/docs/getting-started.md), ran into #73 where the init flow didn't finish because I'm using psql and then followed the [Tutorial doc](https://github.com/prisma/prisma2/blob/master/docs/tutorial.md).

When I tried to run ```prisma2 lift save```, I got the following error, ```Error: Got invalid RPC response without .result property: {}```

Running prisma2@2.0.0-preview-7, binary version: 33e5fc84b6bd61602f8d634beb558230ca3e3054 on macOS 10.14.3 and psql 11.

Thanks :)

**Comment by pantharshit00** [comment] 2019-08-19 12:28
I am unable to reproduce this.

Can you please tell me which OS you are using and where is your postgres instance hosted?

**Comment by alizahid** [comment] 2019-08-19 12:48
@pantharshit00 I'm also having the same issue. Here you go.

Prisma version `prisma2@2.0.0-preview-7, binary version: 33e5fc84b6bd61602f8d634beb558230ca3e3054`
PostgreSQL version `psql (PostgreSQL) 11.4`
macOS version `10.14.5 (18F132)`

**Comment by ralvs** [comment] 2019-08-19 12:48
I got the same error using MySQL 5.7 on localhost on MacOS 10.14.6

**Comment by pantharshit00** [comment] 2019-08-19 15:03
@ralvs @alizahid 

Still no luck. Maybe can you please share your schema files?

**Comment by werevamp** [comment] 2019-08-19 18:51
@pantharshit00 I got the same error, but noticed that the error went away as soon as I took out the enum. I didn't exactly follow the tutorial so my schema is a bit different (this current schema doesn't work).
```
datasource db {
  provider = "postgresql"
  url      = "postgresql://albert@localhost:5432/theorem?schema=public"
}

generator photonjs {
  provider = "photonjs"
}

model Product {
  id          String   @default(cuid()) @id
  createdAt   DateTime @default(now())
  description String?
  name        String?
  type        String?
  updatedAt   DateTime @updatedAt
  url         String?
  vendor      Vendor[] @map("Vendor")
}

model User {
  id         String    @default(cuid())  @id
  createdAt  DateTime  @default(now())
  email      String    @unique
  name       String?
  phone      String?
  updatedAt  DateTime  @updatedAt
  role       Role      @default(USER)
  vendor     Vendor[]
}

model Vendor {
  id        String    @default(cuid()) @id
  createdAt DateTime  @default(now())
  name      String?
  product   Product[] @map("Product")
  slug      String?
  updatedAt DateTime  @updatedAt
  user      User?
}

enum {
  USER
  ADMIN
}
```

**Comment by nilaeus** [comment] 2019-08-19 19:28
I had the same problem, but it turned out to be because of an extra `!` that I left in my schema (what used to signify required fields). I'm no expert on the matter so I don't know what caused it at all, but that's just what happened in my case.

**Comment by Oscarteg** [comment] 2019-08-19 23:22
@pantharshit00 I have the same problem
Docker postgres version: 11.5-1
Created with `docker run --name prisma -v pgdata:/var/lib/postgresql/data -p 54321:5432 -e POSTGRES_PASSWORD=postgres -d postgres`
Prisma version: prisma2@2.0.0-preview-7, binary version: 33e5fc84b6bd61602f8d634beb558230ca3e3054
MacOS version: 10.14.5

This is the `schema.prisma` file:
```
datasource db {
  provider = "postgresql"
  url      = "postgresql://postgres:postgres@localhost:54321/postgres?schema=public"
}

generator photonjs {
  provider = "photonjs"
}

model User {
  id        Int      @id
  createdAt DateTime @default(now())
  email     String   @unique
  name      String?
  role      Role     @default(USER)
  posts     Post[]
  profile   Profile?
  address   Address?
}

embed Address {
  street  String
  zipCode String
}

model Profile {
  id   Int    @id
  user User
  bio  String
}

model Post {
  id         Int        @id
  createdAt  DateTime   @default(now())
  updatedAt  DateTime   @updatedAt
  author     User
  title      String
  published  Boolean    @default(false)
  categories Category[]
}

model Category {
  id    Int    @id
  name  String
  posts Post[]
}

enum Role {
  USER
  ADMIN
}
```

**Comment by Oscarteg** [comment] 2019-08-19 23:29
More info:

When removing:
```
embed Address {
  street  String
  zipCode String
}
```
and `address   Address?` from user the migrations work.

**Comment by bearcanrun** [comment] 2019-08-20 02:00
prisma2@2.0.0-preview-7, binary version: 33e5fc84b6bd61602f8d634beb558230ca3e3054
PostgreSQL 10.3
macOS 10.12.6

I had this issue and fixing two things allow the migration to work.

1. I used a new schema instead of using  'public' but the name had hyphens in it (test-schema). Looking at logs revealed:
```
ERROR:  syntax error at or near "-" at character 23
STATEMENT:  SET search_path = test-schema
```
    - Fixed by deleting dir and rerunning `prisma2 init prisma2` making sure my schema had no hyphens.
2. The next issue might be related to a schema linting. I finally learned of [vscode-prisma](https://github.com/prisma/vscode-prisma) where [issue 8](https://github.com/prisma/vscode-prisma/issues/8) revealed that the linter doesn't accept optional lists `[]?`.
    - Fixed by changing all `[]?` to `[]`

**Comment by deadcoder0904** [comment] 2019-08-20 07:06
@Oscarteg that's because [embed is not supported yet](https://github.com/prisma/lift/issues/43)

**Comment by pantharshit00** [comment] 2019-08-20 10:19
Yes, indeed @Oscarteg, embeds are not implemented yet as pointed out by @deadcoder0904. Follow https://github.com/prisma/lift/issues/43 for updates on that.


@bearcanrun 
We are aware of the error caused by dashes in the schema name. It is being tracked here: https://github.com/prisma/prisma2/issues/311.The other issue is also being tracked for as you have already mentioned.

I think I can close this issue now as it is touching multiple other issues. If anyone of you are getting a different problem which was not already reported, please open a new issue 🙂

**Closed by pantharshit00** 2019-08-20 10:19 UTC
Labels: bug/0-needs-info, kind/bug
