### ISSUE TITLE
[Windows] "Photon binary for current platform windows could not be found" while running "npm run seed"

### ISSUE THREAD

**Issue by amursky** [prisma/prisma2#549] opened 2019-09-13 08:08 UTC
1. Run `prisma2 init`
2. Choose template `TypeScript > GraphQL + Auth > SQLite`
3. Run `npm run seed`

**Result:**
```$ ts-node prisma/seed.ts
(node:7708) UnhandledPromiseRejectionWarning: Error: Photon binary for current platform windows could not be found.
  Make sure to adjust the generator configuration in the schema.prisma file:
generator photon {
  provider  = "photonjs"
  platforms = ["native", "windows"]
}
  Please run prisma2 generate for your changes to take effect.
  Note, that by providing `native`, Photon automatically resolves `windows`.
  Read more about deploying Photon: https://github.com/prisma/prisma2/blob/master/docs/core/generators/photonjs.md
    at NodeEngine.getPrismaPath (C:\Users\user\projects\playground\hello-prisma\node_modules\@generated\photon\runtime\index.js:3771:23)
(node:7708) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7708) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Tried to manually run `prisma2 generate` and then `npm run seed`. To no avail.

**Prisma version:** 2.0.0-preview-11
**OS:** Windows 10 Pro (x64)
**Node version:** 10.16.2
**NPM version:** 6.9.0

**Comment by janpio** [comment] 2019-09-13 08:21
What version of Prisma are you using? (`prisma2 v`)

**Comment by uranusexplorer** [comment] 2019-09-13 09:47
Also `prisma2 init` requires `ts-node` and `typescript` to be installed globally.

**Comment by pantharshit00** [comment] 2019-09-13 11:45
I think this is related to https://github.com/prisma/prisma2/issues/548

Example fetches preview 9.1 by default so it would not work in windows as it requires preview-11.

@uranusexplorer can you please try running prisma2 dev(globally installed version) after the init flow and see whether it is working.

I don't have access to a windows machine right now so I can't test this.

**Comment by ROFL27** [comment] 2019-09-13 19:19
I am getting the same error on every Mutation invoke. Also using preview 11.

**Comment by uranusexplorer** [comment] 2019-09-14 01:19
@pantharshit00, `prisma2 dev` runs well.

**Comment by pantharshit00** [comment] 2019-09-14 04:31
Are you on a 32 bit system or a 64 bit system?

**Comment by uranusexplorer** [comment] 2019-09-14 05:41
64

**Comment by serotonyn** [comment] 2019-09-14 21:48
I get it to work by hardcoding the value of ```alternativePath``` and pointing it to the query-engine-windows.exe in the runtime folder.

**Comment by seed-of-apricot** [comment] 2019-09-15 18:08
@serotonyn Could you please tell me how to set the alternative path?

**Comment by serotonyn** [comment] 2019-09-15 21:03
@seed-of-apricot of course. In node_modules\@generated\photon\runtime\index.js, search for the declaration for ```alternativePath``` (its in the getPrismaPath function at about line nbr 3770) and set its value to ```const alternativePath = 'C:\\Users\\serotonyn\\project\\node_modules\\@generated\\photon\\runtime\\query-engine-windows.exe'```

**Comment by seed-of-apricot** [comment] 2019-09-15 22:16
@serotonyn That worked, thank you!

**Comment by janpio** [comment] 2019-09-16 10:30
Short investigation into this:

The original error message 

> (node:7708) UnhandledPromiseRejectionWarning: Error: Photon binary for current platform windows could not be found.

indeed comes from it not being able to get an `alternativePath`:
https://github.com/prisma/photonjs/blob/36d275c42ad36bd20619d4e47b605cb0306c06d7/packages/engine-core/src/NodeEngine.ts#L210-L217

We missed to adapt the `resolveAlternativeBinaryPath` method for Windows to add the necessary `.exe`:
https://github.com/prisma/photonjs/blob/36d275c42ad36bd20619d4e47b605cb0306c06d7/packages/engine-core/src/NodeEngine.ts#L170-L180

But we probably also missed `resolvePrismaPath` 
https://github.com/prisma/photonjs/blob/36d275c42ad36bd20619d4e47b605cb0306c06d7/packages/engine-core/src/NodeEngine.ts#L147-L165
which would lead to this not even being triggered.

Do you agree @divyenduz? Should be simple enough to fix in a quick PR from me.

(We should probably double check all mentions of `query-engine-` in the codebase for this)

**Comment by divyenduz** [comment] 2019-09-16 11:13
@janpio Yup, sounds like it 👍

**Comment by jferrettiboke** [comment] 2019-09-19 14:52
I'm having the same issue using the latest dependencies for `prisma2`, `nexus`, and `nexus-prisma`.

**The issue**

The issue is coming from `filePath` in `.../node_modules\@generated\photon\runtime\index.js`. If I print the result of `filePath`, the result is `.../node_modules\@generated\photon\runtime\query-engine-linux-musl-libssl1.1.0`, and it should be `.../node_modules\@generated\photon\runtime\query-engine-windows.exe`.

**The hack**

Replace this:

```js
const filePath = path.join(__dirname, `query-engine-${platform}`);
```

For this:

```js
const filePath = path.join(__dirname, `query-engine-windows.exe`);
```

**The problem**

The problem is that each time I do changes in my `schema.prisma` using `prisma2 dev`, it generates a new file and replaces the old one, and the fix goes away.

---

I would appreciate if someone could fix this ASAP.

**Comment by Jaspaul** [comment] 2019-09-24 19:44
Came here to add that I was also experiencing this issue on MacOS (`darwin`), and can confirm it's resolved on `prisma2@2.0.0-alpha.204`, incase anyone else finds themselves here when investigating this issue locally.

**Comment by janpio** [comment] 2019-09-25 17:08
We currently think this might already be fixed by a pending change, will test and let you know when the change is available in `alpha` for confirmation.

**Comment by janpio** [comment] 2019-09-27 12:23
This now works fine with `preview-13`.

Please let us know if this is not true for you, and we can reopen this issue and investigate further.

**Comment by embiem** [comment] 2019-12-11 12:45
Bump, as I'm running into this issue again. Same issue & platform as mentioned in OP.

Fixed by hard-coding the alternativePath.

**Comment by pantharshit00** [comment] 2019-12-11 18:11
@embiem Can you please tell me which version of Prisma 2 are you using?

**Comment by embiem** [comment] 2019-12-11 23:37
@pantharshit00 I'm currently on "2.0.0-preview018.1" for prisma2 and @prisma/photon

**Comment by divyenduz** [comment] 2020-01-20 11:31
@embiem @amursky Is this still an issue?

**Comment by amursky** [comment] 2020-01-24 13:23
@divslinger I'm using `2.0.0-preview019`. Everything is fine.

**Comment by divyenduz** [comment] 2020-01-24 13:57
Thanks for the update, I am closing this one then.

**Closed by divyenduz** 2020-01-24 13:57 UTC
Labels: bug/0-needs-info, kind/bug

**Comment by Vandivier** [comment] 2020-04-12 05:04
minor comment for recent Google arrivals... in Prisma 2 the syntax is like this now:
```
generator client {
  provider       = "prisma-client-js"
  binaryTargets  = ["native", "windows"]
}
```
