### ISSUE TITLE
generate doesn't like spaces in project path

### ISSUE THREAD

**Issue by nicke** [prisma/prisma2#1030] opened 2019-12-02 08:50 UTC
I noticed that prisma2 generate doesn't work when path contains spaces on MacOS.

```
internal/modules/cjs/loader.js:582
    throw err;
    ^
Error: Cannot find module '/Users/me/devel/a'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
Error:
    Error: Generator at /Users/me/devel/a b/test-prisma2/prisma2-backend/node_modules/@prisma/photon/generator-build/index.js could not start:
    internal/modules/cjs/loader.js:582
        throw err;
        ^
    Error: Cannot find module '/Users/me/devel/a'
        at Timeout.setTimeout [as _onTimeout] (/Users/me/devel/a b/test-prisma2/prisma2-backend/node_modules/prisma2/build/index.js:231407:28)
error Command failed with exit code 1.
```

**Comment by pantharshit00** [comment] 2019-12-02 18:08
Can you please share your schema.prisma file?

I was unable to reproduce this, maybe I understood the problem incorrectly:
![image](https://user-images.githubusercontent.com/22195362/69983472-c684fc00-155c-11ea-897b-9b1275d171af.png)

**Comment by janpio** [comment] 2019-12-03 19:04
@nicke has the spaces in the project path itself, not the `output`.

**Comment by nicke** [comment] 2019-12-04 15:47
@janpio in project path itself. output isn‘t set.

**Comment by pantharshit00** [comment] 2019-12-05 14:39
I am still unable to reproduce this :/ 
![image](https://user-images.githubusercontent.com/22195362/70244744-0507fa00-179b-11ea-9479-c6bb9be5e57c.png)

**Comment by nicke** [comment] 2019-12-10 12:50
Hi, 
you should be able to reproduce when deleting node_modules and run "npm install".

the problem happens in "@prisma/photon@2.0.0-preview018.1 postinstall"

**Comment by pantharshit00** [comment] 2019-12-11 12:41
I am still unable to reproduce:
![image](https://user-images.githubusercontent.com/22195362/70622320-b0083000-1c41-11ea-8074-20a5a9273605.png)


Can you share a git repository with the reproduction?

**Comment by divyenduz** [comment] 2020-01-09 14:43
I couldn't reproduce this either, I will close this one, if you think that this is still an issue, please comment here and tag me. Thanks, 

![image](https://user-images.githubusercontent.com/746482/72076031-28234d80-32f5-11ea-922a-d28674bab0c6.png)

**Closed** 2020-01-09 14:43 UTC
Labels: bug/0-needs-info, kind/bug, topic: cli

**Comment by Xaedblade** [comment] 2020-02-20 18:09
This is an issue for windows computers. I've run into this several times. my fix was to change my project folder name on my home pc. But my work laptop uses my name as the user with a space... so can't fix. i.e C:\Users\firstname lastname\ will throw an error because of the space.

error message:
 Are you sure of your inputs? Yes   

  Updating your schema.prisma file...

  Generating prisma clients for both management and tenants...
{ Error: Command failed: C:\Users\C*** V*******\Desktop\warehouse 3\node_modules\.bin/prisma2 generate
'C:\Users\C***' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'C:\\Users\\C*** V****\\Desktop\\warehouse 3\\node_modules\\.bin/prisma2 generate ' }

**Comment by Xaedblade** [comment] 2020-02-21 04:48
This is still an issue, I'm on  a windows machine and get this error when generating with a file path that has a space. In my case my user name for my work laptop is my first name with a space and then a last name.

Error:
`Error: EPERM: operation not permitted, mkdir 'C:\Users\C****'
TypeError: Cannot read property 'loaded' of undefined
    at exit (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:98:27)
    at errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:216:3)
    at C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:77:20
    at cb (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:225:22)
    at C:\Program Files\nodejs\node_modules\npm\lib\npm.js:263:24
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:83:7
    at Array.forEach (<anonymous>)
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:82:13
    at f (C:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:25:25)
    at afterExtras (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:173:20)
C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:98
  var doExit = npm.config.loaded ? npm.config.get('_exit') : true
                          ^

TypeError: Cannot read property 'loaded' of undefined
    at exit (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:98:27)
    at process.errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:216:3)
    at process.emit (events.js:198:13)
    at process._fatalException (internal/bootstrap/node.js:496:27)
Install for prisma2@latest failed with code 7`

**Comment by pantharshit00** [comment] 2020-02-21 13:06
@Xaedblade We had a similar report here: https://github.com/prisma/prisma2/issues/1642#issuecomment-587985335

Please let me know if that is the same issue

**Comment by janpio** [comment] 2020-02-21 18:38
@Xaedblade I am on Windows and can possibly reproduce this. What node version are you using? What are the exact commands that lead to that problem?

**Comment by Xaedblade** [comment] 2020-02-23 02:40
Hey @janpio Im on node 10.16.3

**Comment by Xaedblade** [comment] 2020-02-23 02:42
@pantharshit00 No, I'm just running in git bash terminal on vs code. I think it may have something to do with single and double quotes nor maybe not placing quotes at all? 
Thanks

**Comment by janpio** [comment] 2020-02-24 14:11
@pantharshit00 We should probably create a user with a space in one of our VMs we are using. Do not really want to mess up my local system ;)

**Comment by pantharshit00** [comment] 2020-02-26 12:47
I am still unable to reproduce this:
<img width="631" alt="image" src="https://user-images.githubusercontent.com/22195362/75346166-22dd8a80-58c4-11ea-98f8-97d0d6801bdb.png">

Version used: `prisma2@2.0.0-alpha.832, binary version: 687716d3305368e3f586f8957de2037fd8a50f8f`

**Comment by Xaedblade** [comment] 2020-02-26 14:11
I was able to find the issue on this. It appears that another package was updating the prisma client causing the issue. Thanks for looking into this!

**Comment by janpio** [comment] 2020-02-26 14:24
Uh, can you elaborate a bit on that? Sounds interesting and we probably should be aware that this can happen and what it would look like, so we can identify this in the future if it happens to someone else.

**Comment by Xaedblade** [comment] 2020-02-27 17:30
yes, I was using prisma-mulit-tenant and it rewrites the client file. So the issue was with that code rather then the original code.

**Comment by divyenduz** [comment] 2020-03-02 10:34
Linking the upstream issue here: https://github.com/Errorname/prisma-multi-tenant/issues/22
