### ISSUE TITLE
[Windows] Invalid `photon.()` invocation ... Photon binary for current platform windows could not be found.

### ISSUE THREAD

**Issue by MichalLytek** [prisma/prisma2#585] opened 2019-09-20 11:40 UTC
I've created a blank new repo using `npx prisma2 init hello-prisma2`. It downloaded the newest prisma2 `2.0.0-preview-12` which should have support for windows.

First of all, I have to manually call `npm install` to download the remaining packages. Then it downloaded the windows binary:
```
> prisma2@2.0.0-preview-12 install F:\#Projekty\#JS\hello-prisma2\node_modules\prisma2
> node download-build/index.js || echo ""

> Downloading windows binary [====================] 100%
````
And it generated a `Photon.js Client` sucessfully. After trying to run this app by `npm start`, it failed with this console info:
```
Error: 
Invalid `photon.()` invocation in F:\#Projekty\#JS\hello-prisma2\script.ts:8:36

Photon binary for current platform windows could not be found.
  Make sure to adjust the generator configuration in the schema.prisma file:
generator photon {
  platforms = ["native"]
}
  Please run prisma2 generate for your changes to take effect.
  Note, that by providing `native`, Photon automatically resolves `windows`.
  Read more about deploying Photon: https://github.com/prisma/prisma2/blob/master/docs/core/generators/photonjs.md
    at PhotonFetcher.<anonymous> (F:\#Projekty\#JS\hello-prisma2\node_modules\@generated\photon\index.js:46:27)
    at Generator.throw (<anonymous>)
    at rejected (F:\#Projekty\#JS\hello-prisma2\node_modules\@generated\photon\index.js:5:65)
(node:43808) UnhandledPromiseRejectionWarning: Error: Photon binary for current platform windows could not be found.
  Make sure to adjust the generator configuration in the schema.prisma file:
generator photon {
  provider  = "photonjs"
}
  Please run prisma2 generate for your changes to take effect.
  Note, that by providing `native`, Photon automatically resolves `windows`.
  Read more about deploying Photon: https://github.com/prisma/prisma2/blob/master/docs/core/generators/photonjs.md
    at NodeEngine.getPrismaPath (F:\#Projekty\#JS\hello-prisma2\node_modules\@generated\photon\runtime\index.js:3777:23)
    at F:\#Projekty\#JS\hello-prisma2\node_modules\@generated\photon\runtime\index.js:3828:36
(node:43808) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:43808) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

So I've edited that photon generator block, run npm install again and then received the new error message:

```
Photon binary for current platform windows could not be found.
  Make sure to adjust the generator configuration in the schema.prisma file:
generator photon {
  platforms = ["native", "windows"]
}
  Please run prisma2 generate for your changes to take effect.
```

But after that change, it now trows an error during `prisma2 generate` step:

```
Generating Photon.js Client to F:\#Projekty\#JS\hello-prisma2\node_modules\@generated\photon
Error: Unknown platform windows. Possible platforms: native, darwin, linux-glibc-libssl1.0.1, linux-glibc-libssl1.0.2, linux-glibc-libssl1.1.0, linux-musl-libssl1.1.0
```

**Comment by janpio** [comment] 2019-09-21 20:10
@MichalLytek I assume you followed `Blank project > SQLite > Photon + Lift > JavaScript > Demo scripts` (or very similar) during the wizard?

Do you remember why you had to run `npm install` manually? Did you encounter https://github.com/prisma/prisma2/issues/531 when it downloaded the demo script?

> So I've edited that photon generator block, run npm install again and then received the new error message:

Interesting. Do you recall why you ran `npm install` again instead of `prisma2 generate`?

The PR https://github.com/prisma/photonjs/pull/233 from @wardpeet will probably fix the initial problem, but also the second one 👍

**Comment by MichalLytek** [comment] 2019-09-21 20:13
> I assume you followed Blank project > SQLite > Photon + Lift > JavaScript > Demo scripts (or very similar) during the wizard?

Yes, I've choosen the TypeScript template I think.

> Do you remember why you had to run npm install manually?

VSCode showed me only photon in node_modules, I run npm install and then it downloaded the windows binary.

> Did you encounter #531 when it downloaded the demo script?

No, no this kind of error encountered.

>  Do you recall why you ran npm install again instead of prisma2 generate?

To be sure that everything is ok - prisma2 generate is configured as a postinstall script.

**Comment by wardpeet** [comment] 2019-09-21 20:13
I encountered the same issue. I can't recall the correct error messages but it was complaining about not finding windows binaries.

**Comment by janpio** [comment] 2019-09-21 20:16
Thanks you two. I ask so detailed as I couldn't reproduce these exact error messages in the same way.

Did you always use `npx prisma2` or did you install globally along the way @MichalLytek?

**Comment by wardpeet** [comment] 2019-09-21 20:19
When adding `postinstall: prisma2 generate` when prisma2 was a `devDependency` of my project it failed to generate as well. When I moved it to a global install `postinstall` worked. I'm unsure if it's a prisma2 issue.

**Comment by janpio** [comment] 2019-09-21 20:23
Will probably be best and easiest to try recreate when your PR was merged and released via `alpha`.

**Comment by carlbarrdahl** [comment] 2019-09-22 11:56
Same issue here. Got this error message upon init:
```sh
Preparing your starter kit: GraphQL API (+ Auth)
✔  Downloading the starter kit from GitHub ...
✔  Extracting content to backend ...
✔  Installing dependencies with: `npm install` ...
⠋  Preparing your database ...
5  Seeding your database with: `npm run seed` ...

ERROR  Error during command execution
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.          
```

**Comment by janpio** [comment] 2019-09-23 09:04
That is a different bug @carlbarrdahl which is tracked in https://github.com/prisma/prisma2/issues/531

**Comment by Jaspaul** [comment] 2019-09-24 19:45
Came here to add that I was also experiencing this issue on MacOS (`darwin`), and can confirm it's resolved on `prisma2@2.0.0-alpha.204`, incase anyone else finds themselves here when investigating this issue locally.

**Comment by MichalLytek** [comment] 2019-09-26 11:15
I can confirm that now it works with the newest alpha 😉 Generates client, creates and apply migrations, use generated Photon to save and load data to DB. Haven't checked the starter kit (CLI generator).

**Comment by janpio** [comment] 2019-09-26 12:07
Newest being `alpha.206` here, right?

I still encounter the original problem:

```
C:\Users\Jan\Documents\throwaway\585  (script@1.0.0)
λ npm start

> script@1.0.0 start C:\Users\Jan\Documents\throwaway\585
> node ./script.js

Error:
Invalid `const user1 = await photon.users.create()` invocation in C:\Users\Jan\Documents\throwaway\585\script.js:7:36

   3
   4 // A `main` function so that we can use async/await
   5 async function main() {
   6   // Seed the database with users and posts
→  7   const user1 = await photon.users.create(

Photon binary for current platform windows could not be found.
  Make sure to adjust the generator configuration in the schema.prisma file:
generator photon {
  provider  = "photonjs"
  platforms = ["native"]
}
  Please run prisma2 generate for your changes to take effect.
  Note, that by providing `native`, Photon automatically resolves `windows`.
  Read more about deploying Photon: https://github.com/prisma/prisma2/blob/master/docs/core/generators/photonjs.md
    at PhotonFetcher.<anonymous> (C:\Users\Jan\Documents\throwaway\585\node_modules\@generated\photon\index.js:46:27)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\Jan\Documents\throwaway\585\node_modules\@generated\photon\index.js:5:65)
(node:26456) UnhandledPromiseRejectionWarning: Error: Photon binary for current platform windows could not be found.
  Make sure to adjust the generator configuration in the schema.prisma file:
generator photon {
  provider  = "photonjs"
  platforms = ["native"]
}
  Please run prisma2 generate for your changes to take effect.
  Note, that by providing `native`, Photon automatically resolves `windows`.
  Read more about deploying Photon: https://github.com/prisma/prisma2/blob/master/docs/core/generators/photonjs.md
    at NodeEngine.getPrismaPath (C:\Users\Jan\Documents\throwaway\585\node_modules\@generated\photon\runtime\index.js:3777:23)
    at async C:\Users\Jan\Documents\throwaway\585\node_modules\@generated\photon\runtime\index.js:3828:36
(node:26456) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26456) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

C:\Users\Jan\Documents\throwaway\585  (script@1.0.0)
λ prisma2 -v
prisma2@2.0.0-alpha.206, binary version: 14576370b55d5152d9cb90f4f509bfa56760dbbd
```

**Comment by janpio** [comment] 2019-09-26 12:09
(As I currently can't edit my prev comment, here the additional info: `Blank project > SQLite > Photon + Lift > JavaScript > Demo scripts`, then it fails during setting up the project, so go into the folder and run `npm install` manually which succeeds, then run `npm start` and encounter this problem.)

**Comment by MichalLytek** [comment] 2019-09-26 12:32
> hat tells me about a missing table in the database which might imply it actually working 

I had some issues with that, looks like the path is treated wrong - once as for file in `prisma` folder, once in cwd. I've droped the file prefix and changed to relative to cwd.

**Comment by janpio** [comment] 2019-09-27 10:50
This should be fixed now in the just release `preview-13` - I just tested it and could not trigger this error again 🚀

**Comment by janpio** [comment] 2019-09-27 10:50
test

**Closed by janpio** 2019-09-27 10:50 UTC
Labels: bug/2-confirmed, kind/bug

**Comment by janpio** [comment] 2019-09-27 10:53
bug
