### ISSUE TITLE
Error reporting zip and MacOS catalina

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#1279] opened 2020-01-06 13:10 UTC
The error reports that we upload as a part of the `prisma2` CLI are not working on MacOS catalina. An attempt to unzip them yields: 

![image](https://user-images.githubusercontent.com/746482/71820061-3b80af80-308e-11ea-9892-4e3c2549197f.png)

**Comment by pantharshit00** [comment] 2020-01-06 13:56
Closing as duplicate of #1000

**Closed by pantharshit00** 2020-01-06 13:56 UTC
Labels: bug/2-confirmed, kind/bug, process/candidate, topic: errors

**Comment by divyenduz** [comment] 2020-01-06 15:08
@pantharshit00 thanks, marking the duplicate as a candidate, you missed that bit :)
