### ISSUE TITLE
When running the Prisma2 tutorial

### ISSUE THREAD

**Issue by etelsv** [prisma/prisma2#526] opened 2019-09-09 13:32 UTC
When trying to download the demo script as part of the Prisma2 tutorial init flow, I get this error: 

```
Preparing your demo script (TypeScript) ...

✔  Downloading the demo script from GitHub ...
✔  Extracting content to hello-prisma2 ...
⠙  Installing dependencies with: `npm install` ...
4  Preparing your database ...
 ERROR  Error during command execution

Error: Could not find /Users/etel/Documents/code/test_nikos_article/hello-prisma2/prisma/project.prisma
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! script@ postinstall: `prisma2 generate`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the script@ postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/etel/.npm/_logs/2019-09-09T13_15_08_063Z-debug.log

```
Running `npm install` manually does not result in an error.

**Comment by pantharshit00** [comment] 2019-09-09 14:34
I can't reproduce this, can you please list out the exact step that you took in the init flow.

Also, there is a very similar issue to this one: https://github.com/prisma/prisma2/issues/482. So this might be a duplicate.

**Comment by schickling** [comment] 2019-09-09 17:07
Which `prisma2` version are you using @etelsv 

Given it says `project.prisma` I suspect this to be an older version!

![image](https://user-images.githubusercontent.com/1567498/64551325-10cb5800-d335-11e9-9b87-a07f42cf1da2.png)

**Comment by divyenduz** [comment] 2019-09-30 10:33
This is not reproducible anymore, close this one. Please feel free to open a new issue in case you still run into it and tag me there.

**Closed by divyenduz** 2019-09-30 10:33 UTC
Labels: bug/0-needs-info, kind/bug
