### ISSUE TITLE
Error in lift engine - Fail to introspect schema

### ISSUE THREAD

**Issue by herbertpimentel** [prisma/prisma2#1043] opened 2019-12-04 13:22 UTC
I cannot introspect an existing schema due to following error

```
❯  Introspect          Error in lift engine: 
❮  Back                (Database credentials)
[migration-engine] error: Error: spawn /usr/local/lib/node_modules/prisma2/migration-engine ENOENT
```

using postgres version: 
PostgreSQL 10.5+tjap-20180921 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-16), 64-bit

Running on 
  Nome do Modelo:	iMac
  Identificador do Modelo:	iMac13,1
  Nome do Processador:	Intel Core i5
  Velocidade do Processador:	2,9 GHz
  Número de Processadores:	1
  Número Total de Núcleos:	4
  Cache L2 (por Núcleo):	256 KB
  Cache de L3:	6 MB
  Memória:	8 GB

**Comment by pantharshit00** [comment] 2019-12-05 18:15
Can you please tell me which version of prisma2 you are using? Also, please try install prisma2 once with --unsafe-flag on npm to avoid binary permission issues if you on a root user.
```
npm install -g --unsafe-perm prisma2
```

**Comment by herbertpimentel** [comment] 2019-12-10 13:15
how can I debug (provide more information) . Now, after install prisma using --unsafe-perm it get stuck with the message "Connecting" and no error is shown.

**Comment by pantharshit00** [comment] 2019-12-11 14:04
you can please run the command with `export DEBUG=*` ran before. That will enable debug output. Please paste the output here then.

**Comment by herbertpimentel** [comment] 2019-12-11 14:22
Connecting
❮ Back (Database options)
  IntrospectionEngine:stderr {"message":"[src/libcore/option.rs:1190:5] convert db size result","backtrace":"stack backtrace:\n   0: backtrace::backtrace::trace\n   1: backtrace::capture::Backtrace::new\n   2: user_facing_errors::UnknownError::new_in_panic_hook\n   3: user_facing_errors::panic_hook::set_panic_hook::{{closure}}\n   4: std::panicking::rust_panic_with_hook\n   5: std::panicking::continue_panic_fmt\n   6: rust_begin_unwind\n   7: core::panicking::panic_fmt\n   8: core::option::expect_failed\n   9: <std::future::GenFuture<T> as core::future::future::Future>::poll\n  10: <std::future::GenFuture<T> as core::future::future::Future>::poll\n  11: <std::future::GenFuture<T> as core::future::future::Future>::poll\n  12: tokio::runtime::enter::Enter::block_on\n  13: std::thread::local::LocalKey<T>::with\n  14: std::thread::local::LocalKey<T>::with\n  15: tokio::runtime::spawner::Spawner::enter\n  16: tokio::runtime::time::variant::with_default\n  17: std::thread::local::LocalKey<T>::with\n  18: <introspection_engine::rpc::RpcImpl as introspection_engine::rpc::rpc_impl_Rpc::gen_server::Rpc>::get_database_metadata\n  19: <jsonrpc_core::delegates::DelegateAsyncMethod<T,F> as jsonrpc_core::calls::RpcMethod<M>>::call\n  20: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll\n  21: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll\n  22: <futures::future::map::Map<A,F> as futures::future::Future>::poll\n  23: <futures::future::either::Either<A,B> as futures::future::Future>::poll\n  24: <futures::future::map::Map<A,F> as futures::future::Future>::poll\n  25: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll\n  26: <futures::stream::and_then::AndThen<S,F,U> as futures::stream::Stream>::poll\n  27: <futures::stream::forward::Forward<T,U> as futures::future::Future>::poll\n  28: <futures::future::map::Map<A,F> as futures::future::Future>::poll\n  29: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll\n  30: futures::task_impl::std::set\n  31: std::panicking::try::do_call\n  32: __rust_maybe_catch_panic\n  33: tokio_threadpool::task::Task::run\n  34: tokio_threadpool::worker::Worker::run_task\n  35: tokio_threadpool::worker::Worker::run\n  36: tokio_reactor::with_default\n  37: tokio::runtime::threadpool::builder::Builder::build::{{closure}}\n  38: std::thread::local::LocalKey<T>::with\n  39: std::thread::local::LocalKey<T>::with\n  40: std::sys_common::backtrace::__rust_begin_short_backtrace\n  41: std::panicking::try::do_call\n  42: __rust_maybe_catch_panic\n  43: core::ops::function::FnOnce::call_once{{vtable.shim}}\n  44: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once\n  45: std::sys::unix::thread::Thread::new::thread_start\n  46: _pthread_body\n  47: _pthread_start\n"} +2s
setting lastError
  prisma Error: Error in introspection engine: Dec 11 11:21:09.924  INFO Loading describer: quaint::single: Starting a postgresql pool with 1 connections.    
  prisma Dec 11 11:21:09.926 DEBUG sql_introspection_connector: SqlIntrospectionConnector initialized.
  prisma Dec 11 11:21:09.926 DEBUG sql_schema_describer::postgres: Getting table names    
  prisma Dec 11 11:21:09.928 DEBUG sql_schema_describer::postgres: Found schema names: ["pg_toast", "pg_temp_1", "pg_toast_temp_1", "pg_catalog", "information_schema", "public"]    
  prisma Dec 11 11:21:09.928 DEBUG rpc: Response: {"jsonrpc":"2.0","result":["pg_toast","pg_temp_1","pg_toast_temp_1","pg_catalog","information_schema","public"],"id":1}.    
  prisma Dec 11 11:21:09.953  INFO Loading describer: quaint::single: Starting a postgresql pool with 1 connections.    
  prisma Dec 11 11:21:09.954 DEBUG sql_introspection_connector: SqlIntrospectionConnector initialized.

**Comment by pantharshit00** [comment] 2019-12-11 18:18
Now this looks like a duplicate of #1087 or #1092 

Please wait while those issues are fixed.

**Closed by pantharshit00** 2019-12-11 18:18 UTC
Labels: bug/0-needs-info, kind/bug, topic: cli

**Comment by janpio** [comment] 2019-12-11 19:37
The initial problem that @herbertpimentel posted mentioned "migration engine". Does this make any sense in this context @pantharshit00?

**Comment by pantharshit00** [comment] 2019-12-16 13:37
The initial problem was of missing binary that was fixed via the `--unsafe-perm` flag. The other problem was related to the introspection engine.
