### ISSUE TITLE
Lift trying to drop column with foreign key

### ISSUE THREAD

**Issue by WeslleyNasRocha** [prisma/prisma2#409] opened 2019-08-24 13:51 UTC
When i change the model it trys to drop the column `caller` who has an foreign key

_it dont even set the cascade option_

## Database Steps

```sql
ALTER TABLE `BeHero`.`Call` ADD COLUMN `test` varchar(191)   ,DROP COLUMN `caller`,ADD COLUMN `caller` varchar(191)  ,ADD FOREIGN KEY (`caller`) REFERENCES `BeHero`.`User`(`id`) ON DELETE SET NULL;
```

## Changes

```diff
diff --git datamodel.mdl datamodel.mdl
migration 20190824103746-new-db..20190824104750-test
--- datamodel.dml
+++ datamodel.dml
@@ -25,6 +25,7 @@
   description String
   caller User @relation(references: id, onDelete: CASCADE)
   createdAt DateTime @default(now())
   solved Boolean @default(false)
+  test String?
   location String?
 }
```

**Comment by pantharshit00** [comment] 2019-08-26 14:15
Hey @WeslleyNasRocha 

Can you please provide us with your full datamodel so that we try to reproduce this?

Also, please pinpoint what exact steps you took in also to reach this state.

**Comment by pantharshit00** [comment] 2019-08-27 14:24
Yes, it is an indeed a duplicate of prisma/lift#100

**Closed by pantharshit00** 2019-08-27 14:24 UTC
Labels: bug/0-needs-info, kind/bug
