### ISSUE TITLE
API 'count' required

### ISSUE THREAD

**Issue by zzyyzz1992** [prisma/prisma2#440] opened 2019-08-28 04:10 UTC
Require count method:
Example:
 `const length: number = await photon.users.count(condition); `// `condition`'s type is same as `findMany` method.

which is useful when do custome pagination queries.

**Comment by pantharshit00** [comment] 2019-08-28 10:06
Duplicate of https://github.com/prisma/photonjs/issues/202


This actually has been implemented in the query engine level. It will be available in the client soon.

**Closed by pantharshit00** 2019-08-28 10:06 UTC
