### ISSUE TITLE
Prisma2 init in git-bash results in React component error

### ISSUE THREAD

**Issue by Novalis15** [prisma/prisma2#401] opened 2019-08-23 10:07 UTC
moved from #353 

* Windows 10 Pro version 1809
* prisma2@2.0.0-preview-8
* node v10.15.3 (npm v6.4.1)

**Steps to reproduce**

These steps should be tested with git-bash

1. cd into a testing folder
2. create a hello-prisma2 folder
3. use `prisma2 init hello-prisma2`

After these steps, the error below should occur

```
The above error occurred in one of your React components:
    in Unknown
    in div (created by Box)
    in Box
    in div (created by Box)
    in Box
    in div (created by Box)
    in Box
    in Unknown
    in Unknown
    in App

React will try to recreate this component tree from scratch using the error
boundary you provided, App.

<Error occurs another 2-3 times>
```
Shells which worked after creating a hello-prisma2 folder are:
* PowerShell
* CMD
* Hyper

**Comment by pantharshit00** [comment] 2019-08-23 13:32
I can confirm this.

Since git bash is not an interactive/TTY terminal it might be a difficult workaround.

Maybe #313 can help.

**Comment by vladimirdjurdjevic** [comment] 2019-08-23 18:28
I also get this when running prisma2 dev inside Docker container with docker-compose. I've tried to add "tty: true" in docker-compose.yml for that container, but then I got: "Got invalid RPC response without .result property: {}" error. Also, an error occurs when running it with concurrently (https://www.npmjs.com/package/concurrently)

**Comment by pantharshit00** [comment] 2019-08-23 19:18
@vladimirdjurdjevic 
`Got invalid RPC response without .result property: {}` is an actual binary panic. This issue is being tracked here #381

**Comment by divyenduz** [comment] 2019-09-06 12:47
The init flow is completely rewritten, this error (React thing) should be fixed. The underlying error #381 is also fixed. I am closing this issue. 

If this problem persists for anyone, please create a new GH issue with a minimal reproduction and tag me there.

**Closed by divyenduz** 2019-09-06 12:47 UTC
Labels: bug/2-confirmed, kind/bug
