### ISSUE TITLE
How to set table name without qoute(")?

### ISSUE THREAD

**Issue by imVinayPandya** [prisma/prisma2#638] opened 2019-09-30 07:16 UTC
I have create same project using prisma2 CLI, which is javascript + gRPC + postgresql setup. when have ran prisma2 dev it worked fine, but after doing npm run signupUser i found that in table name is **"User"** instead of **User** (without quote). 

How can i exclude this quote (") from table name.

**Comment by divyenduz** [comment] 2019-09-30 12:20
@imVinayPandya Interesting, which database/OS are you using? Can you please share a minimal reproduction.

**Comment by imVinayPandya** [comment] 2019-10-01 05:17
Here is my **schema.prisma**

```
generator photon {
  provider = "photonjs"
}

datasource db {
  provider = "postgresql"
  url      = "postgresql://username:password@localhost:5432/exploring_prisma"
}

model User {
  id          String  @default(cuid()) @id @unique
  first_name  String
  last_name   String?
  password    String
  last_login  DateTime?
  is_active Boolean?  @default(true)
  is_deleted Boolean? @default(false)
  created_at DateTime @default(now())
  updated_at DateTime @default(now())
  
  contact_details ContactDetails[] @relation(name: "ContactDetailsByUser")
}
```

**Package.json**
```

{
  "name": "node-grpc",
  "dependencies": {
    "@grpc/proto-loader": "0.5.2",
    "chalk": "2.4.2",
    "grpc": "1.24.0"
  },
  "scripts": {
    "start": "node ./server/server.js",
    "seed": "node prisma/seed.js",
    "signupUser": "node ./client/signupUser.js"
  },
  "devDependencies": {
    "prisma2": "2.0.0-preview-12"
  }
}

```

**OS details**
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

**Node.js:** v10.16.0
**Postgresql**: postgres:10 (Docker)

I hope this will help you out.

**Comment by pantharshit00** [comment] 2019-10-07 15:52
I think you are missing taking the console.log of the generated user object that it contains quotes. In the database, they don't contain quotes. It is a way to represent strings in the javascript which is being logged into the terminal:

![image](https://user-images.githubusercontent.com/22195362/66327376-5e44e000-e948-11e9-8212-8465aaf1ffd8.png)

**Comment by pantharshit00** [comment] 2019-10-07 15:53
Closing this as I can verify we don't create table or field names with quotes.

**Comment by imVinayPandya** [comment] 2019-10-09 06:56
@pantharshit00 I have tried to replicate this issue, and i am able to replicate it

First i have dropped database and recreated.

**Schema:**

```
model ContactDetails {
  id          String  @default(cuid()) @id @unique
  type        String
  value       String
  is_primary  Boolean @default(false)
  is_verified Boolean @default(false)
  is_deleted  Boolean @default(false)
  user_id     User    @relation(name: "ContactDetailsByUser")
}
```

Command to start the server: **prisma2 dev**

Here is the screen shot of that database table.
 
![Screenshot from 2019-10-09 12-20-15](https://user-images.githubusercontent.com/5011197/66458106-82f79f80-ea8f-11e9-8681-84ced7904803.png)

**Prisma Version:**
prisma2@2.0.0-preview-13, binary version: 14576370b55d5152d9cb90f4f509bfa56760dbbd

In the screenshot you can see that first i have tried to execute query without quote, table was not found, but after that i have tried with quote and than it is working.

@pantharshit00 feel free to ask anything you want.

**Comment by pantharshit00** [comment] 2019-10-09 14:57
This is not related to Prisma but it is related to postgres.

All identifiers (including column names) that are not double-quoted are folded to lower case in PostgreSQL. Since you are using a snake case like naming convention you would need to reference the table in double quotes so that postgres won't the auto lower case it.

This is surely something that is not serviceable by us and I think this is a postgres default behaviour for a long time.


You can read more about this here: https://blog.xojo.com/2016/09/28/about-postgresql-case-sensitivity/

**Comment by pantharshit00** [comment] 2019-10-09 14:58
Feel free to close this issue if this has addressed your concerns

**Comment by imVinayPandya** [comment] 2019-10-10 05:10
Ohhhh now i got this, i can write Prisma schema like this

```
model contact_details {
  id          String  @default(cuid()) @id @unique
...
}
```

above code solved my problem. I didn't realized that i can also write Prisma Model name in snake_case. Thank you @pantharshit00.

**Closed** 2019-10-10 05:31 UTC
Labels: bug/1-repro-available, kind/bug
