### ISSUE TITLE
Generated starter code has an error when running prisma2 dev for the first time

### ISSUE THREAD

**Issue by robin-macpherson** [prisma/prisma2#1354] opened 2020-01-17 04:49 UTC
When following the `prisma2 init` starter wizard and selecting a minimal setup with just the prisma schema, running `prisma2 dev` for the first time actually complains about syntax errors, which is very surprising for a new user.

Here is the output:
```
➜  backend git:(master) prisma2 dev
Error: Schema parsing
error: Error parsing attribute "@unique": Fields that are marked as id should not have an additional @unique.
  -->  schema.prisma:13
   |
12 | model User {
13 |   id    String  @default(cuid()) @id @unique
   |
error: Error parsing attribute "@unique": Fields that are marked as id should not have an additional @unique.
  -->  schema.prisma:20
   |
19 | model Post {
20 |   id        String   @default(cuid()) @id @unique
```

It was easy to fix by simply removing the `@unique` flags from the `schema.prisma` file on both `id` fields.

### Original Generated File:
```
datasource db {
  provider = "postgresql"
  url      = env("POSTGRESQL_URL")
}

generator photon {
  provider = "photonjs"
}

model User {
  id    String  @default(cuid()) @id @unique
  email String  @unique
  name  String?
  posts Post[]
}

model Post {
  id        String   @default(cuid()) @id @unique
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  published Boolean
  title     String
  content   String?
  author    User?
}
```

### Fix

```
datasource db {
  provider = "postgresql"
  url      = env("POSTGRESQL_URL")
}

generator photon {
  provider = "photonjs"
}

model User {
  id    String  @default(cuid()) @id
  email String  @unique
  name  String?
  posts Post[]
}

model Post {
  id        String   @default(cuid()) @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  published Boolean
  title     String
  content   String?
  author    User?
}
```

**Comment by robin-macpherson** [comment] 2020-01-17 04:52
@nikolasburk I'm happy to say that I've finally made the decision to switch over to Prisma 2 for both of my big personal projects, so I'll be trying my best to provide helpful feedback along the way.

I hope this one is helpful.

**Comment by pantharshit00** [comment] 2020-01-17 14:34
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma2/issues/1223

**Closed by pantharshit00** 2020-01-17 14:34 UTC

**Comment by robin-macpherson** [comment] 2020-01-17 15:41
@pantharshit00 thank you for the quick reply! I tried to look through the existing issues first but must have missed it. I'll try to be more thorough next time to avoid duplicate issues 🙂 Keep up all the great work! 💪🏼
