### ISSUE TITLE
prisma2 lift save fails on PostgreSQL

### ISSUE THREAD

**Issue by ognjenbostjancic** [prisma/prisma2#919] opened 2019-11-11 17:00 UTC
After upgrading to **2.0.0-preview016.1** running `prisma2 lift save` fails with following error on PostgreSQL database:
![image](https://user-images.githubusercontent.com/22957673/68605356-8cb85c80-04ac-11ea-84c8-8ffdb79c6c9a.png)

Deleting migrations and reseting database didn't help.

**Comment by williamluke4** [comment] 2019-11-12 09:06
I'm pretty sure that this is a duplicate of #884  There is a tempory work around there

**Comment by marcantoine** [comment] 2019-11-12 16:08
I've got the same error while trying to use lift with previous migration (error on lift up or down)
The error appeared with version 2.0.0-preview016 and is still occuring with 2.0.0-preview016.2

`Error parsing the migration steps: Error("unknown field `name`, expected `model`",
 line: 1, column: 61)'`

Everything works fine on 2.0.0-preview015

The migrations steps were generated with 2.0.0-preview014.2

**Comment by kokokenada** [comment] 2019-11-13 01:13
As per https://github.com/prisma/prisma2/issues/884, adding  sslaccept=accept_invalid_certs to your datasource url fixes this.

To make matter worse the error message is not displayed when running in Netlify build.  Just a mysterious:
```
7:23:26 PM: The above error occurred in the <TabIndexProvider> component:
7:23:26 PM:     in TabIndexProvider
7:23:26 PM:     in App
```

**Comment by pantharshit00** [comment] 2019-11-14 11:32
Can you all check if `sslaccept=accept_invalid_certs` fixes this error? Otherwise please tell me how to reproduce this. 

The netlify issue is related to #313

**Comment by ognjenbostjancic** [comment] 2019-11-14 13:36
@pantharshit00 I can confirm that @kokokenada 's answer of adding `sslaccept=accept_invalid_certs` fixes this.

**Comment by BiscuiTech** [comment] 2019-11-14 15:59
I can confirm that the `sslaccept=accept_invalid_certs` does **not** in fact fix this entirely. I now have this error after adding the param:
![image](https://user-images.githubusercontent.com/17841919/68873576-d6cc5880-06cd-11ea-8eab-01fa2342861f.png)

**Comment by SvitlanaShepitsena** [comment] 2019-11-14 16:51
Well, I added these params and it helped in my case on ubuntu 19.10. What was that - I did not have time to figure out :-). Hope it would help you guys. 
&sslmode=verify-ca&sslfactory=org.postgresql.ssl.NonValidatingFactory

**Comment by marcantoine** [comment] 2019-11-14 17:09
Reinstalled preview16.2, I still have the same error. I tried adding @kokokenada `sslaccept=accept_invalid_certs` as well as @SvitlanaShepitsena `&sslmode=verify-ca&sslfactory=org.postgresql.ssl.NonValidatingFactory` in my connection string.


![image](https://user-images.githubusercontent.com/4647269/68879317-807d0b00-0709-11ea-934d-002213cd8063.png)

**Comment by pantharshit00** [comment] 2019-11-15 12:44
@marcantoine Can you please share your datamodel?

@BiscuiTech Can you please tell me where your database is hosted? 

I think we should wait while we patch #884

**Comment by tomhoule** [comment] 2019-11-15 15:18
I think this is related to the change in the format of migrations. See the "Breaking changes" section in the [latest release notes](https://github.com/prisma/prisma2/releases/tag/2.0.0-preview016)

**Comment by marcantoine** [comment] 2019-11-15 16:09
Thank you @tomhoule i missed this point in the release notes,  this totally looks like my error.

**Comment by tomhoule** [comment] 2019-11-15 16:26
Glad to help, if that worked :)

**Comment by BiscuiTech** [comment] 2019-11-15 16:34
> @marcantoine Can you please share your datamodel?
> 
> @BiscuiTech Can you please tell me where your database is hosted?
> 
> I think we should wait while we patch #884

Database is hosted on DigitalOcean (Managed DB)



> I think this is related to the change in the format of migrations. See the "Breaking changes" section in the [latest release notes](https://github.com/prisma/prisma2/releases/tag/2.0.0-preview016)


I just what was in there and the issue persists. I also have no problems with my workstation back home, just my work laptop. I just realized that it may be because my home station probably isn't updated to v16. I'll have to check.

**Comment by divyenduz** [comment] 2020-01-09 15:35
"Error parsing the migration steps". This error happens when the internal representation of lift (the migration engine) has a breaking change. 

Since, we are in preview, although we try to contain the surface area of breaking changes, this one is acceptable. 

The workaround is to remove your migrations and the migration table and start from scratch wrt migration. Does that make sense? 

I am closing this one, if the problem persists for you, please comment here or reach out to me in our slack: https://slack.prisma.io.

**Closed by divyenduz** 2020-01-09 15:35 UTC
Labels: bug/0-needs-info, kind/bug
