### ISSUE TITLE
`prisma2 dev` command throws error  when adding required field

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2#69] opened 2019-07-02 09:33 UTC
I've followed the `init` flow:

- SQLite
- Photon + Lift
- From scratch

Then went through all the steps that are printed:

```
  Here are the next steps to get you started:
    1. Run prisma2 lift save --name init to create a migration.
    2. Run prisma2 lift up to apply the migration.
    3. Run yarn seed to seed the database.
    4. Run yarn start (Runs the default script)
    5. That's it !
```

Then ran (added the `Role` enum and added the `role` field to `User`):

```
prisma2 dev
```

I then changed the data model:

```groovy
datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}

generator photon {
  provider = "photonjs"
}

model User {
  id    String  @default(cuid()) @id @unique
  email String  @unique
  name  String?
  posts Post[]
  role  Role    @default(USER)
}

model Post {
  id        String   @default(cuid()) @id @unique
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  published Boolean
  title     String
  content   String?
  author    User?
}

enum Role {
  User
  Admin
}
```

The `dev` command then printed the following error:

```

 Error

   Error: Generic("Generic(\"QueryError(SqliteFailure(Error { code: ConstraintViolation, extended_code: 787 },
 Some(\\\"FOREIGN KEY constraint failed\\\"))\\n\\nstack backtrace:\\n   0: backtrace::backtrace::trace::h8629
03ac52cf58ce (0x10d10e9fe)\\n   1: backtrace::capture::Backtrace::new_unresolved::hb838890310508129 (0x10d10db
c8)\\n   2: failure::backtrace::internal::InternalBacktrace::new::hbdea59428e164bec (0x10d10d569)\\n   3: <fai
lure::backtrace::Backtrace as core::default::Default>::default::h9577f3a4e995077c (0x10d10d755)\\n   4: prisma
_query::connector::sqlite::<impl core::convert::From<rusqlite::error::Error> for prisma_query::error::Error>::
from::hfeea261c70550fc5 (0x10cc08384)\\n   5: prisma_query::connector::sqlite::query_raw_impl::hd13a8f2a4d3337
ac (0x10cbd56fa)\\n   6: <prisma_query::connector::sqlite::Sqlite as prisma_query::transaction::Connectional>:
:query_on_raw_connection::hfaa01f4b6cf61c8b (0x10cbd4538)\\n   7: sql_migration_connector::sql_database_step_a
pplier::SqlDatabaseStepApplier::apply_next_step::ha798970e8b5645e1 (0x10cb693ac)\\n   8: <sql_migration_connec
tor::sql_database_step_applier::SqlDatabaseStepApplier as 
migration_connector::database_migration_step_applier::DatabaseMigrationStepApplier<sql_migration_connector::sq
l_migration::SqlMigration>>::apply_step::h869836b9e6516a6c (0x10cb68d68)\\n   9: <migration_connector::migrati
on_applier::MigrationApplierImpl<T> as migration_connector::migration_applier::MigrationApplier<T>>::apply::hd
2454c0726a9b0e4 (0x10cba4200)\\n  10: migration_core::commands::apply_migration::ApplyMigrationCommand::handle
_migration::h9bb72079854cc846 (0x10ca9970a)\\n  11: <migration_core::commands::apply_migration::ApplyMigration
Command as migration_core::commands::command::MigrationCommand>::execute::h0603299ed9a54146 (0x10ca98988)\\n  
12: <F as jsonrpc_core::calls::RpcMethodSimple>::call::hd2624a075befb389 (0x10cae6ed6)\\n  13: <F as jsonrpc_c
ore::calls::RpcMethod<T>>::call::hedb19f7be90fdf6e (0x10ca8a49c)\\n  14: <futures::future::lazy::Lazy<F, R> as
 futures::future::Future>::poll::h3b5b85445d8d74a6 (0x10ca9d0e2)\\n  15: <futures::future::then::Then<A, B, F>
 as futures::future::Future>::poll::hcf279068325be644 (0x10ca8aaa0)\\n  16: <futures::future::map::Map<A, F> a
s futures::future::Future>::poll::h0b0e8198a896ad62 (0x10caa623f)\\n  17: <futures::future::either::Either<A, 
B> as futures::future::Future>::poll::hc887be37d832628e (0x10ca9d370)\\n  18: futures::task_impl::std::set::ha
48ca7ca98878fb4 (0x10cada9ef)\\n  19: <std::thread::local::LocalKey<T>>::with::hbf7a040c89d328cc (0x10cadd596)
\\n  20: futures::future::Future::wait::h6c47660a8ddc59a4 (0x10caa5eca)\\n  21: <jsonrpc_core::io::IoHandler<M
>>::handle_request_sync::h94618f706a6d72eb (0x10ca8747f)\\n  22: migration_core::rpc_api::RpcApi::handle::h347
c3a0308f3fa33 (0x10cae99fb)\\n  23: migration_engine::main::h56cf3725d9ba3fee (0x10ca6127d)\\n  24: std::rt::l
ang_start::{{closure}}::hb4827f207a9be37a (0x10ca61226)\\n  25: std::panicking::try::do_call::h20c95c457c762d5
f (0x10d127ba8)\\n  26: ___rust_maybe_catch_panic (0x10d12c43f)\\n  27: std::rt::lang_start_internal::he82d111

 Error

   Error: Generic("Generic(\"QueryError(SqliteFailure(Error { code: ConstraintViolation, extended_code: 1299 }
, Some(\\\"NOT NULL constraint failed: new_User.role\\\"))\\n\\nstack backtrace:\\n   0: backtrace::backtrace:
:trace::h862903ac52cf58ce (0x1070009fe)\\n   1: backtrace::capture::Backtrace::new_unresolved::hb8388903105081
29 (0x106fffbc8)\\n   2: failure::backtrace::internal::InternalBacktrace::new::hbdea59428e164bec (0x106fff569)
\\n   3: <failure::backtrace::Backtrace as core::default::Default>::default::h9577f3a4e995077c (0x106fff755)\\
n   4: prisma_query::connector::sqlite::<impl core::convert::From<rusqlite::error::Error> for prisma_query::er
ror::Error>::from::hfeea261c70550fc5 (0x106afa384)\\n   5: prisma_query::connector::sqlite::query_raw_impl::hd
13a8f2a4d3337ac (0x106ac76fa)\\n   6: <prisma_query::connector::sqlite::Sqlite as prisma_query::transaction::C
onnectional>::query_on_raw_connection::hfaa01f4b6cf61c8b (0x106ac6538)\\n   7: sql_migration_connector::sql_da
tabase_step_applier::SqlDatabaseStepApplier::apply_next_step::ha798970e8b5645e1 (0x106a5b3ac)\\n   8: <sql_mig
ration_connector::sql_database_step_applier::SqlDatabaseStepApplier as 
migration_connector::database_migration_step_applier::DatabaseMigrationStepApplier<sql_migration_connector::sq
l_migration::SqlMigration>>::apply_step::h869836b9e6516a6c (0x106a5ad68)\\n   9: <migration_connector::migrati
on_applier::MigrationApplierImpl<T> as migration_connector::migration_applier::MigrationApplier<T>>::apply::hd
2454c0726a9b0e4 (0x106a96200)\\n  10: migration_core::commands::apply_migration::ApplyMigrationCommand::handle
_migration::h9bb72079854cc846 (0x10698b70a)\\n  11: <migration_core::commands::apply_migration::ApplyMigration
Command as migration_core::commands::command::MigrationCommand>::execute::h0603299ed9a54146 (0x10698a988)\\n  
12: <F as jsonrpc_core::calls::RpcMethodSimple>::call::hd2624a075befb389 (0x1069d8ed6)\\n  13: <F as jsonrpc_c
ore::calls::RpcMethod<T>>::call::hedb19f7be90fdf6e (0x10697c49c)\\n  14: <futures::future::lazy::Lazy<F, R> as
 futures::future::Future>::poll::h3b5b85445d8d74a6 (0x10698f0e2)\\n  15: <futures::future::then::Then<A, B, F>
 as futures::future::Future>::poll::hcf279068325be644 (0x10697caa0)\\n  16: <futures::future::map::Map<A, F> a
s futures::future::Future>::poll::h0b0e8198a896ad62 (0x10699823f)\\n  17: <futures::future::either::Either<A, 
B> as futures::future::Future>::poll::hc887be37d832628e (0x10698f370)\\n  18: futures::task_impl::std::set::ha
48ca7ca98878fb4 (0x1069cc9ef)\\n  19: <std::thread::local::LocalKey<T>>::with::hbf7a040c89d328cc (0x1069cf596)
\\n  20: futures::future::Future::wait::h6c47660a8ddc59a4 (0x106997eca)\\n  21: <jsonrpc_core::io::IoHandler<M
>>::handle_request_sync::h94618f706a6d72eb (0x10697947f)\\n  22: migration_core::rpc_api::RpcApi::handle::h347
c3a0308f3fa33 (0x1069db9fb)\\n  23: migration_engine::main::h56cf3725d9ba3fee (0x10695327d)\\n  24: std::rt::l
ang_start::{{closure}}::hb4827f207a9be37a (0x106953226)\\n  25: std::panicking::try::do_call::h20c95c457c762d5
f (0x107019ba8)\\n  26: ___rust_maybe_catch_panic (0x10701e43f)\\n  27: std::rt::lang_start_internal::he82d111

 Error

   Error: Generic("Generic(\"QueryError(SqliteFailure(Error { code: ConstraintViolation, extended_code: 1299 }
, Some(\\\"NOT NULL constraint failed: new_User.role\\\"))\\n\\nstack backtrace:\\n   0: backtrace::backtrace:
:trace::h862903ac52cf58ce (0x101cf59fe)\\n   1: backtrace::capture::Backtrace::new_unresolved::hb8388903105081
29 (0x101cf4bc8)\\n   2: failure::backtrace::internal::InternalBacktrace::new::hbdea59428e164bec (0x101cf4569)
\\n   3: <failure::backtrace::Backtrace as core::default::Default>::default::h9577f3a4e995077c (0x101cf4755)\\
n   4: prisma_query::connector::sqlite::<impl core::convert::From<rusqlite::error::Error> for prisma_query::er
ror::Error>::from::hfeea261c70550fc5 (0x1017ef384)\\n   5: prisma_query::connector::sqlite::query_raw_impl::hd
13a8f2a4d3337ac (0x1017bc6fa)\\n   6: <prisma_query::connector::sqlite::Sqlite as prisma_query::transaction::C
onnectional>::query_on_raw_connection::hfaa01f4b6cf61c8b (0x1017bb538)\\n   7: sql_migration_connector::sql_da
tabase_step_applier::SqlDatabaseStepApplier::apply_next_step::ha798970e8b5645e1 (0x1017503ac)\\n   8: <sql_mig
ration_connector::sql_database_step_applier::SqlDatabaseStepApplier as 
migration_connector::database_migration_step_applier::DatabaseMigrationStepApplier<sql_migration_connector::sq
l_migration::SqlMigration>>::apply_step::h869836b9e6516a6c (0x10174fd68)\\n   9: <migration_connector::migrati
on_applier::MigrationApplierImpl<T> as migration_connector::migration_applier::MigrationApplier<T>>::apply::hd
2454c0726a9b0e4 (0x10178b200)\\n  10: migration_core::commands::apply_migration::ApplyMigrationCommand::handle
_migration::h9bb72079854cc846 (0x10168070a)\\n  11: <migration_core::commands::apply_migration::ApplyMigration
Command as migration_core::commands::command::MigrationCommand>::execute::h0603299ed9a54146 (0x10167f988)\\n  
12: <F as jsonrpc_core::calls::RpcMethodSimple>::call::hd2624a075befb389 (0x1016cded6)\\n  13: <F as jsonrpc_c
ore::calls::RpcMethod<T>>::call::hedb19f7be90fdf6e (0x10167149c)\\n  14: <futures::future::lazy::Lazy<F, R> as
 futures::future::Future>::poll::h3b5b85445d8d74a6 (0x1016840e2)\\n  15: <futures::future::then::Then<A, B, F>
 as futures::future::Future>::poll::hcf279068325be644 (0x101671aa0)\\n  16: <futures::future::map::Map<A, F> a
s futures::future::Future>::poll::h0b0e8198a896ad62 (0x10168d23f)\\n  17: <futures::future::either::Either<A, 
B> as futures::future::Future>::poll::hc887be37d832628e (0x101684370)\\n  18: futures::task_impl::std::set::ha
48ca7ca98878fb4 (0x1016c19ef)\\n  19: <std::thread::local::LocalKey<T>>::with::hbf7a040c89d328cc (0x1016c4596)
\\n  20: futures::future::Future::wait::h6c47660a8ddc59a4 (0x10168ceca)\\n  21: <jsonrpc_core::io::IoHandler<M
>>::handle_request_sync::h94618f706a6d72eb (0x10166e47f)\\n  22: migration_core::rpc_api::RpcApi::handle::h347
c3a0308f3fa33 (0x1016d09fb)\\n  23: migration_engine::main::h56cf3725d9ba3fee (0x10164827d)\\n  24: std::rt::l
ang_start::{{closure}}::hb4827f207a9be37a (0x101648226)\\n  25: std::panicking::try::do_call::h20c95c457c762d5
f (0x101d0eba8)\\n  26: ___rust_maybe_catch_panic (0x101d1343f)\\n  27: std::rt::lang_start_internal::he82d111
f45e8971a (0x101d0f68e)\\n  28: _main (0x1016482d9))\")")
       at LineStream.<anonymous> (/Users/nikolasburk/.config/yarn/global/node_modules/prisma2/build/index.js:1
06414:40)
       at LineStream.emit (events.js:196:13)
       at addChunk (_stream_readable.js:290:12)
       at readableAddChunk (_stream_readable.js:271:11)
       at LineStream.Readable.push (_stream_readable.js:226:10)
       at LineStream.Transform.push (_stream_transform.js:150:32)
       at LineStream.module.exports.7091.LineStream._pushBuffer (/Users/nikolasburk/.config/yarn/global/node_m
odules/prisma2/build/index.js:192838:23)
       at LineStream.module.exports.7091.LineStream._transform (/Users/nikolasburk/.config/yarn/global/node_mo
dules/prisma2/build/index.js:192830:10)
       at LineStream.Transform._read (_stream_transform.js:189:10)
       at LineStream.Transform._write (_stream_transform.js:177:12)
```

It can be fixed by making the `role` field on `User` optional:

```groovy
model User {
  id    String  @default(cuid()) @id @unique
  email String  @unique
  name  String?
  posts Post[]
  role  Role?    @default(USER)
}
```

What should be the expected behaviour in these cases? I assumed that by adding a `@default` value to the `role` field, it would automatically apply this to existing records.

**Comment by schickling** [comment] 2019-07-29 14:20
@pantharshit00 can you confirm this is still a problem?

**Comment by pantharshit00** [comment] 2019-07-29 15:05
This is still an issue if we have existing data in the database even though a @default directive was provided

**Comment by pantharshit00** [comment] 2019-08-01 13:00
Unable to reproduce this now with `prisma2@2.0.0-preview-3.2, binary version: acd6dd8dcf027b84a94af26b36ded779f1f56b1d`

Closing 🙂

**Closed by pantharshit00** 2019-08-01 13:00 UTC
Labels: bug/0-needs-info, kind/bug, priority/high, team/engineering
