### ISSUE TITLE
prisma2 + Docker error

### ISSUE THREAD

**Issue by dangodev** [prisma/prisma2#1309] opened 2020-01-13 03:45 UTC
Trying to deploy the Prisma2 Starter Kit App (TypeScript) via Docker with the most recent version, and when I try and build the container, the command `prisma2 generate` yields the following error:

```
Error: Error: Command failed with ENOENT: /app/node_modules/prisma2/query-engine-debian-openssl-1.1.x cli --dmmf
spawn /app/node_modules/prisma2/query-engine-debian-openssl-1.1.x ENOENT
```

This is my Dockerfile:

```yml
FROM node:13-alpine

WORKDIR /app
COPY . ./
RUN NODE_ENV=production npm install --only=production
RUN npm run build

CMD npm start
```

And here are my dependency versions:

```json
    "@prisma/photon": "2.0.0-preview019",
    "prisma2": "^2.0.0-preview019",
```

Again, it fails at `npm run build`, specifically at the `"generate:prisma": "prisma2 generate"` step.

I’ve recreated this in a [repo here](https://github.com/dangodev/prisma2-docker) for easier debugging (it’s the Prisma2 Starter App, unchanged—all I’ve added is the `Dockerfile` and `.dockerignore` files).

**Comment by alexichepura** [comment] 2020-01-13 10:40
for alpine this workaround can help
https://github.com/prisma/prisma2/issues/702#issuecomment-569778198

**Comment by pantharshit00** [comment] 2020-01-13 17:16
I am going to close this as duplicate of #702 

Please other images or the workaround mentioned by @alexichepura for now.

**Closed by pantharshit00** 2020-01-13 17:16 UTC

**Comment by pantharshit00** [comment] 2020-01-17 10:29
> On a related note, I tried following the guide here: prisma.io/docs/prisma-server/deployment-environments/docker-rty1 but when I ran docker pull prismagraphql/prisma, I got this error:



That image is for Prisma 1 and you need a specify a version there to pull it
