### ISSUE TITLE
CLI wording in `init` flow wrong

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2#532] opened 2019-09-10 12:57 UTC
The wording on the initial screen is wrong, instead of `Languages for starter kits` for starter kits it should say `Project options` (see spec [here](https://prisma-specs.netlify.com/cli/init/)).

```
~/Desktop $ prisma2 init fbefs

  Get started with a blank project or a starter kit.
  Starter kits provide ready-made setups for various use cases.

┌─ Languages for starter kits ──────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                   │
│ ❯ Blank project  Supports introspecting your existing DB                                                          │
│   Starter Kit    Sample setups for GraphQL, REST, gRPC, ...                                                       │
│                                                                                                                   │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by janpio** [comment] 2019-09-10 13:01
Duplicate of https://github.com/prisma/prisma2/issues/501

**Closed by janpio** 2019-09-10 13:01 UTC
