### ISSUE TITLE
primsa2 init cli generates invalid source code.

### ISSUE THREAD

**Issue by 5achinJani** [prisma/prisma2#382] opened 2019-08-20 13:25 UTC
![image](https://user-images.githubusercontent.com/23077544/63350549-42c34d00-c37b-11e9-9ab0-e64611e97490.png)
![image](https://user-images.githubusercontent.com/23077544/63350630-65edfc80-c37b-11e9-8141-b07378a2b4ba.png)
As you can see the source code doesn't have graphql-auth in the package.json dependencies and there contains code for permissions in the source code.
![image](https://user-images.githubusercontent.com/23077544/63350813-bd8c6800-c37b-11e9-961f-1fa2798b287d.png)
The CLI says it is getting the repo from :
[https://api.github.com/repos/prisma/photonjs/tarball/master](https://api.github.com/repos/prisma/photonjs/tarball/master) 
And this url contains a valid code having graphql-auth as a dependency so I think the issue is  the cli is getting the old version of this repo.

**Comment by pantharshit00** [comment] 2019-08-20 16:20
Closing as a duplicate of https://github.com/prisma/prisma2/issues/321

We are also working on a new flow for the prisma2 cli which will use new examples API so this will be fixed in that. 

Link to the spec: https://prisma-specs.netlify.com/cli

**Closed by pantharshit00** 2019-08-20 16:20 UTC
