### ISSUE TITLE
Errors running Prisma on GitHub Actions (linux)

### ISSUE THREAD

**Issue by iRoachie** [prisma/prisma2#899] opened 2019-11-07 12:58 UTC
### What I did

Set up a new prisma2 project with the following options:

- Starter Project
- Javascript
- GraphQL + Auth
- SQLite

I then set up CI using Github Actions, to npm install and run the build command.

### Expected Behaviour
The project should build and the `dist` folder generated on completion.

### Describe the bug
`prisma2 generate` fails with:

```bash
$ npm -s run generate
18
Error: Error: Command failed with exit code 2 (ENOENT): /github/workspace/node_modules/prisma2/query-engine-linux-glibc-libssl1.1.0 cli --dmmf
19
spawn /github/workspace/node_modules/prisma2/query-engine-linux-glibc-libssl1.1.0 ENOENT
20
error Command failed with exit code 1.
21
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
22
##[error]Docker run failed with exit code 1
```

### To Reproduce
I've set up a repo with said options and github actions https://github.com/iRoachie/prisma2-github-ci

---

Prisma Version: `2.0.0-preview015`

**Comment by pantharshit00** [comment] 2019-11-08 09:29
Borales/actions-yarn uses `node:10.16-alpine` which is actually not supported right now #702 

So I think I can close this as a duplicate of #702

**Closed by pantharshit00** 2019-11-08 09:29 UTC
Labels: process/candidate

**Comment by iRoachie** [comment] 2019-11-08 11:07
I would’ve never assumed that from that error 🙈 thanks for the triage
