### ISSUE TITLE
Scaffolding never connects on 2.0.0-preview018.1

### ISSUE THREAD

**Issue by gasparsigma** [prisma/prisma2#1118] opened 2019-12-10 21:15 UTC
I attempted using the latest version of prisma2 CLI scaffolding for GraphQL no auth starter project (currently 2.0.0-preview018.1) but that never connected to the database (Windows 10 + Powershell 6).
I tried using instead `npx prisma2@2.0.0-preview017.2 init myproject` and it worked with the same parameters

**Comment by pantharshit00** [comment] 2019-12-11 18:09
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of #1087 or #1092

**Closed by pantharshit00** 2019-12-11 18:09 UTC
Labels: bug/2-confirmed, kind/bug
