### ISSUE TITLE
Handle non interactive TTYs (like Git Bash on Windows)

### ISSUE THREAD

**Issue by ttsirkia** [prisma/prisma2#554] opened 2019-09-13 18:08 UTC
When using Git Bash in Windows, the `init` fails with the following:

```
The above error occurred in the <TabIndexProvider> component:
    in TabIndexProvider
    in div (created by Box)
    in Box
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, App.
```
Seems to work fine with the standard command line.

**Comment by janpio** [comment] 2019-09-14 08:14
I can confirm this:

![image](https://user-images.githubusercontent.com/183673/64905421-6fe3f080-d6d8-11e9-9b3b-8cf73b19ee16.png)

**Comment by pantharshit00** [comment] 2019-09-15 17:19
This was reported a few days ago(https://github.com/prisma/prisma2/issues/401) but was closed because we thought it should have been fixed by the rewrite.


I think it is solely related to Git Bash being a non-interactive TTY.

**Comment by janpio** [comment] 2019-09-17 09:05
I renamed this issue to become a feature requests that can be added to the CLI. Until this is implemented, we unfortunately do not support non interactive TTYs like Git Bash on Windows.

**Comment by pantharshit00** [comment] 2019-09-17 09:21
@ttsirkia You can use https://hyper.is if you are using Git Bash as a replacement. That one is a good interactive TTY

**Comment by divyenduz** [comment] 2019-09-20 15:17
Internal note: dropping because of product priority

**Comment by LexSwed** [comment] 2019-09-29 14:53
just use WSL on Windows machines
But did anyone have this issue in Docker `node:10`-`12`?
Tried `-alpine` and non`-alpine` versions of 10 and 12 Node, have same error for `prisma2 dev`:
```bash
The above error occurred in the <TabIndexProvider> component:
prisma      |     in TabIndexProvider
prisma      |     in App
```

**Comment by janpio** [comment] 2019-09-29 17:23
> just use WSL2 on Windows machines

That is never an appropriate answer to someone reporting a bug - which is why we are committed to making it work or return a helpful error message if we can't.





> But did anyone have this issue in Docker `node:10`-`12`?
> Tried `-alpine` and non`-alpine` versions of 10 and 12 Node, have same error for `prisma2 dev`:

I can confirm for Git Bash as well (having created the project via `prisma2 init` in another console that works):

```
Jan@Thinkbook MINGW64 ~/Documents/throwaway/prismaGitBash
$ prisma2 dev

The above error occurred in the <DevComponent> component:
    in DevComponent (created by Context.Consumer)
    in Unknown
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, App.
The above error occurred in the <DevComponent> component:
    in DevComponent (created by Context.Consumer)
    in Unknown
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, App.
The above error occurred in the <DevComponent> component:
    in DevComponent (created by Context.Consumer)
    in Unknown
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, App.
Warning: App: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.
The above error occurred in the <DevComponent> component:
    in DevComponent (created by Context.Consumer)
    in Unknown
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, App.
The above error occurred in the <DevComponent> component:
    in DevComponent (created by Context.Consumer)
    in Unknown
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, App.
Warning: App: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.
The above error occurred in the <DevComponent> component:
    in DevComponent (created by Context.Consumer)
    in Unknown
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, App.
The above error occurred in the <DevComponent> component:
    in DevComponent (created by Context.Consumer)
    in Unknown
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, App.
Warning: App: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.
The above error occurred in the <DevComponent> component:
    in DevComponent (created by Context.Consumer)
    in Unknown
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, App.
The above error occurred in the <DevComponent> component:
    in DevComponent (created by Context.Consumer)
    in Unknown
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, App.
Warning: App: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.
The above error occurred in the <DevComponent> component:
    in DevComponent (created by Context.Consumer)
    in Unknown
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, App.
The above error occurred in the <DevComponent> component:
    in DevComponent (created by Context.Consumer)
    in Unknown
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, App.
Warning: App: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.
The above error occurred in the <DevComponent> component:
    in DevComponent (created by Context.Consumer)
    in Unknown
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, App.
The above error occurred in the <DevComponent> component:
    in DevComponent (created by Context.Consumer)
    in Unknown
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, App.
Warning: App: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.

```

![image](https://user-images.githubusercontent.com/183673/65836065-7ab09f00-e2ee-11e9-85aa-effcea2089c2.png)

Do you also get this when just running `prisma2 dev` in your environment or do you have to do anything else? I see an additional `prisma      | ` in the output I do not have.

**Comment by LexSwed** [comment] 2019-10-01 06:17
> That is never an appropriate answer to someone reporting a bug - which is why we are committed to making it work or return a helpful error message if we can't.

There was no bad intention or attitude in my words :) just a suggestion.

> Do you also get this when just running `prisma2 dev` in your environment or do you have to do anything else? I see an additional `prisma | ` in the output I do not have.

it works fine locally, but I'm trying to run it in Docker container, so `prisma |` is from docker service. I can run `prisma2 dev` locally with hardcoded URL to database docker container, but doesn't seem appropriate, would love to have one `docker-compose up` command to run all the dev environment in my monorepo

**Comment by janpio** [comment] 2019-10-01 10:27
> There was no bad intention or attitude in my words :) just a suggestion.

Thanks for clarifying, as a Windows user I am used to get these actually negatively meant reactions so I am sensitive there :)


> it works fine locally, but I'm trying to run it in Docker container, so `prisma |` is from docker service.

Oh, now I understand (again, being a Windows user Docker is not really a thing for me ;) ) - maybe our resident docker expert @divyenduz can reproduce or help out for your case.

**Comment by janpio** [comment] 2019-10-05 18:29
I just researched ink in non interactive TTYs for something related, but as this information might be relevant here as well I will just dump it:

You can reproduce the problem in an interactive TTY quite simply:
- `echo "foo" | prisma2 -v` works
- `echo "foo" | prisma2 init foo` does not

Possibly related ink stuff:
https://github.com/vadimdemedes/ink/issues/40
https://github.com/vadimdemedes/ink/pull/42/files

Some more info around related things:
https://github.com/vadimdemedes/ink/issues/166
https://github.com/vadimdemedes/ink/pull/172

Our probably affected file:
https://github.com/prisma/prisma2/blob/4aef53c9db0f02af5351d90facb08de184237865/cli/ink-components/src/hooks/useStdin.ts

---

Rereading this issue here, is it possible that the actual error message is missing? Usually the "The above error..." refers to something output right before - but here there is nothing.

**Comment by ViableClanMember** [comment] 2019-10-14 22:43
Another solution is to try `winpty bash` before `prisma2`

**Comment by janpio** [comment] 2019-10-15 07:08
> Another solution is to try `winpty bash` before `prisma2`

Interesting suggestion @ViableClanMember. Unfortunately this gives me:

```
$ winpty bash prisma2 init
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'C:\Users\Jan\node_modules\prisma2\build\index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

```

in Git Bash on Windows 10. Am I doing it wrong? But I am also getting it on `$ winpty bash prisma2 -v`, so this doesn't seem to work for me in general.

**Comment by MikeyUchiha** [comment] 2019-12-07 16:22
@janpio Not sure if you're the best person to ask but can you please add this to the roadmap? It's a big blocker to use this in Docker Compose and Kubernetes.
It's even referenced in your limitations documentation here: https://github.com/prisma/prisma2/blob/master/docs/limitations.md
And yet doesn't seem to be being worked on at all.

**Comment by janpio** [comment] 2019-12-07 16:27
I am not really, but that's fine. In exchange you have to explain the usecase of `prisma2 init` in a docker compose or kubernetes environment to me - then I might be able to help out ;)

**Comment by MikeyUchiha** [comment] 2019-12-07 16:40
Sure!
I want to be able to load up my database, prisma2, and app as separate containers. See this docker-compose.yml file.

![image](https://user-images.githubusercontent.com/3036263/70377727-e3675980-18e5-11ea-839f-9c0812ff78e4.png)

Unfortunately, when I try and run it I get the following error:
![image](https://user-images.githubusercontent.com/3036263/70377737-0560dc00-18e6-11ea-80c3-1b083bca613e.png)
Which has to do with the fact that interactive windows don't work. Ultimately, I want to be able to run Prisma in a Kubernetes environment and the first step is getting it to work correctly in a Docker Compose environment.

![image](https://user-images.githubusercontent.com/3036263/70377759-40630f80-18e6-11ea-9dbf-78c86d147918.png)
This is my current folder structure. I had to add a package.json file to my prisma folder just to be able to get it to run.

**Comment by pantharshit00** [comment] 2019-12-09 13:11
You are running the dev command inside the container. I will not recommend that. 

Also, you can get an interactive prompt in docker with the -i flag.

**Comment by MikeyUchiha** [comment] 2019-12-14 13:13
@pantharshit00 I should be able to just run a command in kubernetes and docker in a ci/cd pipleline.

**Comment by MikeyUchiha** [comment] 2019-12-14 13:14
requiring someone to have to create an interactive docker isn't possible in kubernetes.

**Comment by Jolg42** [comment] 2020-02-14 13:25
The `init` command is not interactive anymore and we check if we are in a TTY env in the code when appropriate.

When I tried on Windows recently it was working.

**Closed by Jolg42** 2020-02-14 13:25 UTC
Labels: kind/feature, topic: cli
