### ISSUE TITLE
init error

### ISSUE THREAD

**Issue by lglie** [prisma/prisma2#1270] opened 2020-01-05 01:46 UTC
init error:
![image](https://user-images.githubusercontent.com/931410/71773879-0ac24c80-2fa0-11ea-896c-8414b77135fe.png)

**Comment by sachaw** [comment] 2020-01-05 08:56
Same Issue, OS Windows 10, have tried a clean install

**Comment by pantharshit00** [comment] 2020-01-06 13:58
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma2/issues/1232#issuecomment-569090211

**Closed by pantharshit00** 2020-01-06 13:58 UTC
Labels: topic: cli-init
