### ISSUE TITLE
Existing database with MySQL doesn't print

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#778] opened 2019-10-18 06:57 UTC
To reproduce: 

1. Blank project
2. MySQL
3. Fill the credentials but omit the DB as it is optional
4. In the next step, choose an existing DB
5. Observer the generated schema file has no db in the URL. 
6. Running `prisma2 dev` at this point makes Rust panic

GIF: https://divyendu.s3-eu-west-1.amazonaws.com/prisma2-778.gif

**Comment by divyenduz** [comment] 2019-10-18 07:01
Candidate because it affects getting started experience with a panic 🙏

**Comment by janpio** [comment] 2019-10-18 17:26
Oh, that might explain a few `prisma2 dev` crashes that are probably reported in other issues 👍

**Comment by pantharshit00** [comment] 2019-10-29 09:09
I can confirm this bug. This should be tackled soon as it does crash the `prisma2 dev` with a huge rust panic.

![image](https://user-images.githubusercontent.com/22195362/67752945-38d16080-fa34-11e9-8b8d-505d9fbded72.png)

**Comment by tomhoule** [comment] 2019-11-07 14:02
I haven't had time to work on this yet but it is on my radar.

**Comment by tomhoule** [comment] 2019-11-12 17:42
There are two parts to this issue:

1. The generated `prisma.schema` does not contain the database name. It is an issue with our typescript code.
2. The unhelpful error (rust panic) when you try to `prisma2 lift save` with that schema.

`2.` is fixed in a soon-to-be-merged refactoring of the errors in the migration engine.

I'll look into `1.` myself tomorrow.

**Comment by tomhoule** [comment] 2019-11-13 11:37
Found the relevant code: https://github.com/prisma/prisma2/blob/8f56b8b971b0819845c6f2d19b09445e7e3748ba/cli/introspection/src/prompt/screens/Step4SelectDatabase.tsx#L77

Looks like the database selection only redirects, maybe we could add an event handler that updates the database URL on the `<Link />`? cc @timsuchanek 

If that sounds like the right way I can try to set up the project and make the change myself.

**Comment by timsuchanek** [comment] 2019-12-13 14:51
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `prisma2`.
You can try it out with `npm i -g prisma2@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!

**Closed** 2019-12-13 14:50 UTC
Labels: bug/2-confirmed, kind/bug
