### ISSUE TITLE
Default datetime is `1970-01-01T00:00:00.000Z`

### ISSUE THREAD

**Issue by Veraclins** [prisma/prisma2#520] opened 2019-09-07 17:12 UTC
I have a schema that looks like this:
```
model User {
  id            String      @default(cuid()) @id
  email         String      @unique
  username      String      @unique
  password      String
  firstName     String?
  lastName      String?
  role          String?     @default("USER")
  lastLogin     DateTime?   @default(now())
  createdAt     DateTime    @default(now())
  updatedAt     DateTime    @updatedAt
  deletedAt     DateTime?
  posts         Post[]
  comments      Comment[]
}
```
I expect that when a record is created, the Datetime fields with the `@default(now())` directives will have the current date time. Currently these fields get the value `1970-01-01T00:00:00.000Z` as shown below. Has anyone else noticed this or is it just me? Could I be missing something?
Curiously, the `updatedAt` field that has the `@updatedAt` directive got the right value.
<img width="1440" alt="Screen Shot 2019-09-07 at 6 08 52 PM" src="https://user-images.githubusercontent.com/26969309/64478085-f52c4a00-d19a-11e9-8f33-3c283287853f.png">

**Comment by pantharshit00** [comment] 2019-09-09 15:00
This is a duplicate of https://github.com/prisma/prisma2/issues/457 in my opinion.

You have two DateTime fields that are using `@default(now())` which is currently now working as per https://github.com/prisma/prisma2/issues/457. 

I am going to close this issue as a duplicate. Feel free to comment your findings on that other issue.

**Closed by pantharshit00** 2019-09-09 15:00 UTC
