### ISSUE TITLE
Introspection: Cannot read property 'substring' of undefined [MySQL 8]

### ISSUE THREAD

**Issue by Innomalist** [prisma/prisma2#516] opened 2019-09-07 10:17 UTC
Hello,
Great project just wanted to let you know there could be an issue on Introspection module. Here is the error i have received when trying to do so:

```
Introspecting MySQL schema  with 26  tables.
 ERROR  Introspection failed:
Cannot read property 'substring' of undefined

**Comment by Innomalist** [comment] 2019-09-07 10:19
BTW i have also tried with a much smaller database. Same result

**Comment by pantharshit00** [comment] 2019-09-09 08:25
@Innomalist 

Can you please share your datamodel? Also, we are currently porting our introspection logic from typescript to Rust. We just need to use the updated code now(follow https://github.com/prisma/prisma2/issues/510)

So please share your datamodel so that we can try to reproduce this 🙏

**Comment by Innomalist** [comment] 2019-09-09 08:29
Hello @pantharshit00,
Thanks for response. Sure but just to be sure i got the feature correct: This feature is supposed to read a database model from an already created database and create prisma model from it am i correct?
I am supposed to share sql model of database right?

**Comment by pantharshit00** [comment] 2019-09-09 08:36
Yes, if introspection is failing completely, just share the schema of your database so that we can try a reproduction.

**Comment by AhmedElywa** [comment] 2019-09-18 06:03
[whmcs.pdf](https://github.com/prisma/prisma2/files/3624649/whmcs.pdf)
you can try with this schema i have same error

**Comment by AhmedElywa** [comment] 2019-09-18 06:52
![image](https://user-images.githubusercontent.com/4535142/65122576-9ca64980-d9f1-11e9-8d64-e898ed941f6d.png)
see the error

**Comment by AhmedElywa** [comment] 2019-09-18 08:14
Hello i try to use database with only one table in one time to know where the error in 
i get error in table have 
````status` enum('Active','Inactive','Closed') CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT 'Active',```

so the problem in `enum` type

**Comment by janpio** [comment] 2019-09-18 08:45
Can you please share the exact steps you take in the CLI `init` flow? I tried to create a database with a table with an enum as you mentioned, but could introspect and create the data model just fine - so probably we went a slighty different path during the wizard somewhere.

What is your `prisma -v`?
What version of MySQL are you using? 
Local or remote server?

**Comment by AhmedElywa** [comment] 2019-09-18 08:48
@janpio 

```
➜  $ mysql -V
mysql  Ver 8.0.17 for osx10.14 on x86_64 (Homebrew)
➜  $ prisma2 -v
prisma2@2.0.0-preview-11, binary version: 408c0c08746064a56c8ba7cb167bad49f1d2c2f7
```
in my local MacBook

**Comment by AhmedElywa** [comment] 2019-09-18 08:52
I tried with your table 

```
CREATE TABLE IF NOT EXISTS `bar` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `baz` enum('A','B','C') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'A',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `bar` (`id`, `baz`) VALUES
	(1, 'B'),
	(2, 'A');
```
Same error 
⠋ Introspecting MySQL schema  with 1  tables.
 ERROR  Introspection failed:
Cannot read property 'substring' of undefined

**Comment by janpio** [comment] 2019-09-18 08:54
Interesting, Prisma 2 currently does not really support MySQL 8: https://github.com/prisma/prisma2/issues/384 But as you are not getting this error, it means that in your case the user and database _do_ work and this might be a follow up error.

Here is some background on how that might be possible that it does work for your with MySQL 8: https://github.com/prisma/prisma2/issues/38#issuecomment-532176320 Can you maybe check that, this would enable us to maybe reproduce.

@Innomalist were you also testing with MySQL 8?

**Comment by AhmedElywa** [comment] 2019-09-18 08:57
error in #384  i know how you solve it

**Comment by Innomalist** [comment] 2019-09-18 09:00
@janpio Yes I was testing in mysql 8 too but the thing is the initial schemes I was receiving was for clients so I couldn't share scheme them publicly so I tried to reproduce the error with a test scheme but same error doesn't happens (another error happened in later stages).
So maybe mysql 8 by nature is not the problem I don't know

**Comment by janpio** [comment] 2019-09-18 10:19
Even with [the workaround](https://github.com/prisma/prisma2/issues/384#issuecomment-532594938) applied to make Prisma 2 work with MySQL 8 I can not reproduce the `Cannot read property 'substring' of undefined` error (but get https://github.com/prisma/prisma2/issues/546 before even being able to select a database/schema which is an unrelated thing).

**Comment by divyenduz** [comment] 2019-09-30 10:37
@AhmedElywa Can you still reproduce this? If yes, please `cmd + click` the line number just below the substring error. That should open the text editor and point you to the exact line where it is failing. That might give us more information to proceed.

**Comment by Innomalist** [comment] 2019-10-18 15:18
@divyenduz In my case the line doesn't have reference to anywhere so I would be able to click on it.
<img width="360" alt="Screen Shot 2019-10-18 at 19 17 55" src="https://user-images.githubusercontent.com/37414207/67106659-19d50200-f1dc-11e9-831f-280e41e2a565.png">

**Comment by Innomalist** [comment] 2019-10-18 15:23
With this simple database scheme this error can be reproduced:
```
create database prism;

use prism;

create table customer (
  id int primary key auto_increment,
  name varchar(100),
  type enum('regular', 'vip') default 'regular'
);

create table `order` (
  id int primary key auto_increment,
  customer_id int,
  foreign key (customer_id) references customer(id),
  item varchar(100)
)
```

**Comment by Innomalist** [comment] 2019-10-18 15:28
I can also confirm by removing enum field in customer table this error will be gone.

BTW: I am not sure about it but I am hopeful Prisma supports all mysql fields such as GEOMETRY fields too. I mean enum is a basic one of course.

**Comment by pantharshit00** [comment] 2019-10-18 15:55
@Innomalist 

I am unable to reproduce this. The database was introspected correctly with `prisma2@2.0.0-preview014.2, binary version: 237b46b97773f5018e336550e4285e2a78c38483`

```prisma
generator photon {
  provider = "photonjs"
}

datasource db {
  provider = "mysql"
  url      = "mysql://<REDACTED>@localhost:3306/"
}

model Customer {
  id    Int               @id
  name  String?
  order Order[]
  type  CustomerTypeEnum?

  @@map("customer")
}

model Order {
  id       Int       @id
  customer Customer? @map("customer_id")
  item     String?

  @@map("order")
}

enum CustomerTypeEnum {
  regular
  vip
}
```

Can you please make sure you are on the latest version?

**Comment by Innomalist** [comment] 2019-10-18 18:01
@pantharshit00 Thanks for response,
I am using npx so yes I think I am on latest version. Maybe this is related to having mysql version 8?

**Comment by pantharshit00** [comment] 2019-10-21 09:43
Can you please tell me the output of `mysqld --version` instead of mysql client version? Just to be sure here.

**Comment by Innomalist** [comment] 2019-10-21 12:17
@pantharshit00 Sadly i have removed mysql 8 in favor of mysql 5.7 to be able to use prisma (I couldn't :( ) so i can't check that. Maybe other users with same problem could tell that

**Comment by pantharshit00** [comment] 2019-10-21 13:25
Were you able to use Prisma with MySQL 5.7. Your comment didn't make that clear enough

**Comment by Innomalist** [comment] 2019-10-24 11:07
@pantharshit00 With mysql 5.7 this issue was gone but there was another issue I was facing on a later stage and it led to not being able to generate model files. As it was unrelated to this issue I didn't mentioned it in previous comment.

**Comment by janpio** [comment] 2019-10-29 14:31
Please coordinate with @do4gr that a schema that triggers this is added as a test case for Introspection @pantharshit00 <3

**Comment by divyenduz** [comment] 2020-01-09 16:00
We [rewrote introspection](https://github.com/prisma/prisma2/releases) recently. Can you please see if this issue still exists in the latest alpha or preview?

**Comment by pantharshit00** [comment] 2020-01-11 14:07
Unable to reproduce this now and I was even able to write data to the database without any issue. Closing, please comment here or open a new issue if you are still facing this..

**Closed** 2020-01-11 14:07 UTC
Labels: bug/2-confirmed, kind/bug, topic: old-introspection
