### ISSUE TITLE
[Photon] engine connect ECCONNREFUSED

### ISSUE THREAD

**Issue by Devlin556** [prisma/prisma2#1488] opened 2020-01-30 13:53 UTC
![image](https://user-images.githubusercontent.com/16045765/73455314-d7959200-4380-11ea-8bfa-9a09247f1d94.png)
prisma2 version is `prisma2@2.0.0 preview19`
engine version is `e7579bd35e0938dbf773f1706c098a0d14a5a038`
It happened when I tried to make many photon requests (about 100 requests). It may be fixed only by the server restart. The server works fine but the photon doesn't work until the server restart.

**Comment by UWellFail** [comment] 2020-01-30 14:02
Yes! I have the same problem, would be great to fix it.

**Comment by pantharshit00** [comment] 2020-01-30 14:17
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma-client-js/issues/272

Also, please follow https://github.com/prisma/prisma-client-js/issues/433

**Closed by pantharshit00** 2020-01-30 14:17 UTC
