### ISSUE TITLE
init hangs at 'introspecting database'

### ISSUE THREAD

**Issue by Andrew1325** [prisma/prisma2#377] opened 2019-08-19 22:37 UTC
When I try init it connects to the database but then just hangs on the introspection.

![Screen Shot 2019-08-19 at 8 32 40 pm](https://user-images.githubusercontent.com/38718635/63304142-69ef2f80-c325-11e9-8ce8-c66af15bb447.png)

It doesn't end, just sits like this until I ctrl-c to get out. Was going all night last night.

Am using a local postgres, new empty database that I can connect to and see in pgAdmin.

Can successfully complete init if I select sqlLite

**Comment by pantharshit00** [comment] 2019-08-20 10:21
Can you please tell me which version of postgres you are using. Also, please tell me the version of Prisma CLI you are using.

**Comment by pantharshit00** [comment] 2019-08-20 10:23
I am unable to reproduce this locally
![image](https://user-images.githubusercontent.com/22195362/63339505-a8efa600-c362-11e9-9d49-bdc2a3a32380.png)

**Comment by Andrew1325** [comment] 2019-08-20 10:27
The postgres version is 11.2
the prisma2 cli is prisma2@2.0.0-preview-7

**Comment by pantharshit00** [comment] 2019-08-20 10:35
I am using the same setup. 

Well, can you please try doing the creation of files manually and trying to connect to the database.

In an empty folder, make the following `prisma/schema.prisma` file:

```groovy
datasource db {
  provider = "postgresql"
  url      = "postgresql://<username>:<pass>@localhost:5432?schema=hello_prisma2"
}

model User {
  id String @id @default(cuid())
  name String
}
```

Change the username and password accordingly and run `prisma2 dev`. Then please check whether the tables have been created in your database or not.

**Comment by Andrew1325** [comment] 2019-08-20 10:50
Ok, it seems to just hang with that too. Nothing in the database. I checked postgres is running and restarted it anyway.

![Screen Shot 2019-08-20 at 8 48 22 pm](https://user-images.githubusercontent.com/38718635/63341194-09470d80-c38c-11e9-865d-809823d56e42.png)

**Comment by pantharshit00** [comment] 2019-08-20 11:07
Are you able to connect to the database using a GUI like postico or tableplus.io?

**Comment by Andrew1325** [comment] 2019-08-20 11:16
I've got pgAdmin and I can connect to it. I tried deleting the original database and creating a new one and running init again but still get the same thing. I can see the database in pgAdmin but it has no tables. I tried running introspect on "public" schema but still the same thing. 

It must be a postgres issue, surely. I did an init selecting sqLite and that went through ok.

**Comment by Andrew1325** [comment] 2019-08-20 11:16
I might set up a new heroku postgres database and try with that.

**Comment by Andrew1325** [comment] 2019-08-21 02:32
I have tried with a heroku database and have the exact same issue from my original post. Connects to the database and hangs on the introspection.

**Comment by Andrew1325** [comment] 2019-08-21 10:51
I have got around this by re-installing prisma2. It installed and gave the warning to install with --unsafe-perm flag which I did, `npm install --unsafe-perm  -g prisma2` and now it seems to work.

**Comment by pantharshit00** [comment] 2019-08-21 12:44
I guess the binary was not updated because of the lack of write permissions.

Since we don't have a reproduction and it is not fixed for you I am going to close this.

If anyone is still experiencing this, feel free to open a new issue.

**Closed by pantharshit00** 2019-08-21 12:44 UTC
Labels: bug/0-needs-info, kind/bug
