### ISSUE TITLE
Error on prisma2 init: Couldn't find any versions for "@prisma/engine-core" that matches "workspace:^2.0.8" (+others)

### ISSUE THREAD

**Issue by jladuval** [prisma/prisma2#957] opened 2019-11-19 12:34 UTC
Sorry for the long post, might be a couple of issues in here
```
$ npx prisma2 init
Preparing your starter kit: GraphQL API (+ Auth)

✔  Downloading the starter kit from GitHub ...
✔  Extracting content to ./ ...
⠴  Installing dependencies with: `npm install` ...
4  Preparing your database ...
5  Seeding your database with: `npm run seed` ...
 ERROR  Error during command execution

warning graphql-yoga > @types/graphql@14.5.0: This is a stub types definition. graphql pro
vides its own type definitions, so you do not need this installed.
warning graphql-yoga > apollo-upload-server@7.1.0: Please migrate to https://npm.im/graphq
l-upload (see https://git.io/fADhl).
warning graphql-yoga > apollo-server-express > apollo-server-core > graphql-extensions > c
ore-js@2.6.10: core-js@<3.0 is no longer maintained and not recommended for usage due to t
he number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
error Couldn't find any versions for "@prisma/engine-core" that matches "workspace:^2.0.8"
```
So with some playing around I get to here
```
$ npm i
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:^2.0.8
$ yarn
yarn install v1.17.3
info No lockfile found.
[1/4] Resolving packages...
warning graphql-yoga > @types/graphql@14.5.0: This is a stub types definition. graphql provides its own type definitions, so you do not need this installed.
warning graphql-yoga > apollo-upload-server@7.1.0: Please migrate to https://npm.im/graphql-upload (see https://git.io/fADhl).
warning graphql-yoga > apollo-server-lambda > apollo-server-core > graphql-extensions > core-js@2.6.10: core-js@<3.0 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
Couldn't find any versions for "@prisma/engine-core" that matches "workspace:^2.0.8"
? Please choose a version of "@prisma/engine-core" from this list: 2.0.8
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > graphql-shield@5.7.3" has unmet peer dependency "graphql-middleware@^2.0.0 || ^3.0.0".
warning "graphql-yoga > graphql-playground-middleware-lambda@1.7.12" has unmet peer dependency "aws-lambda@^0.1.2".
warning "graphql-yoga > graphql-subscriptions@0.5.8" has incorrect peer dependency "graphql@^0.10.5 || ^0.11.3 || ^0.12.0 || ^0.13.0".
warning "graphql-yoga > apollo-server-lambda > apollo-server-core@1.4.0" has incorrect peer dependency "graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
warning "graphql-yoga > apollo-server-lambda > apollo-server-core > graphql-extensions@0.0.10" has incorrect peer dependency "graphql@0.10.x - 0.13.x".
warning "graphql-yoga > apollo-server-lambda > apollo-server-core > apollo-tracing@0.1.4" has incorrect peer dependency "graphql@0.10.x - 0.13.x".
warning "graphql-yoga > apollo-server-lambda > apollo-server-core > apollo-cache-control@0.1.1" has incorrect peer dependency "graphql@0.10.x - 0.13.x".
[4/4] Building fresh packages...
success Saved lockfile.
$ npm -s run generate
> Downloading linux-glibc-libssl1.1.0 binary for query-engine [============] 100%

Generating Photon.js to /home/jacob/code/today/foo/node_modules/@generated/photon
Done in 2.48s

You should specify a configuration value for outputs in Nexus' makeSchema. Provide one to remove this warning.
Done in 25.70s.
```
So far so good _however_ running build gives a few more errors
```
$ yarn build
yarn run v1.17.3
$ npm -s run clean && npm -s run generate && tsc
> Downloading linux-glibc-libssl1.1.0 binary for query-engine [============] 100%

Generating Photon.js to PATH_TO_DIR/foo/node_modules/@generated/photon
Done in 2.90s

You should specify a configuration value for outputs in Nexus' makeSchema. Provide one to remove this warning.
node_modules/nexus-prisma/dist/dmmf/transformer.d.ts:2:22 - error TS7016: Could not find a declaration file for module '@prisma/photon'. 'PATH_TO_DIR/foo/node_modules/@prisma/photon/index.js' implicitly has an 'any' type.
  Try `npm install @types/prisma__photon` if it exists or add a new declaration (.d.ts) file containing `declare module '@prisma/photon';`

2 import { DMMF } from '@prisma/photon';
                       ~~~~~~~~~~~~~~~~

node_modules/nexus-prisma/dist/dmmf/utils.d.ts:1:25 - error TS7016: Could not find a declaration file for module '@prisma/photon'. 'PATH_TO_DIR/foo/node_modules/@prisma/photon/index.js' implicitly has an 'any' type.
  Try `npm install @types/prisma__photon` if it exists or add a new declaration (.d.ts) file containing `declare module '@prisma/photon';`

1 import * as Photon from '@prisma/photon';
                          ~~~~~~~~~~~~~~~~

src/types/Post.ts:6:7 - error TS2339: Property 'model' does not exist on type 'ObjectDefinitionBlock<"Post">'.

6     t.model.id()
        ~~~~~

src/types/Post.ts:9:7 - error TS2339: Property 'model' does not exist on type 'ObjectDefinitionBlock<"Post">'.

9     t.model.published()
        ~~~~~

src/types/Post.ts:10:7 - error TS2339: Property 'model' does not exist on type 'ObjectDefinitionBlock<"Post">'.

10     t.model.title()
         ~~~~~

src/types/Post.ts:11:7 - error TS2339: Property 'model' does not exist on type 'ObjectDefinitionBlock<"Post">'.

11     t.model.content()
         ~~~~~

src/types/Post.ts:12:7 - error TS2339: Property 'model' does not exist on type 'ObjectDefinitionBlock<"Post">'.

12     t.model.author()
         ~~~~~

src/types/User.ts:6:7 - error TS2339: Property 'model' does not exist on type 'ObjectDefinitionBlock<"User">'.

6     t.model.id()
        ~~~~~

src/types/User.ts:7:7 - error TS2339: Property 'model' does not exist on type 'ObjectDefinitionBlock<"User">'.

7     t.model.name()
        ~~~~~

src/types/User.ts:8:7 - error TS2339: Property 'model' does not exist on type 'ObjectDefinitionBlock<"User">'.

8     t.model.email()
        ~~~~~

src/types/User.ts:9:7 - error TS2339: Property 'model' does not exist on type 'ObjectDefinitionBlock<"User">'.

9     t.model.posts({ pagination: false })
        ~~~~~


Found 11 errors.

error Command failed with exit code 2.
```
My setup
```
$ node -v && npm -v && yarn -v && lsb_release -a
v12.8.0
6.13.1
1.17.3
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
```

**Comment by pantharshit00** [comment] 2019-11-20 13:17
I am unable to reproduce this. 

Details of the system that I used:
![image](https://user-images.githubusercontent.com/22195362/69242105-26c38780-0bc6-11ea-9add-103fb1154e1e.png)


Can you please make sure that you are on that latest version of the cli and please try this again one time again.

**Comment by pantharshit00** [comment] 2019-11-20 13:17
I am unable to reproduce this. 

Details of the system that I used:
![image](https://user-images.githubusercontent.com/22195362/69242105-26c38780-0bc6-11ea-9add-103fb1154e1e.png)


Can you please make sure that you are on that latest version of the cli and please try this again one time again.

**Comment by jladuval** [comment] 2019-11-20 14:07
I'm using `npx prisma2 init` so it should be using the latest. 
Just to double check though.
```
$ npx prisma2 -v
prisma2@2.0.0-preview016.2, binary version: b72fd0a786adc77ba6c61d0a9637ff0371e433b0
```
I noticed your node version though, so I updated to 13 and it got past the first issue. I've made this a little easier to debug by replicating it in a docker container.

```
$ docker run -it --rm node:13.1.0 bash
root@0ca6d40977ad:/# npm i -g --unsafe-perm prisma2
root@0ca6d40977ad:/# mkdir foo && cd foo && prisma2 init
# Now choose Starter Kit -> Typescript -> GraphQL + API (+ Auth) -> SQLite
root@0ca6d40977ad:/foo# npm run build
# You should see 11 Typescript build errors
```

**Comment by pantharshit00** [comment] 2019-11-20 15:22
Ok, this issue is already reported here: https://github.com/prisma/prisma-examples/issues/974

We will need to fix the examples :). I am going to close this issue as a duplicate.

**Closed** 2019-11-20 15:26 UTC
Labels: bug/2-confirmed, kind/bug
