### ISSUE TITLE
Changing `provider = "sqlite"` to `provider = "postgres"` does not crash any more.

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#1096] opened 2019-12-09 21:12 UTC
I used to be able to crash Lift by following these steps from https://github.com/prisma/prisma2/issues/617#issuecomment-536478218:

> * Create project with `prisma2 init foo`: `Blank project > SQLite > Confirm > Javascript > Demo script`
> * Open `prisma/schema.prisma` and replace `provider = "sqlite"` with `provider = "postgres"`
> * Run `prisma2 dev`

Now the replacement of `sqlite` with `postgres` in the `provider` is just ignored and the sqlite file is migrated anyway.

**Comment by pantharshit00** [comment] 2019-12-10 16:25
I can confirm this. Looks like we are ignoring the provider and just using the protocol from the URL as the parser.

**Comment by tomhoule** [comment] 2020-01-07 12:20
Yes it's a change in quaint I was afraid would leak through the public API, and it did indeed. I'll fix this.

**Comment by tomhoule** [comment] 2020-01-08 13:31
https://github.com/prisma/prisma-engine/pull/346 gives an error. Do we want to create a specific user facing error for this, to make the end-user experience nicer?

**Comment by janpio** [comment] 2020-01-14 11:17
Can you please see how this works now @pantharshit00 and if this is indeed a good way to trigger the Lift error reporting again?

**Comment by tomhoule** [comment] 2020-01-16 15:03
Status update: this now crashes with a readable and appropriate error message. What is left: decide if this is important enough to warrant a proper user facing error definition with an error code.

**Comment by tomhoule** [comment] 2020-01-30 14:27
I'll close this issue for now, as we have a decent error message. Please open a new issue for error reporting changes.

**Closed by tomhoule** 2020-01-30 14:27 UTC
Labels: bug/2-confirmed, kind/bug, topic: schema
