### ISSUE TITLE
prisma init flow doesn't work for local mysql

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma2#38] opened 2019-06-27 16:04 UTC
Keep getting `ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; co
nsider upgrading MySQL client`

Where the database client for TablePlus is correctly connecting:

<img width="1249" alt="Screen Shot 2019-06-27 at 6 03 56 PM" src="https://user-images.githubusercontent.com/170299/60281820-f6710900-9905-11e9-9356-aea375576937.png">

**Comment by divyenduz** [comment] 2019-06-28 13:31
I think this is related to MySQL 8 not being supported by the underlying connection provider? 

We should also have a better UI for error handling.

**Comment by timsuchanek** [comment] 2019-08-05 09:15
Belongs to https://github.com/prisma/prisma2/issues/278

**Comment by iki** [comment] 2019-09-17 11:16
Will this be fixed for prisma1 too?

Temporary workaround: ```ALTER USER 'user' IDENTIFIED WITH mysql_native_password BY 'password'```

Reason: MySQL 8.0 now uses `caching_sha2_password` by default, instead of `mysql_native_password` supported by most clients.

**Comment by janpio** [comment] 2019-09-17 16:57
@matthewmueller 's original issue here is actually a duplicate of this issue: https://github.com/prisma/prisma2/issues/384 So closing this now.

Did I understand correctly @iki that using `ALTER USER 'user' IDENTIFIED WITH mysql_native_password BY 'password'` might be a temporary workaround?

**Closed by janpio** 2019-09-17 16:57 UTC
Labels: bug/2-confirmed, kind/bug
