### ISSUE TITLE
Error with Prisma2 installation on Linux

### ISSUE THREAD

**Issue by frbrz** [prisma/prisma2#993] opened 2019-11-26 02:21 UTC
After installing prisma2 with the following command (#836) in a clean system (#966):

```
npm install -g --unsafe-perm prisma2
```

And simply doing:

```
prisma2 init hello-prisma
```

Whenever I try to run ```prisma2 dev``` I get the following error with Photon on Linux:

```
Failed to generate Photon client: Error: Error: Command failed with ENOENT: /home/username/Documents/Code/hello-prisma/node_modules/prisma2/query-engine-linux-glibc-libssl1.1.0 cli --dmmf
spawn /home/username/Documents/Code/hello-prisma/node_modules/prisma2/query-engine-linux-glibc-libssl1.1.0 ENOENT
    at Object.<anonymous> (/home/username/Documents/Code/hello-prisma/node_modules/prisma2/build/index.js:121706:19)
    at Generator.throw (<anonymous>)
    at rejected (/home/username/Documents/Code/hello-prisma/node_modules/prisma2/build/index.js:121635:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error starting Photon: TypeError: Cannot destructure property 'dmmf' of '(intermediate value)' as it is undefined.
    at Photon.start (/home/username/Documents/Code/hello-prisma/node_modules/prisma2/build/index.js:307034:25)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async connect (/home/username/Documents/Code/hello-prisma/node_modules/prisma2/build/photon-worker.js:44:31)
    at async process.<anonymous> (/home/username/Documents/Code/hello-prisma/node_modules/prisma2/build/photon-worker.js:9:18)
Error connecting to photon TypeError: Cannot destructure property 'dmmf' of '(intermediate value)' as it is undefined.
    at connect (/home/username/Documents/Code/hello-prisma/node_modules/prisma2/build/photon-worker.js:44:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async process.<anonymous> (/home/username/Documents/Code/hello-prisma/node_modules/prisma2/build/photon-worker.js:9:18)
```

My specs ```npx envinfo``` are the following:
```
  System:
    OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
    Container: Yes
    Shell: 3.0.2 - /usr/bin/fish
  Binaries:
    Node: 13.2.0 - ~/.config/nvm/13.2.0/bin/node
    Yarn: 1.19.1 - /usr/bin/yarn
    npm: 6.13.1 - ~/.config/nvm/13.2.0/bin/npm
  Utilities:
    Make: 4.2.1 - /usr/bin/make
    GCC: 8.3.0 - /usr/bin/gcc
    Git: 2.20.1 - /usr/bin/git
  Virtualization:
    Docker: 18.09.7 - /usr/bin/docker
    VirtualBox: 6.0.14 - /usr/bin/vboxmanage
  Languages:
    Bash: 5.0.3 - /bin/bash
    Perl: 5.28.1 - /usr/bin/perl
    Python: 2.7.16 - /usr/bin/python
    Ruby: 2.5.5 - /usr/bin/ruby
  Databases:
    MongoDB: 4.0.13 - /usr/bin/mongo
```

I already have libssl1.1 installed (#2) wich I can confirm by running ```apt-cache policy libssl1.1``` or ```openssl version -a```. The former says

```
libssl1.1:
  Installed: 1.1.1b-1ubuntu2.4
  Candidate: 1.1.1b-1ubuntu2.4
  Version table:
 *** 1.1.1b-1ubuntu2.4 500
        500 http://ar.archive.ubuntu.com/ubuntu disco-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     1.1.1b-1ubuntu2 500
        500 http://ar.archive.ubuntu.com/ubuntu disco/main amd64 Packages
```

My problem seems to emerge due to libssl1.1 or glibc (#2, specifically this comment https://github.com/prisma/prisma2/issues/2#issuecomment-541399718) but I have that library installed too,  wich I can confirm by running ```apt-cache policy libc-bin``` wich says

```
libc-bin:
  Installed: 2.29-0ubuntu2
  Candidate: 2.29-0ubuntu2
  Version table:
 *** 2.29-0ubuntu2 500
        500 http://ar.archive.ubuntu.com/ubuntu disco/main amd64 Packages
        100 /var/lib/dpkg/status
```

Other useful information (#935) is...

..."lsb_release -a"
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco
```

..."openssl version"
```
OpenSSL 1.1.1b  26 Feb 2019
```

...and "uname -a"
```
Linux envy 5.0.0-36-generic #39-Ubuntu SMP Tue Nov 12 09:46:06 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

Is there something I can do to effectively run Prisma2 on my Linux machine? 

////////////////////////

UPDATE: 

Even when I try to run ```npm install -g --unsafe-perm prisma2``` but with sudo privileges by doing ```sudo -s``` and with my VPN disabled (#938) I get the same error.

**Comment by FrancoisVeauvy** [comment] 2019-11-26 07:35
I got a similar issue in my dockerized environment.

**Comment by pantharshit00** [comment] 2019-11-26 17:41
I am unable to reproduce this. It is strange that your cli is still using the old binary name instead of the new ones. 

Can you please make sure that your cli is using on preview017 version?

I am unable to reproduce this with system with similar config:
```

  System:
    OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
    CPU: (1) x64 Intel(R) Xeon(R) CPU E5-2650L v3 @ 1.80GHz
    Memory: 400.54 MB / 983.02 MB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 10.15.2 - /usr/bin/node
    npm: 5.8.0 - /usr/bin/npm
  Managers:
    Apt: 1.8.3 - /usr/bin/apt
  Utilities:
    Make: 4.2.1 - /usr/bin/make
    GCC: 8.3.0 - /usr/bin/gcc
    Git: 2.20.1 - /usr/bin/git
  IDEs:
    Nano: 3.2 - /usr/bin/nano
    Vim: 8.1 - /usr/bin/vim
  Languages:
    Bash: 5.0.3 - /usr/bin/bash
    Perl: 5.28.1 - /usr/bin/perl
    Python: 2.7.16 - /usr/bin/python
    Python3: 3.7.3 - /usr/bin/python3
```

```
prisma2@2.0.0-preview017, binary version: 6159bf3a263921c3c28ee68e2c9e130b5a69c293
```

**Comment by frbrz** [comment] 2019-11-26 21:55
I tried again today doing this ```npm install -g --unsafe-perm prisma2@2.0.0-preview017``` wich showed me the same message that I was seeing before but I forgot to post here:
```
> prisma2@2.0.0-preview017 install /home/username/.config/nvm/13.2.0/lib/node_modules/prisma2
> node download-build/index.js || echo ""

> Downloading debian-openssl-1.1.x binary for query-engine and migration-engine [====================] 100%

+ prisma2@2.0.0-preview017
added 1 package from 1 contributor in 9.784s
```

```prisma2 dev``` gave me exactly the same result of ```command failed with ENOENT [...]```.

You said: 
> It is strange that your cli is still using the old binary name instead of the new ones.

This is interesting because I tried to install prisma2 when it was announced and (I think) it gave me the same error at that time. I used ```yarn global add prisma2``` at that time. I tried with yarn too yesterday with no avail.

**Comment by pantharshit00** [comment] 2019-11-27 18:40
Thanks, I am able to reproduce this now with Ubuntu 19.04 with nvm and with a sudo user. The global installation is without `--unsafe-perm` here as I used nvm.

![image](https://user-images.githubusercontent.com/22195362/69750578-15085400-1173-11ea-99b2-46595623b855.png)


```
prisma2@2.0.0-preview017.1, binary version: 6159bf3a263921c3c28ee68e2c9e130b5a69c293
```

I think this issue is very similar to https://github.com/prisma/prisma2/issues/999  so might get already fixed once https://github.com/prisma/prisma2/issues/999 as we are working on that one.

I think we are still using the old binary names for that command somehow.

**Comment by frbrz** [comment] 2019-11-28 00:31
Thank you @pantharshit00 for your time. Please keep me informed if you have news. 
I will test again with every minor version, as I'm eager to start new projects with Prisma2.

**Comment by timsuchanek** [comment] 2019-11-28 10:09
Thanks @frbrz for providing all the infos! We just released a new alpha - alpha.368. Please try it out, it should fix the `prisma2 dev` command :)

**Comment by rejmank** [comment] 2019-11-28 12:01
This is what i see when acces localhost:555 
![image](https://user-images.githubusercontent.com/10515532/69804558-225b2800-11df-11ea-8fd3-f5233829321c.png)
(ubuntu on wls)

**Comment by FrancoisVeauvy** [comment] 2019-11-28 12:56
> This is what i see when acces localhost:555
> ![image](https://user-images.githubusercontent.com/10515532/69804558-225b2800-11df-11ea-8fd3-f5233829321c.png)
> It is only chrome issue, on firefox everything is working fine

I got a similar output in localhost:5555 with prisma2.0.0 alpha 368 on docker after prisma2 dev

**Comment by timsuchanek** [comment] 2019-11-28 13:57
Thanks for reporting that, everyone! The big plus should be gone now in the latest alpha (369).
We'll do a patch release now including a fix for this!
Let me know if it's still an issue for you and I'll reopen this issue.

**Closed by timsuchanek** 2019-11-28 13:57 UTC
Labels: bug/2-confirmed, kind/bug

**Comment by FrancoisVeauvy** [comment] 2019-11-28 14:29
It's working fine now.
Thank you very much !

**Comment by frbrz** [comment] 2019-11-29 03:47
Marvelous team. Thank you !
