### ISSUE TITLE
@@unique not supported

### ISSUE THREAD

**Issue by zzyyzz1992** [prisma/prisma2#271] opened 2019-07-29 12:14 UTC
It seems that @@unique not supported. Please fix this.

Relevant issue(#266 )

![image](https://user-images.githubusercontent.com/3894825/62043355-b7024900-b232-11e9-8af9-0fea4a52752b.png)
![image](https://user-images.githubusercontent.com/3894825/62043385-cb464600-b232-11e9-94e4-52af26afbb33.png)

Here is [the schema file](https://gist.github.com/zzyyzz1992/b14bce7a6433f1e2e68635fb5b068854),

**Comment by zzyyzz1992** [comment] 2019-07-29 12:16
Noticing that sometimes vscode reporting attribute not known, sometimes it reporting unexpect token error

**Comment by pantharshit00** [comment] 2019-07-29 12:31
This hasn’t been implemented yet. It will get implemented in the coming weeks.

**Comment by timsuchanek** [comment] 2019-07-29 13:20
Duplicate of https://github.com/prisma/lift/issues/29

**Closed** 2019-08-05 09:54 UTC
Labels: kind/feature, priority/mid
