### ISSUE TITLE
[Ubuntu 19.04] - Prisma2 Init hangs at "Preparing your database" when using MySQL database

### ISSUE THREAD

**Issue by izio38** [prisma/prisma2#522] opened 2019-09-08 07:51 UTC
I just started by installing prisma2 globally, goes into `/stacks` and start with a boilerplate (GraphQL API (+Auth))

### Tree:
![image](https://user-images.githubusercontent.com/9900846/64485175-70cedb00-d21d-11e9-991c-22f5a6ae394a.png)

### Prisma2 version:
`prisma2@2.0.0-preview-10, binary version: 1b0c271f14ca00606f56c93717e228fe48c5603c`

### MySQL version:
`8.0.17` via docker hub (latest)

### Nodejs version:
`v10.15.2`

### Docker compose file:
```
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: ChangeMe
      MYSQL_DATABASE: izio
```

### Command I wrote:
`prisma2 init project`

### Database overview (via adminer):
![image](https://user-images.githubusercontent.com/9900846/64485221-0bc7b500-d21e-11e9-9e00-452e6f43774b.png)
![image](https://user-images.githubusercontent.com/9900846/64485224-171ae080-d21e-11e9-88b7-ea14890f1f10.png)

### Output:
![image](https://user-images.githubusercontent.com/9900846/64485212-e89d0580-d21d-11e9-95bf-2ff10d87a87c.png)

### After some tries:
It seems it worked with a PostgresQL server instance:
```
  kong-database:
    image: postgres
    restart: always
    container_name: kong-database
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: ChangeMe
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 3308:5432
    volumes:
      - kong-postgres-data:/var/lib/postgresql/data/pgdata
```
![image](https://user-images.githubusercontent.com/9900846/64485456-7e865f80-d221-11e9-885f-3baca09f9647.png)

If you need other informations, feel free to ask. However, I'm not an expert... :)

**Comment by pantharshit00** [comment] 2019-09-09 08:28
Duplicate of https://github.com/prisma/prisma2/issues/384

Can you please try this again using MySQL 5.7?

If you can still reproduce this with MySQL 5.7, please comment here so I can reopen the issue.

**Comment by shah05** [comment] 2019-11-11 04:33
Hi, 
![image](https://user-images.githubusercontent.com/20430495/68561174-67f9c000-047f-11ea-858f-fd1848080aa9.png)

**Comment by shah05** [comment] 2019-11-11 04:35
Hi, I am facing similar issues. Trying to create a Javascript client against MySQL DB (5.7).

I am following the tutorial in GitHub but the project initialization gets stuck at "Preparing your database" for a long time. Please help ?

Prisma2 version : prisma2@2.0.0-preview016.1

**Comment by darrylyoung** [comment] 2019-11-13 15:47
I'm also going through the tutorial and it's hanging on "Preparing your database...". I'm using `2.0.0-preview016.2` and testing with a MySQL 5.7 database on RDS. I chose TypeScript, by the way.

**Comment by pantharshit00** [comment] 2019-11-14 06:48
I think you all are running into https://github.com/prisma/prisma2/issues/884.

Can you please try cancelling the preparing step with `Ctrl + C` and performing `prisma2 lift save` and `prisma2 lift up` on the generated files. If you ran into `certificate not trusted` error, please add `&sslaccept=accept_invalid_certs` to your connection string in schema.prisma file meanwhile we fix this issue.

**Comment by tomhoule** [comment] 2019-11-15 15:20
https://github.com/prisma/prisma2/issues/884 is specific to postgres, I think it's probably something different on MySQL.

**Comment by shah05** [comment] 2019-11-18 13:31
Ok guys I managed to resolve from my side. I updated my nodejs to the latest version (12). Before this was using node version 8.

**Comment by chernandezweb** [comment] 2019-11-21 00:30
![image](https://user-images.githubusercontent.com/22950332/69289952-3b0a8300-0bcc-11ea-88c8-2ad5c0e57a7a.png)

I am having the issue.

**Comment by chernandezweb** [comment] 2019-11-21 00:31
I ran in debug mode as you said

**Comment by chernandezweb** [comment] 2019-11-21 01:08
I figured out a way fix the issue on my side. It's weird.

Actually the problem was happening when I didnt specify the specific database when database infos are asked and selected it in suggested databases.

So I tried to put the name of the database a the beginning where it says (optional), then on the next step it says it didnt find it, but it still appears on the suggested databases. So I select it from there an then it worked. 

I can't tell what is the cause. I sent the error report on debug mode.

**Comment by pantharshit00** [comment] 2019-11-21 12:54
@chernandezweb Looks like your issue is related to https://github.com/prisma/prisma2/issues/778. So the fix is to add the mysql database name in the url in the schema manually.

**Comment by TSTsankov** [comment] 2019-12-06 11:36
I had the same issue (being stuck at Preparing the database) for a bit, then I upgraded my MySQL from 5.5 to 5.6 and the issue was resolved. Even the old prisma had problems with <= 5.5...

**Comment by pantharshit00** [comment] 2019-12-06 14:37
Yes, we currently recommend you to use MySQL 5.7 as our tests are running on that.

**Comment by pantharshit00** [comment] 2019-12-06 14:37
I am going to close this issue now, feel free to open a new issue if someone is still facing this.

**Closed by pantharshit00** 2019-12-06 14:37 UTC
Labels: bug/0-needs-info, kind/bug
