### ISSUE TITLE
Question about find's methods

### ISSUE THREAD

**Issue by yovanoc** [prisma/prisma2#230] opened 2019-07-24 13:29 UTC
Currently when a record is not found in the database we have that:

![image](https://user-images.githubusercontent.com/7302317/61797375-9481c180-ae27-11e9-8887-866e443f5173.png)

But I think it will be better to return `undefined` in this case, to check with an if like so:

![image](https://user-images.githubusercontent.com/7302317/61797445-b54a1700-ae27-11e9-8494-7a819fcdd0ec.png)

e.g the return type should be `User | undefined` I think, so give me your opinion about that, thanks

**Comment by pantharshit00** [comment] 2019-07-25 16:19
Closing as a duplicate of https://github.com/prisma/photonjs/issues/89

**Closed by pantharshit00** 2019-07-25 16:19 UTC
