### ISSUE TITLE
Error with Prisma v15: can't find prisma.schema

### ISSUE THREAD

**Issue by CaptainChemist** [prisma/prisma2#824] opened 2019-10-22 17:32 UTC
I updated to prisma version 15 and when I run prisma2 generate in a docker environment, I receive the error:

```
Error: Can't find prisma.schema
```

I don't see that the filename has been changed from `schema.prisma` to `prisma.schema` so this seems like a bug.

**Comment by janpio** [comment] 2019-10-22 18:05
Can you tell us a bit more about the steps you took to create your project so we can try to reproduce this? Did you create a new project with `prisma2 init` or do you have an existing one?

**Comment by janpio** [comment] 2019-10-22 18:16
Ok, so I can reproduce the wrongly worded error message when I create a new project with `prisma2 init` (Blank, SQLite, both, Demo), go into the project, rename the `schema.prisma` file and then run `prisma2 generate`:

```
C:\Users\Jan\Documents\throwaway\preview15  (script@1.0.0)
λ prisma2 generate
Error: Can't find prisma.schema

C:\Users\Jan\Documents\throwaway\preview15  (script@1.0.0)
λ ls prisma
dev.db  migrations/  schemdfa.prisma
```

**Comment by janpio** [comment] 2019-10-22 18:17
@CaptainChemist So now the question is, should you actually be getting the error message? Do you have a `prisma/schema.prisma` file in your project?

**Comment by timsuchanek** [comment] 2019-10-23 08:30
The latest alpha has a fix with the correct error message.
In case you indeed didn't have a `schema.prisma` file in your folder, we can close this.

**Comment by CaptainChemist** [comment] 2019-10-23 20:12
All I did was upgrade from version 13.2 where it was working and I had a schema.prisma file located in the prisma folder. It's funny though because today I cannot reproduce this issue, so I am not exactly sure what it is. 

From what @timsuchanek is saying, the error message incorrectly was identifying the wrong file as missing, so perhaps my docker volumes were out of wack and even though my project had that file locally, perhaps it was missing in the docker container. I did notice that naming the file `schema.prisma` or `prisma.schema` didn't actually affect the error that I was receiving, so that does point to a docker/user related error. :)

In any case, I'll close this for now. Thanks everyone!

**Comment by ajmcclary** [comment] 2019-10-23 21:12
I'm having the exact same issue.  The error message states "prisma.schema" instead of "schema.prisma". I think that's just a typo. 

But my installation can't find the schema.prisma file either when I use the following command (which is automatically run postinstall): cd libs/nest/api-photon && prisma2 generate

**Comment by ajmcclary** [comment] 2019-10-23 21:17
Thought I'd mention, I installed the latest alpha and I still have the same issue as @CaptainChemist. The error message is fixed, but it still won't find the schema.prisma like it does in previous versions.

**Comment by ajmcclary** [comment] 2019-10-23 21:19
@janpio, thought I'd share (since I'm having the same problem as @CaptainChemist), I did not start my project with prisma2 init. I started from an existing project. That might explain some things. I'm using an NX mono-repo. I'm guessing bet the path in the version 15 release changed?

**Comment by CaptainChemist** [comment] 2019-10-23 21:27
@ajmcclary Are you working in a dockerized or non-dockerized environment? Also you should try running `prisma2 -v` to make sure your global version is what you think it is since that could potentially switch around if you are using `nvm` or a similar node version manager.

**Comment by ajmcclary** [comment] 2019-10-23 21:28
@CaptainChemist, I just figured it out. They introduced a new environmental variable:

process.env.INIT_CWD

So that is why it couldn't find it.

**Comment by ajmcclary** [comment] 2019-10-23 21:31
Also, thank you for the suggestion. I'm non-dockerized, but I'm using an Nx repo. So my directory structure is different than a normal installation.

**Comment by ajmcclary** [comment] 2019-10-23 21:40
OMG, @CaptainChemist, I did what you mentioned (just to be safe) and it WAS showing an older version of Prisma2! I swear and I double and triple checked it before I posted my comment.  As soon as I rebooted, the new version finally showed up.

**Comment by CaptainChemist** [comment] 2019-10-23 21:45
Ha computers will be the death of us all- I'm glad you have it working better now!

**Comment by poulainv** [comment] 2019-10-25 12:58
I am facing the same issue when I am trying to deploy on Now. 
My dependencies: 
```
{
    // ...
    "prisma2": "^2.0.0-preview015",
    "nexus": "^0.12.0-beta.14",
    "nexus-prisma": "^0.5.0",
}
```

My prisma2 version
```bash
prisma2 -v
prisma2@2.0.0-preview015, binary version: 20b6dc13949cccccfef5be07c0be7a3d7c858abe
```

I only get the error on Now during build
```bash
> script@ postinstall /zeit/56e0d573/api
--
02:53:48 PM | > yarn -s generate
02:53:50 PM | Error: Can't find prisma.schema
```

I was able to reproduce error many times. I did not create a new project from scratch, I updated an existing one.

**Comment by poulainv** [comment] 2019-10-25 13:18
Note that my `schema.prisma` is located in `api/prisma/schema.prisma` 
Locally I make it work setting `INIT_CWD` variable to `api`. 
On Now I've tried to add 
```
{
    "INIT_CWD": "api"
}
```
without success

**Comment by iherger** [comment] 2019-10-26 06:09
Same problem here (works locally, but can't deploy to Now [or Heroku, for that matter])

**Comment by poulainv** [comment] 2019-10-26 11:19
Is your prisma directory located in a subdirectory as well?

**Comment by iherger** [comment] 2019-10-26 12:16
@poulainv , no, I am using the standard setup with `schema.prisma` located in the `prisma` directory.

**Comment by pantharshit00** [comment] 2019-10-28 10:37
Hi everyone,

We have recently merged a PR fixing this issue but it is not available in a preview yet: https://github.com/prisma/prisma2/pull/789

Can you please test this out using the alpha channel. `npm install -g prisma2@alpha`

**Comment by iherger** [comment] 2019-10-28 13:09
My deployment to zeit now still fails.

Here's the build log:
```
Installing build runtime...
Build runtime installed: 3873.861ms
Looking up build cache...
Downloading user files...
download complete [0ms]
Installing dependencies...
missing `engines` in `package.json`, using default range: 8.10.x
Installing to /zeit/60a17008/src
yarn install v1.17.3
warning package.json: No license field
warning typescript-graphql: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "graphql-yoga > graphql-playground-middleware-lambda@1.7.12" has unmet peer dependency "aws-lambda@^0.1.2".
warning "graphql-yoga > graphql-subscriptions@0.5.8" has incorrect peer dependency "graphql@^0.10.5 || ^0.11.3 || ^0.12.0 || ^0.13.0".
warning "graphql-yoga > apollo-server-express > apollo-server-core@1.4.0" has incorrect peer dependency "graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
warning "graphql-yoga > apollo-server-express > apollo-server-core > apollo-cache-control@0.1.1" has incorrect peer dependency "graphql@0.10.x - 0.13.x".
warning "graphql-yoga > apollo-server-express > apollo-server-core > apollo-tracing@0.1.4" has incorrect peer dependency "graphql@0.10.x - 0.13.x".
warning "graphql-yoga > apollo-server-express > apollo-server-core > graphql-extensions@0.0.10" has incorrect peer dependency "graphql@0.10.x - 0.13.x".
[4/4] Building fresh packages...
$ prisma2 generate
Error: Can't find schema.prisma
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Exited with 1
    at ChildProcess.child.on (/zeit/f07645855977bda8/.build-utils/.builder/node_modules/@now/node/dist/index.js:78330:24)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
worker exited with code 20 and signal null
done
```
Repo: https://github.com/iherger/prisma2-now

**Comment by aifedespaix** [comment] 2019-10-28 14:58
@iherger I think zeit now prepare the container by installing only packages.
src files are copied after.

Try to remove the "postinstall" line from your `package.json`
And config your zeit now to run `npm run generate` post build.

(I got the same issue with my dockerfile)

**Comment by iherger** [comment] 2019-10-28 15:09
Thanks, @aifedespaix 

I am hesitant to make the changes you suggest because a) the repo would deploy to zeit now without any problems before and b) the "official" prisma2 zeit now deployment example also uses `postinstall`, see: https://github.com/prisma/prisma-examples/blob/prisma2/deployment-platforms/zeit-now/api/package.json

**Comment by aputinski** [comment] 2019-10-30 15:12
I'm having the same issue when deploying to Firebase functions. This was working fine in `2.0.0-preview-12`

**Comment by timsuchanek** [comment] 2019-11-04 10:57
Thanks a lot for reporting everyone! That was a regression introduced in https://github.com/prisma/prisma2/pull/789/files.

We will have a fix on alpha in about 10min.
You can install it with `npm install -g prisma2@alpha`.

**Comment by iherger** [comment] 2019-11-04 13:59
@timsuchanek , unfortunately, this still doesn't work for me on zeit now with `alpha-279`.

**Comment by timsuchanek** [comment] 2019-11-04 14:59
Thanks @iherger ! Is that the case in the repo you shared? https://github.com/iherger/prisma2-now

We just tested it with an internal Now deployment and it got fixed in alpha.279.
Can you validate that you didn't just update the global prisma2 version, but also in the `package.json` of the example?

**Comment by iherger** [comment] 2019-11-04 15:12
@timsuchanek , I tested with another repo, but https://github.com/iherger/prisma2-now actually also doesn't work (I just upgraded `package.json` and redeployed).

**Comment by timsuchanek** [comment] 2019-11-04 15:25
@iherger I just tried your repo and I can successfully deploy it https://prisma2-now.timsuchanek.now.sh/

**Comment by iherger** [comment] 2019-11-04 15:35
@timsuchanek , nothing short of magic!  

I can deploy it locally, using `now dev` but not remotely on zeit...

Are you also using a postgresql database?

**Comment by timsuchanek** [comment] 2019-11-04 15:56
Hmm interesting. I've kept the postgres env var empty, so it fails in runtime, but the error "Can't find prisma.schema" aka "Can't find schema.prisma" doesn't appear anymore.

**Comment by iherger** [comment] 2019-11-04 16:21
@timsuchanek so you are not using now secrets, if I unterstand you correctly, and everything elsr is the same as in the repo. Maybe it‘s got something to with those now secrets. I can test tomorrow, and will let you know my findings.

**Comment by poulainv** [comment] 2019-11-05 22:10
On my side, this patch have fixed this issue

**Comment by pantharshit00** [comment] 2019-11-06 11:44
@iherger were you able to still reproduce this?

**Comment by iherger** [comment] 2019-11-06 14:34
@pantharshit00 , yes, I am still able to reproduce it.

What I found, though, is that it works if I use `npm` in my build script, and it will fail (with the error above) when I use `yarn`.

**Comment by pantharshit00** [comment] 2019-11-08 09:48
I am also able to deploy your repo and I am sure that zeit used yarn for this:
![image](https://user-images.githubusercontent.com/22195362/68466662-df8add80-023a-11ea-8e03-a52c33c31c58.png)


Also, try with preview 016 once.

**Comment by iherger** [comment] 2019-11-08 19:33
@pantharshit00 , I can now longer reproduce this.

**Comment by timsuchanek** [comment] 2019-11-10 10:53
Perfect! Then I'll close this for now. In case you can reproduce it again, just let us know and we'll reopen.

**Closed by timsuchanek** 2019-11-10 10:53 UTC
Labels: bug/0-needs-info, kind/bug

**Comment by ephor** [comment] 2019-12-13 09:58
This error appears again in preview 18.2

**Comment by robabby** [comment] 2019-12-15 19:16
Also getting this in the latest alpha.

**Comment by pantharshit00** [comment] 2019-12-17 13:28
@robabby or @ephor Can you please open a new issue with a minimal reproduction? State whether you are getting it while development or when you are trying to deploy Prisma to something like now.

**Comment by robabby** [comment] 2019-12-19 21:45
@pantharshit00 I'll be back in this code over the weekend and see if I can still repro the issue on the latest versions that have been released this week and report back.

**Comment by AviBueno** [comment] 2020-07-15 16:48
Prisma `2.2.1` with `prisma/schema.prisma' at the root of the project.

Trying to deploy to AWS Beanstalk, I get the following error:
`Error: Either provide --schema or make sure that you are in a folder with a schema.prisma file.`

It happens during this phase:
```
> @prisma/client@2.2.1 postinstall /var/app/staging/node_modules/@prisma/client
> node scripts/postinstall.js
```

Any ideas?

**Comment by pantharshit00** [comment] 2020-07-15 16:54
@AviBueno Please open a new issue with a minimal reproduction. Thanks!

**Comment by binajmen** [comment] 2021-03-14 22:01
> I'm having the same issue when deploying to Firebase functions. This was working fine in `2.0.0-preview-12`. I'm using `2.0.0-alpha.276`

Did you manage to solved it?

**Comment by miriam-may** [comment] 2022-09-04 22:17
I'm having the same issue with Prisma 4.3.1 - when I run the command `npx prisma migrate dev --name init` I get `could not find a schema.prisma file that is required for this command`. I have the schema.prisma file in the default location (./prisma/schema.prisma). I tried adding the file path to my package.json as well just in case, but am getting the same error. Has there been any updates on this?

**Comment by janpio** [comment] 2022-09-06 22:29
This is a closed issue, so there will be no more updates. If you still have this problem, please open a new issue and provide all the information the issue template asks for. Thanks.
