### ISSUE TITLE
Follow [2.0.0-preview017] Error: Get config SyntaxError: Unexpected token P in JSON at position 0

### ISSUE THREAD

**Issue by YannSuissa** [prisma/prisma2#1284] opened 2020-01-07 11:53 UTC
following the issue : [https://github.com/prisma/prisma2/issues/985](https://github.com/prisma/prisma2/issues/985) that have been closed (I didn't had time to post my solution)

I managed to make it fully works with 2.0.0-preview019 under windows.

I had 2 problems : 
- Git bash : it's not good since some prisma2 menus are using termcaps and it's not really supported under git bash, first thing to do is to install hyper : [https://hyper.is/](https://hyper.is/), and since problems comes after anothers, the installer freeze under windows and after some searches you just have to wait for the installer to finish (about 5-10 minutes)

- prisma2 : not installed globally, but doing it requires everything must be done right
=> clean node_modules
=> `npm -g install prisma2`
=> here is my `package.json` (photon must be 2.0.0-preview019 too), (do an `npm install` to have all the packages installed) : 

```
 {
   "name": "graphql-auth",
   "version": "1.0.0",
   "dependencies": {
     "@prisma/photon": "^2.0.0-preview019",
     "bcryptjs": "2.4.3",
     "graphql": "14.5.8",
     "graphql-shield": "5.7.3",
     "graphql-yoga": "1.18.3",
     "jsonwebtoken": "8.5.1",
     "nexus": "0.12.0-rc.5",
     "nexus-prisma": "0.6.1"
   },
   "scripts": {
     "dev": "node src",
     "seed": "node prisma/seed"
   },
   "devDependencies": {
     "prisma2": "2.0.0-preview019"
   },
   "prettier": {
     "singleQuote": true,
     "semi": false,
     "trailingComma": "all"
   }
 }
```

Now everything works fine under windows with the last prisma version.
Hope it helps
Yann

**Comment by pantharshit00** [comment] 2020-01-07 13:08
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of #1232

**Comment by pantharshit00** [comment] 2020-01-07 13:09
As a workaround, please run `npm install -g prisma2` to redownload the binaries. Read #1232 for more details

**Closed by pantharshit00** 2020-01-07 13:08 UTC
