### ISSUE TITLE
query-engine and migration-engine executable bit missing in Docker container

### ISSUE THREAD

**Issue by ghost** [prisma/prisma2#601] opened 2019-09-25 16:37 UTC
Hi,

when you run `yarn add prisma2` in a Docker container as a user that doesn't exist inside the container, `query-engine` and `migration-engine` aren't executable.

This works because the user "node" exists inside the container:

```sh
mkdir ~/test1 && chown 1000:1000 ~/test1 && cd ~/test1
docker run --rm -u node:node -v $PWD:/test -w /test node yarn add prisma2
```

This doesn't work:

```sh
mkdir ~/test2 && chown 1234:1234 ~/test2 && cd ~/test2
docker run --rm -u 1234:1234 -v $PWD:/test -w /test node yarn add prisma2
ls -Al node_modules # -> query-engine and migration-engine aren't executable
```

I was able to ignore this by building my own images for the last few weeks, but now I've discovered that this is pretty much how the Docker executor of GitLab Runner works - which means I can't run tests or build images in GitLab Runner because of this.

**Comment by divyenduz** [comment] 2019-09-26 09:43
Did you checkout the docker example we have: https://github.com/prisma/prisma-examples/tree/prisma2/deployment-platforms/docker

**Comment by lboecker** [comment] 2019-09-26 14:44
I haven't, but setting `unsafe-perm` doesn't help if that's what you mean.

**Comment by lboecker** [comment] 2019-09-26 19:07
Just to emphasize one thing: Even if I build a Docker image, create a user in it (or use the "node" user they provide), copy my app into it, etc. I still can't build that image inside a Docker container because the executable bits are missing again.

So as far as I can tell, there currently is no way to build a Docker image containing an app that depends on prisma2 inside a container running in Docker or Kubernetes.

**Comment by divyenduz** [comment] 2019-09-27 16:50
@lboecker Interesting, can you please try the docker example that we have cooked and map that back to

> So as far as I can tell, there currently is no way to build a Docker image containing an app that depends on prisma2 inside a container running in Docker or Kubernetes.

What is different in our example as opposed to what you need? 

Here are some key aspects of how our example works: 

1. We are using a specific docker image (https://github.com/prisma/prisma-examples/blob/prisma2/deployment-platforms/docker/Dockerfile#L1) that has the necessary environment to make Photon's binaries work. What docker base image are you using? Most of the images should work. The dependencies are mainly `openssl` and `node`. 

2. We run `prisma2 generate` inside docker to fetch the correct binaries inside the container. 

Does that answer your question?

**Comment by lboecker** [comment] 2019-09-27 19:14
The base images I've tried are node:latest (which currently is 12.10.0-stretch) and node:12.10.0-buster. Both should be fine.

There are two differences between your example and what I'm trying to do:

1. You're installing prisma2 as the user root, I'm installing it as a user that doesn't exist inside the image. (I'm using the UID and GID "1234" as an example, but you could use something else.)
2. You're installing prisma2 globally.

Other than you installing prisma2 globally, what you're doing in your Dockerfile is equivalent to the first example in my first post (the one that works). So I assume your Dockerfile also works.

It stops working as soon as you try to build the image in another Docker container (I use [kaniko](https://github.com/GoogleContainerTools/kaniko) for this), or when you run one of the base images, mount your app into the container and change the user to the one you're using on your host system. That is, assuming a user with the same UID and GID doesn't also exist in the image. That's what I'm doing in both of my examples and how GitLab Runner works.

**Comment by lboecker** [comment] 2019-09-27 19:52
By the way (I hope I'm not coming off as rude or anything), but since you asked if this answers my question and you labeled this issue a question, do you really understand the two examples from my first post? I feel like it should be pretty obvious that they both should work.

**Comment by divyenduz** [comment] 2019-09-28 14:51
@lboecker Thanks for the detailed comments, I completely understand now. I will do some further research into this and get back, I agree that the original examples should work. 

I originally marked this as a question because I understood it like that but this now looks like a bug/usability issue 👍

**Comment by lboecker** [comment] 2019-09-28 15:34
@divyenduz Thanks! I appreciate you looking into it. You should be able to reproduce the issue by running the `docker run` commands.

If I had to guess, I'd say there's probably a post-install script somewhere that downloads query-engine and migration-engine for a given platform and then tries to set the executable bit. It looks like that code doesn't work under the circumstances I described above.

**Comment by divyenduz** [comment] 2019-10-01 09:08
@lboecker in the workflow that does not work, what step fails for you exactly and with what error? Asking because there are multiple binaries and it could be that all workflows do not fail. 

Photon for example in runtime sets the executable bit if it does not exist. 

Would it be possible for you to share a minimal reproduction with a `Dockerfile` and exact steps of what doesn't work. 

I understand the you mention the executable bits are not set in certain circumstances but what operation failed for you?

**Comment by lboecker** [comment] 2019-10-01 17:05
Here are the steps to reproduce the issue:

1. Create a test directory (e.g., `~/test`)
2. Create ~/test/package.json with the following contents:

```json
{
  "name": "test",
  "version": "0.1.0",
  "dependencies": {
    "prisma2": "*"
  }
}
```

3. Copy and paste [this](https://github.com/prisma/prisma2/blob/master/docs/prisma-schema-file.md#example) example to `~/test/prisma/schema.prisma`
4. Run the following command to change to owner of the test directory to a UID/GID that doesn't exist in the node base image:

```sh
sudo chown -R 1234:1234 ~/test
```
5. Change to the test directory and run `yarn install` and `prisma2 generate`:

```sh
cd ~/test
sudo docker run --rm -u 1234:1234 -v "$PWD":/app -w /app node /bin/bash -c 'yarn install && yarn prisma2 generate'
```

That's it. On my machine this fails with the following error:
```
[migration-engine] error: Error: spawn /app/node_modules/prisma2/migration-engine EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'spawn /app/node_modules/prisma2/migration-engine',
  path: '/app/node_modules/prisma2/migration-engine',
  spawnargs: []
}
Error: Error in lift engine: 
```

Which makes sense given that the file is not executable. You can confirm that it isn't by running:

```sh
ls -Al node_modules/prisma2/migration-engine
```

**Comment by pantharshit00** [comment] 2019-10-07 14:52
In my machine even yarn fails with the current setup:
![image](https://user-images.githubusercontent.com/22195362/66322536-e8d51180-e93f-11e9-98a2-96f3b965953c.png)


Any specific reason to use a different UID and GUID? It seems to be working without it
![image](https://user-images.githubusercontent.com/22195362/66322714-2f2a7080-e940-11e9-8230-4c23cd4b6b64.png)

**Comment by lboecker** [comment] 2019-10-07 15:18
@pantharshit00

> In my machine even yarn fails with the current setup

You probably forgot to change the owner of the directory.

> Any specific reason to use a different UID and GUID?

The default user is root. If you don't change to a different user, then all files created in your Docker volume are owned by root, meaning you may not be able to modify them.

**Comment by pantharshit00** [comment] 2019-10-08 09:25
> In my machine even yarn fails with the current setup

I double-checked the permissions as seen here: 
![image](https://user-images.githubusercontent.com/22195362/66384016-9812f680-e9db-11e9-9b7f-83690b31dbbf.png)

I think you will need to install the deps using the root user and then run the app using your specified as we have done in the example Dockerfile: 
![image](https://user-images.githubusercontent.com/22195362/66384062-ae20b700-e9db-11e9-9535-5cae0cf087b5.png)

https://github.com/prisma/prisma-examples/blob/prisma2/deployment-platforms/docker/Dockerfile

**Closed** 2020-01-09 17:25 UTC
Labels: bug/0-needs-info, kind/bug
