### ISSUE TITLE
can't create a set with Float[] and whole numbers

### ISSUE THREAD

**Issue by justin-hackin** [prisma/prisma2#953] opened 2019-11-19 04:53 UTC
Thanks to this issue https://github.com/prisma/prisma2/issues/169 I was able to figure out how to use a set of primitives.  I tried seeding my database with some JSON data and I noticed when I tried to seed an array with both "floats" and "ints" I hit an error like 
```
Argument set: Got invalid value 
[
  1.618033988749895,
  1,
  1.618033988749895
]
on photon.createOneThingSpec. Provided List<Float | Int>, expected List<Float>.
```
 I tried adding `.0` to the numbers but that didn't seem to help.

I would expect that with a Float[] there would be casting performed silently.  For Int[] I would expect an error with non-ints, but an opt-in feature to convert by ceiling, floor, or rounding function would be nice to have. 

Is this feature expected to be working?

**Comment by pantharshit00** [comment] 2019-11-19 12:59
Hi,

Thanks for reporting this but this has been already reported once. So I am going to close this as a duplicate ofhttps://github.com/prisma/photonjs/issues/279

**Closed by pantharshit00** 2019-11-19 12:59 UTC

**Comment by justin-hackin** [comment] 2019-11-19 18:17
Thanks, I did try searching for the error but I should have tried other terms
