### ISSUE TITLE
Following the tutorial gives me error

### ISSUE THREAD

**Issue by joshuarobs** [prisma/prisma2#761] opened 2019-10-16 10:54 UTC
This is the tutorial I'm following: https://github.com/prisma/prisma2/blob/master/docs/tutorial.md

I'm using a Heroku server with a postgres db add on. It wouldn't let me create a new schema under the name "hello-prisma2" so I just used the public one.

I can get to the part **2.6. Explore next steps** before it fails. This is what I get in my console:

````
Preparing your demo script (TypeScript) ...

✔  Downloading the demo script from GitHub ...
✔  Extracting content to hello-prisma2 ...
⠧  Installing dependencies with: `npm install` ...
4  Preparing your database ...
 ERROR  Error during command execution

(node:4582) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, mkdir
(node:4582) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing in
side of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejec
tion id: 1)
(node:4582) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejectio
ns that are not handled will terminate the Node.js process with a non-zero exit code.
Error: Get config Error: Command failed with exit code 13 (EACCES): /Users/joshua/WebstormProjects/my-app/db2/hello-prisma2/node_modules/prisma2/query-engine-darwin cli --get_config {"datamodel":"generator photon {\
n  provider = \"photonjs\"\n}\n\ndatasource db {\n  provider = \"postgresql\"\n  url      = 
\"postgresql://sizdushdzwxnoq:84239e808230266d1e5a91300669e3776b3caa823567880b151b6dc7fb261709@ec2-54-163-227-205.comp
ute-1.amazonaws.com/dc4s65qj9jci71?schema=hello-prisma2&sslmode=prefer\"\n}\n\nmodel User {\n  id    String  @default(
cuid()) @id\n  email String  @unique\n  name  String?\n  posts Post[]\n}\n\nmodel Post {\n  id        String   @defaul
t(cuid()) @id\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n  published Boolean  @default(tr
ue)\n  title     String\n  content   String?\n  author    User?\n}"}

spawn /Users/joshua/WebstormProjects/my-app/db2/hello-prisma2/node_modules/prisma2/query-engine-d
arwin EACCES
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! script@ postinstall: `prisma2 generate`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the script@ postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/joshua/.npm/_logs/2019-10-16T10_49_16_495Z-debug.lo
````

What is going on here and why am I encountering obstacles in the tutorial? Thanks

**Comment by lvauvillier** [comment] 2019-10-16 11:39
Hi, seem related to #668

**Comment by pantharshit00** [comment] 2019-10-16 14:41
Yes, looks like a duplicate of #668.

@joshuarobs Can you please tell me how did you install `prisma2`? What exact command you run and in which OS you are using Prisma. 

Maybe comment this on #668 and close this one as a duplicate.

**Comment by joshuarobs** [comment] 2019-10-19 04:53
I'm running on MacOS 10.15 Catalina and Node 10.16.3. I tried all sorts of things, in https://github.com/prisma/prisma2/issues/668, including installing with `sudo` and `--unsafe-perm`. I even tried what lvauvillier tried, with the link he provided, in zsh, and still it didn't work. I guess there's nothing I can do to make prisma2 work unfortunately.

**Closed** 2019-10-19 04:53 UTC
Labels: bug/0-needs-info, kind/bug
