### ISSUE TITLE
Query Engine failed ENOENT

### ISSUE THREAD

**Issue by impowski** [prisma/prisma2#1427] opened 2020-01-23 22:38 UTC
OS: `MacOS`
Database: `PostgreSQL`
Version: `alpha`

When I'm running this command `prisma2 generate`, sometimes I get this error:
```console
Error: Error: Command failed with ENOENT: ../node_modules/prisma2/query-engine-darwin cli --dmmf
spawn ../node_modules/prisma2/query-engine-darwin ENOENT
```
The only way to make it work again is to `rm -rf node_modules` and install again. When I'm making a deploy to my server I need to manually do the same thing.

**Comment by pantharshit00** [comment] 2020-01-24 08:52
Can you list out the exact steps to reproduce this? I can't reproduce this so far by running `prisma2 generate`.

**Comment by lvauvillier** [comment] 2020-01-24 10:37
Hello, see my comment on #668 
The binary seems missing. Hope this helps

**Comment by AlexanderProd** [comment] 2020-01-25 08:43
Just got this as well after adding a new dependency, removing `node_modules` and installing again fixed it.

**Comment by pantharshit00** [comment] 2020-01-26 11:57
Can anyone of you list out the exact steps for a reproduction? I didn't get this so far. Also, please provide details about which operating system you are using.

**Comment by AlexanderProd** [comment] 2020-01-26 16:48
The bug didn't happen again for me, can't reproduce it either.

**Comment by thehappycoder** [comment] 2020-02-04 22:35
@pantharshit00 
I think I have steps. It happened for me when I upgraded from prisma2@2.0.0-preview019 to     prisma2@2.0.0-preview021 and also upgraded a few other packages:
```
$ yarn add --dev @types/lodash prisma2 ts-node ts-node-dev typescript
$ prisma2 generate
Error: Error: Command failed with ENOENT: /Users/anton/projects/workbooks/apps/api/node_modules/prisma2/query-engine-darwin cli --dmmf
spawn /Users/anton/projects/workbooks/apps/api/node_modules/prisma2/query-engine-darwin ENOENT
error Command failed with exit code 1.
$ rm -r node_modules && yarn && prisma2 generate
Error: Oops! Photon has been renamed to Prisma Client. Please make the following adjustments:
  1. Rename provider = "photonjs" to provider = "prisma-client-js" in your schema.prisma file.
  2. Replace your package.json's @prisma/photon dependency to @prisma/client
  3. Replace import { Photon } from '@prisma/photon' with import { PrismaClient } from '@prisma/client' in your code.
  4. Run prisma2 generate again.
$ yarn remove @prisma/photon && yarn add @prisma/client
$ prisma2 generate
Error: Error: Command failed with ENOENT: /Users/anton/projects/workbooks/apps/api/node_modules/prisma2/query-engine-darwin cli --dmmf
spawn /Users/anton/projects/workbooks/apps/api/node_modules/prisma2/query-engine-darwin ENOENT
error Command failed with exit code 1.
$ rm -r node_modules && yarn && prisma2 generate
worked this time!
```

**Comment by pantharshit00** [comment] 2020-02-06 09:02
@thehappycoder I tried your reproduction, I can't reproduce this. Can you please tell me which OS are you using? I tried this on MacOS 10.15.2

**Comment by thehappycoder** [comment] 2020-02-06 09:05
@pantharshit00 I am using macos 10.15.3. Maybe upgrading macos caused this. I am not sure. Originally, I installed prisma2 when I had 10.15.2.

**Comment by pantharshit00** [comment] 2020-02-06 09:15
Ok, can you also tell me which yarn version you are using?

**Comment by thehappycoder** [comment] 2020-02-06 09:17
yarn version: 1.21.1

**Comment by luhagel** [comment] 2020-02-06 12:27
Just had the same issue, basic steps:
1. Have preview021 installed
2. Bump the versions of other packages
3. `yarn install`
-> ENOEnt, looks like binaries aren't getting downloaded after the prune

To fix, manuallly remove all node_modules folders. (The yarn default pruning in of itself isn't enough)

Yarn 1.21.1, Linux 5.5.1

**Comment by pantharshit00** [comment] 2020-02-08 01:22
I am still unable to reproduce :/ 

Do you all have `prisma2` globally installed as well or it is just a local dependency?

**Comment by thehappycoder** [comment] 2020-02-08 02:07
I have it globally installed as well.

**Comment by pantharshit00** [comment] 2020-02-10 13:31
Maybe try resetting the binary cache. Run `rm -rf .cache/prisma` to reset the cache.

We don't have a reproduction here so we can only guess what is the source of the issue here.

**Comment by danielmahon** [comment] 2020-02-11 00:37
With `prisma2` installed locally (latest sdk) I get this error randomly after working with it in development for a while (restarting the process many times in the process). Looks like the node process hangs and then continues to hang on subsequent starts until I dump the local `node_modules` folder and reinstall.

```
Error: Error: Command failed with ENOENT: /wkdir/node_modules/prisma2/query-engine-darwin cli --dmmf
spawn /wkdir/node_modules/prisma2/query-engine-darwin ENOENT
error Command failed with exit code 1.
```

**Comment by narciero** [comment] 2020-02-15 21:54
I am seeing this as well:

1. Everything was running fine
1. bumped a minor version of a single package (apollo-server)
1. `yarn install`
1. `yarn prisma2 generate` fails
````
Error: Error: Command failed with ENOENT: /<project_path>/node_modules/prisma2/query-engine-darwin cli --dmmf
spawn /<project_path>/node_modules/prisma2/query-engine-darwin ENOENT
error Command failed with exit code 1.

````

- yarn v1.22.0
- macOS 10.15.3
- `prisma2 ^2.0.0-preview021` installed locally

**Comment by pantharshit00** [comment] 2020-02-18 09:08
I can reproduce this now, thank you @narciero for the steps.

<img width="1327" alt="image" src="https://user-images.githubusercontent.com/22195362/74720626-1621bc80-525c-11ea-8bd5-8d765678d116.png">

My package.json before:
```
{
  "name": "issue-1427",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "@prisma/client": "^2.0.0-preview021",
    "apollo-server": "^2.10.0",
    "prisma2": "^2.0.0-preview021"
  }
}
```

After the minor bump:
```
{
  "name": "issue-1427",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "@prisma/client": "^2.0.0-preview021",
    "apollo-server": "^2.10.1",
    "prisma2": "^2.0.0-preview021"
  }
}
```

Then when I ran `yarn prisma2 generate`, I got the ENOENT error.

**Comment by timsuchanek** [comment] 2020-02-21 13:24
We did a fix in `prisma2@alpha`. Please try it out, everyone :)

**Comment by pantharshit00** [comment] 2020-02-21 13:27
I am unable to reproduce this anymore :)

**Comment by timsuchanek** [comment] 2020-02-21 17:58
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `prisma2`.
You can try it out with `npm i -g prisma2@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!

**Closed by timsuchanek** 2020-02-21 17:58 UTC
Labels: bug/2-confirmed, kind/bug, topic: ENOENT, topic: cli-generate
