### ISSUE TITLE
[Introspection] Panic: Unable to resolve scalar field / @@unique does not work with non-scalar fields

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#1377] opened 2020-01-20 14:01 UTC
Introspection error message might look like:

```
Schema parsing
thread 'main' panicked at 'Unable to resolve scalar field 'A'', src/libcore/option.rs:1185:5
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   ...
```

Example schema where it happens: https://github.com/prisma/database-schema-examples/blob/master/mysql/sakila/schema.sql

![image](https://user-images.githubusercontent.com/746482/72732280-a0abc900-3b95-11ea-8b18-fc348afc87fa.png)

Introspection Analysis Pattern Description: 

> Panic: Model (probably) has a @@id or @@unique, that refers to a non-scalar field. This usually happens in table inheritance and join tables without IDs.

More details in the internal introspection analysis repository, look for the known pattern: `panic-unable-to-resolve-scalar-field`

---

This problem can also appear if you write your schema by hand or used introspection to create it before: https://github.com/prisma/prisma2/issues/1534

**Comment by ssalbdivad** [comment] 2020-01-24 15:08
@divyenduz @schickling I'm confused as to the expected behavior here. Is ```@@unique``` only supported for scalar fields now? The following snippet from [the PSL spec](https://github.com/prisma/specs/tree/master/schema#why-not-support-id-for-multiple-blocks) appears to contradict that:

```@unique([recipe, ingredient])``` would mean that the combination of fields must be unique in the table:
```
model RecipeIngredient {
  recipe                            Recipe
  ingredient                      Ingredient
  amount                          Float
  quantitativeDisclosures String
  comment                       String
  @@unique([recipe, ingredient])
}
```

I commented on https://github.com/prisma/prisma2/issues/1352 over a month ago that this was blocking me from upgrading. Currently my schema contains this model:

```
model Test {
  id    Int    @id
  user  User
  name  String
  steps Step[]
  tags  Tag[]
  @@unique([name, user])
}
```

Which works totally fine as of ```2.0.0-preview017.2``` and correctly ensures a user cannot create two tests with the same name. Is ```@@unique``` only supposed to be used for scalar fields now?

**Comment by janpio** [comment] 2020-01-24 19:54
Hey @ssalbdivad, can you please open a new issue for this? I get the connection to this issue, but the original is really just a bug tracking issue for this specific problem with this specific error message. Thanks!

**Comment by ssalbdivad** [comment] 2020-01-24 22:52
@janpio If this issue is just about the error message than perhaps #1352 should be reopened? @divyenduz commented on #1352 "Closing this in favor of #1377". Several people have already commented on #1352 stating they had the same problem so it seems like it would be best to use that issue so that they are in the loop. I'd be happy to add my comment to #1352 if that would be helpful.

**Comment by janpio** [comment] 2020-01-26 09:50
As I said, most helpful would be to open a new issue. You are asking questions that are not covered in the other #1352, and not topic of this issue here.

**Comment by ssalbdivad** [comment] 2020-01-26 13:35
@janpio Opened #1440 to track this. However, I don't think #1352 should have been closed "in favor of" this issue if they don't have the same goal.

**Comment by tomhoule** [comment] 2020-02-03 17:29
This crash should be fixed by https://github.com/prisma/prisma-engine/pull/445

**Comment by RyuX51** [comment] 2020-02-03 20:21
I thought, this would fix my error, too, because it was nearly the same but seems to have not?
Is this fix already in alpha 697?

```
Schema parsing
thread 'main' panicked at 'Unable to resolve scalar field 'id_courrier'', src/libcore/option.rs:1188:5
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::option::expect_failed
   9: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  10: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  11: prisma_models::index::IndexTemplate::build
  12: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  13: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  14: prisma_models::model::ModelTemplate::build
  15: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  16: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
```

I reported it as `#1641`.

**Comment by tomhoule** [comment] 2020-02-03 20:52
The PR is not merged, so it's not in alpha yet :) I will try to get a review tomorrow.

**Comment by tomhoule** [comment] 2020-02-04 10:14
The PR fixed the crash short term, but we're not going to merge it, because we have a much deeper and larger refactoring ongoing that will fix this issue (and do the right thing, instead of just not crashing), among many others. PR for the refactoring for reference: https://github.com/prisma/prisma-engine/pull/383

**Comment by tomhoule** [comment] 2020-02-04 10:15
Internal note: unassigning myself, since this is addressed by AUMFIDARR

**Comment by janpio** [comment] 2020-02-04 13:16
For the record:

With the PR https://github.com/prisma/prisma-engine/pull/445 from @tomhoule this would have been the next error message someone would have gotten with the sakila schema that was mentioned in the initial issue description:

```
thread 'main' panicked at 'called Result::unwrap() on an Err value: "No id field defined! Model: film_actor"', src/libcore/result.rs:1188:5
```

**Comment by RyuX51** [comment] 2020-02-04 13:38
I already added id fields to all tables from the db I want to create the schema for. :)
But thanks for updating me. I'll keep a grateful and patient eye on the refactoring.

**Comment by ssalbdivad** [comment] 2020-02-04 19:31
As detailed in my conversation with @janpio on #1440, from a user perspective, this is a regression for those who used non-scalar fields in ```@@unique``` with prisma migrate (worked fine before ```preview018```). I understand the desire to avoid merge conflicts but after religiously adopting most new releases, I've been stuck on ```preview017.2``` for months due to this bug.

prisma/prisma-engine#445 appears relatively limited in scope. If we're confident it's not worth merging, does that mean there is an ETA on prisma/prisma-engine#383?

**Comment by janpio** [comment] 2020-02-05 10:18
No, there is no ETA (and the linked PR is also just part of the bigger story). We are working hard on fixing this problem and will update you as soon as we know more.

**Comment by janpio** [comment] 2020-02-05 19:45
Quick update to the issue title here for correctness: 
Although the error message says "Unable to resolve scalar field", what actually does not work in `@@unique` are non-scalar fields. `inventory_id` in the example of the issue description is a non-scalar, but as the code does not expect that at this location (yet), it tries to resolve it as a scalar what of course does not work. When this is fixed, it will probably resolve this as non-scalar ans thus not fail.

**Comment by janpio** [comment] 2020-02-05 19:53
As this can also happen out of Introspection context, where it used to work before, this is now also tracked as an additional regression issue: https://github.com/prisma/prisma2/issues/1534

**Comment by janpio** [comment] 2020-02-18 14:27
This is now fixed <3

**Closed by janpio** 2020-02-18 14:27 UTC
Labels: bug/2-confirmed, kind/bug, topic: AUMFIDARR, topic: introspection

**Comment by ssalbdivad** [comment] 2020-02-18 22:48
@janpio @tomhoule Thanks so much :bowtie:
