### ISSUE TITLE
Missing environment variables error is not as beautiful as before anymore

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma2#1783] opened 2020-03-07 07:38 UTC
Using alpha `2.0.0-alpha.880`

<img width="551" alt="image" src="https://user-images.githubusercontent.com/5013932/76139301-1d7cfe80-6081-11ea-8b99-daecf26c7019.png">

Some errors such as when an environment variable is missing renders this error instead. The error was more beautiful before.

**Comment by janpio** [comment] 2020-03-12 16:35
Internal Note: @timsuchanek plese update the issue to reflect actual bug

**Comment by timsuchanek** [comment] 2020-03-12 16:36
This reflects work in progress, where we still need to lift the env var requirement for our internal `getConfig` command. As this is not working as intended yet, we can classify this as a bug.

**Comment by janpio** [comment] 2020-03-16 22:33
Original issue here was https://github.com/prisma/prisma2/issues/800

**Comment by mavilein** [comment] 2020-03-20 14:03
fixed in https://github.com/prisma/prisma-engines/commit/3ebc5fea01c4f428202f7a3c5703f6f64a904247

**Closed by mavilein** 2020-03-20 14:03 UTC
Labels: kind/regression, topic: errors

**Comment by janpio** [comment] 2020-03-20 21:45
Can you confirm this fix with a current `alpha` please, @steebchen? Thanks.

**Comment by steebchen** [comment] 2020-03-21 08:16
It seems that `prisma2 generate` does not require environment variables anymore (which is the correct behaviour). So in theory, no, I can't reproduce this.
