### ISSUE TITLE
prisma2 dev fails during migration of a simple MySQL database

### ISSUE THREAD

**Issue by petasis** [prisma/prisma2#947] opened 2019-11-17 11:37 UTC
Hi all,

I am trying to build a graphql api over a simple MySQL database (just 3 tables). But I get a failure during migration, and I do not know how to debug it.
A report id 621 has been generated by prisma2 and uploaded (somewhere).

**Comment by pantharshit00** [comment] 2019-11-18 08:18
Hi,

Can you please tell paste your model here?

**Comment by petasis** [comment] 2019-11-18 09:38
Here it is:

model Entry {
  id     Int    @id
  e1     Int?
  e10    Int?
  e11    Int?
  e12    Int?
  e13    Int?
  e14    Int?
  e15    Int?
  e16    Int?
  e17    Int?
  e18    Int?
  e19    Int?
  e2     Int?
  e20    Int?
  e21    Int?
  e22    Int?
  e23    Int?
  e24    Int?
  e25    Int?
  e26    Int?
  e27    Int?
  e28    Int?
  e29    Int?
  e3     Int?
  e30    Int?
  e4     Int?
  e5     Int?
  e6     Int?
  e7     Int?
  e8     Int?
  e9     Int?
  form   String @unique
  root1  Int?
  root10 Int?
  root11 Int?
  root12 Int?
  root13 Int?
  root14 Int?
  root15 Int?
  root16 Int?
  root17 Int?
  root18 Int?
  root19 Int?
  root2  Int?
  root20 Int?
  root21 Int?
  root22 Int?
  root23 Int?
  root24 Int?
  root25 Int?
  root26 Int?
  root27 Int?
  root28 Int?
  root29 Int?
  root3  Int?
  root30 Int?
  root4  Int?
  root5  Int?
  root6  Int?
  root7  Int?
  root8  Int?
  root9  Int?

  @@map("entry")
}

model INFO {
  id         Int  @id
  accent     Int?
  case       Int?
  degree     Int?
  detail     Int?
  egklish    Int?
  gender     Int?
  helper     Int?
  inflection Int?
  mood       Int?
  number     Int?
  person     Int?
  pos        Int
  pronoun    Int?
  tense      Int?
  voice      Int?
}

model INFOPART {
  id          Int    @id
  description String
  label       String @unique
}

**Comment by pantharshit00** [comment] 2019-11-22 10:23
Hi, 

I checked the error report. The error said, "Query was empty". This is a known bug which will be fixed in preview 17(which will get released today). https://github.com/prisma/prisma2/issues/902

**Comment by pantharshit00** [comment] 2019-11-22 13:40
But I am still unable to reproduce your error so please wait till preview 17 and test this out again then

**Comment by pantharshit00** [comment] 2019-11-26 17:48
@petasis Preview 17 was released. Can you please try this again now with that?

**Comment by divyenduz** [comment] 2020-01-09 15:38
I am closing this one due to inactivity, if you still think that this is an issue, please comment here and tag me. Thank you 🙏

**Closed by divyenduz** 2020-01-09 15:38 UTC
Labels: bug/0-needs-info, kind/bug
