### ISSUE TITLE
Error when deploying migration

### ISSUE THREAD

**Issue by mckernanin** [prisma/prisma2#441] opened 2019-08-28 07:27 UTC
I am receiving the following error when trying to run a migration on my database:
`  LiftEngine:stderr thread 'tokio-runtime-worker-1' panicked at 'old Field for MigrationStep not found', src/libcore/option.rs:1034:5 +0ms`

**Comment by divyenduz** [comment] 2019-08-28 08:24
Please share your DB, datamodel in form of a minimal reproduction! If possible, zip your current folder and put that on the issue.

**Comment by pantharshit00** [comment] 2019-08-29 15:23
Can you please tell me which version of `prisma2` you are using?

I am unable to reproduce this with `prisma2@2.0.0-preview-8, binary version: 6146c81a771bef78248317cef9e37fc00863dc08` and `prisma2@2.0.0-alpha.150, binary version: 7f41d7dc79ff7da2d927b91d23ff5bf2004b308f`

**Comment by mckernanin** [comment] 2019-08-30 19:54
Just updated to latest versions.
cli: `prisma2@2.0.0-preview-9.1, binary version: bbbeff6f84b408e534ebd866bfd378748e6d6611`

Now when trying to run the deployment on my prod database, I get the following error:

```
  LiftEngine:stderr thread 'tokio-runtime-worker-0' panicked at 'Deserializing the database migration failed.: Error("missing field `table`", line: 0, column: 0)', src/libcore/
result.rs:999:5 +0ms
  LiftEngine:stderr stack backtrace: +0ms
  LiftEngine:stderr    0: std::panicking::default_hook::{{closure}} +33ms
  LiftEngine:stderr    1: std::panicking::default_hook +0ms
  LiftEngine:stderr    2: std::panicking::rust_panic_with_hook +0ms
  LiftEngine:stderr    3: std::panicking::continue_panic_fmt +0ms
  LiftEngine:stderr    4: rust_begin_unwind +0ms
  LiftEngine:stderr    5: core::panicking::panic_fmt +0ms
  LiftEngine:stderr    6: core::result::unwrap_failed +0ms
  LiftEngine:stderr    7: <sql_migration_connector::SqlMigrationConnector as migration_connector::MigrationConnector>::deserialize_database_migration +0ms
  LiftEngine:stderr    8: <migration_core::api::MigrationApi<C,D> as migration_core::api::GenericApi>::list_migrations +0ms
  LiftEngine:stderr    9: migration_core::api::rpc::RpcApi::create_sync_handler +0ms
  LiftEngine:stderr   10: tokio_executor::enter::exit +0ms
  LiftEngine:stderr   11: tokio_threadpool::blocking::blocking +0ms
  LiftEngine:stderr   12: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll +0ms
  LiftEngine:stderr   13: futures::future::chain::Chain<A,B,C>::poll +0ms
  LiftEngine:stderr   14: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll +0ms
  LiftEngine:stderr   15: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll +0ms
  LiftEngine:stderr   16: futures::future::chain::Chain<A,B,C>::poll +1ms
  LiftEngine:stderr   17: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll +0ms
  LiftEngine:stderr   18: <futures::future::map::Map<A,F> as futures::future::Future>::poll +0ms
  LiftEngine:stderr   19: <futures::future::either::Either<A,B> as futures::future::Future>::poll +0ms
  LiftEngine:stderr   20: <futures::future::map::Map<A,F> as futures::future::Future>::poll +0ms
  LiftEngine:stderr   21: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll +0ms
  LiftEngine:stderr   22: <futures::stream::and_then::AndThen<S,F,U> as futures::stream::Stream>::poll +0ms
  LiftEngine:stderr   23: <futures::stream::forward::Forward<T,U> as futures::future::Future>::poll +0ms
  LiftEngine:stderr   24: <futures::future::map::Map<A,F> as futures::future::Future>::poll +0ms
  LiftEngine:stderr   25: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll +0ms
  LiftEngine:stderr   26: futures::task_impl::std::set +0ms
  LiftEngine:stderr   27: std::panicking::try::do_call +0ms
  LiftEngine:stderr   28: __rust_maybe_catch_panic +0ms
  LiftEngine:stderr   29: tokio_threadpool::task::Task::run +0ms
  LiftEngine:stderr   30: tokio_threadpool::worker::Worker::run_task +0ms
  LiftEngine:stderr   31: tokio_threadpool::worker::Worker::run +1ms
  LiftEngine:stderr   32: std::thread::local::LocalKey<T>::with +0ms
  LiftEngine:stderr   33: std::thread::local::LocalKey<T>::with +0ms
  LiftEngine:stderr   34: tokio_reactor::with_default +0ms
  LiftEngine:stderr   35: tokio::runtime::threadpool::builder::Builder::build::{{closure}} +0ms
  LiftEngine:stderr   36: std::thread::local::LocalKey<T>::with +0ms
  LiftEngine:stderr   37: std::thread::local::LocalKey<T>::with +0ms
  LiftEngine:stderr note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace. +0ms
```

**Comment by mckernanin** [comment] 2019-08-30 20:12
@pantharshit00 I sent you an invite to the private repo for this, I'll DM you credentials to a DB instance on prisma slack

**Comment by mckernanin** [comment] 2019-09-03 14:45
This seems to have been resolved by upgrading everything, backing up my database, initializing from scratch, then importing my data back in. Maybe a regression between prisma2 versions? The dev DB credentials I provided to @pantharshit00 still exhibit this issue, so if you want to dig into it you can.

**Comment by divyenduz** [comment] 2019-09-30 11:16
Regressions in preview are expected, although I completely agree that they should be pointed out by the release notes. We did so in the latest release as well. 

I am closing this issue as it is not actionable in current context. Please feel free to open a new issue in case you disagree 🙏

**Closed by divyenduz** 2019-09-30 11:16 UTC
Labels: bug/0-needs-info, kind/bug

**Comment by mckernanin** [comment] 2019-09-30 15:32
No problem, was a few versions back.
