### ISSUE TITLE
Cannot find module 'nexus' -  2.0.0-preview-9.1

### ISSUE THREAD

**Issue by ryanking1809** [prisma/prisma2#476] opened 2019-08-30 18:42 UTC
With `2.0.0-preview-9.1` I'm getting the following issue when trying to run `yarn start` after running `prisma2 generate` - I've reverted back `preview-8` and everything runs as expected.

```
Ryans-MacBook-Pro-2:prisma_toy ryanking$ yarn start
yarn run v1.9.2
$ node src/index.js
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'nexus'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.313 (/Users/ryanking/Documents/Projects/prisma_toy/node_modules/@generated/nexus-prisma/index.js:795:18)
    at __webpack_require__ (/Users/ryanking/Documents/Projects/prisma_toy/node_modules/@generated/nexus-prisma/index.js:22:30)
    at Object.656 (/Users/ryanking/Documents/Projects/prisma_toy/node_modules/@generated/nexus-prisma/index.js:837:17)
    at __webpack_require__ (/Users/ryanking/Documents/Projects/prisma_toy/node_modules/@generated/nexus-prisma/index.js:22:30)
    at Object.826 (/Users/ryanking/Documents/Projects/prisma_toy/node_modules/@generated/nexus-prisma/index.js:1182:30)
    at __webpack_require__ (/Users/ryanking/Documents/Projects/prisma_toy/node_modules/@generated/nexus-prisma/index.js:22:30)
error Command failed with exit code 1.
```

**Comment by keepforever** [comment] 2019-09-01 21:57
I experienced a similar issue after upgrading. 

Reverting to `preview-8` also put things back to normal and running again.

```
/Users/bcilenti/Desktop/projects/deck/server/src/resolvers/User.ts:9
        t.model.id();
                ^
TypeError: Cannot read property 'id' of undefined
    at Object.definition (/Users/bcilenti/Desktop/projects/deck/server/src/resolvers/User.ts:9:17)
    at SchemaBuilder.walkOutputType (/Users/bcilenti/Desktop/projects/deck/server/node_modules/@prisma/nexus/src/builder.ts:1192:9)
    at SchemaBuilder.walkTypes (/Users/bcilenti/Desktop/projects/deck/server/node_modules/@prisma/nexus/src/builder.ts:456:16)
    at SchemaBuilder.getFinalTypeMap (/Users/bcilenti/Desktop/projects/deck/server/node_modules/@prisma/nexus/src/builder.ts:464:10)
    at buildTypes (/Users/bcilenti/Desktop/projects/deck/server/node_modules/@prisma/nexus/src/builder.ts:1313:18)
    at makeSchemaInternal (/Users/bcilenti/Desktop/projects/deck/server/node_modules/@prisma/nexus/src/builder.ts:1357:9)
    at Object.makeSchema (/Users/bcilenti/Desktop/projects/deck/server/node_modules/@prisma/nexus/src/builder.ts:1408:9)
    at Object.<anonymous> (/Users/bcilenti/Desktop/projects/deck/server/src/index.ts:18:16)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Module.m._compile (/Users/bcilenti/Desktop/projects/deck/server/node_modules/ts-node/src/index.ts:473:23)
```

**Comment by pantharshit00** [comment] 2019-09-02 09:38
Reproduction Steps:
1. prisma2 init > Starter Kit > GraphQL > Javascript > SQLite
2. npm start (error described @ryanking1809 will happen)
3. npm install nexus
4. npm start

I can confirm this. `nexus-prisma` started using `nexus` package `@prisma/nexus` because I guess the fix we introduced in the fork has been merged. We are not including `nexus` in package.json so it is not being fetched from the npm registry.

@keepforever You issue seems to be caused by the usage of `nexus` in nexus-prisma's output instead of `@prisma/nexus`

cc @jasonkuhrt

**Comment by keepforever** [comment] 2019-09-02 20:10
@pantharshit00,

Is this something I can fix **(easily)** so that my current code will run with the latest version of **prisma2 cli** or do I need to wait for a patch or the next preview version?  

Because, when I revert back to `prisma2@2.0.0-preview-8`, I didn't need to change anything in my code, and it began to work as expected.

**Comment by jasonkuhrt** [comment] 2019-09-02 20:40
Hey @keepforever you can find a working example [here](https://github.com/prisma/nexus-prisma/tree/next/example). I think you still need to be using the latest Prisma 2 alpha.

**Comment by jasonkuhrt** [comment] 2019-10-17 12:34
Hey again @keepforever, things have moved a lot since you opened this issue. Take a look at the latest [examples](https://github.com/prisma-labs/nexus-prisma/tree/master/examples/blog) and [docs](https://github.com/prisma-labs/nexus-prisma#reference).

**Closed by jasonkuhrt** 2019-10-17 12:34 UTC
Labels: bug/2-confirmed, kind/bug
