### ISSUE TITLE
Error: prisma2 init hello-prisma

### ISSUE THREAD

**Issue by vladano** [prisma/prisma2#118] opened 2019-07-09 10:41 UTC
I try to install prisma2 on Windows 10 Pro build 1703 x64.

When start "prisma2 init hello-prisma" I got following output messages:
**(OK means green check sign, ERR means red cross sign, + selected option from list)**

**OK** Connected to database
**OK** Connected to database
**OK** Connected to database
 Which parts of Prisma do you want to use?
 Learn more about the tools at prisma.io/docs
 ¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦
>  From Scratch        Basic Prisma setup + simple script
**+>  GraphQL boilerplate GraphQL server example**
>  REST boilerplate    REST API example (using express.js)
>  gRPC boilerplate    gRPC API example (client + server)
 ¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦
<  Back                (Language selection)
**OK** Downloading starter from https://api.github.com/repos/prisma/photonjs/tarball/master
**OK** Extracting content to G:\prisma2\hello-prisma
**ERR** Installing dependencies 

 Your template has been successfully set up!

  Here are the next steps to get you started:
    1. Run prisma2 lift save --name init to create a migration.
    2. Run prisma2 lift up to apply the migration.
    3. Run yarn seed to seed the database.
    4. Run yarn start (Starts the GraphQL server)
    5. That's it !

PS G:\prisma2> prisma2 lift save --name init
[migration-engine] error: Error: spawn C:\Users\{Username}\AppData\Roaming\npm\node_modules\prisma2\migration-engine ENOENT
Error: Error in lift engine: 

It's confusing red cross sign when install dependencies?! Message under says "Your template has been successfully set up!"

After that when I start command "prisma2 lift save --name init", I got error:
[migration-engine] error: Error: spawn C:\Users\{Username}\AppData\Roaming\npm\node_modules\prisma2\migration-engine ENOENT
Error: Error in lift engine: 

Does anyone have an idea of what the problem is?

Thanks in advance

**Comment by pantharshit00** [comment] 2019-07-09 16:36
Windows is currently isn't supported.

Closing as a duplicate of https://github.com/prisma/prisma2/issues/4****

**Closed** 2019-07-09 16:36 UTC
