### ISSUE TITLE
[2.0.0-preview017, Win10] Error with global npm install of 'prisma2' CLI

### ISSUE THREAD

**Issue by D2KX** [prisma/prisma2#987] opened 2019-11-25 16:24 UTC
On Windows 10, I get an error immediately when I try to install the newest version of the Prisma Framework CLI (2.0.0-preview017).

<img width="835" alt="prisma2" src="https://user-images.githubusercontent.com/4834966/69557998-c8245200-0fa7-11ea-8c5c-4373c62c3bf5.png">

"TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined"

I haven't tried yet, but I guess it won't be a problem if I try installing using WSL, as it looks like another case of a Windows-specific file access issue.

**Comment by timsuchanek** [comment] 2019-11-25 16:44
Thanks a lot for reporting @D2KX! We're looking into it and will probably release a patch tomorrow.

**Comment by pantharshit00** [comment] 2019-11-25 16:49
Hi,

Thanks for reporting this but this has been already reported once. So I am going to close this as a duplicate of #985

**Comment by timsuchanek** [comment] 2019-11-25 18:05
@pantharshit00 this issue has to do with the cache directory and is, therefore, unrelated to #985 .

**Comment by timsuchanek** [comment] 2019-11-25 18:30
@D2KX I can't reproduce it on my Windows testing machine but published a fix, which should at least fix this one (you'll still run into https://github.com/prisma/prisma2/issues/985)
Can you try out `prisma2@2.0.0-alpha.353` please?
Thanks 🙏

**Comment by D2KX** [comment] 2019-11-25 20:06
> @D2KX I can't reproduce it on my Windows testing machine but published a fix, which should at least fix this one (you'll still run into #985)
> Can you try out `prisma2@2.0.0-alpha.353` please?
> Thanks 🙏

2.0.0-alpha.353 indeed fixes the problem ❤️ Thank you!

**Comment by timsuchanek** [comment] 2019-11-26 08:56
Perfect! Thanks for getting back to me so quick. I'll close this one then.

**Closed by timsuchanek** 2019-11-26 08:56 UTC
Labels: bug/2-confirmed, kind/bug
