### ISSUE TITLE
photon with preview-5 DriverError

### ISSUE THREAD

**Issue by mazzaker** [prisma/prisma2#322] opened 2019-08-05 10:20 UTC
prisma2@2.0.0-preview-5:

```
{
  "errors": [
    {
      "message": "Error querying the database: DriverError { Could not connect: address not specified } date=2019-08-05T10:14:50.903Z",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "findOneProfile"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Error querying the database: DriverError { Could not connect: address not specified } date=2019-08-05T10:14:50.903Z",
            "    at NodeEngine.engineReady (/Users/DC-BT/Documents/Projects/necom/server/node_modules/@generated/photon/runtime/index.js:13091:23)",
            "    at /Users/DC-BT/Documents/Projects/necom/server/node_modules/@generated/photon/runtime/index.js:13014:21"
          ]
        }
      }
    }
  ],
  "data": {
    "findOneProfile": null
  }
}
```

if I downgrade to prisma2@2.0.0-preview-3 photon works normal

**Comment by mazzaker** [comment] 2019-08-05 15:19
Found it myself in project.prisma I had:

```
datasource db {
  provider = "mysql"
  url      = "mysql://root:@localhost:3306/necom"
  default  = true
}

//datasource db {
//  url      = "file:dev.db"
//  provider = "sqlite"
//}

```

removing the sqllite was the solution.

**Comment by pantharshit00** [comment] 2019-08-05 18:52
Can we close this now?

I can't seem to reproduce this with SQLite. All operation works fine.

**Comment by gihrig** [comment] 2019-08-05 19:16
It seems the underlying problem is that prisma appears to be acting on commented code.

Could this be due not having run `prisma2 generate` since the sqlite code was commented?

If I comment the (only) `datasource` key in my `schema.prisma` file, everything still works until I run `prisma2 generate`.

@mazzaker Does this scenario make sense?

**Comment by mazzaker** [comment] 2019-08-06 07:16
Yes you can close this but as @gihrig mentioned nobody would expect that prisma react on comments...

**Comment by pantharshit00** [comment] 2019-08-06 10:27
I think issue not with comments rather than not running prisma2 generate after commenting the code. That is why it used the driver for a separate DB.

**Comment by divyenduz** [comment] 2019-08-08 14:34
This is a bug, running generate after commenting code does not mitigate this.

**Comment by divyenduz** [comment] 2019-08-08 14:35
To summarize: 

This breaks

```
datasource db {
  provider = "mysql"
  // url      = "file:./dev.db"
  url      = "mysql://root:@localhost:3306/necom"
  default  = true
}
```

And this works

```
datasource db {
  provider = "mysql"
  url      = "mysql://root:@localhost:3306/necom"
  default  = true
}
```

I ran generate after changing the schema file. The same behavior can be observed in Postgres.

**Comment by timsuchanek** [comment] 2019-08-08 15:00
Fixed in latest alpha.

**Closed by timsuchanek** 2019-08-08 15:00 UTC
Labels: bug/2-confirmed, kind/bug
