### ISSUE TITLE
Ambiguous self relation detected

### ISSUE THREAD

**Issue by AbdusamadTurdiev** [prisma/prisma2#671] opened 2019-10-06 12:55 UTC
`prisma2@2.0.0-preview-13.2`

I'm running `prisma2 lift up` and getting

```
ERROR  Oops, an unexpected error occured!
Error in migration engine: thread 'tokio-runtime-worker-0' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorCollection { errors: [ModelValidationError { message: "Ambiguous self relation detected.", mod 
el_name: "User", span: Span { start: 147, end: 173 } }] }', src\libcore\result.rs:999:5
stack backtrace:
```

My schema
```
model User {
  id String @default(cuid()) @id
  username String @unique
  password String
  friends User[]
  conversations Conversation[] @relation(name: "UserConversations")
  messages Message[] @relation(name: "UserMessages")
  sentInvitations Invitation[] @relation(name: "SentInvitations", onDelete: CASCADE)
  receivedInvitations Invitation[] @relation(name: "ReceivedInvitations", onDelete: CASCADE)
}

model Conversation {
  id String @default(cuid()) @id
  members User[] @relation(name: "UserConversations")
  messages Message[] @relation(name: "ConversationMessages")
}

model Message {
  id String @default(cuid()) @id
  message String
  author User @relation(name: "UserMessages")
  conversation Conversation @relation(name: "ConversationMessages")
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}

model Invitation {
  id String @default(cuid()) @id
  from User @relation(name: "SentInvitations")
  to User @relation(name: "ReceivedInvitations")
  status InvitationStatus @default(PENDING)
}

enum InvitationStatus {
  PENDING
  ACCEPTED
  REJECTED
}
```

**Comment by divyenduz** [comment] 2019-10-08 14:03
@AbdusamadTurdiev Do you think that this is a duplicate of https://github.com/prisma/prisma2/issues/488#issuecomment-535506097

If yes, please feel free to close this one.

**Closed** 2019-10-08 18:04 UTC
Labels: bug/0-needs-info, kind/bug
