### ISSUE TITLE
[Introspection] Operation timed out

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#1493] opened 2020-01-31 09:57 UTC
Introspection CI fails with "Operation timed out" error frequently for bigger databases. 
This can be seen in our internal introspection analysis CI.

**Comment by tomhoule** [comment] 2020-02-28 13:26
Can we close this?

**Comment by janpio** [comment] 2020-02-28 17:59
Yes we can.

For whoever might read this: Was caused by using macOS as the platform to run CI, not Ubuntu.

**Closed by janpio** 2020-02-28 17:59 UTC
Labels: bug/2-confirmed, kind/bug, topic: introspection

**Comment by divyenduz** [comment] 2020-03-02 10:00
Timeouts shouldn't happen on mac either right?

**Comment by janpio** [comment] 2020-03-02 12:13
They should not, but we were not able to reproduce or anything, right?

**Comment by olance** [comment] 2020-03-23 23:41
@janpio @divyenduz I have an issue with Prisma that seems to be hanging, on macOS.

Could that help and/or could you help me figure it out?

So far I've been able to determine that the `query-engine-darwin` runtime downloaded on that specific machine is faulty.
When I diff it with the runtime downloaded on another computer of mine, there are differences (at least 3 contiguous MB are pure zeroes in one binary, versus some data in the other). Replacing the faulty `query-engine-darwin` with the working one makes the entire thing work.

More details in this conversation: https://community.redwoodjs.com/t/tutorial-fetching-posts-throws-errors/162/11

**Comment by olance** [comment] 2020-03-23 23:57
So actually after clearing Prisma's binary cache (`rm -rf ~/.cache/prisma`), the package pulled in the very last release of the binaries (from today apparently!) and everything is now working perfectly!

Looking into the macOS Console app, I discovered that Prisma was actually not hanging, but crashing.

So I do have a few crash reports for:
- `query-engine-darwin`
- `migration-engine-darwin`
- `introspection-engine-darwin`

I'm on macOS Mojave 10.14.6 (18G103).

If that could be of any interest to you, do let me know and I'll upload them!

**Comment by janpio** [comment] 2020-03-24 11:19
Yes that would indeed be interesting. But better create a new issue (you can just copy paste the text you wrote here) because a closed one might be overlooked. Thanks!

**Comment by janpio** [comment] 2020-03-24 17:53
Hey @olance, after actually reading the forum thread you posted to I could connect this to a bug we have: https://github.com/prisma/prisma2/issues/1819 There you can read a bit more about what is going on.
