### ISSUE TITLE
Modular Database Model

### ISSUE THREAD

**Issue by newtack** [prisma/prisma2#170] opened 2019-07-17 00:53 UTC
We plan on having several databases (e.g. CRM databases) that share a lot of the database models but differ in some regard. Ideally we define the common tables, fields, etc. once and only specify the differences for each specific implementation.

At a minimum I'd expect that we could have multiple database schema files that point to the same database (and schema/user) and it would work, i.e. we have a schema file schemaGeneral that defines the common tables and schemaCRM1 that defines the CRM1 specific tables and when we run migrations using prisma2, it would just work. 

Is this supported, and if not can you support this?

Ideally we have some way of combining multiple database schemas/models, e.g. have some sort of import/include mechanism. From what I saw from the documentation that is not yet supported, are there any plans to support this?

**Comment by SimonErich** [comment] 2019-08-10 17:06
I would also be interested in that. Did you find a solution for this already?
In general: We work very modular and having ways to import other schema definitions from other folders and seeders, ... would be amazing.

**Comment by SimonErich** [comment] 2019-08-10 17:09
Duplicate of #92

**Closed** 2019-12-13 12:21 UTC
Labels: kind/feature, topic: schema

**Comment by muslimakhan** [comment] 2024-07-14 12:07
Hey @newtack, please check my blog and script here:
[New Trick – Organizing Prisma Models with the MERN Stack](https://muslimahmad.com/trick-organizing-prisma-models-with-the-mern-stack/)
[Github Repo](https://github.com/muslimakhan/Blog-Trick-Organizing-Prisma-Models-with-the-MERN-Stack)

This script could be help in both model split into multiple files and also for enum & types of Prisma ORM. And there is also a way to import predefined data into database too.
Hope, it would be solve your problem.
Thanks
