### ISSUE TITLE
[Introspection] Schema parser should collect all errors before failing

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#1117] opened 2019-11-29 10:00 UTC
Schema parser fails fast in some scenarios. See [these](https://www.notion.so/prismaio/shopware-da730f7228294f108ba65d22677659fe) introspection notes for example. 

It should collect all parsing errors and report them together. 

This might need some spec work.

**Comment by pantharshit00** [comment] 2019-12-11 14:34
Using both candidate and product labels so that we can discuss exactly where this belongs.

**Comment by janpio** [comment] 2019-12-11 19:41
The linked Notion page doesn't explain anything to me @divyenduz. Can you elaborate please?

**Comment by divyenduz** [comment] 2019-12-12 09:43
Maybe similar to this: https://github.com/prisma/prisma2/issues/1097

**Comment by janpio** [comment] 2019-12-15 10:29
Duplicate of https://github.com/prisma/prisma2/issues/1097

**Closed by janpio** 2019-12-15 10:29 UTC
Labels: kind/improvement, process/candidate, process/product, topic: introspection
