### ISSUE TITLE
embed interface type for mongodb

### ISSUE THREAD

**Issue by GaborTorma** [prisma/prisma2#1269] opened 2020-01-03 15:57 UTC
I should to define interface type for embed and save to mongodb.

Please find my example:
Schema: 
interface ClientData { 
  id String @default(cuid()) @id
}

model IndividualData @implements(ClientData) @embedded{
  name         String?
  zip          String?
  city         String?
  street       String?
}

model CompanyData @implements(ClientData) @embedded {
  company         String?
  tax          String?
  regNo         String?
}

model Client {
  id        String     @default(cuid()) @id
  dataId    ClientData @relation(storage: Embedded)
}

I want to push data from graphql nexus with photon directly to mongodb client.data with different data structure like IndividualData or CompanyData.

**Comment by pantharshit00** [comment] 2020-01-06 13:00
Hi,

We currently don't support MongoDB. Also, we have a different syntax for embed already proposed here: https://github.com/prisma/specs/tree/master/schema#embed-block

Also, there is an issue around interfaces here with some discussion: https://github.com/prisma/prisma2/issues/253

So I am going to close this as a duplicate of these

**Closed by pantharshit00** 2020-01-06 13:00 UTC

**Comment by GaborTorma** [comment] 2020-01-06 13:26
Can you tell me when do you support mongodb and embed block?

**Comment by pantharshit00** [comment] 2020-01-06 15:05
I can't give a timeline for that as we are currently focusing on stabilizing the core but it would be after the first release photon and not before that as mongo is a very different dialect than the current SQL ones we have.
