### ISSUE TITLE
Connect to Heroku SSL problem

### ISSUE THREAD

**Issue by lasharela** [prisma/prisma2#1027] opened 2019-11-30 22:25 UTC
I'm trying to connect to Heroku Database `prisma2 init`, blank template.

everything is filed correctly but I'm getting an error:

```
 ERROR  self signed certificate
```

**Comment by williamluke4** [comment] 2019-12-01 07:43
Pretty sure this is related to #884

**Comment by williamluke4** [comment] 2019-12-01 07:44
Try this
> Adding `sslaccept=accept_invalid_certs` to your datasource url should work for now

_Originally posted by @williamluke4 in https://github.com/prisma/prisma2/issues/884#issuecomment-551697427_

**Comment by lasharela** [comment] 2019-12-02 05:16
> Try this
> 
> > Adding `sslaccept=accept_invalid_certs` to your datasource url should work for now
> 
> _Originally posted by @williamluke4 in [#884 (comment)](https://github.com/prisma/prisma2/issues/884#issuecomment-551697427)_

Yes, I'm connecting to local DB and then `sslaccept=accept_invalid_certs` is helping

**Comment by pantharshit00** [comment] 2019-12-02 17:37
I am going to close this as a duplicate of https://github.com/prisma/prisma2/issues/884

**Closed by pantharshit00** 2019-12-02 17:37 UTC
