### ISSUE TITLE
[2.0.0-preview-8] `prisma2 init hello-prisma` is not working

### ISSUE THREAD

**Issue by reiwa** [prisma/prisma2#410] opened 2019-08-24 16:08 UTC
## Problem

I cannot make new project by using `prisma2 init`.

```
Error: ENOENT: no such file or directory, scandir 'hello-prisma'
```

## Steps to reproduce

run:

```
$ npm install -g prisma2
$ prisma2 init hello-prisma
Error: ENOENT: no such file or directory, scandir 'hello-prisma'
```

## Environment

macOS Mojave 10.14.6

```
$ prisma2 --version
prisma2@2.0.0-preview-8, binary version: 6146c81a771bef78248317cef9e37fc00863dc08
```

## workaround

make directory before running `prisma2 init`, run:

```
$ mkdir hello-prisma
$ prisma2 init hello-prisma
```

**Comment by pantharshit00** [comment] 2019-08-26 14:12
Duplicate of https://github.com/prisma/prisma2/issues/353

**Closed** 2019-08-26 14:13 UTC
