### ISSUE TITLE
Running operations in postgres is throwing a type error

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma2#339] opened 2019-08-07 16:37 UTC
Reproduction:
Try running the following query:
```js
const test = await photon.users.create({
    data: {
      email: 'pantharshit00@gmil.com',
      name: 'Harshit Pant',
      posts: {
        create: {
          data: 'test',
          date: new Date().toISOString(),
          slug: 'new-posts',
          title: 'New Posts',
        },
      },
    },
  })
```

datamodel:
```groovy
datasource db {
  provider = "postgresql"
  url      = "postgresql://xxx:xxxx@localhost:5432/issue_test_pg?schema=public"
}

generator js {
  provider = "photonjs"
}


model User {
  id    String @id @default(cuid())
  name  String
  email String @unique
  posts Post[]
}

model Post {
  id    String   @id @default(uuid())
  title String
  slug  String   @unique
  data  String
  date  DateTime
  user  User
}
```

Version: prisma2@2.0.0-alpha.95, binary version: 026ffceadcf2b8c42e6b9568a90ba48bbf7c47f1

Error:

![image](https://user-images.githubusercontent.com/22195362/62640626-a010d480-b95f-11e9-9b51-45f475ca917f.png)

**Comment by divyenduz** [comment] 2019-08-09 13:58
This is a duplicate of https://github.com/prisma/prisma2/issues/197

**Closed by divyenduz** 2019-08-09 13:58 UTC
Labels: bug/2-confirmed, kind/bug
