### ISSUE TITLE
Error in <TabIndexProvider> in prisma2@2.0.0-alpha.376

### ISSUE THREAD

**Issue by heymartinadams** [prisma/prisma2#1050] opened 2019-12-04 21:39 UTC
1. Prisma2 version: `"prisma2": "2.0.0-alpha.376"` and `"@prisma/photon": "2.0.0-alpha.376"`

The below error does not occur in `prisma2@2.0.0-alpha.374` (there doesn’t appear to be a `375`).

2. Logs from Developer Tools Console upon `npx prisma2 dev`:
```
d: diff
The above error occurred in the <TabIndexProvider> component:
    in TabIndexProvider
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, App.
Warning: App: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: Cannot read property 'Symbol(keypress-decoder)' of undefined
    at Object.emitKeypressEvents (readline.js:1117:13)
    at Object.useStdin (/Users/martinadams/Apps/ecstatic/prisma/node_modules/prisma2/build/index.js:122801:16)
    at TabIndexProvider (/Users/martinadams/Apps/ecstatic/prisma/node_modules/prisma2/build/index.js:38325:16)
    at renderWithHooks (/Users/martinadams/Apps/ecstatic/prisma/node_modules/prisma2/build/index.js:200168:18)
    at mountIndeterminateComponent (/Users/martinadams/Apps/ecstatic/prisma/node_modules/prisma2/build/index.js:202402:13)
    at beginWork$1 (/Users/martinadams/Apps/ecstatic/prisma/node_modules/prisma2/build/index.js:203546:16)
    at Object.invokeGuardedCallbackImpl (/Users/martinadams/Apps/ecstatic/prisma/node_modules/prisma2/build/index.js:204814:10)
    at invokeGuardedCallback (/Users/martinadams/Apps/ecstatic/prisma/node_modules/prisma2/build/index.js:204998:31)
    at beginWork$$1 (/Users/martinadams/Apps/ecstatic/prisma/node_modules/prisma2/build/index.js:208511:7)
    at performUnitOfWork (/Users/martinadams/Apps/ecstatic/prisma/node_modules/prisma2/build/index.js:207505:12)
(node:19962) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

3. Does the issue persist even after updating to the latest `prisma2` alpha (`npm i -g prisma2@alpha`)?

Yes.

**Comment by pantharshit00** [comment] 2019-12-05 18:40
Looks like it was temporarily broken in alpha. I was able to reproduce this in `2.0.0-alpha.376` but I am no longer able to reproduce this in `prisma2@2.0.0-alpha.414, binary version: a7b03466b4d18c4690a0dfff75efdef816c9cf6b`


I am going to close this since it is fixed now

**Closed by pantharshit00** 2019-12-05 18:40 UTC
