### ISSUE TITLE
 PhotonRequestError: Invalid `photon.()` invocation in

### ISSUE THREAD

**Issue by AhmedElywa** [prisma/prisma2#1319] opened 2020-01-13 17:17 UTC
This my code 

```ts
function getWeightCategory(courseTakingWeightCategories: any[], type: any) {
  if (type === 'TSK' || type === 'NON') return null
  const a = courseTakingWeightCategories.find(
    c => c.courseContentWeightCategory?.assignmentType === type,
  )
  if (!a) return null
  return {
    create: {
      weightCategory: {
        connect: {
          id: a.id,
        },
      },
    },
  }
}

let LessonTakings = LessonContents.map(l => ({
    student: { connect: { id: courseTaking.student.id } },
    user: { connect: { id: courseTaking.student.person.user.id } },
    lessonContent: { connect: { id: l.id } },
    assignmentTakings: {
      create: l.assignmentContents.map(a => {
        const assignmentTakingWeight = courseTakingWeights
        ? getWeightCategory(
          courseTakingWeights?.courseTakingWeightCategories,
          a.type,
        )
        : null;
        return {
// if i removed comment from the next line i get issues that user not in this type 
        // user: { connect: { id: courseTaking.student.person.user.id } },
        isCounted: true,
        requiresReview: !!a.parentInstructions && a.type === 'TSK',
        hasBeenGraded: false,
        canBeRetaken: a.type === 'PRT',
        maxPoints: a.totalPoints,
        assignmentContent: { connect: { id: a.id } },
// the problem here when i add this field to create connect
        assignmentTakingWeight
      }}),
    },
  }))
  await photon.courseTakings.update({
    data: {
      lessonTakings: {
        create: LessonTakings,
      },
    },
    where: {
      id: courseTaking.id,
    },
  })
```

And this is the error message if you can show good message will be great to know what is the problem

```
[GQL] PhotonRequestError: 
[GQL] Invalid `photon.()` invocation in /Users/imac2019/Sites/homeschool_hub/server/prisma2/src/types/Mutations/Course.ts:537:30
[GQL] 
[GQL] 
[GQL] 
[GQL] P2009: Failed to validate the query `Error occurred during query validation & transformation:
[GQL] Assertion error: Attempted conversion of non-map ParsedInputValue (Single(Null)) into map failed..` at ``
[GQL] 
[GQL]     at PhotonFetcher.<anonymous> (/Users/imac2019/Sites/homeschool_hub/server/prisma2/node_modules/@prisma/photon/index.js:63:31)
[GQL]     at Generator.throw (<anonymous>)
[GQL]     at rejected (/Users/imac2019/Sites/homeschool_hub/server/prisma2/node_modules/@prisma/photon/index.js:6:65)
[GQL]     at processTicksAndRejections (internal/process/task_queues.js:94:5) {
[GQL]   code: 'P2009',
[GQL]   meta: {
[GQL]     queryValidationError: 'Error occurred during query validation & transformation:\n' +
[GQL]       'Assertion error: Attempted conversion of non-map ParsedInputValue (Single(Null)) into map failed..',
[GQL]     queryPosition: ''
[GQL]   }
[GQL] }
```

**Comment by AhmedElywa** [comment] 2020-01-14 01:28
I get the problem this field `assignmentTakingWeight` can be null in database but can't pass with null value when create. 
This code working good in Prisma 1 but get this issue with Prisma 2

Second issue i don't know how solve it. 
why this type without user 

```
Unknown arg `user` in data.lessonTakings.create.179.assignmentTakings.create.1.user for type AssignmentTakingCreateWithoutUserInput. Available args:
[GQL] 
[GQL] type AssignmentTakingCreateWithoutUserInput {
[GQL]   assignedAt?: DateTime
[GQL]   startedAt?: DateTime
[GQL]   submittedAt?: DateTime
[GQL]   dueDateAt?: DateTime
[GQL]   timeTaken?: Int
[GQL]   isGradeOverride?: Boolean
[GQL]   isCounted?: Boolean
[GQL]   isSkipped?: Boolean
[GQL]   isDone?: Boolean
[GQL]   requiresReview?: Boolean
[GQL]   numericGrade?: Float
[GQL]   totalPoints?: Float
[GQL]   maxPoints?: Float
[GQL]   hasBeenGraded?: Boolean
[GQL]   canBeRetaken?: Boolean
[GQL]   maxSecondsAllowed?: Int
[GQL]   createdAt?: DateTime
[GQL]   updatedAt?: DateTime
[GQL]   assignmentContent?: AssignmentContentCreateOneWithoutAssignmentContentInput
[GQL]   lessonTaking?: LessonTakingCreateOneWithoutLessonTakingInput
[GQL]   assessmentTakingQuestions?: AssessmentTakingQuestionCreateManyWithoutAssessmentTakingQuestionsInput
[GQL]   assignmentTakingWeight?: AssignmentTakingWeightCreateOneWithoutAssignmentTakingWeightInput
[GQL] }
```

**Comment by pantharshit00** [comment] 2020-01-30 14:47
@AhmedElywa Sorry for the late reply here. Can you please try again with the latest version?

I think this issue is now a duplicate of https://github.com/prisma/prisma2/issues/1475 as it has a more minimal reproduction.

**Comment by pantharshit00** [comment] 2020-01-30 14:48
Yeah, I am sure now, closing this in favour of https://github.com/prisma/prisma2/issues/1475

**Closed by pantharshit00** 2020-01-30 14:48 UTC
Labels: bug/0-needs-info, kind/bug
