### ISSUE TITLE
Does photon support Windows ?

### ISSUE THREAD

**Issue by serotonyn** [prisma/prisma2#445] opened 2019-08-28 10:05 UTC
Hi, I'm building an electron app destined for windows, can I use photon ?

**Comment by pantharshit00** [comment] 2019-08-28 10:09
Duplicate of https://github.com/prisma/prisma2/issues/4.

Windows builds are in our build pipeline now. It is now only a matter of testing them and launching.

**Closed by pantharshit00** 2019-08-28 10:09 UTC
