### ISSUE TITLE
Is support split .prisma file?

### ISSUE THREAD

**Issue by zerox12311** [prisma/prisma2#296] opened 2019-07-30 16:07 UTC
Support split .prisma file?
I want to split prisma schema file as each Model file, and final can merge it.
Is support it?

**Comment by pantharshit00** [comment] 2019-07-30 16:26
Duplicate of https://github.com/prisma/prisma2/issues/92

**Closed by pantharshit00** 2019-07-30 16:26 UTC

**Comment by muslimakhan** [comment] 2024-07-14 12:17
Hey @zerox12311, please check my blog and script here:
[New Trick – Organizing Prisma Models with the MERN Stack](https://muslimahmad.com/trick-organizing-prisma-models-with-the-mern-stack/)
[Github Repo](https://github.com/muslimakhan/Blog-Trick-Organizing-Prisma-Models-with-the-MERN-Stack)

This script could be help in both model split into multiple files and also for enum & types of Prisma ORM. And there is also a way to import predefined data into database too.
Hope, it would be solve your problem.
Thanks
