### ISSUE TITLE
Introspection failed with "Please wait until the 'prisma query-engine' download completes! / SyntaxError: Unexpected token P in JSON at position 0"

### ISSUE THREAD

**Issue by yiruka114514** [prisma/prisma2#1232] opened 2019-12-26 09:00 UTC
I tried to initialize a new project and using my existing MySQL DB, but when I tried to introspect an existing schema, it threw out an error:

>  ERROR  Introspection failed:
Problem while parsing the query engine response at C:\Users\xxxxxxxxx\AppData\Roaming\npm\node_modules\prisma2\query-
engine-windows.exe. Please wait until the 'prisma query-engine' download completes!
SyntaxError: Unexpected token P in JSON at position 0
    at JSON.parse (<anonymous>)
    at C:\Users\xxxxxxxxx\AppData\Roaming\npm\node_modules\prisma2\build\index.js:73749:25
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\xxxxxxxxx\AppData\Roaming\npm\node_modules\prisma2\build\index.js:73659:58)

**Comment by yiruka114514** [comment] 2019-12-26 09:00
How to solve it?

**Comment by janpio** [comment] 2019-12-26 13:15
How did you install the `prisma2` CLI?
How did you create the project?
Can you reproduce this problem consistently?

**Comment by malekjaroslav** [comment] 2019-12-26 14:49
I am getting the same error in the last alpha `2.0.0-alpha.479`, I did not get it in `2.0.0-alpha.476`. I haven't made any changes since the previous version.
```
$ prisma2 dev
Error: Get config SyntaxError: Unexpected token P in JSON at position 0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by janpio** [comment] 2019-12-26 16:30
@malekjaroslav If your error does not contain `Please wait until the 'prisma query-engine' download completes!` please open a new issue for this - the ` SyntaxError: Unexpected token P in JSON at position 0` might be identical but the underlying error is most probably a different one. Thanks.

**Comment by pantharshit00** [comment] 2019-12-26 16:53
I also got this when my prisma binaries were partially downloaded. I got `Error: Get config SyntaxError: Unexpected token P in JSON at position 0`

I think this is related to the fix we did for #944. We need a better error message here. It was fixed for me after I ran `npm install -g prisma2`

**Comment by malekjaroslav** [comment] 2019-12-26 17:27
@pantharshit00 You are right, reinstalling it helped

**Comment by yiruka114514** [comment] 2019-12-27 09:20
@janpio
Thk for reply.    
I installed prisma2 by `npm install prisma2`   
I created my project by `prisma2 init hello-prisma2`  
just following the announcement article.

**Comment by yiruka114514** [comment] 2019-12-31 08:17
Will this problem fixed in next milestone? :-)

**Comment by pantharshit00** [comment] 2020-01-06 09:56
You can fix it now by reinstalling `npm install -g prisma2`. We will try to improve that error message in the future.

**Comment by pantharshit00** [comment] 2020-01-07 13:10
I managed to find a reliable reproduction for the problem.

Steps:
1. Disconnect from the internet
2. Run `prisma2 dev` on any project. It should throw an error saying failed to download the binaries from
3. Run `prisma2 dev` again and see the above error `Unexpected token at JSON position 0`

![image](https://user-images.githubusercontent.com/22195362/71897668-38182180-317d-11ea-9551-60fb95b707a2.png)

**Comment by timsuchanek** [comment] 2020-01-07 17:07
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `prisma2`.
You can try it out with `npm i -g prisma2@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!

**Comment by janpio** [comment] 2020-01-07 20:07
Current alpha is completely broken:

```
C:\Users\Jan\Documents
λ npx prisma2 -v
prisma2@2.0.0-preview019, binary version: e7579bd35e0938dbf773f1706c098a0d14a5a038

C:\Users\Jan\Documents
λ npx prisma2@alpha -v

C:\Users\Jan\Documents
λ
```

**Comment by pantharshit00** [comment] 2020-01-08 13:28
@janpio I am unable to reproduce this. Maybe you got an old version of alpha, can you please give this another shot.
![image](https://user-images.githubusercontent.com/22195362/71981514-90682580-3248-11ea-9e63-45ceb5bb40b1.png)

**Comment by timsuchanek** [comment] 2020-01-08 14:40
This is fixed in the latest alpha.

**Closed by timsuchanek** 2020-01-08 14:40 UTC
Labels: bug/2-confirmed, kind/bug, topic: binaries
