### ISSUE TITLE
`prisma2 dev` fails for new MySQL DB

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#674] opened 2019-10-07 09:21 UTC
When I create a new project with `Blank project > MySQL > Create new MySQL database > Confirm > JavaScript > Demo script` it later fails on `prisma2 dev`:

```
C:\Users\Jan\Documents\throwaway\641_21  (script@1.0.0)
λ prisma2 dev

 Error

   Error: Error in migration engine: [migration-engine/connectors/sql-migration-connector/src/sql_migration_persistence.rs:40] &sql_str = "CRE ATE TABLE `641_21`.`_Migration` (`revision` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY, `name` TEXT NOT NULL, `datamodel` LONGTEXT NOT NULL,
`status` TEXT NOT NULL, `applied` INTEGER NOT NULL, `rolled_back` INTEGER NOT NULL, `datamodel_steps` LONGTEXT NOT NULL, `database_migration`
LONGTEXT NOT NULL, `errors` LONGTEXT NOT NULL, `started_at` datetime(3) NOT NULL, `finished_at` datetime(3));"
   thread 'tokio-runtime-worker-1' panicked at 'called `Result::unwrap()` on an `Err` value: QueryError(MySqlError { ERROR 1146 (42S02): Table  '641_21._migration' doesn't exist }
   stack backtrace:
      0: backtrace::backtrace::trace
      1: backtrace::capture::Backtrace::new_unresolved
      2: failure::backtrace::internal::InternalBacktrace::new
      3: <failure::backtrace::Backtrace as core::default::Default>::default
      4: prisma_query::connector::mysql::error::<impl core::convert::From<mysql::error::Error> for prisma_query::error::Error>::from
      5: prisma_query::connector::metrics::query
      6: <prisma_query::connector::mysql::Mysql as prisma_query::connector::queryable::Queryable>::query
      7: <sql_migration_connector::migration_database::Mysql as sql_migration_connector::migration_database::MigrationDatabase>::query
      8: <sql_migration_connector::sql_migration_persistence::SqlMigrationPersistence as migration_connector::migration_persistence::Migration Persistence>::update
      9: <migration_connector::migration_applier::MigrationApplierImpl<T> as migration_connector::migration_applier::MigrationApplier<T>>::app ly
     10: migration_engine::commands::apply_migration::ApplyMigrationCommand::handle_migration
     11: <migration_engine::commands::apply_migration::ApplyMigrationCommand as migration_engine::commands::command::MigrationCommand>::execut e
     12: <migration_engine::api::MigrationApi<C,D> as migration_engine::api::GenericApi>::apply_migration
     13: migration_engine::api::rpc::RpcApi::create_sync_handler
     14: tokio_executor::enter::exit
     15: tokio_threadpool::blocking::blocking
     16: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
     17: futures::future::chain::Chain<A,B,C>::poll
     18: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
     19: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
     20: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
     21: <futures::future::either::Either<A,B> as futures::future::Future>::poll
     22: <futures::future::map::Map<A,F> as futures::future::Future>::poll
     23: <futures::future::either::Either<A,B> as futures::future::Future>::poll
     24: <futures::future::map::Map<A,F> as futures::future::Future>::poll
     25: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
     26: <futures::stream::and_then::AndThen<S,F,U> as futures::stream::Stream>::poll
     27: <futures::stream::forward::Forward<T,U> as futures::future::Future>::poll
     28: <futures::future::map::Map<A,F> as futures::future::Future>::poll
     29: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
     30: futures::task_impl::std::set
     31: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
     32: std::panicking::try::do_call
     33: __rust_maybe_catch_panic
                at src\libpanic_unwind/lib.rs:82
     34: tokio_threadpool::task::Task::run
     35: tokio_threadpool::worker::Worker::run_task
     36: tokio_threadpool::worker::Worker::run
     37: std::thread::local::LocalKey<T>::with
     38: std::thread::local::LocalKey<T>::with
     39: tokio_reactor::with_default
     40: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
     41: std::thread::local::LocalKey<T>::with
```

![image](https://user-images.githubusercontent.com/183673/66299857-9a4e5580-e8f4-11e9-82e8-7c31b707cdcc.png)

```
λ prisma2 -v
prisma2@2.0.0-alpha.226, binary version: fddd59aef42ed6be4bd1c942a0648bab26b0f2a4
```

**Comment by pantharshit00** [comment] 2019-10-10 13:33
Unable to reproduce on a Mac with `prisma2@2.0.0-alpha.233, binary version: 19ed9db8b704a89eef6fe710fa52c2ad0493443f`

@webnoob also reported the issue with the same error message in #710. So can you and @webnoob can try this with the latest alpha and report back 🙂

**Comment by janpio** [comment] 2019-10-10 14:07
Unfortunately not as `alpha.233`'s `prisma2 dev` does not work on Windows at all: https://github.com/prisma/prisma2/issues/712 But I maybe can retest later when a newer, working alpha is available.

**Comment by webnoob** [comment] 2019-10-11 06:53
How is the alpha to be tested - do we need to pull the repo or are nightly releases done?

**Comment by pantharshit00** [comment] 2019-10-11 09:34
@webnoob 

Use the following command to install alpha:
```
npm install -g prisma2@alpha
```

**Comment by webnoob** [comment] 2019-10-11 12:04
Perfect thanks! I'll use that to keep up to date in that case.

**Comment by janpio** [comment] 2019-10-12 18:15
A later alpha and `preview014` fixed the problem.

**Comment by janpio** [comment] 2019-10-14 12:13
Unfortunately this is not fixed:

```
C:\Users\Jan\Documents\throwaway\710  (node-graphql@1.0.0)
λ prisma2 dev

Error

Error: Error in migration engine: [migration-engine/connectors/sql-migration-connector/src/sql_migration_persistence.rs:40] &sql_str = "CREATE TABLE `e2e`.`_Migration` (`revision` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY, `name` TEXT NOT NULL, `datamodel` LONGTEXT NOT NULL, `status` TEXT NOT NULL, `applied` INTEGER NOT NULL, `rolled_back` INTEGER NOT NULL, `datamodel_steps` LONGTEXT NOT NULL, `database_migration` LONGTEXT NOT NULL, `errors` LONGTEXT NOT NULL, `started_at` datetime(3) NOT NULL, `finished_at` datetime(3));"
thread 'tokio-runtime-worker-1' panicked at 'called `Result::unwrap()` on an `Err` value: QueryError(MySqlError { ERROR 1146 (42S02): Table 'e2e._migration' doesn't exist }
stack backtrace:
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new_unresolved
   2: failure::backtrace::internal::InternalBacktrace::new
   3: <failure::backtrace::Backtrace as core::default::Default>::default
   4: prisma_query::connector::mysql::error::<impl core::convert::From<mysql::error::Error> for prisma_query::error::Error>::from
   5: prisma_query::connector::metrics::query
   6: <prisma_query::connector::mysql::Mysql as prisma_query::connector::queryable::Queryable>::query
   7: <sql_migration_connector::migration_database::Mysql as sql_migration_connector::migration_database::MigrationDatabase>::query
   8: <sql_migration_connector::sql_migration_persistence::SqlMigrationPersistence as migration_connector::migration_persistence::MigrationPersistence>::update
   9: <migration_connector::migration_applier::MigrationApplierImpl<T> as migration_connector::migration_applier::MigrationApplier<T>>::apply
  10: migration_engine::commands::apply_migration::ApplyMigrationCommand::handle_migration
  11: <migration_engine::api::MigrationApi<C,D> as migration_engine::api::GenericApi>::apply_migration
  12: migration_engine::api::rpc::RpcApi::create_sync_handler
  13: tokio_executor::enter::exit
  14: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
  15: futures::future::chain::Chain<A,B,C>::poll
  16: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  17: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
  18: futures::future::chain::Chain<A,B,C>::poll
  19: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  20: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  21: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  22: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  23: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  24: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
  25: <futures::stream::and_then::AndThen<S,F,U> as futures::stream::Stream>::poll
  26: <futures::stream::forward::Forward<T,U> as futures::future::Future>::poll
  27: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  28: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
  29: futures::task_impl::std::set
  30: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  31: std::panicking::try::do_call
  32: __rust_maybe_catch_panic
             at src\libpanic_unwind/lib.rs:80
  33: tokio_threadpool::task::Task::run
  34: tokio_threadpool::worker::Worker::run_task
  35: tokio_threadpool::worker::Worker::run
  36: std::thread::local::LocalKey<T>::with
  37: std::thread::local::LocalKey<T>::with
  38: std::thread::local::LocalKey<T>::with
  39: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  40: std::thread::local::LocalKey<T>::with
  41: std::sys_common::backtrace::__rust_begin_short_backtrace
  42: std::panicking::try::do_call
  43: __rust_maybe_catch_panic
             at src\libpanic_unwind/lib.rs:80
  44: core::ops::function::FnOnce::call_once{{vtable.shim}}
  45: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/fa5c2f3e5724bce07bf1b70020e5745e7b693a57\src\liballoc/boxed.rs:922
  46: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/fa5c2f3e5724bce07bf1b70020e5745e7b693a57\src\liballoc/boxed.rs:922
      std::sys_common::thread::start_thread
             at src\libstd\sys_common/thread.rs:13
      std::sys::windows::thread::Thread::new::thread_start
             at src\libstd\sys\windows/thread.rs:47
  47: sqlite3GenerateConstraintChecks
  48: sqlite3GenerateConstraintChecks
)', src\libcore\result.rs:1165:5
stack backtrace:
   0: backtrace::backtrace::dbghelp::trace
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.37\src\backtrace/dbghelp.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.37\src\backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src\libstd\sys_common/backtrace.rs:76
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src\libstd\sys_common/backtrace.rs:60
   4: core::fmt::write
             at src\libcore\fmt/mod.rs:1030
   5: std::io::Write::write_fmt
             at src\libstd\io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src\libstd\sys_common/backtrace.rs:64
   7: std::sys_common::backtrace::print
             at src\libstd\sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src\libstd/panicking.rs:196
   9: std::panicking::default_hook
             at src\libstd/panicking.rs:210
  10: migration_engine::main::{{closure}}
  11: std::panicking::rust_panic_with_hook
             at src\libstd/panicking.rs:477
  12: std::panicking::continue_panic_fmt
             at src\libstd/panicking.rs:380
  13: rust_begin_unwind
             at src\libstd/panicking.rs:307
  14: core::panicking::panic_fmt
             at src\libcore/panicking.rs:85
  15: core::result::unwrap_failed
             at src\libcore/result.rs:1165
  16: <sql_migration_connector::sql_migration_persistence::SqlMigrationPersistence as migration_connector::migration_persistence::MigrationPersistence>::update
  17: <migration_connector::migration_applier::MigrationApplierImpl<T> as migration_connector::migration_applier::MigrationApplier<T>>::apply
  18: migration_engine::commands::apply_migration::ApplyMigrationCommand::handle_migration
  19: <migration_engine::api::MigrationApi<C,D> as migration_engine::api::GenericApi>::apply_migration
  20: migration_engine::api::rpc::RpcApi::create_sync_handler
  21: tokio_executor::enter::exit
  22: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
  23: futures::future::chain::Chain<A,B,C>::poll
  24: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  25: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
  26: futures::future::chain::Chain<A,B,C>::poll
  27: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  28: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  29: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  30: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  31: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  32: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
  33: <futures::stream::and_then::AndThen<S,F,U> as futures::stream::Stream>::poll
  34: <futures::stream::forward::Forward<T,U> as futures::future::Future>::poll
  35: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  36: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
  37: futures::task_impl::std::set
  38: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  39: std::panicking::try::do_call
  40: __rust_maybe_catch_panic
             at src\libpanic_unwind/lib.rs:80
  41: tokio_threadpool::task::Task::run
  42: tokio_threadpool::worker::Worker::run_task
  43: tokio_threadpool::worker::Worker::run
  44: std::thread::local::LocalKey<T>::with
  45: std::thread::local::LocalKey<T>::with
  46: std::thread::local::LocalKey<T>::with
  47: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  48: std::thread::local::LocalKey<T>::with
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
    at ChildProcess.<anonymous> (C:\ProgramData\nvm\v12.6.0\node_modules\prisma2\build\index.js:215297:35)
    at ChildProcess.emit (events.js:203:13)
    at ChildProcess.EventEmitter.emit (domain.js:471:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)

```

```
λ prisma2 -v
prisma2@2.0.0-preview014.1, binary version: 188a379c9b8c6650e5812f9bdb7407d7b197692f
```

**Comment by janpio** [comment] 2019-10-14 12:13
Please confirm this @pantharshit00

**Comment by webnoob** [comment] 2019-10-14 12:26
I can confirm via: https://github.com/prisma/prisma2/issues/710

I tried this morning and got an error re: get_type() in tokio.

**Comment by pantharshit00** [comment] 2019-10-14 12:40
I am still unable to reproduce this problem on macOS.

Video demo: https://www.youtube.com/watch?v=T6LpxWUcWGE&feature=youtu.be

**Comment by fmeyertoens** [comment] 2019-10-14 14:47
I get the same error when running `prisma2 dev`
I also get the MySQL equivalent error of #107 with `npm run dev`.
The database is created but when I inspect it there are no tables in it. (There should be a `user` and `post` table)

Windows, MariaDB 10.4

**Comment by pantharshit00** [comment] 2019-10-18 05:55
I can reproduce this on windows but not on macOS as I have reported here: https://github.com/prisma/prisma2/issues/735#issuecomment-542761631

Since that issue has a more concrete reproduction I am going to close this one in favour of that issue. The problem reported by both is the same

**Closed by pantharshit00** 2019-10-18 05:55 UTC
Labels: bug/0-needs-info, kind/bug

**Comment by hsouiti** [comment] 2019-11-02 23:11
I have same issue Here.
$ prisma2 -v
prisma2@2.0.0-preview015, binary version: 20b6dc13949cccccfef5be07c0be7a3d7c858abe

**Comment by pantharshit00** [comment] 2019-11-05 16:38
@hsouiti 

Please follow #735 :)
