### ISSUE TITLE
Impossible to change generator binaryTargets

### ISSUE THREAD

**Issue by Prattjames** [prisma/prisma2#1231] opened 2019-12-25 13:56 UTC
Hi,

I tried Prisma 2 on my Ubuntu(Bionic), but the binaryTargets field in generator doesn't seem to work.

Here's my setting:
```
generator photon {
  provider = "photonjs"
  binaryTargets = ["debian-openssl-1.1.x"] 
}
```

Here is what it says, when I try to use photon.js in my code:
```
Error: Photon binary for current platform linux-glibc-libssl1.1.0 could not be found.
Photon looked in null but couldn't find it.
Make sure to adjust the generator configuration in the schema.prisma file:
generator photon {
provider      = "photonjs"
binaryTargets = ["native", "debian-openssl-1.1.x"]
}
Please run prisma2 generate for your changes to take effect.
Note, that by providing `native`, Photon automatically resolves `linux-glibc-libssl1.1
```

Is it possible to replace the native for another value like "debian-openssl-1.1.x" so I don't get this error?
Am I doing it wrong?

**Comment by pantharshit00** [comment] 2019-12-26 17:48
I am unable to reproduce this. Can you please tell me which version of photon are you using. In some parts of the output that you have shared the binary names are out of the date. I faintly remember that we fixed a bug regarding this recently.

I used `prisma2@2.0.0-preview019, binary version: e7579bd35e0938dbf773f1706c098a0d14a5a038` to reproduce this error.

**Comment by divyenduz** [comment] 2020-01-09 14:40
@Prattjames What version of Photon did you use? The error indeed looks incorrect, it lists `linux-glibc-libssl1.1.0` in the content but `debian-openssl-1.1.x` in the fix suggestion. 

`linux-glibc-libssl1.1.0` was the old name of the binary and shouldn't exist anymore. Maybe you are using a newer CLI version in conjunction with an older Photon version? 

Can you please confirm?

**Comment by jean-noelp** [comment] 2020-01-14 14:55
Also, how to synchronize CLI version and Photon version ?

**Comment by divyenduz** [comment] 2020-01-14 15:03
The CLI should warn you if the versions are out of sync. You can bring them to the same version manually via

```sh
yarn add -D prisma2
yarn add -D @prisma/photon 
```

**Comment by jean-noelp** [comment] 2020-01-14 15:15
These commands seems to resolve the initial pb. Thanks.

Now I have an other error looks like i didn't generate schema, even i have. ("no such table: dev.mytable"). But it's an other subject.

**Comment by divyenduz** [comment] 2020-01-14 15:34
Sure, please feel free to close this issue and open a new issue for that one. Thanks.

**Comment by pantharshit00** [comment] 2020-01-17 10:02
> "no such table: dev.mytable")

This happens when you haven't run the migrations so the query engine can't find the tables. Please run migrations using `prisma2 dev` or `prisma2 lift up` 

I am going to close this now

**Closed by pantharshit00** 2020-01-17 10:02 UTC
Labels: bug/0-needs-info, kind/bug, topic: generator
