### ISSUE TITLE
Default for DateTime is '1970-01-01 00:00:00'::timestamp without time zone in PSQL

### ISSUE THREAD

**Issue by malekjaroslav** [prisma/prisma2#1674] opened 2020-02-21 12:07 UTC
Having this user model 
```
model User {
  id                   CUID
  name                 String?
  email                String?              @unique
  username             String?              @unique
  profilePicture       String?
  password             String?
  facebookId           String?              @unique
  googleId             String?              @unique
  newsletter           Boolean              @default(false)
  school               School?
  role                 Role
  deactivatedAt        DateTime?
  deletedAt            DateTime?
  student              Student?
  createdAt            DateTime             @default(now())
  updatedAt            DateTime             @updatedAt
  notificationToken    String?
  isTemporary          Boolean              @default(false)
  notificationSettings NotificationSettings
}
```

Creating a new user fills in `deactivatedAt` and `deletedAt` with default `1970-01-01 00:00:00` 

(Prisma 2.0.0-preview021)

**Comment by pantharshit00** [comment] 2020-02-21 12:36
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/migrate/issues/291

**Closed by pantharshit00** 2020-02-21 12:36 UTC
