### ISSUE TITLE
prisma2 dev cannot find heroku postgres database

### ISSUE THREAD

**Issue by miyi** [prisma/prisma2#869] opened 2019-10-30 18:43 UTC
I'm running the prisma2 demo scripts with heroku postgres database. After the database connects with the correct credentials I'm unable to run prisma2 dev. I'm able to create new users and posts but unable to run `prisma2 dev` so I can change the schema. This is the message I receive.

`You are trying to run prisma2 dev for PostgreSQL database daf9fq054h2b3a.
A database with that name doesn't exist at ec2-107-21-126-201.compute-1.amazonaws.com:5432.
Do you want to create the database?`

The database does exist with that name. If not I wouldn't be able to create users in that database.  What could be the problem?

**Comment by janpio** [comment] 2019-10-30 19:14
What does your connection string in your `schema.prisma` file look like? Does it have both a database name and a schema name?

**Comment by miyi** [comment] 2019-10-30 19:23
<img width="701" alt="Screen Shot 2019-10-30 at 12 18 18 PM" src="https://user-images.githubusercontent.com/6610928/67891288-85d63500-fb0f-11e9-9132-7a29be1dd539.png">

the file includes the database name, otherwise the cli could not have identified that I'm trying to access `database daf9fq054h2b3a`. The file is mostly unedited aside from the new publisher model. Why does prisma2 init succeed but prisma2 lift save fail?

**Comment by janpio** [comment] 2019-10-30 21:12
Can you please show the right part of the connection string, where it should include database and schema name? It might be possible one of both is missing and the error message is misleading/wrong.

**Comment by miyi** [comment] 2019-10-30 21:26
the full string

"postgresql://username:password@ec2-107-21-126-201.compute-1.amazonaws.com:5432/daf9fq054h2b3a?schema=default&sslmode=prefer"

**Comment by pantharshit00** [comment] 2019-10-31 16:16
I am unable to reproduce this. Can you please try making a new heroku database and connecting to it?

**Comment by miyi** [comment] 2019-10-31 23:47
created a new database and switched out the datasource url. I'll give you the full string so you can test it out. 

`postgresql://whenuwtphybfvh:c10f06bbf3d6b0d08f7ab86c3620441ef04e23efb8a423f6e5bc570615bed4e8@ec2-23-21-94-99.compute-1.amazonaws.com:5432/d8bc8llj745u7u?schema=default&sslmode=prefer`

this includes the username and password but its just a test so i guess its alright if I delete it after.

I'll even give you the full credentials

<img width="1208" alt="Screen Shot 2019-10-31 at 4 45 19 PM" src="https://user-images.githubusercontent.com/6610928/67993391-ed6aae00-fbfd-11e9-8412-b5cce2009328.png">

not only does prisma2 lift fail, but I prisma2 init now also fail for the new database

**Comment by pantharshit00** [comment] 2019-11-05 12:10
I wasn't able to reproduce the exact same error posted by you but I was able to reproduce this connection error.
![image](https://user-images.githubusercontent.com/22195362/68206660-503fb900-fff3-11e9-9e84-2e25e052b434.png)

To reproduce this, run `prisma2 lift save --name 'init'` on a default prisma2 project that is using heroku postgres instance.

**Comment by lednhatkhanh** [comment] 2019-11-28 03:06
I got exact same error with a postgres database instance hosted on heroku, failed when running lift up

**Comment by pantharshit00** [comment] 2019-11-28 08:13
@lednhatkhanh Can you please tell me which version of Prisma 2 are you using?

**Comment by lednhatkhanh** [comment] 2019-11-28 09:33
@pantharshit00 I'm using `prisma2@2.0.0-preview017` on MacOS and this is the error I get when trying to run `yarn prisma2 lift up` locally:

![image](https://user-images.githubusercontent.com/9303093/69794365-b12a6d80-11fc-11ea-9526-aa96e3059408.png)

I can still connect to the database using `pgAdmin` though.

**Comment by lednhatkhanh** [comment] 2019-11-28 09:34
@pantharshit00 And I will get the same error as @miyi when running my application on `heroku`

**Comment by pantharshit00** [comment] 2019-11-28 13:27
Certificate not trusted error is related to #884. It will get fixed once we decrease the SSL requirements of our client so please watch that issue for now. There is also a workaround in the issue that you can use for the time being.

**Comment by divyenduz** [comment] 2019-12-09 12:37
@pantharshit00 Please re-triage this one, the behavior changed in preview 18.

**Comment by pantharshit00** [comment] 2019-12-09 18:05
I am no longer able to reproduce this now :)

**Closed by pantharshit00** 2019-12-09 18:05 UTC
Labels: bug/2-confirmed, kind/bug, topic: deployment-platforms
