### ISSUE TITLE
Multiple databases and multiple language support?

### ISSUE THREAD

**Issue by lglie** [prisma/prisma2#1526] opened 2020-02-05 06:20 UTC
Is it possible to provide support for multiple databases and multiple language libraries from the cli based on this prisma.schema, developers operate crud like a database.  specify the database with @@ in model, and specify language with multple generator,  look like:

```
//  prisma.schema file:
datasource db_A {
  provider = "mysql"
  url = "db_A address"
}
datasource db_B {
  provider = "mysql"
  url = "db_B address"
}
generator  js {
  provider      = "js"
  output        ="js_path"
}
generator  go  {
  provider      = "go"
  output        ="go_path"
}
model User {
  @@database(db_A)   // like this
  id               String     @id @default(cuid())
  name         String
}
model Post {
  @@database(db_B)  // like this
  id           String     @id @default(cuid())
  user       User
}
```

**Comment by pantharshit00** [comment] 2020-02-06 09:06
Yes, we have designed the schema to keep this feature in mind. But the scope of this feature is very vast and it would take us quite some time to support this.

You can watch @mavilein's talk on how Prisma works under the hood and how we are going to achieve this in future: https://www.youtube.com/watch?v=RAoXdyI_PH4


We are focusing on the stability of the current feature set right now. 

Closing this as a duplicate of #265

**Closed by pantharshit00** 2020-02-06 09:06 UTC
Labels: kind/question
