### ISSUE TITLE
CASCADE relation not applied in Postgres

### ISSUE THREAD

**Issue by tomitrescak** [prisma/prisma2#810] opened 2019-10-22 03:02 UTC
Hi

I have following model

```
model User {
  id              String                @default(cuid()) @id
  processes       BpmnProcessInstance[] @relation(name: "ProcessOwner", onDelete: CASCADE)
}

model BpmnProcessInstance {
  id            String                    @default(cuid()) @id
  owner         User                      @relation(name: "ProcessOwner")
}
```

When this is lifted to Postgres DB, the Foreign Key is NOT set to CASCADE, but SET NULL.

**Comment by tomitrescak** [comment] 2019-10-22 05:58
This is what is generated

```
CREATE TABLE "public"."BpmnProcessInstance" (
    "id" text NOT NULL,
    "owner" text,
    CONSTRAINT "BpmnProcessInstance_owner_fkey" FOREIGN KEY ("owner") REFERENCES "public"."User"("id") ON DELETE SET NULL,
    PRIMARY KEY ("id")
);
```

**Comment by pantharshit00** [comment] 2019-10-22 15:57
Hi,

Thanks for reporting. This hasn't been implemented yet. I am closing as a duplicate of https://github.com/prisma/prisma2/issues/267

**Closed** 2019-10-22 15:57 UTC
