### ISSUE TITLE
I'm always getting the following issue with prisma2 in @prisma/nexus

### ISSUE THREAD

**Issue by james-ff** [prisma/prisma2#371] opened 2019-08-17 15:57 UTC
I'm always getting the following issue with prisma2 in @prisma/nexus, any ideas as to why?

The error seems to always relate to an "Invalid Invocation" of photon

Could this be caused by the database?

Playground Error output:
```
{
  "errors": [
    {
      "message": "\n\u001b[31mInvalid \u001b[1m`photon.()`\u001b[22m invocation in \u001b[4m/Users/jamesbellamy/Developer/Repositories/my-api/node_modules/apollo-server-core/node_modules/graphql-extensions/src/index.ts:274:18\u001b[24m\u001b[39m\n\n\n\n\u001b[31m\u001b[1mSchema \u001b[22m\u001b[39m",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "findOneItem"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: ",
            "\u001b[31mInvalid \u001b[1m`photon.()`\u001b[22m invocation in \u001b[4m/Users/jamesbellamy/Developer/Repositories/my-api/node_modules/apollo-server-core/node_modules/graphql-extensions/src/index.ts:274:18\u001b[24m\u001b[39m",
            "",
            "",
            "",
            "\u001b[31m\u001b[1mSchema \u001b[22m\u001b[39m",
            "    at PhotonFetcher.<anonymous> (/Users/jamesbellamy/Developer/Repositories/my-api/packages/photon/node_modules/@generated/photon/index.js:46:27)",
            "    at Generator.throw (<anonymous>)",
            "    at rejected (/Users/jamesbellamy/Developer/Repositories/my-api/packages/photon/node_modules/@generated/photon/index.js:5:65)"
          ]
        }
      }
    }
  ],
  "data": {
    "findOneItem": null
  }
}
```

index.ts
```
if (process.env.NODE_ENV.toLowerCase() === 'development') {
  require('dotenv').config()
}

import { ApolloServer } from 'apollo-server'
import { makeSchema, objectType } from '@prisma/nexus'
import { nexusPrismaPlugin } from '@generated/nexus-prisma'
import Photon from '@generated/photon'

import { Context } from './types'

const photon = new Photon()

const nexusPrisma = nexusPrismaPlugin({
  photon: (ctx: Context) => ctx.photon
})

const Item = objectType({
  name: 'Item',
  definition(t) {
    t.model.id()
    t.model.name()
    t.model.image()
    t.model.url()
  }
})

// Query & Mutation

const Query = objectType({
  name: 'Query',
  definition(t) {
    t.crud.findManyItem()
  }
})

const Mutation = objectType({
  name: 'Mutation',
  definition(t) {
    t.crud.createOneItem()
    t.crud.deleteOneItem()
  }
})

// Schema

const schema = makeSchema({
  types: [Query, Mutation, Item, nexusPrisma],
  outputs: {
    typegen: __dirname + '/generated/nexus-typegen.ts',
    schema: __dirname + '/generated/schema.graphql'
  },
  typegenAutoConfig: {
    sources: [{ source: '@generated/photon', alias: 'photon' }, { source: __dirname + '/types.ts', alias: 'ctx' }],
    contextType: 'ctx.Context'
  }
})

// Server

const server = new ApolloServer({
  schema,
  context: { photon }
})

server.listen({ port: 4467 }).then(({ url }) => console.log(`🚀 Server ready at ${url}`))

```

schema.prisma
```
datasource db {
  provider = "postgresql"
  url      = env("POSTGRES_URL")
  default  = true
}

generator photon {
  provider  = "photonjs"
  platforms = ["native", "linux-glibc-libssl1.0.2"]
}

generator nexus_prisma {
  provider = "nexus-prisma"
}

model Item {
  id    Int    @id
  name  String
  image String
  url   String
}
```

**Comment by pantharshit00** [comment] 2019-08-19 11:14
This is caused by #135 

To fix this for either use string ids like so:
```groovy
model Item {
  id    String    @id @default(cuid())
  name  String
  image String
  url   String
}
```

or you can mark the id column auto-incrementing manually.

I am closing this as a duplicate of #135

**Closed by pantharshit00** 2019-08-19 11:14 UTC

**Comment by Fsociety-sem** [comment] 2022-12-27 14:15
I changed to minimal or removed field errorFormat and it gone
