### ISSUE TITLE
`prisma2 dev`: Lots of blank space which hides a lot of output when terminal is small & it basically looks like nothing is below while scrolling

### ISSUE THREAD

**Issue by deadcoder0904** [prisma/prisma2#652] opened 2019-09-30 16:24 UTC
There's also a lot of blank space above `Studio endpoint: http://localhost:5555/`

![prisma2 dev](https://user-images.githubusercontent.com/16436270/65889598-26c1bb00-e3bf-11e9-89e5-ae9885e34af4.png)

I was searching for `Studio endpoint` since I couldn't remember it but when I scrolled I couldn't see anything. Then I had to full-screen my terminal. Mind u, I use VSCode's built-in terminal so I can't see anything more than 1/4 of the screen vertically.

**Comment by divyenduz** [comment] 2019-10-01 13:45
I am unable to reproduce, I made my terminal small but I still see the URL (my terminal always starts at the bottom)

![image](https://user-images.githubusercontent.com/746482/65967800-7f965f80-e462-11e9-8d02-2e88368bf3ba.png)

@deadcoder0904 Maybe a screencast of your screen?

**Comment by deadcoder0904** [comment] 2019-10-01 13:46
@divyenduz use VSCode's built-in terminal, not iTerm

**Comment by divyenduz** [comment] 2019-10-01 13:58
LGTM at least on a big screen:

![image](https://user-images.githubusercontent.com/746482/65968995-5676ce80-e464-11e9-8fbd-6f1c01d566e1.png)

**Comment by deadcoder0904** [comment] 2019-10-01 14:05
Ohh I got to know how to reproduce it. Reduce the terminal until u can see the `d: diff` & then clear the terminal out & start again. U would be unable to scroll below.

Let me know if this works out or I'll share a screencast :)

**Comment by divyenduz** [comment] 2019-10-01 14:57
@deadcoder0904 still cannot reproduce! :)

**Comment by deadcoder0904** [comment] 2019-10-01 16:10
![bug](https://user-images.githubusercontent.com/16436270/65979935-d5cfc680-e493-11e9-8b4d-c759d80986f1.gif)

**Comment by deadcoder0904** [comment] 2019-10-01 16:11
Starts at 5s

**Comment by divyenduz** [comment] 2019-10-02 10:22
Weird indeed, do you know what shell your vscode teminal relies on?

**Comment by deadcoder0904** [comment] 2019-10-02 13:44
The best one 😉 Oh my zsh.

**Comment by pantharshit00** [comment] 2019-10-07 13:19
I think it is related to xterm.js which vscode uses as a renderer.

I was able to reproduce kinda similar thing in https://hyper.is term which also uses the same renderer.

![image](https://user-images.githubusercontent.com/22195362/66315277-19fb1500-e933-11e9-9a69-a1f2bee76ecc.png)
(Notice d:diff doesn't render now)

Now question is that should we allocate bandwidth for this as this gets fixed as soon as you resize and I don't think most people use that small-sized terminal.

**Comment by janpio** [comment] 2019-10-07 13:42
Creating an issue with a concise description of the actual problem with reproduction steps and screenshots etc. is still very valid - we will just not prioritize it for now.

**Comment by deadcoder0904** [comment] 2019-10-07 15:50
Or maybe u guys can put it up somewhere visible. Or u know just the `studio` repo.

**Comment by pantharshit00** [comment] 2019-10-18 05:57
Marking this as a confirmed bug for now so that we can discuss upon it in the planning meeting

**Comment by timsuchanek** [comment] 2020-03-05 11:14
As we removed the `prisma2 dev` command, I'm closing this.

**Closed by timsuchanek** 2020-03-05 11:14 UTC
Labels: bug/2-confirmed, kind/bug, topic: dev
