### ISSUE TITLE
Unable to exit `prisma2 dev` process when an error occurs

### ISSUE THREAD

**Issue by madebysid** [prisma/prisma2#871] opened 2019-10-31 15:12 UTC
When a fatal error occurs during `prisma2 dev` like so:

<img width="1920" alt="Screenshot 2019-10-31 at 16 05 20" src="https://user-images.githubusercontent.com/7689783/67959111-81397b80-fbf8-11e9-8672-f18cad48e96b.png">

The telemetry modal shows up. Instead of selecting something there, if I just try to exit directly using `Ctrl+C`, the process locks up. I'm now in a state where I cannot select an option from the telemetry modal, and cannot exit either.

(To get a fatal error, install prisma2@alpha.270 (before lift's `steps.json` breaking change), run a few migrations, then update to the latest alpha and run `prisma2 dev`)

**Comment by madebysid** [comment] 2019-10-31 15:22
Actually, it seems to be happening for `prisma2 dev` in general, nothing to do with a fatal error. Just run `prisma2 dev` and try to exit using `Ctrl+C`.

`prisma2@2.0.0-alpha.278, binary version: b3ad3ca7cfef392cfd300262c07bfe431b70ff4e`

**Comment by pantharshit00** [comment] 2019-10-31 16:18
I am unable to reproduce this.

![image](https://user-images.githubusercontent.com/22195362/67965506-71bf3000-fc02-11e9-8c23-b423761694ea.png)


Are you able to reproduce this again and again?

**Comment by madebysid** [comment] 2019-10-31 16:55
@pantharshit00 I tried to consistently reproduce this. Here's how.

Perhaps a different issue is that the first `Ctrl+C` doesn't end the process after a fatal error, the second one does. It is all very strange, but hear me out:

1. Run into a fatal error during `prisma2 dev`
2. Press `Ctrl+C` once.
3. Resize your terminal (or open a new tab)
4. Now try `Ctrl+C` again.

Other observations:

Now that `prisma2 dev` is stuck, if I manually kill the process by a `kill -9`, it seems `Ctrl+C` is still captured by something. I know this because pressing `Ctrl+C` in this window now does nothing (It should normally present me with a new prompt)

I am 99% sure this is only a shell (or Ink) issue, but it is consistently reproducible. I'm using ZSH with iTerm2.

I've run into issues like this in the past as well, this is the first time I've been able to pin it down to a terminal resize (or opening a new terminal tab)

**Comment by pantharshit00** [comment] 2019-11-13 12:23
I am still unable to reproduce this. Maybe this is also tied to the exception that you are encountering. 

Anyways, the error spec defines that Rust panics should not be user-facing(https://github.com/prisma/specs/tree/master/errors#unknown-errors). So I think this will get automatically fixed once error spec is implemented.

**Comment by divyenduz** [comment] 2020-01-09 17:18
I am closing this one due to inactivity, if you still think that this is an issue, please comment here and tag me. Thank you 🙏

**Closed by divyenduz** 2020-01-09 17:18 UTC
Labels: bug/0-needs-info, kind/bug
