### ISSUE TITLE
Can't connect to local PostgreSQL DB in `prisma2 init`

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2#1168] opened 2019-12-17 13:20 UTC
I have a local PostgreSQL DB server running that I can access e.g. with Postico:

![image](https://user-images.githubusercontent.com/4058327/70998679-24c2ea80-20d8-11ea-8d1c-f3eaab354f65.png)

However, when I'm trying to connect to it via `prisma2 init`, the `Connecting` loader spins indefinitely after I provided the credentials:

![image](https://user-images.githubusercontent.com/4058327/70998736-415f2280-20d8-11ea-9471-cf17bfdb079c.png)

I enabled `DEBUG`, here's the output that was printed after I ran the command:

```
$ prisma2 init coinflips

  Connect to your PostgreSQL database
  https://pris.ly/d/postgres-connector

┌─ PostgreSQL database credentials ─────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                                               │
│   Host: localhost                                                                                                                             │
│   Port: 5432                                                                                                                                  │
│   User: nikolasburk                                                                                                                           │
│   Password: nikolasburk                                                                                                                       │
│   Database: coinflips                                                                                                                         │
│   Schema (optional):                                                                                                                          │
│   ☐ Use SSL                                                                                                                                   │
│                                                                                                                                               │
├─ PostgreSQL database credentials ─────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│                                                                                                                                               │
│   URL: postgresql://nikolasburk:nikolasburk@localhost:5432/coinflips                                                                          │
│                                                                                                                                               │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

⠋ Connecting
❮ Back (Database options)
  getos { platform: 'darwin', libssl: undefined } +0ms
  getos { platform: 'darwin', libssl: undefined } +20ms
  IntrospectionEngine:rpc SENDING RPC CALL {"id":1,"jsonrpc":"2.0","method":"listDatabases","params":[{"url":"postgresql://nikolasburk:nikolasburk@localhost:5432/coinflips"}]} +0ms
  IntrospectionEngine:stderr Dec 17 14:17:37.945  INFO Loading describer: quaint::single: Starting a postgresql pool with 1 connections.     +0ms
  IntrospectionEngine:stderr Dec 17 14:17:37.945 DEBUG sql_introspection_connector: SqlIntrospectionConnector initialized. +1ms
  IntrospectionEngine:stderr Dec 17 14:17:37.945 DEBUG sql_schema_describer::postgres: Getting table names     +0ms
  IntrospectionEngine:stderr Dec 17 14:17:37.947 DEBUG sql_schema_describer::postgres: Found schema names: ["pg_toast", "pg_temp_1", "pg_toast_temp_1", "pg_catalog", "public", "information_schema"]     +1ms
  IntrospectionEngine:stderr Dec 17 14:17:37.947 DEBUG rpc: Response: {"jsonrpc":"2.0","result":["pg_toast","pg_temp_1","pg_toast_temp_1","pg_catalog","public","information_schema"],"id":1}.     +0ms
  IntrospectionEngine:rpc SENDING RPC CALL {"id":2,"jsonrpc":"2.0","method":"getDatabaseMetadata","params":[{"url":"postgresql://nikolasburk:nikolasburk@localhost:5432/coinflips?schema=pg_toast"}]} +14ms
  IntrospectionEngine:rpc SENDING RPC CALL {"id":3,"jsonrpc":"2.0","method":"getDatabaseMetadata","params":[{"url":"postgresql://nikolasburk:nikolasburk@localhost:5432/coinflips?schema=pg_temp_1"}]} +0ms
  IntrospectionEngine:rpc SENDING RPC CALL {"id":4,"jsonrpc":"2.0","method":"getDatabaseMetadata","params":[{"url":"postgresql://nikolasburk:nikolasburk@localhost:5432/coinflips?schema=pg_toast_temp_1"}]} +0ms
  IntrospectionEngine:rpc SENDING RPC CALL {"id":5,"jsonrpc":"2.0","method":"getDatabaseMetadata","params":[{"url":"postgresql://nikolasburk:nikolasburk@localhost:5432/coinflips?schema=pg_catalog"}]} +1ms
  IntrospectionEngine:rpc SENDING RPC CALL {"id":6,"jsonrpc":"2.0","method":"getDatabaseMetadata","params":[{"url":"postgresql://nikolasburk:nikolasburk@localhost:5432/coinflips?schema=public"}]} +0ms
  IntrospectionEngine:rpc SENDING RPC CALL {"id":7,"jsonrpc":"2.0","method":"getDatabaseMetadata","params":[{"url":"postgresql://nikolasburk:nikolasburk@localhost:5432/coinflips?schema=information_schema"}]} +0ms
  IntrospectionEngine:stderr Dec 17 14:17:37.952  INFO Loading describer: quaint::single: Starting a postgresql pool with 1 connections.     +5ms
  IntrospectionEngine:stderr Dec 17 14:17:37.953 DEBUG sql_introspection_connector: SqlIntrospectionConnector initialized. +1ms
  IntrospectionEngine:stderr Dec 17 14:17:37.953 DEBUG sql_schema_describer::postgres: Getting table names     +0ms
  IntrospectionEngine:stderr Dec 17 14:17:37.957 DEBUG sql_schema_describer::postgres: Found table names: []     +4ms
  IntrospectionEngine:stderr Dec 17 14:17:37.957 DEBUG sql_schema_describer::postgres: Getting db size     +0ms
  IntrospectionEngine:stderr {"message":"[src/libcore/option.rs:1190:5] convert db size result","backtrace":"stack backtrace:\n   0: backtrace::backtrace::trace\n   1: backtrace::capture::Backtrace::new\n   2: user_facing_errors::UnknownError::new_in_panic_hook\n   3: user_facing_errors::panic_hook::set_panic_hook::{{closure}}\n   4: std::panicking::rust_panic_with_hook\n   5: std::panicking::continue_panic_fmt\n   6: rust_begin_unwind\n   7: core::panicking::panic_fmt\n   8: core::option::expect_failed\n   9: <std::future::GenFuture<T> as core::future::future::Future>::poll\n  10: <std::future::GenFuture<T> as core::future::future::Future>::poll\n  11: <std::future::GenFuture<T> as core::future::future::Future>::poll\n  12: tokio::runtime::enter::Enter::block_on\n  13: std::thread::local::LocalKey<T>::with\n  14: std::thread::local::LocalKey<T>::with\n  15: tokio::runtime::spawner::Spawner::enter\n  16: tokio::runtime::time::variant::with_default\n  17: std::thread::local::LocalKey<T>::with\n  18: <introspection_engine::rpc::RpcImpl as introspection_engine::rpc::rpc_impl_Rpc::gen_server::Rpc>::get_database_metadata\n  19: <jsonrpc_core::delegates::DelegateAsyncMethod<T,F> as jsonrpc_core::calls::RpcMethod<M>>::call\n  20: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll\n  21: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll\n  22: <futures::future::map::Map<A,F> as futures::future::Future>::poll\n  23: <futures::future::either::Either<A,B> as futures::future::Future>::poll\n  24: <futures::future::map::Map<A,F> as futures::future::Future>::poll\n  25: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll\n  26: <futures::stream::and_then::AndThen<S,F,U> as futures::stream::Stream>::poll\n  27: <futures::stream::forward::Forward<T,U> as futures::future::Future>::poll\n  28: <futures::future::map::Map<A,F> as futures::future::Future>::poll\n  29: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll\n  30: futures::task_impl::std::set\n  31: std::panicking::try::do_call\n  32: __rust_maybe_catch_panic\n  33: tokio_threadpool::task::Task::run\n  34: tokio_threadpool::worker::Worker::run_task\n  35: tokio_threadpool::worker::Worker::run\n  36: tokio_reactor::with_default\n  37: tokio::runtime::threadpool::builder::Builder::build::{{closure}}\n  38: std::thread::local::LocalKey<T>::with\n  39: std::thread::local::LocalKey<T>::with\n  40: std::sys_common::backtrace::__rust_begin_short_backtrace\n  41: std::panicking::try::do_call\n  42: __rust_maybe_catch_panic\n  43: core::ops::function::FnOnce::call_once{{vtable.shim}}\n  44: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once\n  45: std::sys::unix::thread::Thread::new::thread_start\n  46: _pthread_start\n"} +23ms
setting lastError
  prisma Error: Error in introspection engine: Dec 17 14:17:37.945  INFO Loading describer: quaint::single: Starting a postgresql pool with 1 connections.    
  prisma Dec 17 14:17:37.945 DEBUG sql_introspection_connector: SqlIntrospectionConnector initialized.
  prisma Dec 17 14:17:37.945 DEBUG sql_schema_describer::postgres: Getting table names    
  prisma Dec 17 14:17:37.947 DEBUG sql_schema_describer::postgres: Found schema names: ["pg_toast", "pg_temp_1", "pg_toast_temp_1", "pg_catalog", "public", "information_schema"]    
  prisma Dec 17 14:17:37.947 DEBUG rpc: Response: {"jsonrpc":"2.0","result":["pg_toast","pg_temp_1","pg_toast_temp_1","pg_catalog","public","information_schema"],"id":1}.    
  prisma Dec 17 14:17:37.952  INFO Loading describer: quaint::single: Starting a postgresql pool with 1 connections.    
  prisma Dec 17 14:17:37.953 DEBUG sql_introspection_connector: SqlIntrospectionConnector initialized.
  prisma Dec 17 14:17:37.953 DEBUG sql_schema_describer::postgres: Getting table names    
  prisma Dec 17 14:17:37.957 DEBUG sql_schema_describer::postgres: Found table names: []    
  prisma Dec 17 14:17:37.957 DEBUG sql_schema_describer::postgres: Getting db size    
  prisma {"message":"[src/libcore/option.rs:1190:5] convert db size result","backtrace":"stack backtrace:\n   0: backtrace::backtrace::trace\n   1:
  Connect to your PostgreSQL database
  https://pris.ly/d/postgres-connector

┌─ PostgreSQL database credentials ─────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                                               │
│   Host: localhost                                                                                                                             │
│   Port: 5432                                                                                                                                  │
│   User: nikolasburk                                                                                                                           │
│   Password: nikolasburk                                                                                                                       │
│   Database: coinflips                                                                                                                         │
│   Schema (optional):                                                                                                                          │
│   ☐ Use SSL                                                                                                                                   │
│                                                                                                                                               │
├─ PostgreSQL database credentials ─────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│                                                                                                      
```

**Comment by pantharshit00** [comment] 2019-12-18 15:32
I think this is a duplicate of https://github.com/prisma/prisma2/issues/1087 or https://github.com/prisma/prisma2/issues/1092

This should be fixed in alpha so please try this again with alpha.

**Comment by divyenduz** [comment] 2020-01-09 15:05
Closing this issue, @nikolasburk please re-open and tag me if the problem persists. I am able to use local PG + CLI.

**Closed by divyenduz** 2020-01-09 15:05 UTC
Labels: bug/0-needs-info, kind/bug, topic: cli-init
