### ISSUE TITLE
`alpha.233`: 

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#712] opened 2019-10-10 14:07 UTC
`prisma2 dev` fails on Windows in this version:

```
C:\Users\Jan\Documents\throwaway\674Repro  (script@1.0.0)
λ prisma2 dev
Error:
    Error: C:/ProgramData/nvm/v12.6.0/node_modules/prisma2/build/photon-generator/index.js is not executable. Please run chmod +x ../../../../../ProgramData/nvm/v12.6.0/node_modules/prisma2/build/photon-generator/index.js
        at new GeneratorProcess (C:/ProgramData/nvm/v12.6.0/node_modules/prisma2/build/index.js:471417:19)
        at new Generator (C:/ProgramData/nvm/v12.6.0/node_modules/prisma2/build/index.js:72038:33)
        at Object.<anonymous> (C:/ProgramData/nvm/v12.6.0/node_modules/prisma2/build/index.js:585951:43)
        at Generator.next (<anonymous>)
        at C:/ProgramData/nvm/v12.6.0/node_modules/prisma2/build/index.js:585900:71
        at new Promise (<anonymous>)
        at module.exports.__awaiter (C:/ProgramData/nvm/v12.6.0/node_modules/prisma2/build/index.js:585896:12)
        at p_map_1.default.stopOnError (C:/ProgramData/nvm/v12.6.0/node_modules/prisma2/build/index.js:585943:94)
        at C:/ProgramData/nvm/v12.6.0/node_modules/prisma2/build/index.js:595708:21
```

![image](https://user-images.githubusercontent.com/183673/66576439-02f93480-eb78-11e9-8671-5bd9f26b4740.png)

**Comment by pantharshit00** [comment] 2019-10-11 09:57
Closing as a duplicate of https://github.com/prisma/prisma2/issues/711

**Closed by pantharshit00** 2019-10-11 09:57 UTC
Labels: process/candidate
