### ISSUE TITLE
preview016+ : TLS error with self signed certificate

### ISSUE THREAD

**Issue by marcantoine** [prisma/prisma2#1038] opened 2019-12-04 09:11 UTC
On one of my server, I'm using prisma2 with a managed DB by digital ocean.

My connection string looks like this : 
`"postgresql://user:password@db-prod-fra1-do-user-123456-0.db.ondigitalocean.com:25000/prod?schema=service&slmode=require"`

It was working great until i updated preview016. Now i get a TLS error : 
```
ConnectorError(TlsError { message: "error:1416F086:SSL routines:tls_process_server_certificate:certificate
 verify failed:../ssl/statem/statem_clnt.c:1924: (self signed certificate in certificate chain)" })
```

I don't see any change in the release on the ssl / tls management on preview016. 
Everything worked great before this version. 
My current installation still works great with postgres on local server without SSL.

**Comment by tomhoule** [comment] 2019-12-04 09:15
It's a known issue - we changed SSL certificate handling in postgres recently. This is being fixed and we will align with the behaviour of other postgres clients in the next preview (18). Until then this can be fixed by adding a `sslaccept=accept_invalid_certs` parameter to your connection string.

**Comment by marcantoine** [comment] 2019-12-04 10:03
Thank you Tom, I'll try to add the sslaccept params, looking forward to preview 18!

Should we keep this issue opened or should i close it since its known ?

**Comment by janpio** [comment] 2019-12-04 10:13
@pantharshit00 will close it with a link to the main issue about this topic - until then it is fine to keep it open @marcantoine. Thanks for asking.

**Comment by pantharshit00** [comment] 2019-12-05 12:30
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of #884

**Closed by pantharshit00** 2019-12-05 12:30 UTC
