### ISSUE TITLE
Error: Cannot connect prisma to postgresql certificate verify failed

### ISSUE THREAD

**Issue by rejmank** [prisma/prisma2#1010] opened 2019-11-28 07:36 UTC
Hello, 
i created an demo project of prisma2 with connection to postgresql.  It fails on last step with this error:   
`Error: Could not connect to database: Starting a postgresql pool with 5 connections.
[2019-11-28T07:28:14Z ERROR migration_engine] Error opening a TLS connection. error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1924: (self signed certificate)`
I get the same result when running prisma2 dev.
Postgresql v.12 running on WLS.
The prisma2 is also run from WLS.

**Comment by pantharshit00** [comment] 2019-11-28 08:15
Hi,

Thanks for reporting this but this has been already reported once. So I am going to close this as a duplicate of https://github.com/prisma/prisma2/issues/884

Basically right now our SSL policy in the engine is very strict than other clients. We are planning to loosen it.

**Closed by pantharshit00** 2019-11-28 08:15 UTC
