### ISSUE TITLE
Error in migration engine - Cannot start a runtime from within a runtime. 

### ISSUE THREAD

**Issue by AlexanderProd** [prisma/prisma2#1419] opened 2020-01-22 18:22 UTC
When running `prisma2 migrate save --experimental` with the latest version `2.0.0-preview020.1` I get the following error.

```
ERROR  Oops, an unexpected error occured!
Error in migration engine.
Error in migration engine.
Reason: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.10/src/runtime/ent
er.rs:19:5] Cannot start a runtime from within a runtime. This happens because a function (
like `block_on`) attempted to block the current thread while the thread is being used to dr
ive asynchronous tasks.
```

report id 1313
OS: macOS

schema: 
```
datasource mysql {
  url      = "mysql://*****:****@*****/******"
  provider = "mysql"
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id        String   @id @default(cuid())
  createdAt DateTime @default(now())
  email     String   @unique
  name      String?
  phone     String?
  role      Role     @default(USER)
  posts     Post[]
}

model Post {
  id         String     @id @default(cuid())
  createdAt  DateTime   @default(now())
  updatedAt  DateTime   @updatedAt
  author     User
  title      String
  categories Category[]
  published  Boolean    @default(false)
}

model Category {
  id    String  @id @default(cuid())
  name  String 
}

enum Role {
  USER
  ADMIN
}
```

**Comment by pantharshit00** [comment] 2020-01-22 18:39
I can confirm this
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/22195362/72923175-82e88a80-3d74-11ea-9143-59f06d45243a.png">

**Comment by impowski** [comment] 2020-01-22 18:47
Same here

**Comment by tomhoule** [comment] 2020-01-22 19:52
Working in the dark since I can't reproduce the crash on my machine (linux), but here's a PR that should fix it https://github.com/prisma/prisma-engine/pull/410 - we'll do more manual testing tomorrow

**Comment by impowski** [comment] 2020-01-22 20:38
@tomhoule When the new release will be available to try it out?

**Comment by timsuchanek** [comment] 2020-01-23 08:27
@impowski we'll have a new release today.

**Comment by tomhoule** [comment] 2020-01-23 10:04
We're working on this - I replaced the dependency causing all this misery in this PR https://github.com/prisma/prisma-engine/pull/411

The next steps is testing this in our e2e tests and on OSX manually, then we can release the fix.

**Comment by timsuchanek** [comment] 2020-01-23 10:46
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `prisma2`.
You can try it out with `npm i -g prisma2@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!

**Closed by timsuchanek** 2020-01-23 10:46 UTC
Labels: bug/2-confirmed, kind/regression

**Comment by AlexanderProd** [comment] 2020-01-23 11:00
@timsuchanek Thanks for the quick fix, `migrate save` works now, when applying the changes with `migrate up` there's a new error unfortunately. #1423

**Comment by timsuchanek** [comment] 2020-01-23 12:19
Thanks @AlexanderProd ! We'll look into the other issue in a bit.
