### ISSUE TITLE
Integer ID does not work with PostgreSQL (autoincrement issue ?)

### ISSUE THREAD

**Issue by arn00s** [prisma/prisma2#75] opened 2019-07-02 18:40 UTC
I'm using Prisma2 with a **PostgreSQL** database.
Here's my model :

```
 model User {
   id        Int      @id
   createdAt DateTime @default(now())
   updatedAt  DateTime   @updatedAt
   email     String   @unique
   role        String
}
```

When trying to create some users with this JS script :  

```
const Photon = require('@generated/photon')
const photon = new Photon.default()

async function main() {
  
  const user1 = await photon.users.create({
    data: {
      email: "test@gmail.com",
      name: "test",
      role: "ADMIN"
    },
  })
  const user2 = await photon.users.create({
    data: {
      email: "test2@gmail.com",
      name: "test2",
      role: "USER"
    },
  })
}

main().finally(async () => {
  await photon.disconnect()
})
```

I get the following error : 

```
> node prisma/seed.js
(node:1662) UnhandledPromiseRejectionWarning: Error: Error in Photon: 
[
  {
    "error": "ConnectorError(UniqueConstraintViolation { field_name: \"User.id\" })"
  }
]
    at PhotonFetcher.<anonymous> (/graphql/node_modules/@generated/photon/index.js:35:23)
    at Generator.throw (<anonymous>)
    at rejected (/graphql/node_modules/@generated/photon/index.js:5:65)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
(node:1662) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1662) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
The first user is always created, with ID: 0

However, after switching the ID type to   **id        String   @id @default(cuid())**, it works perfectly.

**Comment by mikaelrss** [comment] 2019-07-26 19:12
I am having the same issue

**Comment by arn00s** [comment] 2019-08-22 09:04
Is that a duplicate of #135  ?

**Comment by mikaelrss** [comment] 2019-08-22 09:25
@arn00s The issue I was experiencing looks like the one described in #135 yes.

**Comment by pantharshit00** [comment] 2019-08-22 09:49
Yes, this is a duplicate of #135 

Even though this was opened before that issue but that issue covers MySQL as well so I am going to close this issue in favour of #135

**Closed by pantharshit00** 2019-08-22 09:49 UTC
Labels: bug/2-confirmed, kind/bug
