### ISSUE TITLE
PRISMA2 CLI: `prisma2 introspect` on MySQL instance running on docker

### ISSUE THREAD

**Issue by rbidanta** [prisma/prisma2#862] opened 2019-10-29 15:47 UTC
`prisma2 introspect --mysql-host 127.0.0.1 --mysql-port 3306 --mysql-user username --mysql-password password --mysql-db database` returns the following error

```Error: The provided database "blob-metadata-storage" does not exist. The following are available: , , , , , ```

Tested on following versions:
**Prisma**
`prisma2@2.0.0-preview014.2, binary version: 237b46b97773f5018e336550e4285e2a78c38483`
`prisma2@2.0.0-preview015, binary version: 20b6dc13949cccccfef5be07c0be7a3d7c858abe`

**macOS** Mojave
**Docker Version** 2.1.0.4
**MySQL** 8.0

I have the port forwarding setup from MySQL Docker container to my local machine and I am able to connect to the MySQL instance running on Docker using MySQL Workbench.

This makes me believe that there is something no quite right with the `prisma2 introspect` CLI

**Comment by rbidanta** [comment] 2019-10-29 16:09
@pantharshit00 I am using `docker-compose`

```

**Comment by pantharshit00** [comment] 2019-11-08 05:35
I can reproduce this:
![image](https://user-images.githubusercontent.com/22195362/68452113-72198580-0217-11ea-9bda-11c82ed8884d.png)

Database test actually exists in the MySQL instance:
![image](https://user-images.githubusercontent.com/22195362/68452130-8198ce80-0217-11ea-9202-f86e50ba9f46.png)


This might get automatically fixed once we start to use the introspection engine written in Rust instead of the current typescript version.

cc @do4gr This might be interesting for you.

**Comment by divyenduz** [comment] 2020-01-09 15:31
We [rewrote introspection](https://github.com/prisma/prisma2/releases) recently. Can you please see if this issue still exists in the latest alpha or preview?

**Comment by pantharshit00** [comment] 2020-01-11 15:32
Unable to reproduce now, closing

![image](https://user-images.githubusercontent.com/22195362/72206581-a9c1d980-34b5-11ea-9990-5465bf4aff6e.png)

**Closed by pantharshit00** 2020-01-11 15:32 UTC
Labels: bug/2-confirmed, kind/bug, topic: old-introspection
