### ISSUE TITLE
How to handle photonjs errors

### ISSUE THREAD

**Issue by kingRayhan** [prisma/prisma2#600] opened 2019-09-25 09:17 UTC
I tried to handle errors thrown by photonjs via `try ... catch` but can't catch this.

```js
const signup = async (_, { data }, { photon }) => {
    try {
        // ............
        // ............
        let user = await photon.users.create({ data })
        return user
    } catch (error) {
        // can not get the error message
         console.log(error) <---- ??
         console.log(error.message) <---- ??
    }
}
```
![image](https://user-images.githubusercontent.com/7611746/65587368-8ecf6600-dfa7-11e9-8edd-e6dff4b0b7c2.png)

**Comment by kingRayhan** [comment] 2019-09-25 09:24
#600

**Comment by divyenduz** [comment] 2019-09-25 13:13
@kingRayhan Do you have a reproduction that I can try? I think native Photon errors are cached but query engine errors are not.

**Comment by kingRayhan** [comment] 2019-09-25 15:21
Here is the reproduction repo 
https://github.com/kingRayhan/photon-problem

**Comment by kingRayhan** [comment] 2019-09-26 07:04
@divyenduz any update?

**Comment by divyenduz** [comment] 2019-09-26 09:59
I think that this error is being caught, I just added a `console.log('=====')` in the catch block and I could see it when the query engine fails to start. 

I tried the following: 

1. Tried unique constraint error
2. Removed the underlying binary
3. Made the underlying binary invalid by using an empty file as the binary

All are correctly caught. Can you confirm? @kingRayhan

**Comment by kingRayhan** [comment] 2019-09-26 20:06
@divyenduz 
Did you get any output in your catch block thrown by **when** you do this `console.log(e.message)`

```js
try {
    // ............
    // ............
    let user = await photon.users.create({ data })
    return user
} catch (error) {
    console.log(error.message) // <-- I expect a message here which will be thrown by photon
}
```

**Comment by divyenduz** [comment] 2019-09-27 08:19
Yes, I think it is related to this https://github.com/prisma/photonjs/issues/195

You are getting the message but since it is pretty formatted with ANSI characters, it is hard to spot. Do you agree?

**Comment by kingRayhan** [comment] 2019-09-27 11:55
@divyenduz Thanks.
Can I somehow stop pretty formatted message and get a plain error object? Or it's an upcoming feature?

**Comment by divyenduz** [comment] 2019-09-27 11:58
Those are ANSI characters that makes Photon's output in the shell colorful etc. For now, you can pass Photon's error through a strip ANSI lib (https://www.npmjs.com/package/strip-ansi)

This spec (not implemented yet) talks about this more and would enable disabling it. https://github.com/prisma/specs/tree/master/photonjs#error-handling

If you think that this issue is now a duplicate, please feel free to close it :)

**Closed** 2019-09-27 12:00 UTC
Labels: bug/0-needs-info, kind/bug
