### ISSUE TITLE
 Does the prisma schema support folders?

### ISSUE THREAD

**Issue by lglie** [prisma/prisma2#1562] opened 2020-02-09 00:59 UTC
When the project is relatively large, a schema.prisma file will become very large, developer need to split the schema file into multiple files. Is it possible to add an optional folder (if named models) to place these files, Like this:
![image](https://user-images.githubusercontent.com/931410/74094392-575af380-4b1b-11ea-8aef-baf1fe7d6df4.png)

**Comment by pantharshit00** [comment] 2020-02-10 13:40
Hi,

Thanks for requesting this! It has already been requested before, so I am going to close this as a duplicate of https://github.com/prisma/prisma2/issues/92

**Closed by pantharshit00** 2020-02-10 13:40 UTC
