### ISSUE TITLE
[bug] missing field `on_delete` in preview-6

### ISSUE THREAD

**Issue by beeplin** [prisma/prisma2#342] opened 2019-08-09 04:23 UTC
After upgrading to preview-6, `prisma2 lift save` reports the following error:

```Error: Error in lift engine for rpc listMigrations:
  thread 'main' panicked at 'Deserializing the database migration failed.: Error("missing field `on_delete`", line: 0, column: 0)', src/libcore/result.rs:997:5
```

**Comment by divyenduz** [comment] 2019-08-09 08:57
@beeplin Can you share some more information about this project, like the DB used and the datamodel? Maybe if possible, a minimal reproduction? Thanks :)

**Comment by keepforever** [comment] 2019-08-10 03:22
I ran into this issue too.  

Chronology:  

I hadn't made any edits to my data model for some time, just stopping and starting the server.  

Things had been working fine.

I decided to add two fields to a model.  

I add the fields (`altList` and `altCard`, in `schema.prisma`. )

```
model Deck {
    id         String  @id @default(cuid())
    title      String?
    list       String?
    altList    String?
    altCard    String?
    comments   Comment[]
    author     User?
}
```

I update the model with two new fields.  
```
export const Deck = objectType({
  name: 'Deck',
  definition(t: any) {
    t.model.id()
    t.model.title()
    t.model.list()
    t.model.altList()
    t.model.altCard()
    t.model.author()
    t.model.comments({ pagination: false })
  },
})
```

I name my migration `prisma2 lift save --name 'edit-deck'`

this is when that error occurred.  

I had to nuke my container and start fresh.  

then it worked.  

I run into this issue a lot where migrations get out of sync and editing the model has errors. 

I have to start over every time I make an edit to a model.

I wish the steps were clearer on what order you must do things when you make an edit.  

video tutorals would be great.

**Comment by gihrig** [comment] 2019-08-10 07:03
A Reproduction project:

>prisma2: prisma2@2.0.0-preview-6, binary version: 4d17a0639165e5a8e54c7e5cf538ffdf114edb53
>macOS: 10.14.6
>Node: 12.7.0

Preview-6: `prisma2 lift save --name 'addLogin'` when run on unchanged (and changed) schema always throws the error, for me.

Reverting to Preview-5 eliminates the error and migrates the new schema as expected.

This issue appears on a project which is a modified version of the Photon TS example `graphql-auth`.
The problem does _not_ appear on the 'official', unaltered example.

***To produce the error:***

With preview-6.1

`$ git clone https://github.com/gihrig/hello-photon-graphql-auth.git`
`$ git checkout addLogin-err`
`$ yarn`
`$ prisma2 lift save --name 'addLogin'`

revert to preview-5 and there is no error

`$ sudo npm i -g --unsafe-perm prisma2@2.0.0-preview-5`
`$ prisma2 lift save --name 'addLogin'`

-------------------------------------------

>Error: Error in lift engine for rpc listMigrations:
>thread 'main' panicked at 'Deserializing the database migration failed.: Error("missing field `on_delete`", line: 0, column: 0)', src/libcore/result.rs:997:5

schema.prisma
```graphql
datasource db {
  provider = "sqlite"
  url      = "file:dev.db"
  default  = true
}

generator photon {
  provider = "photonjs"
}

generator nexus_prisma {
  provider = "nexus-prisma"
}

model Post {
  id        String   @default(cuid()) @id @unique
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  published Boolean
  title     String
  content   String?
  author    User?
}

model User {
  id       String  @default(cuid()) @id @unique
  email    String  @unique
  password String
  name     String?
  posts    Post[]
}
```

Failed listMigrations
```markdown

# Failed listMigrations at 2019-08-10T05:30:59.341Z
## RPC Input One Line
```json
{"id":1,"jsonrpc":"2.0","method":"listMigrations","params":{"projectInfo":"","sourceConfig":"datasource db {\n  provider = \"sqlite\"\n  url      = \"file:dev.db\"\n  default  = true\n}\n\ngenerator photon {\n  provider = \"photonjs\"\n}\n\ngenerator nexus_prisma {\n  provider = \"nexus-prisma\"\n}\n\nmodel Post {\n  id        String   @default(cuid()) @id @unique\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n  published Boolean\n  title     String\n  content   String?\n  author    User?\n}\n\nmodel User {\n  id       String  @default(cuid()) @id @unique\n  email    String  @unique\n  password String\n  name     String?\n  posts    Post[]\n}\n"}}
```

## RPC Input Readable
```json
{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "listMigrations",
  "params": {
    "projectInfo": "",
    "sourceConfig": "datasource db {\n  provider = \"sqlite\"\n  url      = \"file:dev.db\"\n  default  = true\n}\n\ngenerator photon {\n  provider = \"photonjs\"\n}\n\ngenerator nexus_prisma {\n  provider = \"nexus-prisma\"\n}\n\nmodel Post {\n  id        String   @default(cuid()) @id @unique\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n  published Boolean\n  title     String\n  content   String?\n  author    User?\n}\n\nmodel User {\n  id       String  @default(cuid()) @id @unique\n  email    String  @unique\n  password String\n  name     String?\n  posts    Post[]\n}\n"
  }
}
```


## RPC Response
```
null
```

## Stack Trace
```bash
thread 'main' panicked at 'Deserializing the database migration failed.: Error("missing field `on_delete`", line: 0, column: 0)', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: <sql_migration_connector::SqlMigrationConnector as migration_connector::MigrationConnector>::deserialize_database_migration
  10: migration_core::commands::list_migrations::convert_migration_to_list_migration_steps_output
  11: <migration_core::commands::list_migrations::ListMigrationStepsCommand as migration_core::commands::command::MigrationCommand>::execute
  12: <F as jsonrpc_core::calls::RpcMethodSimple>::call
  13: <F as jsonrpc_core::calls::RpcMethod<T>>::call
  14: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
  15: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  16: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  17: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  18: futures::task_impl::std::set
  19: std::thread::local::LocalKey<T>::with
  20: futures::future::Future::wait
  21: jsonrpc_core::io::IoHandler<M>::handle_request_sync
  22: migration_core::rpc_api::RpcApi::handle
  23: migration_engine::main
  24: std::rt::lang_start::{{closure}}
  25: std::panicking::try::do_call
  26: __rust_maybe_catch_panic
  27: std::rt::lang_start_internal
  28: main

```

```

**Comment by pantharshit00** [comment] 2019-08-12 16:07
I can confirm this

**Comment by divyenduz** [comment] 2019-08-13 09:46
Happened once to me as well but only on a DB that is setup with preview 5 and below, a new DB setup with preview 6 does not exhibit this: https://gist.github.com/divyenduz/ca80533a8b4dfa0b2a2023de7e3c7cae

**Comment by gihrig** [comment] 2019-08-13 19:14
I agree, the problem is more a preview 5 to 6 migration issue than a bug, per se.

I tried editing or deleting records in the `_migrations` table, even dropping the the table, and removing different items in `prisma/migrations`. In the end I had to delete the database file to get preview-6 to work.

To get to preview-6 I did the following, working with SQLite:

1. Export db data, excluding the `_migrations` table
2. Delete the database file (dev.db)
3. Delete `prisma/migrations/lift.lock`
4. Remove any folders under `prisma/migrations` that correspond to earlier failed migrations.
5. `prisma2 lift up`
6. Import data

Now `prisma2 lift up` reports '**All migrations are already applied**'

**Comment by divyenduz** [comment] 2019-08-15 09:25
Update: Thanks for raising this issue, we missed this regression between preview-5 and preview-6 and this should have been mentioned in the release notes. We will take measures to make sure that we avoid that in future. 

We expect breaking changes like these to occasionally pop up between preview releases and we will have release notes for all regressions. I will close this issue. 

Please re-open a new issue if you feel that something is still unaddressed from this issue.

**Closed by divyenduz** 2019-08-15 09:25 UTC
Labels: bug/2-confirmed, kind/bug
