### ISSUE TITLE
Get an issue when trying to run prisma2 dev 

### ISSUE THREAD

**Issue by etelsv** [prisma/prisma2#307] opened 2019-08-01 16:46 UTC
When I run Prisma 2 dev on a database from here: https://github.com/raosaif/sample_postgresql_database

with the following schema (already adapted to add @id fields for everything requiring it)

```
datasource db {
  provider = "postgresql"
  url      = "postgresql://etel:etel@localhost:5432/imdb?schema=public"
}

generator photonjs {
  provider = "photonjs"
}

model Actor {
  actor_id      Int            @id
  contentActors ContentActor[]
  lastUpdated   DateTime       @map("last_updated")
  name          String

  @@map("actors")
}

model Content {
  content_id       Int               @id
  contentActors    ContentActor[]
  contentDirectors ContentDirector[]
  contentGenres    ContentGenre[]
  contentRating    ContentRating?    @map("content_rating")
  contentType      ContentType       @map("content_type")
  description      String?
  episodeList      EpisodeList[]
  imdbLink         String            @map("imdb_link") @unique
  imdbScore        Float             @map("imdb_score")
  imdbScoreVotes   Int               @map("imdb_score_votes")
  lastUpdated      DateTime          @map("last_updated")
  playTime         String            @map("play_time")
  releaseDates     String            @map("release_dates")
  title            String
  totalEpisodes    Int               @map("total_episodes")
  totalSeasons     Int               @map("total_seasons")

  @@map("contents")
}

model ContentActor {
  content_actor_id Int       @id
  actor            Actor?    @map("actor_id")
  content          Content?  @map("content_id")
  lastUpdated      DateTime? @map("last_updated")

  @@map("content_actors")
}

model ContentDirector {
  content_director_id Int       @id
  content             Content?  @map("content_id")
  director            Director? @map("director_id")
  lastUpdated         DateTime? @map("last_updated")

  @@map("content_directors")
}

model ContentGenre {
  content_genre_id Int       @id
  content          Content?  @map("content_id")
  genre            Genre?    @map("genre_id")
  lastUpdated      DateTime? @map("last_updated")

  @@map("content_genres")
}

model ContentRating {
  content_rating_id Int          @id
  contents          Content[]
  contentType       ContentType? @map("content_type_id")
  description       String?
  lastUpdated       DateTime?    @map("last_updated")
  name              String       @unique

  @@map("content_ratings")
}

model ContentType {
  content_type_id Int             @id
  contentRatings  ContentRating[]
  contents        Content[]
  lastUpdated     DateTime?       @map("last_updated")
  name            String          @unique

  @@map("content_types")
}

model Director {
  director_id      Int               @id
  contentDirectors ContentDirector[]
  lastUpdated      DateTime          @map("last_updated")
  name             String

  @@map("directors")
}

model EpisodeList {
  episode_id        Int      @id
  content           Content? @map("content_id")
  description       String?
  episodeImdbLink   String   @map("episode_imdb_link") @unique
  episodeName       String   @map("episode_name")
  episodeNum        Int      @map("episode_num")
  episodeRating     Float    @map("episode_rating")
  episodeScoreVotes Int      @map("episode_score_votes")
  lastUpdated       DateTime @map("last_updated")
  releaseDate       String   @map("release_date")
  seasonNum         Int      @map("season_num")

  @@map("episode_list")
}

model Genre {
  genre_id      Int            @id
  contentGenres ContentGenre[]
  lastUpdated   DateTime       @map("last_updated")
  name          String         @unique

  @@map("genres")
}

model Language {
  language_id Int      @id
  lastUpdated DateTime @map("last_updated")
  name        String   @unique

  @@map("languages")
}
```
I get the following error when I try to run `prisma2 dev`

```
 Error

   Error: Error in lift engine for rpc inferMigrationSteps:
     [migration-engine/connectors/sql-migration-connector/src/lib.rs:391] format!("CREATE SCHEMA IF NOT EXISTS \"{}\";" , & self . schema_name) = "CREATE SCHEMA IF NOT EXISTS \"publ
ic\";"
   [migration-engine/connectors/sql-migration-connector/src/sql_migration_persistence.rs:39] m.make_from(barrel_variant) = "CREATE TABLE \"public\".\"_Migration\" (\"revision\" SERI
AL PRIMARY KEY NOT NULL, \"name\" TEXT NOT NULL, \"datamodel\" TEXT NOT NULL, \"status\" TEXT NOT NULL, \"applied\" INTEGER NOT NULL, \"rolled_back\" INTEGER NOT NULL, \"datamodel_s
teps\" TEXT NOT NULL, \"database_migration\" TEXT NOT NULL, \"errors\" TEXT NOT NULL, \"started_at\" timestamp(3) NOT NULL, \"finished_at\" timestamp(3));"
   [/var/root/.cargo/git/checkouts/prisma-query-a8c45647247f5d6d/1107e25/src/connector/postgres.rs:118] visitor::Postgres::build(q) = (
       "SELECT \"public\".\"_Migration\".* FROM \"public\".\"_Migration\" WHERE \"status\" = $1 ORDER BY \"revision\" DESC",
       [
           Text(
               "MigrationSuccess",
           ),
       ],
   )
   thread 'main' panicked at 'type json is not supported here yet. Column was: rating_details', migration-engine/connectors/sql-migration-connector/src/database_inspector/postgres_i
nspector.rs:103:14
   stack backtrace:
      0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
      1: std::sys_common::backtrace::_print
      2: std::panicking::default_hook::{{closure}}
      3: std::panicking::default_hook
      4: std::panicking::rust_panic_with_hook
      5: std::panicking::begin_panic
      6: sql_migration_connector::database_inspector::postgres_inspector::column_type
      7: sql_migration_connector::database_inspector::database_inspector_impl::convert_introspected_columns::{{closure}}
      8: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
      9: sql_migration_connector::database_inspector::database_inspector_impl::convert_introspected_columns
     10: sql_migration_connector::database_inspector::postgres_inspector::Postgres::get_table
     11: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
     12: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
     13: <sql_migration_connector::database_inspector::postgres_inspector::Postgres as sql_migration_connector::database_inspector::DatabaseInspector>::introspect
     14: <sql_migration_connector::sql_database_migration_inferrer::SqlDatabaseMigrationInferrer as migration_connector::database_migration_inferrer::DatabaseMigrationInferrer<sql_m
igration_connector::sql_migration::SqlMigration>>::infer
     15: <migration_core::commands::infer_migration_steps::InferMigrationStepsCommand as migration_core::commands::command::MigrationCommand>::execute
     16: <F as jsonrpc_core::calls::RpcMethodSimple>::call
     17: <F as jsonrpc_core::calls::RpcMethod<T>>::call
     18: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
     19: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
     20: <futures::future::map::Map<A,F> as futures::future::Future>::poll
     21: <futures::future::either::Either<A,B> as futures::future::Future>::poll
```
running `prisma generate` on this dataset still faces this issue: https://github.com/prisma/prisma2/issues/274

**Comment by divyenduz** [comment] 2019-08-13 10:45
This is marked as an FR because JSON type is not supported yet `panicked at 'type json is not supported here yet.`

**Comment by divyenduz** [comment] 2019-08-14 14:00
Closing this one as a duplicate of https://github.com/prisma/prisma2/issues/186
Please re-open if you think that this is a separate issue. Thanks :)

**Closed by divyenduz** 2019-08-14 14:00 UTC
Labels: kind/feature
