### ISSUE TITLE
How to count the data in nexus prisma ?

### ISSUE THREAD

**Issue by justicejoe** [prisma/prisma2#1230] opened 2019-12-25 05:49 UTC
Is there a way to  only count the data ? For example, 
with something like 
{
    events(where : { ... }){
        count
    }
}

I want to get only the number of data that I filtered.

**Comment by pantharshit00** [comment] 2019-12-26 17:23
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/photonjs/issues/252

**Closed by pantharshit00** 2019-12-26 17:23 UTC
