### ISSUE TITLE
Cannot auto-generate int ids on Linux

### ISSUE THREAD

**Issue by baby1990** [prisma/prisma2#1288] opened 2020-01-08 01:21 UTC
I use mac to develop backend service.Auto-generate int ids is working well on mac. But the moment I run the program on Linux machine.The service send an error message, which shows that I did not provide the id field.

**Comment by pantharshit00** [comment] 2020-01-08 13:30
Hi,

Can you please give me a reproduction? Please share your schema(or a part of it) and please also tell me which connector you are using and which version of Prisma 2 are you using.

Also, details about your OS(paste output of `uname -a`, `lsb_release -a`) would also be appreciated.

**Comment by webnoob** [comment] 2020-01-08 14:01
I am also facing this issue on Windows.

Using Preview19.
SQLite DB

Schema:
```
datasource db {
  provider = "sqlite"
  url = env("SQLITE_URL")
  enabled = env("SQLITE_URL")
}

generator photon {
  provider = "photonjs"
}

model Book {
  id    Int  @default(autoincrement()) @id
  createdDate Int
  updatedDate Int?
  title String
  description  String?
}

model PenName {
  id    Int  @default(autoincrement()) @id
  createdDate Int
  updatedDate Int?
  name String
  bio  String?
  image String?
  facebookLink String?
  bookbubLink String?
  twitterLink String?
}

model User {
  id    Int  @default(autoincrement()) @id
  createdDate Int
  updatedDate Int?
  username String @unique
  emailAddress String @unique
  password String
  role Int
  canActAs User[] @relation(name: "canActAs")
  hasActingAs User[] @relation(name: "canActAs")
}
```

If I try to call
```
photon.users.create({
  data: {
	createdDate: Date.now(),
	updatedDate: dto.updatedDate,
	username: dto.username,
	emailAddress: dto.emailAddress,
	password: dto.password,
	role: dto.role,
	createdDate: 0
  }
})
```
It results in an error from regarding typ mismatch in SQLite DB.

The SQL Lite DB column is generated correctly as an `Int NOT NULL PRIMARY KEY AUTOINCREMENT` field.

**Comment by pantharshit00** [comment] 2020-01-13 12:45
@webnoob I am unable to reproduce this. Can you paste the screenshot of the type error here? 

Your code contains `createDate` twice with different types of values assigned to it so that is likely is the cause of the type mismatch.

**Comment by webnoob** [comment] 2020-01-14 09:16
I'll take a look today and try to provide some more information.

This was a subset of the data (I was trying to insert another model and got this error) and granted this model is incorrect with that field showing twice but the error went away as soon as I reverted to using strings as ids.

Will come back to you ASAP.

**Comment by webnoob** [comment] 2020-01-14 09:35
I can no longer reproduce this - I must have been doing some strange the first time around .... 🤔

**Comment by webnoob** [comment] 2020-01-14 10:08
I can no longer recreate this so am not sure what the initial issue was - It must have been an error on my side which has since been fixed. Sorry.

**Closed** 2020-01-17 01:10 UTC
Labels: bug/0-needs-info, kind/bug, topic: photon
