### ISSUE TITLE
SQLite introspection fails with "thread 'main' panicked at 'No id field defined!" for Chinook dataset

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2#1088] opened 2019-12-09 15:15 UTC
The Chinook dataset is the [default example used in the SQLite documentation](https://www.sqlitetutorial.net/sqlite-sample-database/), you can find the DB file [here](https://github.com/prisma/prisma-datasets/blob/master/datasets/sqlite/chinook/prisma/chinook.db).

I just ran introspection against it using this command:

```
prisma2 introspect --url="file:./chinook.db"
```

The command failed with this message:

```
Introspection failed: Introspected schema can't be parsed.
Introspected Schema:

model artists {
  ArtistId Int      @id
  Name     String?
  albumses albums[]
}

model genres {
  GenreId  Int      @id
  Name     String?
  trackses tracks[] @relation(references: [GenreId])
}

model media_types {
  MediaTypeId Int      @id
  Name        String?
  trackses    tracks[] @relation(references: [MediaTypeId])
}

model playlists {
  Name                String?
  PlaylistId          Int                  @id
  playlist_tracks     playlist_track[]
  new_playlist_tracks new_playlist_track[]
}

model playlist_track {
  PlaylistId playlists
  TrackId    tracks

  @@id([PlaylistId, TrackId])
}

model tracks {
  AlbumId             albums?
  Bytes               Int?
  Composer            String?
  GenreId             genres?
  MediaTypeId         media_types
  Milliseconds        Int
  Name                String
  TrackId             Int                  @id
  UnitPrice           Float
  playlist_tracks     playlist_track[]
  invoice_itemses     invoice_items[]
  new_playlist_tracks new_playlist_track[]
}

model albums {
  AlbumId  Int      @id
  ArtistId artists
  Title    String   @default("'n/a'")
  trackses tracks[] @relation(references: [AlbumId])
}

model customers {
  Address      String?
  City         String?
  Company      String?
  Country      String?
  CustomerId   Int        @id
  Email        String     @default("''")
  Fax          String?
  FirstName    String     @default("''")
  LastName     String     @default("''")
  Phone        String?
  PostalCode   String?
  State        String?
  SupportRepId employees?
  invoiceses   invoices[] @relation(references: [CustomerId])
}

model employees {
  Address     String?
  BirthDate   DateTime?
  City        String?
  Country     String?
  Email       String?
  EmployeeId  Int         @id
  Fax         String?
  FirstName   String      @default("''")
  HireDate    DateTime?
  LastName    String      @default("''")
  Phone       String?
  PostalCode  String?
  ReportsTo   employees?  @relation("employeesToemployees_ReportsTo")
  State       String?
  Title       String?
  customerses customers[]
  employeeses employees[] @relation("employeesToemployees_ReportsTo")
}

model invoices {
  BillingAddress    String?
  BillingCity       String?
  BillingCountry    String?
  BillingPostalCode String?
  BillingState      String?
  CustomerId        customers
  InvoiceDate       DateTime
  InvoiceId         Int             @id
  Total             Float           @default(0)
  invoice_itemses   invoice_items[]
}

model invoice_items {
  InvoiceId     invoices
  InvoiceLineId Int      @id
  Quantity      Int      @default(0)
  TrackId       tracks
  UnitPrice     Float    @default(0)
}

model new_playlist_track {
  PlaylistId playlists
  TrackId    tracks
  id         String    @id
}

Error: Schema parsing
thread 'main' panicked at 'No id field defined!', src/libcore/option.rs:1190:5
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::continue_panic_fmt
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::option::expect_failed
  10: once_cell::imp::OnceCell<T>::initialize::{{closure}}
  11: once_cell::imp::initialize_inner
  12: once_cell::imp::OnceCell<T>::initialize
  13: prisma_models::fields::Fields::id
  14: query_core::schema_builder::object_type_builder::ObjectTypeBuilder::many_records_arguments
  15: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
  16: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::next
  17: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  18: query_core::schema_builder::object_type_builder::ObjectTypeBuilder::new
  19: query_core::schema_builder::query_schema_builder::QuerySchemaBuilder::new
  20: prisma::cli::CliCommand::execute
  21: <std::future::GenFuture<T> as core::future::future::Future>::poll
  22: tokio::runtime::global::with_thread_pool
  23: tokio::runtime::global::with_state
  24: tokio::runtime::spawner::Spawner::enter
  25: tokio::runtime::time::variant::with_default
  26: std::thread::local::LocalKey<T>::with
  27: prisma::main
  28: std::rt::lang_start::{{closure}}
  29: std::panicking::try::do_call
  30: __rust_maybe_catch_panic
  31: std::rt::lang_start_internal
  32: main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
    at Object.<anonymous> (/Users/nikolasburk/.config/yarn/global/node_modules/prisma2/build/index.js:73435:23)
    at Generator.throw (<anonymous>)
    at rejected (/Users/nikolasburk/.config/yarn/global/node_modules/prisma2/build/index.js:73330:65)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)

```

CLI version:

```
prisma2@2.0.0-preview018, binary version: 8d88815bac0dd673ab8c2def11f441ef44fb189d
```

**Comment by janpio** [comment] 2019-12-09 20:25
This is a more general problem we have right now, see also this issue: https://github.com/prisma/prisma-engine/issues/254

**Comment by janpio** [comment] 2019-12-15 10:54
Closing as duplicate of https://github.com/prisma/prisma2/issues/1113

**Comment by divyenduz** [comment] 2020-01-09 15:23
@janpio Can't this one be closed and the underlying issue is now tracked?

**Comment by janpio** [comment] 2020-01-09 15:34
Yeah, good enough.

**Closed by janpio** 2020-01-09 15:34 UTC
Labels: bug/2-confirmed, kind/bug, topic: introspection, topic: sqlite
