### ISSUE TITLE
Generate CRUD schema from Photon

### ISSUE THREAD

**Issue by terion-name** [prisma/prisma2#383] opened 2019-08-20 16:04 UTC
In first prisma server was generating a CRUD SDL schema, that was an awesome thing for many reasons: beginning from a readable crud documentation and ending with possibility to import CRUD definitions in application schema, which saved A TON of time and effort, because most of API operations are commonly just flavoured CRUD.

As far as I understand now only Photon js-client is generated for CRUD and this is very upsetting.

Is there a way to generate CRUD SDL from photon client now? It is really crucial for rapid development and automation.

## UPD
Investigating of examples lead me to a possible "hack" with traversing crud something like this:
```
// sudo code
const Query = objectType({
  name: 'Query',
  definition(t) {
     Object.keys(t.crud).forEach(f => t.crud[f]());
  }
});
// The same for mutation
// And then generate with:
const schema = makeSchema({types: [Query, Mutation]}.....);
```

This yet to be tested but in any case looks quite dirty in client code, maybe it would be better to generate it correctly in Photon?

**Comment by pantharshit00** [comment] 2019-08-20 16:31
This is more related to the nexus prisma API and there is already a feature request pending in the repository(https://github.com/prisma/nexus-prisma/issues/339)

Also, Prisma 2 will support custom generators using the DMMF(datamodel meta format). The current nexus-prisma generator is an example of a custom generator. Here you can read the code for a custom generator: https://github.com/prisma/nexus-prisma/blob/next/src/nexus-prisma/NexusPrismaBuilder.ts which uses the DMMF exposed by photon.

So you will be able to generate anything you want by writing a generator.

For now, I am going to close this as a duplicate of https://github.com/prisma/nexus-prisma/issues/339 as this belongs to nexus land not in photon land.

**Closed by pantharshit00** 2019-08-20 16:31 UTC
