### ISSUE TITLE
embed error

### ISSUE THREAD

**Issue by arn00s** [prisma/prisma2#101] opened 2019-07-05 19:17 UTC
I have a quite basic scheme.
I'm using PostgreSQL, and I would like to use the **embed** feature.

Embed definition:
```
embed Address {
  street: String
  zipCode: String
}
```
then, run
`prisma2 lift save`

I get this error:  

```
Error: Error in lift engine for rpc listMigrations:
  thread 'main' panicked at 'loading the connector failed.: DataModelErrors { code: 1001, errors: ["Unexpected token. Expected one of: end of input, type declaration, model declaration, enum declaration, source definition, generator definition."] }', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: migration_core::migration_engine::MigrationEngine::init
  10: <F as jsonrpc_core::calls::RpcMethodSimple>::call
  11: <F as jsonrpc_core::calls::RpcMethod<T>>::call
  12: <futures::future::lazy::Lazy<F, R> as futures::future::Future>::poll
  13: <futures::future::then::Then<A, B, F> as futures::future::Future>::poll
  14: <futures::future::map::Map<A, F> as futures::future::Future>::poll
  15: <futures::future::either::Either<A, B> as futures::future::Future>::poll
  16: futures::task_impl::std::set
  17: <std::thread::local::LocalKey<T>>::with
  18: futures::future::Future::wait
  19: <jsonrpc_core::io::IoHandler<M>>::handle_request_sync
  20: migration_core::rpc_api::RpcApi::handle
  21: migration_engine::main
  22: std::rt::lang_start::{{closure}}
  23: std::panicking::try::do_call
  24: __rust_maybe_catch_panic
  25: std::rt::lang_start_internal
  26: main
```

**Comment by pantharshit00** [comment] 2019-07-09 14:58
I think embedded models haven't been implemented yet

**Comment by nelsonpecora** [comment] 2019-08-14 15:03
This is being tracked here: https://github.com/prisma/lift/issues/43

**Comment by pantharshit00** [comment] 2019-08-15 08:09
Yes, @nelsonpecora you are correct.

I think I can close this as a duplicate of prisma/lift#43

**Closed by pantharshit00** 2019-08-15 08:09 UTC
Labels: kind/feature
