### ISSUE TITLE
`prisma2 reset` support

### ISSUE THREAD

**Issue by jferrettiboke** [prisma/prisma2#1932] opened 2020-03-25 17:56 UTC
## Problem
When testing, it is necessary for some scenarios to reset database data. With Prisma 1 we had the CLI option `prisma reset`.

## Solution
Provide a function programmatically to reset database data.

## Alternatives
If the solution requires work, a CLI option works for now.

## Additional context
I know Prisma 2 is not production-ready, but this feature is a must since we as a developer can automate tests and catch even more bugs not only for our apps but also for Prisma 2 and all its ecosystem.

**Comment by pantharshit00** [comment] 2020-03-26 12:36
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma2/issues/742

**Closed by pantharshit00** 2020-03-26 12:36 UTC
Labels: kind/feature, process/candidate
