### ISSUE TITLE
[Preview 2] Error on saving migration

### ISSUE THREAD

**Issue by reinvanimschoot** [prisma/prisma2#195] opened 2019-07-21 10:06 UTC
I just updated to preview2 and since I am working on a side project I just cleared everything and started from scratch with my datamodel. 

However, when trying to save my first migration I get the following error:

```
[migration-engine/connectors/sql-migration-connector/src/lib.rs:388] format!("CREATE SCHEMA IF NOT EXISTS \"{}\";" , & self . schema_name) = "CREATE SCHEMA IF NOT EXISTS \"public\";"
[migration-engine/connectors/sql-migration-connector/src/sql_migration_persistence.rs:38] m.make_from(barrel_variant) = "CREATE TABLE \"public\".\"_Migration\" (\"revision\" SERIAL PRIMARY KEY NOT NULL, \"name\" TEXT NOT NULL, \"datamodel\" TEXT NOT NULL, \"status\" TEXT NOT NULL, \"applied\" INTEGER NOT NULL, \"rolled_back\" INTEGER NOT NULL, \"datamodel_steps\" TEXT NOT NULL, \"database_migration\" TEXT NOT NULL, \"errors\" TEXT NOT NULL, \"started_at\" timestamp(3) NOT NULL, \"finished_at\" timestamp(3));"
[/var/root/.cargo/git/checkouts/prisma-query-a8c45647247f5d6d/bed0838/src/connector/postgres.rs:178] visitor::Postgres::build(q) = (
    "SELECT \"public\".\"_Migration\".* FROM \"public\".\"_Migration\" WHERE \"status\" = $1 ORDER BY \"revision\" DESC",
    [
        Text(
            "MigrationSuccess",
        ),
    ],
)
```

**Comment by timsuchanek** [comment] 2019-07-23 14:16
Thanks a lot @reinvanimschoot for reporting!
Can you share your schema.prisma file with us and optimally a link to a github repo containing the project?

**Comment by reinvanimschoot** [comment] 2019-07-25 08:35
@timsuchanek I added you as a collaborator on my github.

**Comment by theRocket** [comment] 2019-07-26 19:27
That doesn't appear to be the actual error, since the last line was successful. I have a similar bug for MySQL and don't want to report it if it's a duplicate of this one. Does the rest of the error look like this?
`[/var/root/.cargo/git/checkouts/prisma-query-a8c45647247f5d6d/bed0838/src/connector/mysql.rs:83] self.pool.state() = State {
    connections: 10,
    idle_connections: 10,
}
[/var/root/.cargo/git/checkouts/prisma-query-a8c45647247f5d6d/bed0838/src/connector/mysql.rs:83] self.pool.state() = State {
    connections: 10,
    idle_connections: 10,
}
thread 'main' panicked at 'Error accessing result set, column not found: column_default', migration-engine/connectors/sql-migration-connector/src/database_inspector/information_schema.rs:58:33`

**Comment by theRocket** [comment] 2019-07-26 22:10
I tried this with preview 3 today and get a different result, but more similar to the original posters:

`Error: Error in lift engine for rpc inferMigrationSteps:
  [migration-engine/connectors/sql-migration-connector/src/lib.rs:394] format!("CREATE SCHEMA IF NOT EXISTS `{}` DEFAULT CHARACTER SET latin1;" , &
        self . schema_name) = "CREATE SCHEMA IF NOT EXISTS `graphql_prisma2` DEFAULT CHARACTER SET latin1;"
[migration-engine/connectors/sql-migration-connector/src/sql_migration_persistence.rs:39] m.make_from(barrel_variant) = "CREATE TABLE graphql_prisma2._Migration (revision INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY, name TEXT NOT NULL, datamodel TEXT NOT NULL, status TEXT NOT NULL, applied INTEGER NOT NULL, rolled_back INTEGER NOT NULL, datamodel_steps TEXT NOT NULL, database_migration TEXT NOT NULL, errors TEXT NOT NULL, started_at datetime(3) NOT NULL, finished_at datetime(3));"
[/var/root/.cargo/git/checkouts/prisma-query-a8c45647247f5d6d/0773bc9/src/connector/mysql.rs:60] visitor::Mysql::build(q) = (
    "SELECT `graphql_prisma2`.`_Migration`.* FROM `graphql_prisma2`.`_Migration` WHERE `status` = ? ORDER BY `revision` DESC",
    [
        Text(
            "MigrationSuccess",
        ),
    ],
)
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic
   9: <&str as prisma_query::connector::result_set::index::ValueIndex<prisma_query::connector::result_set::result_row::ResultRow,prisma_query::ast::values::ParameterizedValue>>::index_into
  10: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
  11: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  12: sql_migration_connector::database_inspector::information_schema::InformationSchema::get_columns
  13: sql_migration_connector::database_inspector::mysql_inspector::MysqlInspector::get_table
  14: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  15: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  16: <sql_migration_connector::database_inspector::mysql_inspector::MysqlInspector as sql_migration_connector::database_inspector::DatabaseInspector>::introspect
  17: <sql_migration_connector::sql_database_migration_inferrer::SqlDatabaseMigrationInferrer as migration_connector::database_migration_inferrer::DatabaseMigrationInferrer<sql_migration_connector::sql_migration::SqlMigration>>::infer
  18: <migration_core::commands::infer_migration_steps::InferMigrationStepsCommand as migration_core::commands::command::MigrationCommand>::execute
  19: <F as jsonrpc_core::calls::RpcMethodSimple>::call
  20: <F as jsonrpc_core::calls::RpcMethod<T>>::call
  21: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
  22: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  23: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  24: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  25: futures::task_impl::std::set
  26: std::thread::local::LocalKey<T>::with
  27: futures::future::Future::wait
  28: jsonrpc_core::io::IoHandler<M>::handle_request_sync
  29: migration_core::rpc_api::RpcApi::handle
  30: migration_engine::main
  31: std::rt::lang_start::{{closure}}
  32: std::panicking::try::do_call
  33: __rust_maybe_catch_panic
  34: std::rt::lang_start_internal
  35: main
`

**Comment by mavilein** [comment] 2019-07-31 16:34
This is fixed now. It will ship with `preview4`.

@theRocket : Your issue is different. Please open a separate one. 🙏

**Closed by mavilein** 2019-07-31 16:34 UTC
Labels: bug/1-repro-available, release/preview4
