### ISSUE TITLE
Introspection produces invalid schema: Invalid id field configuration

### ISSUE THREAD

**Issue by schickling** [prisma/prisma2#1363] opened 2020-01-17 12:50 UTC
![image](https://user-images.githubusercontent.com/1567498/72613621-583fa180-3930-11ea-9757-c5ae4854fa47.png)

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = "postgresql://schickling@localhost:5432/schickling"
}

model Comment {
  author User
  id     String @id
  post   Post
  text   String @default("")
}

model Post {
  author   User
  id       String    @id
  title    String    @default("")
  comments Comment[]
}

model User {
  email    String    @default("") @unique
  id       String    @id
  name     String    @default("")
  comments Comment[]
  posts    Post[]
}
```

**Comment by janpio** [comment] 2020-01-17 14:16
What version of the CLI were you using for this? 

I could successfully generate a Client for this schema with `prisma2@2.0.0-alpha.571, binary version: 1a0db4166ffce810428c731661582371d3ab88c4`

```
C:\Users\Jan\Documents\throwaway\1363>prisma2 generate
In order to use the "prisma-client-js" generator, you need to install @prisma/client to your project.
√ Do you want to install it now? ... yes
yarn add v1.17.3
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ @prisma/client@2.0.0-alpha.571
info All dependencies
└─ @prisma/client@2.0.0-alpha.571
Done in 3.01s.


C:\Users\Jan\Documents\throwaway\1363>tree
Folder PATH listing for volume Local Disk
Volume serial number is 8EC2-149E
C:.
├───.vscode
├───node_modules
│   ├───.cache
│   │   └───prisma
│   └───@prisma
│       └───client
│           ├───dist
│           │   ├───fixtures
│           │   ├───generation
│           │   ├───runtime
│           │   │   ├───highlight
│           │   │   │   └───languages
│           │   │   └───utils
│           │   ├───utils
│           │   └───__tests__
│           │       ├───generation
│           │       └───runtime-tests
│           ├───generator-build
│           │   └───typescript
│           │       └───lib
│           │           ├───cs
│           │           ├───de
│           │           ├───es
│           │           ├───fr
│           │           ├───it
│           │           ├───ja
│           │           ├───ko
│           │           ├───pl
│           │           ├───pt-br
│           │           ├───ru
│           │           ├───tr
│           │           ├───zh-cn
│           │           └───zh-tw
│           ├───runtime
│           │   ├───highlight
│           │   │   └───languages
│           │   └───utils
│           └───scripts
└───prisma

C:\Users\Jan\Documents\throwaway\1363>
```

**Comment by do4gr** [comment] 2020-01-17 14:41
The picture says 538, seems to be an old version of the CLI / Binary.

**Comment by janpio** [comment] 2020-01-17 15:04
The picture only mentions `@prisma/client`, which might very well be different.

**Comment by pantharshit00** [comment] 2020-01-21 12:10
Yes, I also can't reproduce this with the latest alpha.

**Comment by janpio** [comment] 2020-01-21 18:01
The command that was output to install `@prisma/client` was missing the `@alpha`, so @schickling got a strange Prisma Client version here that probably in combination with his CLI did bad things.

Can you please retest with `preview020` and confirm that you are not getting the same error for this database @schickling?

**Comment by janpio** [comment] 2020-02-04 11:50
Can you please reproduce this @schickling with current alpha or preview or close this issue? Thanks.

**Comment by janpio** [comment] 2020-02-18 14:22
Any update here @schickling?

**Comment by janpio** [comment] 2020-03-05 13:50
Hey, any news here @schickling?

**Closed** 2020-03-30 22:06 UTC
Labels: bug/0-needs-info, kind/bug, topic: introspection
