### ISSUE TITLE
`prisma2 dev` continues creating dev.db even when DB_URL is a PostgresSQL

### ISSUE THREAD

**Issue by Albert-Gao** [prisma/prisma2#1261] opened 2020-01-02 00:31 UTC
```prisma
datasource db {
  provider = "postgresql"
  url      = env("DB_URL")

  default  = true
}

generator photon {
  provider = "photonjs"
}

model User {
  id          String   @default(cuid()) @id
}

model Company {
  id        String   @default(cuid()) @id
}

model Project {
  id          String   @default(cuid()) @id
}
```

The command is `DB_URL=postgresql://AlbertGao@localhost:5432/teamingCloud prisma2 generate`

Executing the command for the 1st time, everything will be fine.
Executing the command for the 2nd time, the `dev.db` will be created in the `prisma` folder

Furthermore, executing the tests will create this file as well.

I use SQLite for quite some time, and `dev.db` is the file name used for it.
migrated to PostgresSQL recently.

If you guys can not re-create this bug, I can provided the access to the repo.

**Comment by pantharshit00** [comment] 2020-01-06 11:30
I am unable to reproduce this. It might be useful to give me access to the project or paste the exact datasources and generators used in this project.

**Comment by divyenduz** [comment] 2020-01-09 15:15
@Albert-Gao What does your development environment look like? It looks like your are loading an older version of Photon, maybe due to [node's require cache](https://stackoverflow.com/questions/9210542/node-js-require-cache-possible-to-invalidate).

**Comment by Albert-Gao** [comment] 2020-01-10 10:30
hmm, I re-cloned my repo, couldn't reproduce it, I used the project from `prisma-examples`, could not either.

One thing I notice is something like this:

```prisma
datasource db {
  provider = "postgresql"
  url      = "postgresql://AlbertGao@localhost:5432/testp"

  // provider = "sqlite"
  // url      = "file:dev.db"

  default  = true
}
```

I added the commented part, so I can swap between them.

I noticed that when I doing the `lift`,

the archived schema file is this:

```prisma
datasource db {
  provider = "postgresql"
  url = "***"

  // provider = "sqlite"
     url = "***"

  default  = true
}
```

You can see that the 2nd `url` part is not been commented.

Do not know if this cause the trouble, but I was running `prisma2 dev` multiple times, no issues at all.

So maybe I can close this? Do you guys think this is an issue?

**Comment by divyenduz** [comment] 2020-01-10 10:38
> You can see that the 2nd url part is not been commented.

That is intentional, we redact that as it might contain credentials and might be accidentally pushed to git. 

I am closing this issue then, please open a new issue if you are able to reproduce this in future. 

Thank you 🙌

**Closed by divyenduz** 2020-01-10 10:38 UTC
Labels: bug/0-needs-info, kind/bug, topic: dev
