### ISSUE TITLE
Support PageInfo for pagination

### ISSUE THREAD

**Issue by marcjulian** [prisma/prisma2#1343] opened 2020-01-16 09:09 UTC
Please add support for `PageInfo` for [pagination](https://github.com/prisma/specs/tree/master/photonjs#pagination-before-after-first-last-skip).

`PageInfo` could look like this [PageInfo from GitHub v4](https://developer.github.com/v4/object/pageinfo/)

```typescript
interface PageInfo {
 endCursor: string;
 hasNextPage: boolean;
 hasPreviousPage: boolean;
 startCursor: string;
}
```

The [Connection Model](https://graphql.org/learn/pagination/#complete-connection-model) could be:

```typescript
interface ConnectionModel<T> {
 nodes: T[];
 pageInfo: PageInfo;
 totalCount: number;
}
```

**Comment by pantharshit00** [comment] 2020-01-17 14:04
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/photonjs/issues/321

Also, @ctrlplusb wrote a helper for this which you are can use as a workaround for now: https://gist.github.com/ctrlplusb/17b5a1bd1736b5ba547bb15b3dd5be29

**Closed by pantharshit00** 2020-01-17 14:04 UTC

**Comment by marcjulian** [comment] 2020-01-17 17:23
Cool @pantharshit00 thank you and have great weekend!
