### ISSUE TITLE
Enabling crud filtering on model with nexus generates wrong nested filter

### ISSUE THREAD

**Issue by emolr** [prisma/prisma2#598] opened 2019-09-25 08:15 UTC
Not sure if this issue is reported in the right repository, let me know if i should move it to photonjs or nexus :) 

In my nexus code:
```
t.crud.videos({filtering: true, ordering: true});
t.crud.topics({filtering: true, ordering: true});
```

From this code i would expect to be able to run this query:
```
query {
    videos(where: { topics: { some: { title: "a topic title" } } }) {
        id
    }
}
```

I would expect the type on the `where` `topics` to be `QueryFindManyTopicFilter` instead its `QueryFindManyVideoFilter` as shown in the image below.

<img width="1192" alt="Screenshot 2019-09-25 at 09 49 02" src="https://user-images.githubusercontent.com/2789549/65581868-8ca3e200-df7c-11e9-96c9-0877c29f95ae.png">

Any help would be appreciated. Thanks

**Comment by osterkraft** [comment] 2019-10-05 21:58
I can confirm this, running prisma2@2.0.0-alpha.226 and nexus-prisma 0.4.2. Sometimes the input filter gets really messed up and the input types in schema.graphql becomes either DateTime or Int.

![image](https://user-images.githubusercontent.com/16091980/66261288-c66db780-e7ca-11e9-9a3e-a3b0860d7d03.png)

I expect it to look more like this:
![image](https://user-images.githubusercontent.com/16091980/66261300-fcab3700-e7ca-11e9-8acf-6f8d09c9b39d.png)

Same problem in playground:

![image](https://user-images.githubusercontent.com/16091980/66261252-2f086480-e7ca-11e9-973f-90165b0a00f3.png)
![image](https://user-images.githubusercontent.com/16091980/66261254-39c2f980-e7ca-11e9-980d-b2e1c1f33050.png)

**Comment by iherger** [comment] 2019-10-06 14:16
There is a bug in photon (https://github.com/prisma/photonjs/issues/222), which seems related. 

I guess as long as the underlying photon filtering doesn't work properly, nexus-prisma will also not work properly.

**Comment by osterkraft** [comment] 2019-10-07 20:46
Hi, thanks for looking into this, please check out this minimal [reproduction repo](https://github.com/osterkraft/prisma2-nested-filter).

I have added Tags to Posts:

```
model Post {
  id        String   @default(cuid()) @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  published Boolean  @default(true)
  title     String
  content   String?
  author    User?
  tags      Tag[]    @relation(name: "PostTags")
}

model Tag {
  id        String   @default(cuid()) @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  name      String
  posts     Post[]   @relation(name: "PostTags")
}
```

The problem appears when querying for posts filtered by tags:

```
query {
  posts(where: {tags: {in: {id: "ck1gv0p3q000232rmasipgdql"}}}){
    id
    title
    tags {
      name
      id
    }
  }
}
```

Error message:

```
Unknown arg "in" in where.tags.in for type TagFilter. Available args:

type TagFilter {
  every?: TagWhereInput
  some?: TagWhereInput
  none?: TagWhereInput
}
```

I expect to receive the posts filtered by certain tags, either by filtering on ID or name etc.

**Comment by nhuesmann** [comment] 2019-11-07 01:29
Any update on this issue? I'm running into the same problem.

**Comment by pantharshit00** [comment] 2019-11-08 09:11
Looks I accidentally applied wrong labels here. I am marking this as a confirmed bug now.

**Comment by janpio** [comment] 2019-11-08 16:40
Internal Note: Dropping because not enough info for us to decide ad hoc

**Closed** 2020-01-09 17:10 UTC
Labels: bug/2-confirmed, kind/bug
