### ISSUE TITLE
Introspection crashes on tables without primary key

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#559] opened 2019-09-18 08:40 UTC
Introspecting MySQL with

```
-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.7.27-log - MySQL Community Server (GPL)
-- Server OS:                    Win64
-- HeidiSQL Version:             10.2.0.5599
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Dumping database structure for foo
CREATE DATABASE IF NOT EXISTS `foo` /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci */;
USE `foo`;

-- Dumping structure for table foo.bar
CREATE TABLE IF NOT EXISTS `bar` (
  `baz` enum('A','B','C') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'A'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- Dumping data for table foo.bar: ~0 rows (approximately)
/*!40000 ALTER TABLE `bar` DISABLE KEYS */;
INSERT INTO `bar` (`baz`) VALUES
	('B');
/*!40000 ALTER TABLE `bar` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;

```

leads to

```
C:\Users\Jan\Documents\throwaway
λ prisma2 init p2516_2

Preparing your demo script (JavaScript) ...

✔  Downloading the demo script from GitHub ...
⠙  Extracting content to p2516_2 ...
3  Installing dependencies with: `npm install` ...
 ERROR  Error during command execution

Schema parsing error: Error validating model "Bar": Exactly one field must be marked as the id field with the `@id` directive..
  -->  schema.prisma:6
   |
 5 |
 6 | model Bar {
 7 |   baz BarBazEnum
   |
```

![image](https://user-images.githubusercontent.com/183673/65132059-9c617a80-da00-11e9-9ec5-cea6b2146126.png)

**Comment by AhmedElywa** [comment] 2019-09-18 09:13
Yes i get same error and edit schema.prisma manual

**Comment by pantharshit00** [comment] 2019-09-18 11:09
I think this has been already reported a long time ago. This is also stated in the limitations page(https://github.com/prisma/prisma2/blob/master/docs/limitations.md), point number 6

Closing as duplicate of https://github.com/prisma/prisma2/issues/175

**Closed by pantharshit00** 2019-09-18 11:09 UTC
