### ISSUE TITLE
cannot create new schema via `Prisma2 init`

### ISSUE THREAD

**Issue by miyi** [prisma/prisma2#872] opened 2019-11-01 01:16 UTC
I'm creating a new project with Heroku Postgres database. After inserting the credentials, cli fails to create new schema. Error message:

<img width="1280" alt="Screen Shot 2019-10-31 at 6 10 27 PM" src="https://user-images.githubusercontent.com/6610928/67995872-01b4a800-fc0a-11e9-8aef-3af64e952824.png">

I shouldn't have any certificate issues. Here are the credentials in case if I'm creating the project wrong for some reason. 

<img width="1208" alt="Screen Shot 2019-10-31 at 4 45 19 PM" src="https://user-images.githubusercontent.com/6610928/67995979-7f78b380-fc0a-11e9-8c25-85d5bc6937cc.png">

I had this issue before but it magically resolved itself for some reason. Now I'm running into it again.

**Comment by miyi** [comment] 2019-11-01 01:40
what I did

<img width="1280" alt="Screen Shot 2019-10-31 at 6 36 12 PM" src="https://user-images.githubusercontent.com/6610928/67996702-c9af6400-fc0d-11e9-97b7-832aec599411.png">



full traceback

<img width="1069" alt="Screen Shot 2019-10-31 at 6 37 29 PM" src="https://user-images.githubusercontent.com/6610928/67996669-9f5da680-fc0d-11e9-98ef-1e8806627ff8.png">
<img width="1280" alt="Screen Shot 2019-10-31 at 6 37 40 PM" src="https://user-images.githubusercontent.com/6610928/67996672-a389c400-fc0d-11e9-90fc-613562169218.png">

**Comment by janpio** [comment] 2019-11-01 18:22
Thanks @miyi - someone will look into this with your reproduction steps.

**Comment by pantharshit00** [comment] 2019-11-05 14:54
I am unable to reproduce this:
![image](https://user-images.githubusercontent.com/22195362/68218298-16c67800-000a-11ea-884f-0ee729f0ac75.png)


Although I am unable to migrate the database later as I have posted in my findings here: https://github.com/prisma/prisma2/issues/869#issuecomment-549796941

**Comment by LongLiveCHIEF** [comment] 2019-11-12 21:04
I was able to recreate this consistently using the latest docker postgres image and that images defaults.

**Comment by pantharshit00** [comment] 2019-11-13 12:18
Can you please share your docker setup @LongLiveCHIEF? I mean whether you run simply the docker run command or set up a docker-compose file.

**Comment by LongLiveCHIEF** [comment] 2019-11-14 00:23
I tend to never install anything natively on my machine, always using docker. I created a gist with my setup: https://gist.github.com/LongLiveCHIEF/4a4e56c16fa97d724512c9b117bd4f4e

Add each of those files, then run:

```
$ make build
$ make ready
$ make start
$ ./prisma2 init
```

The `make build` command will create a `prisma2:latest` docker image, and make the `./prisma2` shell script executable.  This shell script basically simulates native installation of `prisma2` cli, but has the added benefit of isolating networks and allowing the code for connecting to postgres very simple.

The `make ready` command will create the docker network for photon/lift/nexus to connect to.

The `make start` command spins up the postgres image on that same network.

Then you call the `./prisma2 init` shell script/command just like you always would.

The connection to postgres is always succesful, and it always find the public schema, but always fails when trying to create a new schema.

**Comment by LongLiveCHIEF** [comment] 2019-11-14 00:33
note, connection info:

```
Host: postgres
Port: 5432
User: appuser
Password: password
Database: newapp

URL: postgresql://appuser:password@postgres/newapp
```

**Comment by pantharshit00** [comment] 2019-11-14 12:48
Looks like you didn't add the `--unsafe-perm` flag in your npm command in your Dockerfile.

```
FROM node:latest

RUN npm install --global --unsafe-perm  prisma2

ENTRYPOINT ["prisma2"]
```

Can you please try again using this file?

**Comment by LongLiveCHIEF** [comment] 2019-11-14 14:35
I missed that, but that's a non-starter for me unfortunately. In this day and age, things don't get to run as root.

**Comment by LongLiveCHIEF** [comment] 2019-11-14 14:40
Can i ask, is the only reason you want the `--unsafe-perm` flag is so you can install `query-engine-linux-glibc-libssl`, or are there are reasons?

If it's just the library install issue, I can figure out a better security/policy compatible way to get that installed and submit a PR. (see my comments in https://github.com/prisma/prisma2/issues/931)

**Comment by pantharshit00** [comment] 2019-11-15 11:34
I am going to close this issue now. We can continue our discussion on a better mechanism to manage the binary over at #931

**Closed by pantharshit00** 2019-11-15 11:34 UTC
Labels: bug/0-needs-info, kind/bug
