### ISSUE TITLE
Prisma is not including columns of Postgres type 'time without time zone' in schema

### ISSUE THREAD

**Issue by yim77** [prisma/prisma2#487] opened 2019-09-03 09:07 UTC
Unfortunately Prisma is not including columns of Postgres type 'time without time zone' in schema. These columns are simply missing in schema.

SQL DB Script:
```sql
CREATE TABLE public.oeffnungszeiten
(
    id integer NOT NULL DEFAULT nextval('oeffnungszeiten_id_seq'::regclass),
    res_id integer NOT NULL,
    wt integer NOT NULL,
    slot1_von time without time zone NOT NULL,
    slot1_bis time without time zone NOT NULL,
    slot2_von time without time zone,
    slot2_bis time without time zone,
    CONSTRAINT oeffnungszeiten_pkey PRIMARY KEY (id),
    CONSTRAINT fk_oeffnungszeiten_restaurant FOREIGN KEY (res_id)
        REFERENCES public.restaurant (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.oeffnungszeiten
    OWNER to postgres;

-- Index: fki_fk_oeffnungszeiten_restaurant

-- DROP INDEX public.fki_fk_oeffnungszeiten_restaurant;

CREATE INDEX fki_fk_oeffnungszeiten_restaurant
    ON public.oeffnungszeiten USING btree
    (res_id)
    TABLESPACE pg_default;
```

Generated Schema:
```
model Oeffnungszeiten {
  id  Int        @id
  res Restaurant @map("res_id")
  wt  Int

  @@map("oeffnungszeiten")
}
```

How should I include this columns?

**Comment by pantharshit00** [comment] 2019-09-03 14:09
I can confirm this.

**Comment by johannesschobel** [comment] 2019-09-20 09:34
that is most likely, because `Prisma2` does not have support for `DateTime With Timezones`. The `DateTime Without Timezone` is mapped to `DateTime` type.

I am in desperate need of `Timezone Support` as well :(

**Comment by AhmedElywa** [comment] 2020-01-24 07:18
>I am in desperate need of Timezone Support as well 

Me too any update in this

**Comment by janpio** [comment] 2020-01-31 15:43
Just to clarify: Do I understand correctly that you ran `prisma2 introspect` on your database @yim77 and the `time without time zone` columns were not represented in the created `schema.prisma`?

**Comment by pantharshit00** [comment] 2020-01-31 15:52
@janpio They are straight missing from the schema

**Comment by janpio** [comment] 2020-02-06 10:05
Related: https://github.com/prisma/prisma2/issues/1104

**Comment by do4gr** [comment] 2020-02-20 16:12
I just tested this and they are now in the schema as DateTime. We will still need a more fine grained mapping than just DateTime to represent the different Time/Date types but that is a different issue. I am therefore closing this.

**Closed by do4gr** 2020-02-20 16:12 UTC
Labels: bug/2-confirmed, kind/bug, topic: introspection, topic: native database types
