### ISSUE TITLE
Failed to update one to many on SQLite

### ISSUE THREAD

**Issue by tristancaron** [prisma/prisma2#141] opened 2019-07-10 19:17 UTC
The error I'm getting is 
```
ConnectorError(RelationViolation { relation_name: "SchoolToStudent", model_a_name: "School", model_b_name: "Student" })
```

Here a sample
```
model School {
  id Int @id
  name String
 
  students: Student[]
}

model Student {
  id Int @id
  name String

  school: School
}
```

Some code
```js
const school = await photon.schools.create({
  data: {
    name: 'Photon'
  }
})

const student = await photon.students.create({
  data: {
    name: 'Louis'
    school: {
      connect: {
        id: school.id
      }
    }
  }
})

await photon.students.update({
  data: {
    school: {
      connect: {
        id: school.id
      }
    }
  },
  where: {
    id: student.id
  }
})
```

**Comment by pantharshit00** [comment] 2019-07-18 13:58
Closing as a duplicate of https://github.com/prisma/prisma2/issues/166

**Closed by pantharshit00** 2019-07-18 13:58 UTC
