### ISSUE TITLE
Empty object issue in findOne

### ISSUE THREAD

**Issue by tvvignesh** [prisma/prisma2#1156] opened 2019-12-16 14:14 UTC
This is in relation to the issue which was filed here: https://github.com/prisma/prisma2/issues/914#issuecomment-566062290

I am not sure why, but I am getting this error. To test, I ran 2 queries against database with no records.

This works (with findMany):
```
photon.userAuthentications.findMany({
            where: {
              email: "test@xyz.com",
              mobile: "123456789"
            },
            select: {
                id: true,
                local: true,
                username: true,
                email: true,
                mobile: true,
                status: true,
                password: true
            }
        });
```

This does not (with findOne) - It just says error in Photon:
```
photon.userAuthentications.findOne({
            where: {
              email: "test@xyz.com"
            },
            select: {
                id: true,
                local: true,
                username: true,
                email: true,
                mobile: true,
                status: true,
                password: true
            }
        });
```

When I open the details of the error, it says:

```
Cannot convert undefined or null to object
```

My Schema:
```
model UserAuthentication {
    id                String   @default(cuid()) @id
    email             String   @unique
    mobile            String?  @unique
    local             String
    username          String   @unique
    password          String?
    facebook          String?
    google            String?
    github            String?
    microsoft         String?
    amazon            String?
    status            String
    connectedAccounts String[]
    metadata          String?
    tagIDList         String[]
    createdDate       DateTime @default(now())
    updatedDate       DateTime @updatedAt
}
```

Prisma2 version: `prisma2@2.0.0-preview018.2, binary version: 3c4da1d6caa0c40a0210a346ec982c77f74e18c7`

_Originally posted by @tvvignesh in https://github.com/prisma/prisma2/issues/914#issuecomment-566062290_

**Comment by pantharshit00** [comment] 2019-12-17 16:15
I was unable to reproduce this: 
<img width="698" alt="image" src="https://user-images.githubusercontent.com/22195362/71013169-3e832280-2116-11ea-94f3-eb919763f5d7.png">

Can you please paste the output of the command here in debug mode? To enable debug mode, please run `export DEBUG=*` before running your script.

**Comment by tvvignesh** [comment] 2019-12-17 16:33
@pantharshit00 I hope you have emptied the table before trying it out. It does not come up on non-empty tables. I tried the same again for a change on a different field (username) and still got the error. Adding debug logs below.

```
@prisma/studio-server Request from client: "{\"channel\":\"photon\",\"payload\":{\"requestId\":9,\"action\":\"request\",\"data\":{\"query\":\"photon.userAuthentications.findOne({\\n            where: {\\n              username: 'tvvignesh'\\n            },\\n            select: {\\n                id: true,\\n                local: true,\\n                username: true,\\n                emails: true,\\n                mobiles: true,\\n                status: true,\\n                password: true\\n            }\\n        });\"}}}" +22s
  photon Request: +22s
  photon query {
  photon   findOneUserAuthentication(where: {
  photon     username: "tvvignesh"
  photon   }) {
  photon     id
  photon     local
  photon     username
  photon     emails {
  photon       id
  photon       status
  photon       value
  photon       otp
  photon       otpExpiry
  photon       tagIDList
  photon       createdDate
  photon       updatedDate
  photon     }
  photon     mobiles {
  photon       id
  photon       status
  photon       value
  photon       otp
  photon       otpExpiryDate
  photon       tagIDList
  photon       createdDate
  photon       updatedDate
  photon     }
  photon     status
  photon     password
  photon   }
  photon } +0ms
  photon Response: +10ms
  photon { findOneUserAuthentication: null } +0ms
```

Also this is what studio's stacktrace says:
```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at hn.add (http://localhost:5555/studioBundle.js:87:25736)
    at $ (http://localhost:5555/studioBundle.js:16:6357)
    at hn.i (http://localhost:5555/studioBundle.js:16:6129)
    at http://localhost:5555/studioBundle.js:87:22461
    at Array.map (<anonymous>)
    at qt (http://localhost:5555/studioBundle.js:87:22451)
    at async Ii.run (http://localhost:5555/studioBundle.js:87:52797)
```

with the error `Cannot convert undefined or null to object`

**Comment by janpio** [comment] 2019-12-17 20:31
@tvvignesh Please do not mention team members in your initial issue description (I edited your description to remove this), we will get to your issue and triage it without you intruding into our GitHub notifications. Thanks.

**Comment by tvvignesh** [comment] 2019-12-18 08:19
@janpio Sure. I had been doing that just to make sure that my comment/issue does not go unnoticed. Will stick to just the descriptions from now. Its kind of hard to get a productive discussion going with a lot of people involved in OSS contributions with maintainers taking more than 6-7 months to reply back in many cases (in other repos). Hence I had a practice of doing this whenever I raise any issues in any repository. This is the same reason why I also post the link in slack along with the Github issue. Thanks for letting me know.

**Comment by pantharshit00** [comment] 2019-12-18 18:32
> I hope you have emptied the table before trying it out.

Yes, my database was empty.


The query seems weird to me. In the debug output, photon is trying to query `mobile` as a model but it is just a scalar. Can you please regenerate photon once using `prisma2 generate` and try this again? Maybe you did some changes to your model and photon is in a stale state.

**Comment by pantharshit00** [comment] 2019-12-18 18:37
Oh ok, I got your issue now.

You are running the photon query in prisma studio. Also, I think I missed that second query is a findOne instead of a findMany. `findOne` returns null if it doesn't find a matching object which is expected but studio is unable to render and it is throwing the following error as reported by you:
<img width="452" alt="image" src="https://user-images.githubusercontent.com/22195362/71113406-83c95200-21f3-11ea-878b-ae154926cb4d.png">

**Comment by pantharshit00** [comment] 2019-12-18 18:42
Closing in favour of https://github.com/prisma/studio/issues/320

**Closed by pantharshit00** 2019-12-18 18:42 UTC
Labels: bug/0-needs-info, kind/bug
