### ISSUE TITLE
Prisma 2 is failing to migrate remote database (DO hosted instance)

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma2#562] opened 2019-09-18 10:58 UTC
I tried to perform migration in a Digitalocean hosted instance in order to triage this issue: https://github.com/prisma/prisma2/issues/556

I used the default script starter

But the migration failed with the following rust panic:
![image](https://user-images.githubusercontent.com/22195362/65142759-0d208b00-da31-11e9-8475-21c42d93ee4a.png)

Connection string:
```
postgresql://doadmin:XXXXXXXX@XXXXXXXXXXXX.db.ondigitalocean.com:25060/defaultdb?schema=issue_552&sslmode=prefer
```

*Internal note*: You can find the credentials in 1password.

**Comment by tomhoule** [comment] 2019-09-23 14:03
The error message should improve after https://github.com/prisma/prisma-engine/pull/45.

I've done some digging and the issue seems to be caused by the absence of a default database named `postgres` in DigitalOcean managed postgres. [The default database name appears to be completely configurable](https://www.digitalocean.com/docs/databases/postgresql/how-to/manage-users-and-databases/). But at the moment prisma 2 assumes there is a default database called `postgres` we can log into to issue commands like CREATE DATABASE. [Relevant code](https://github.com/prisma/prisma-engine/blob/1aa23ebe2f9b947684547de9b92ee9a886d8d676/migration-engine/core/src/cli.rs#L94).

There's an always-present `template1` database in postgres but it doesn't guarantee it would work for what we want to do from it, so I'll wait until I can reproduce the issue with the database from the description.

**Comment by tomhoule** [comment] 2019-09-23 15:32
Implemented solution: try to connect to `postgres`, then `template1` (should always be there), and failing that return with a descriptive error message. PR: https://github.com/prisma/prisma-engine/pull/51

I haven't been able to reproduce the 'schema with underscore fails to migrate' issue locally, I'll try later on DO.

I'll start investigating the pgBouncer issue.

**Comment by tomhoule** [comment] 2019-09-23 16:57
From the digitalocean doc, it looks like database creation is pretty locked down and it's meant to be done through their UI. I will keep researching, but we may have to resort to just having a good error message there.

On an existing DO database with pgBouncer, I didn't encounter any issue migrating with a schema with underscores in its name.

**Comment by divyenduz** [comment] 2019-10-09 11:22
I was able to create database and schema using tableplus with or without pgbouncer.

**Comment by divyenduz** [comment] 2019-10-09 11:35
@pantharshit00 I am no longer able to reproduce this error with the latest alpha, are you? If no, please close this issue.

**Closed** 2019-10-10 12:04 UTC
Labels: bug/2-confirmed, kind/bug
