### ISSUE TITLE
Failed to validate the query `Error occurred during query validation & transformation:

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#1820] opened 2020-03-11 13:47 UTC
Import the following table into a local MySQL database and introspect it: 

```sql
CREATE TABLE `q4hat_categories` (
  `id` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL DEFAULT '',
  `commentable` enum('true','false') NOT NULL DEFAULT 'true',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
```

Then run the following client call on it: 

```ts
const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient()

async function main() {
  const data = await prisma.q4hat_categories.create({
    data: {
      name: 'Alice',
      commentable: 'true',
    },
  })
  console.log(data)
}

main().finally(() => prisma.disconnect())
```

Error observed:

```
divyendusingh [p2-enum-bool]$ node index.js 
(node:8559) UnhandledPromiseRejectionWarning: Error: 
Invalid `prisma.q4hat_categories.create()` invocation in
/Users/divyendusingh/Documents/prisma/p2-enum-bool/index.js:6:46

Failed to validate the query `Error occurred during query validation & transformation:
Mutation (object)
  ↳ createOneq4hat_categories (field)
    ↳ data (argument)
      ↳ q4hat_categoriesCreateInput (object)
        ↳ commentable (field)
          ↳ Value types mismatch. Have: Boolean(true), want: Enum(Internal(InternalEnum { name: "q4hat_categories_commentable", values: [InternalEnumValue { name: "true", database_name: None }, InternalEnumValue { name: "false", database_name: None }] }))` at `.Mutation.createOneq4hat_categories.data.q4hat_categoriesCreateInput.commentable`
    at PrismaClientFetcher.request (/Users/divyendusingh/Documents/prisma/p2-enum-bool/node_modules/@prisma/client/runtime/index.js:1:47071)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:8559) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8559) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

---

Internal notes: 

Test utils database(s) affected: 
- https://github.com/prisma/introspection-engine-output/blob/test_utils/test-utils/results/mysql_public_test_utils_piwigo_stderr.log

**Comment by janpio** [comment] 2020-03-11 20:00
Seems the string `"true"` becomes a boolean `true` along the way somewhere:
```
Value types mismatch. Have: Boolean(true), want: Enum(Internal(InternalEnum { name: "q4hat_categories_commentable", values: [InternalEnumValue { name: "true", database_name: None }, InternalEnumValue { name: "false", database_name: None }] }))
```

**Comment by yovanoc** [comment] 2020-03-15 10:23
I have the same error but with that message

![image](https://user-images.githubusercontent.com/7302317/76699608-6fd8a380-66af-11ea-8c7c-5f4bc22cbba8.png)

**Comment by janpio** [comment] 2020-03-15 15:44
That points to you having a different underlying problem @yovanoc. Can you please create a new issue and include all the relevant information? Thanks.

**Comment by timsuchanek** [comment] 2020-03-16 20:48
The problem here is, that we send a query like so to the query engine from TypeScript:
.q4hat_categories.create({
    data: {
      name: 'Alice',
      commentable: 'true',
    },
```graphql
mutation {
  createOneq4hat_categories(data: {
    name: 'Alice'
    commentable: true
  }) {
    ...
  }
}
```
We do that because enums are represented without "quotes" in the query.
Therefore, the query parser of the query engine needs to be able to distinguish this from the same-looking boolean `true`.

**Comment by dpetrick** [comment] 2020-03-17 13:08
I pushed a fix for the query engine, it should be available shortly on alpha.

**Comment by janpio** [comment] 2020-03-17 21:10
I can confirm this works now 🚀 

```
C:\Users\Jan\Documents\throwaway\1820>node index.js
{ commentable: 'true', id: 1, name: 'Alice' }

C:\Users\Jan\Documents\throwaway\1820>prisma2 -v
Prisma CLI Version   : prisma2@2.0.0-alpha.927
Current platform     : windows
Query Engine         : prisma a50009b3729b0c9187c88c8cf6cebd268881c9bb (at C:\ProgramData\nvm\v12.6.0\node_modules\prisma2\query-engine-windows.exe)
Migration Engine     : migration-engine-cli a50009b3729b0c9187c88c8cf6cebd268881c9bb (at C:\ProgramData\nvm\v12.6.0\node_modules\prisma2\migration-engine-windows.exe)
Introspection Engine : introspection-core a50009b3729b0c9187c88c8cf6cebd268881c9bb (at C:\ProgramData\nvm\v12.6.0\node_modules\prisma2\introspection-engine-windows.exe)

C:\Users\Jan\Documents\throwaway\1820>
```

Can you test if the test-utils problem is also gone @divyenduz?
Maybe your problem is also fixed @yovanoc although it pointed to an underlying reason? If not, please do open a new issue - we are really interested in fixing this.

**Closed by janpio** 2020-03-17 21:10 UTC
Labels: bug/2-confirmed, kind/bug, topic: test-utils, topic: types
