### ISSUE TITLE
Can't deleteMany when using UUID

### ISSUE THREAD

**Issue by ellipticaldoor** [prisma/prisma2#260] opened 2019-07-28 18:15 UTC
I get the following error message when trying to deleteMany a model that has uuid.

I'm currently using postgres as database provider

model
```
model Vault {
  id String @id @default(uuid())
  createdAtTick Int
  x Int
  y Int
  userId String?
  resourceId String
  facilityId String
}
```

code
``` typescript
const { findMany, deleteMany } = photon.vaults];
const results = await findMany();

if (results.length > 0) {
  await deleteMany({
    where: { id: { in: results.map(({ id }) => id) } },
  });
}
```

error message
```
    Invalid `photon.vaults.deleteMany()` invocation:

    {
      where: {
        id: {
          in: [
            'd4082b42-b161-11e9-8754-6542abf52968',
            'd4082b45-b161-11e9-8754-6542abf52968',
            'd4f9de42-b161-11e9-b0ed-f5aa37e6d1ec',
            'd4f9de45-b161-11e9-b0ed-f5aa37e6d1ec'
          ]
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        }
      }
    }

    Argument in: Got invalid value
    [
      'd4082b42-b161-11e9-8754-6542abf52968',
      'd4082b45-b161-11e9-8754-6542abf52968',
      'd4f9de42-b161-11e9-b0ed-f5aa37e6d1ec',
      'd4f9de45-b161-11e9-b0ed-f5aa37e6d1ec'
    ]
    on photon.deleteManyVault. Provided List<UUID>, expected List<String>.

      1836 |         return `${this.args
      1837 |             .map(arg => arg.toString())
    > 1838 |             .filter(a => a)
           |                       ^
      1839 |             .join('\n')}`;
      1840 |     }
      1841 |     collectErrors() {

      at Document.validate (src/server/photon/runtime/index.js:1838:23)
      at VaultClient.validate (src/server/photon/index.js:250:22)
      at VaultClient.document [as then] (src/server/photon/index.js:272:61)
```

**Comment by pantharshit00** [comment] 2019-07-29 11:13
I can confirm this. Our validator is not taking UUIDs as it is expecting String there. It treats UUID different from String.

**Comment by ellipticaldoor** [comment] 2019-07-29 19:18
Awesome, thank you :)

**Comment by timsuchanek** [comment] 2019-07-30 09:42
Thanks for reporting! Fixed in latest alpha.

**Comment by ellipticaldoor** [comment] 2019-08-03 09:13
I just updated and with the same code above I get this error

```
    Error in Photon:
    ConnectorError(QueryError(Error { kind: ToSql(0), cause: Some(WrongType(Type(Text))) }

    stack backtrace:
       0: backtrace::backtrace::trace::h33eb18a9548cdf19 (0x10b9fef3e)
       1: backtrace::capture::Backtrace::new_unresolved::hbe15ca481078b281 (0x10b9fd168)
       2: failure::backtrace::internal::InternalBacktrace::new::h677d3f07444347de (0x10b9fcaf9)
       3: <failure::backtrace::Backtrace as core::default::Default>::default::hcac8ae7a11909b53 (0x10b9fccf5)
       4: prisma_query::connector::postgres::error::<impl core::convert::From<tokio_postgres::error::Error> for prisma_query::error::Error>::from::h3ab990a6a5efdce8 (0x10b553eac)
       5: prisma_query::connector::metrics::query::h2fcb0cfc0bc7ef04 (0x10b50a734)
       6: <prisma_query::connector::postgres::PostgreSql as prisma_query::connector::queryable::Queryable>::execute::h68243be4545fc280 (0x10b56f61e)
       7: <prisma_query::connector::transaction::Transaction as prisma_query::connector::queryable::Queryable>::execute::h3d66e8599ac86c45 (0x10b4f0c24)
       8: prisma_query::connector::queryable::Queryable::delete::h2bc4f1d1a364e481 (0x10b090604)
       9: sql_connector::transactional::database_writer::delete_many::execute::h472c0a2e83e57a97 (0x10b2a6ad3)
      10: <sql_connector::database::postgresql::PostgreSql as sql_connector::transactional::Transactional>::with_transaction::h3fc7a80f13e8d7c0 (0x10afff188)
      11: sql_connector::transactional::database_writer::<impl connector::database_writer::DatabaseWriter for sql_connector::database::SqlDatabase<T>>::execute::h1fdc347ac34639ee (0x10af6c9a6)
      12: core::executor::write::WriteQueryExecutor::exec_one::h0ccc6701e405ec6a (0x10b3c4816)
      13: core::executor::write::WriteQueryExecutor::execute::h497d6e03d0a09a2b (0x10b3c416b)
      14: core::executor::Executor::exec_all::h070a91c9e5a27627 (0x10b3c52a1)
      15: <prisma::req_handlers::graphql::GraphQlRequestHandler as prisma::req_handlers::RequestHandler>::handle::hf611b92cc0065776 (0x10af652c3)
      16: prisma::http_handler::h98b848e95ac153e0 (0x10b0854bf)
      17: <F as actix_web::with::FnWith<T,R>>::call_with::h24e09cfd3efd8de0 (0x10b04c083)
      18: <actix_web::with::WithHandlerFut<T,S,R> as futures::future::Future>::poll::hb32d659914008924 (0x10b05042b)
      19: actix_web::pipeline::PipelineState<S,H>::poll::he2a205b53449c068 (0x10b0a2fd4)
      20: <actix_web::pipeline::Pipeline<S,H> as actix_web::server::handler::HttpHandlerTask>::poll_io::h2e9dd79a5fabfa8b (0x10b08f450)
      21: actix_web::server::h1::Http1Dispatcher<T,H>::poll_handler::h0c4a83ceff0cc96b (0x10afca9ea)
      22: actix_web::server::h1::Http1Dispatcher<T,H>::poll::h03420eeef0326ae4 (0x10aff226b)
      23: <actix_web::server::channel::HttpChannel<T,H> as futures::future::Future>::poll::hfc7e322ce2f63706 (0x10aff1096)
      24: <actix_web::server::channel::HttpChannel<T,H> as futures::future::Future>::poll::hfc7e322ce2f63706 (0x10aff1f18)
      25: <actix_net::service::and_then::AndThenFuture<A,B> as futures::future::Future>::poll::h43c43d12be1cbff1 (0x10b086436)
      26: futures::future::chain::Chain<A,B,C>::poll::h85b6624dffa6781e (0x10af9f174)
      27: futures::task_impl::std::set::h8b7c56a59149b0f5 (0x10b16bc1d)
      28: futures::task_impl::Spawn<T>::poll_future_notify::ha6a02020c58ff08d (0x10b184a7f)
      29: tokio_current_thread::CurrentRunner::set_spawn::h89f74106f23ddd01 (0x10b165b74)
      30: tokio_current_thread::scheduler::Scheduler<U>::tick::hed0054497a96e004 (0x10b171f25)
      31: tokio_current_thread::Entered<P>::block_on::hffcebfc36ff22191 (0x10b16672a)
      32: std::thread::local::LocalKey<T>::with::h825cf2ebc7178148 (0x10b17d304)
      33: std::thread::local::LocalKey<T>::with::h2e4e8ad4450a7b1e (0x10b17b867)
      34: std::thread::local::LocalKey<T>::with::h19af0aea2b759c27 (0x10b17b1ec)
      35: std::thread::local::LocalKey<T>::with::h74f99c958e90ca82 (0x10b17ce08)
      36: tokio::runtime::current_thread::runtime::Runtime::block_on::h5d768289d15f58a8 (0x10b169ed2)
      37: std::sys_common::backtrace::__rust_begin_short_backtrace::h733c614f53e190b2 (0x10b182618)
      38: std::panicking::try::do_call::h5f45919ea9b5b48f (0x10b1682fb)
      39: __rust_maybe_catch_panic (0x10ba308df)
      40: core::ops::function::FnOnce::call_once{{vtable.shim}}::hb77ef77d4e0a71fa (0x10b182e86)
      41: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hf8766009c029bc09 (0x10ba1743e)
      42: std::sys::unix::thread::Thread::new::thread_start::hfdef4649a42cf26c (0x10ba2fe4e)
      43: _pthread_body (0x7fff59c5d2eb)
      44: _pthread_start (0x7fff59c60249)))

      33 |             }
      34 |             catch (e) {
    > 35 |                 throw new Error(`Error in Photon${path}: \n` + e.message);
         |                       ^
      36 |             }
      37 |         });
      38 |     }

      at PhotonFetcher.<anonymous> (src/server/photon/index.js:35:23)
          at Generator.throw (<anonymous>)
      at rejected (src/server/photon/index.js:5:47)
```

Can we reopen the issue?

**Comment by ellipticaldoor** [comment] 2019-08-03 09:21
I think it will be nice to make a suite of end to end tests for prisma 2 so every posible kind of query gets made, just to catch this kind of errors before release.

**Comment by timsuchanek** [comment] 2019-08-05 11:48
Thanks! The second stack trace you reported is a duplicate of https://github.com/prisma/prisma2/issues/147 so I close this in favor of that.

**Closed by timsuchanek** 2019-08-05 11:48 UTC
Labels: bug/2-confirmed, kind/bug, release/preview4

**Comment by ellipticaldoor** [comment] 2019-08-05 20:36
Looks like the problem is caused by another reason, but maybe fixing one will fix this one?
