### ISSUE TITLE
Sometimes it doesn't quit even after pressing ⌃C multiple times

### ISSUE THREAD

**Issue by deadcoder0904** [prisma/prisma2#676] opened 2019-10-05 15:09 UTC
I don't think it's my Mac's problem. Does anyone else face this issue? 🙋‍♂️

**Comment by madebysid** [comment] 2019-10-07 13:01
Hey @deadcoder0904, I think this is a prisma2 CLI issue, so I'm moving it to that repo so that the right people can take a look!

**Comment by janpio** [comment] 2019-10-07 13:18
What commands do you refer to here @deadcoder0904? I am aware of a few commands where this is actually a problem, but which ones are you talking about here?

**Comment by deadcoder0904** [comment] 2019-10-07 15:51
I think it was the studio one so `prisma2 dev` I think

**Comment by janpio** [comment] 2019-10-07 17:43
Ok, we are aware of that, probably because of running generation or similar things. @pantharshit00 will know if we have an existing issue for that.

**Comment by pantharshit00** [comment] 2019-10-08 10:03
I am not aware of this issue. Can you provide a reproduction 🙂?

**Comment by deadcoder0904** [comment] 2019-10-09 04:24
Idk how to provide a repro. Maybe ask @janpio @madebysid 

Or try doing `prisma2 dev` & when it's generating then try quitting. Also, it happens at random times, so don't know how I can repro.

**Comment by janpio** [comment] 2019-10-09 11:03
@pantharshit00 This is one example: https://github.com/prisma/prisma2/issues/675

But I can confirm anecdotally that `prisma2 dev` also not always handles Ctrl+C as expected when regenerating.

**Comment by pantharshit00** [comment] 2019-10-09 14:01
Marking this one as confirmed as we need to investigate the blocking process issue #675 anyways.

**Comment by divyenduz** [comment] 2020-01-09 15:45
Also, closing this as a duplicate of https://github.com/prisma/prisma2/issues/650

@deadcoder0904 Please comment here and tag me if you disagree 🙏

**Closed by divyenduz** 2020-01-09 15:45 UTC
Labels: bug/2-confirmed, kind/bug

**Comment by deadcoder0904** [comment] 2020-01-10 04:54
Haha, both are opened by me. Idk man. Haven’t touched Prisma since Oct/Nov I think so I’ll let u know when I get back to it :)
