### ISSUE TITLE
Sort by nestes objects/relations

### ISSUE THREAD

**Issue by BjoernRave** [prisma/prisma2#1065] opened 2019-12-06 20:38 UTC
Hey, I would like to sort my data by a value in contained in another entity.

So I have 

```
model Product {
id
name: String
}
model Movement {
id
product: Product
}
```

and I would like to be able to do the following: 

```
query movements(orderBy: { product: {name: asc } }) {
id
}
```

**Comment by pantharshit00** [comment] 2019-12-09 10:51
Hi,

Thanks for requesting this! It has already been requested before, so I am going to close this as a duplicate of https://github.com/prisma/photonjs/issues/249

**Closed by pantharshit00** 2019-12-09 10:51 UTC
