### ISSUE TITLE
Feature: Split schema files into multiple files

### ISSUE THREAD

**Issue by malekjaroslav** [prisma/prisma2#1019] opened 2019-11-29 05:39 UTC
As the `schama.prisma` file gets bigger it is getting harder to find models and it feels messy. Have you considered a functionality to make this more scalable? 
Thanks!

**Comment by pantharshit00** [comment] 2019-12-02 13:56
Hi,

Thanks for requesting this! It has already been requested before, so I am going to close this as a duplicate of https://github.com/prisma/prisma2/issues/92

**Closed by pantharshit00** 2019-12-02 13:56 UTC

**Comment by muslimakhan** [comment] 2024-07-14 12:07
Hey @malekjaroslav, please check my blog and script here:
[New Trick – Organizing Prisma Models with the MERN Stack](https://muslimahmad.com/trick-organizing-prisma-models-with-the-mern-stack/)
[Github Repo](https://github.com/muslimakhan/Blog-Trick-Organizing-Prisma-Models-with-the-MERN-Stack)

This script could be help in both model split into multiple files and also for enum & types of Prisma ORM. And there is also a way to import predefined data into database too.
Hope, it would be solve your problem.
Thanks
