### ISSUE TITLE
How can I increase max body size?(413 Payload Too Large)

### ISSUE THREAD

**Issue by xero0001** [prisma/prisma2#771] opened 2019-10-16 22:44 UTC
I'm building online text editor and it uploads image which is converted into base64, so text size is little bit large.

this is the error message. it happend on "update mutaiton"
```
...
"statusCode": 413,
  "statusMessage": "Payload Too Large",
...
```

I already increased graphql server payload limit like this.

(index.ts)
```
server.start(
  {
    endpoint: "/graphql",
    playground: "/graphql",
    subscriptions: false,
    cors: {
      credentials: true,
      origin: ...
    },
    bodyParserOptions: { limit: "64mb", type: "application/json" }
  },
  () =>
    console.log(
      `🚀 Server ready at: http://localhost:4000\n⭐️ See sample queries: http://pris.ly/e/ts/graphql-auth#6-using-the-graphql-api`
    )
);
```
but sadly it doesn't work.

**Comment by pantharshit00** [comment] 2019-10-17 11:48
Hi,

Are you using photon in your setup? With the current information, it is not very clear that you are using photon in your setup.

This looks like more of a GraphQL Yoga issue to me. Try using the body-parser middleware itself instead of the `bodyParserOptions`. Maybe use apollo-server-express if graphql-yoga is not working for you.

**Comment by xero0001** [comment] 2019-10-17 12:05
Oh hi. I'm using photonjs, because I setup my project with "prisma2 init" with typescript, Auth example, mysql.

I'll try with body-parser middleware and apollo-server-express. Then I'll share my feedback again.

Thank you so much for your support!

**Comment by xero0001** [comment] 2019-10-21 00:00
Firstly, it doesn't work on graphql-yoga with body-parser middleware.
(With "prisma2 preview014.2 initialization") 

Following code is from my server.ts
```
const server = new GraphQLServer({
  schema,
  context: createContext,
  middlewares: [permissions],
})

server.express.use(bodyParser.json({ limit: '1mb' }))

server.start(
  {
    endpoint: '/graphql',
    playground: '/graphql',
    subscriptions: false,
    cors: {
      credentials: true,
      origin: 'http://localhost:3000',
    },
  },
  () =>
    console.log(
      `🚀 Server ready at: http://localhost:4000/graphql\n⭐️ See sample queries: http://pris.ly/e/ts/graphql-auth#5-using-the-graphql-api`,
    ),
)
```

Following is from backend console.
```
...

    "method": "POST"
  },
  "statusCode": 413,
  "statusMessage": "Payload Too Large",
  "headers": {
    "connection": "close",
    "content-length": "0",
    "date": "Sun, 20 Oct 2019 23:53:36 GMT"
  },
  "body": ""
}

    at PhotonFetcher.<anonymous> (/Users/arais/workspace/araisdraft/backend-latest/node_modules/@generated/photon/index.js:47:27)
    at Generator.throw (<anonymous>)
    at rejected (/Users/arais/workspace/araisdraft/backend-latest/node_modules/@generated/photon/index.js:6:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I will try "apollo-server-express" and comment again.

**Comment by xero0001** [comment] 2019-10-21 20:43
I found that "apollo-server-express" doesn't also works.

I used "graphql-apollo-server" example to setup, and replaced "apollo-server" module with "apollo-server-express" module. Also added "express" module and modified code little bit.

```
import { ApolloServer } from 'apollo-server-express'
import express from 'express'
import { schema } from './schema'
import { createContext } from './context'
import bodyParser from 'body-parser'

const app = express()
app.use('/graphql', bodyParser.json({ limit: '50mb' }))

const server = new ApolloServer({
  schema,
  context: createContext,
})

server.applyMiddleware({ app, path: '/graphql' })

app.listen(4000, () =>
  console.log(
    `🚀 Server ready at: http://localhost:4000\n⭐️ See sample queries: http://pris.ly/e/ts/graphql-apollo-server#5-using-the-graphql-api`,
  ),
)
```

Error message is just exactly same with the one from "graphql-yoga" trial.

captured from "Safari"
```
[31m    "method": "POST"[39m
[31m  },[39m
[31m  "statusCode": 413,[39m
[31m  "statusMessage": "Payload Too Large",[39m
[31m  "headers": {[39m
[31m    "connection": "close",[39m
[31m    "content-length": "0",[39m
[31m    "date": "Mon, 21 Oct 2019 20:26:16 GMT"[39m
[31m  },[39m
[31m  "body": ""[39m
[31m}[39m
[31m[39m, Location: [object Object], Path: updateText
```

And I found that this error message is referred to be not from GraphQL Yoga or Apollo Server, but from Photonjs.

[https://github.com/prisma/photonjs/issues/246](https://github.com/prisma/photonjs/issues/246)

So should I go there and ask help to resolve this?

But difference is that in my case, the error doesn't come up when payload is less than around 200kb. On the other hand, photon is said to have 32kb limitation(according to https://github.com/prisma/photonjs/issues/246).

**Comment by pantharshit00** [comment] 2019-10-22 15:30
If there is already a photonjs issue for this, we will address this.

I will close this as a duplicate for now. Can you please provide me with the exact queries and maybe a git repository of the code for reproduction(post it in the other issue)? That would help us a ton as the other bug is not confirmed.

**Closed by pantharshit00** 2019-10-22 15:30 UTC
Labels: bug/0-needs-info, kind/bug

**Comment by xero0001** [comment] 2019-10-22 23:45
I shared my repository at the other issue.
https://github.com/prisma/photonjs/issues/246

Thank you!
