### ISSUE TITLE
Could not run `prisma generate` introspecting a specific db

### ISSUE THREAD

**Issue by etelsv** [prisma/prisma2#281] opened 2019-07-29 16:49 UTC
I introspected this database https://github.com/catherinedevlin/opensourceshakespeare which I was able to get running on my computer. I was able to see the schema and added the photonjs generator. When I ran `prisma generate` I got the following error:

```
Errors during Photon generation:
Return type of public method from exported class has or is using private name 'FindOneWorkArgsRequired'.
Return type of public method from exported class has or is using private name 'FindOneCharacterArgsRequired'.
Return type of public method from exported class has or is using private name 'FindOneWorkArgsRequired'.
Return type of public method from exported class has or is using private name 'FindOneCharacterArgsRequired'.
Return type of public method from exported class has or is using private name 'FindOneWorkArgsRequired'.
Done in 2.03s
```
My schema.prisma file looked like this:
```
datasource db {
  provider = "postgresql"
  url      = "postgresql://blah:blah@localhost:5432/shakespeare4?schema=public"
}

generator photonjs {
  provider = "photonjs"
}

model Chapter {
  chapterid   Int    @id
  chapter     Int
  description String
  section     Int
  workid      Work

  @@map("chapter")
}

model Character {
  charid        String          @default(cuid()) @id
  abbrev        String?
  characterWork CharacterWork[]
  charname      String
  description   String?
  paragraph     Paragraph[]
  speechcount   Int

  @@map("character")
}

model CharacterWork {
  charid Character
  workid Work

  @@map("character_work")
}

model Paragraph {
  paragraphid   Int       @id
  chapter       Int
  charcount     Int
  charid        Character
  paragraphnum  Int
  paragraphtype String
  phonetictext  String
  plaintext     String
  section       Int
  stemtext      String
  wordcount     Int
  workid        Work

  @@map("paragraph")
}

model Wordform {
  wordformid   Int    @id
  occurences   Int
  phonetictext String
  plaintext    String
  stemtext     String

  @@map("wordform")
}

model Work {
  workid          String          @default(cuid()) @id
  chapter         Chapter[]
  characterWork   CharacterWork[]
  genretype       String
  longtitle       String
  notes           String?
  paragraph       Paragraph[]
  source          String
  title           String
  totalparagraphs Int
  totalwords      Int
  year            Int

  @@map("work")
}
```

**Comment by pantharshit00** [comment] 2019-07-29 18:08
Closing as a duplicate of https://github.com/prisma/prisma2/issues/274

**Closed by pantharshit00** 2019-07-29 18:08 UTC
