### ISSUE TITLE
`generate`: "Error: Schema parsing --- thread 'main' has overflowed its stack"

### ISSUE THREAD

**Issue by maartenraes** [prisma/prisma2#1496] opened 2020-01-31 15:57 UTC
```
$ prisma2 generate
(node:21024) ExperimentalWarning: The fs.promises API is experimental
Error: Schema parsing
thread 'main' has overflowed its stack
error Command failed with exit code 1.
```

Seems to be Windows related and related to Rust it's stack size limit which is 1MB on Windows;  (that's what I've found on the interwebs)

Running it in Docker seems to fix it since that's unix, but then when starting the project from Windows CLI it complains about not finding the windows query engine since the generate was done in unix 🤦‍♂ 
Happened after adding a new model to my prisma-schema, probably increased the necessary stack_size with that causing it to error.

**Comment by janpio** [comment] 2020-01-31 18:55
Ohoh. Can you share the schema, or maybe give some information about it? (count of models and lines)

**Comment by maartenraes** [comment] 2020-01-31 19:07
@janpio ```
generator photon {
  provider = "photonjs"
}

datasource postgresql {
  provider  = "postgresql"
  url       = env("POSTGRES_URL")
  enabled   = true
}

model Domain  {
  id            String   @default(cuid()) @id
  createdAt     DateTime @default(now())
  updatedAt     DateTime @updatedAt

  name          String   @unique
  description   String?
  logo          String?   
  email         String
  telephone     String
  mobile   String
  website       String?

  address       DomainAddress?
  organisations Organisation[] @relation(onDelete: CASCADE)
  contact       Contact?

  deleted       Boolean @default(false)
}

model DomainAddress {
  id            String   @default(cuid()) @id
  createdAt     DateTime @default(now())
  updatedAt     DateTime @updatedAt

  street        String?
  number        String?
  bus           String?
  zip           String
  city          String
  country       String?

  domain        Domain

  deleted       Boolean @default(false)
}

model Organisation  {
  id            String   @default(cuid()) @id
  createdAt     DateTime @default(now())
  updatedAt     DateTime @updatedAt

  name          String   @unique
  description   String?
  logo          String?   
  email         String
  telephone     String
  mobile        String
  website       String?
  
  domain        Domain
  address       OrganisationAddress?
  departments   Department[] @relation(onDelete: CASCADE)
  contact       Contact?
  customers     Customer[]

  deleted       Boolean @default(false)
}

model OrganisationAddress {
  id            String   @default(cuid()) @id
  createdAt     DateTime @default(now())
  updatedAt     DateTime @updatedAt

  street        String?
  number        String?
  bus           String?
  zip           String
  city          String
  country       String?

  domain        Domain?
  organisation  Organisation

  deleted       Boolean @default(false)
}

model Department  {
  id            String   @default(cuid()) @id
  createdAt     DateTime @default(now())
  updatedAt     DateTime @updatedAt

  name          String   @unique
  description   String?
  logo          String?   
  email         String
  telephone     String
  mobile        String
  website       String?
  
  organisation  Organisation
  domain        Domain?
  address       DepartmentAddress?
  locations     Location[]
  contact       Contact?
  activities    Activity[]

  deleted       Boolean @default(false)
}

model DepartmentAddress {
  id            String   @default(cuid()) @id
  createdAt     DateTime @default(now())
  updatedAt     DateTime @updatedAt

  street        String?
  number        String?
  bus           String?
  zip           String
  city          String
  country       String?

  domain        Domain?
  organisation  Organisation?
  department    Department

  deleted       Boolean @default(false)
}

model Location  {
  id            String   @default(cuid()) @id
  createdAt     DateTime @default(now())
  updatedAt     DateTime @updatedAt

  name          String   @unique
  description   String?
  email         String?
  telephone     String?
  mobile        String?
  website       String?
  visitComputers Int?
  visitsEnabled  Boolean @default(false)
  
  department    Department
  domain        Domain?
  organisation  Organisation?
  address       LocationAddress?
  contact       Contact?
  classrooms    Classroom[]
  accessories   Accessory[]
  visits        Visit[]
  openingSlots  OpeningSlot[]

  deleted       Boolean @default(false)
}

model LocationAddress {
  id            String   @default(cuid()) @id
  createdAt     DateTime @default(now())
  updatedAt     DateTime @updatedAt

  street        String?
  number        String?
  bus           String?
  zip           String
  city          String
  country       String?

  domain        Domain?
  organisation  Organisation?
  department    Department?
  location      Location

  deleted       Boolean @default(false)
}

model Classroom {
  id            String   @default(cuid()) @id
  createdAt     DateTime @default(now())
  updatedAt     DateTime @updatedAt

  name          String
  computers     Int

  location      Location
  domain        Domain?
  organisation  Organisation?
  department    Department?

  deleted       Boolean @default(false)
}

model Accessory {
  id            String   @default(cuid()) @id
  createdAt     DateTime @default(now())
  updatedAt     DateTime @updatedAt

  amount        Int
  type          AccessoryType
  inUse         Boolean @default(false)
  props         String?

  location      Location
  domain        Domain?
  organisation  Organisation?
  department    Department?

  deleted       Boolean @default(false)
}

enum AccessoryType {
  COMPUTER
  HEADPHONE
  MOUSE
  KEYBOARD
  TABLET
  MOBILEPHONE
  WEBCAM
}

model Visit {
  id            String   @default(cuid()) @id
  createdAt     DateTime @default(now())
  updatedAt     DateTime @updatedAt

  checkIn       DateTime @default(now())
  checkOut      DateTime?
  note          String?
  usesComputer  Boolean @default(true)

  location      Location
  customer      Customer
  domain        Domain?
  organisation  Organisation?
  department    Department?

  deleted       Boolean @default(false)
}

model Contact {
  id    String @default(cuid()) @id

  firstname String
  lastname  String
  email     String
  mobile    String

  deleted       Boolean @default(false)
}

model Customer {
  id            String   @default(cuid()) @id
  createdAt     DateTime @default(now())
  updatedAt     DateTime @updatedAt

  email         String?
  cell          String?
  telephone     String?
  rrn           String? //rijksregisternummer
  username      String?
  firstname     String
  lastname      String
  nationality   String?
  gender        String?
  birthdate     DateTime?
  aCardNumber   String?
  sequenceNumber  Int @unique
  nameParent    String?
  cellParent    String?

  professionStatus Status?
  education     String?
  motherTongue  String?
  vt            Boolean?

  computer      Boolean?
  internet      Boolean?
  smartphone    Boolean?
  tablet        Boolean?
  notifications Boolean?
  notificationChannel String?
  attendance    Float?
  yearlyCheck   Boolean? @default(false)
  suspended     Boolean? @default(false)
  warned        Boolean? @default(false)

  address       CustomerAddress?
  organisation  Organisation
  domain        Domain?
  notes         Note[] @relation(onDelete: CASCADE)
  registrations Registration[] @relation(onDelete: CASCADE)
  applicants    Applicant[] @relation(onDelete: CASCADE)
  visits        Visit[] @relation(onDelete: CASCADE)
  attendances   Attendance[] @relation(onDelete: CASCADE)
  emailTasks    EmailTask[]
  smsTasks      SmsTask[]

  deleted       Boolean @default(false)
}

model CustomerAddress {
  id            String   @default(cuid()) @id
  createdAt     DateTime @default(now())
  updatedAt     DateTime @updatedAt

  street        String?
  number        String?
  bus           String?
  zip           String?
  city          String?
  country       String?

  domain        Domain?
  organisation  Organisation?
  customer      Customer

  deleted       Boolean @default(false)
}

enum Status {
    CIVIL_SERVANT
    STAMPING_JOB_SEEKER
    SOCIAL_EMPLOYMENT
    REGULAR_EMPLOYMENT
    LIVING_WAGE
    SICKNESS_INVALIDITY_ALLOWANCE
    BRIDGE_RETIRED
    RETIRED
    UNEMPLOYED
    STUDENT
    ARTICLE60
}

model Admin {
  id            String   @default(cuid()) @id
  createdAt     DateTime @default(now())
  updatedAt     DateTime @updatedAt

  customer      Customer
  organisation  Organisation?
  domain        Domain?

  deleted       Boolean @default(false)
}

model Note {
  id            String   @default(cuid()) @id
  createdAt     DateTime @default(now())
  updatedAt     DateTime @updatedAt

  type          NoteType
  text          String
  date          DateTime
  validUntil    DateTime

  location      Location?
  customer      Customer
  organisation  Organisation?
  domain        Domain?

  deleted       Boolean @default(false)
}

enum NoteType {
  INFO
  WARNING
  EXPELL
}

model Registration {
  id            String   @default(cuid()) @id
  createdAt     DateTime @default(now())
  updatedAt     DateTime @updatedAt

  confirmed     Boolean? @default(false)
  canceled      Boolean? @default(false)
  paid          Boolean @default(false)
  note          String? 

  customer      Customer
  activity      Activity
  domain        Domain?
  organisation  Organisation?
  department    Department?

  deleted       Boolean @default(false)
}

model Activity {
  id            String   @default(cuid()) @id
  createdAt     DateTime @default(now())
  updatedAt     DateTime @updatedAt

  name          String
  abbreviation  String
  courseNumber  Int
  content       String
  remark        String?
  publicNote    String?

  price         Float
  priceVT       Float?
  priceAnt      Float? // Prijs niet antwerpenaar
  priceType     PriceType  // price per unit (dus per les of activiteit)
  
  minParticipants Int
  maxParticipants Int
  
  canceled      Boolean @default(false)
  notifyOnCancel Boolean @default(true)

  published     Boolean @default(false)
  publicationTime DateTime?

  activityType  ActivityType
  notifications Notification[]
  organisation  Organisation?
  registrations Registration[] @relation(onDelete: CASCADE)
  lessons       Lesson[] @relation(onDelete: CASCADE)
  domain        Domain?
  department    Department

  deleted       Boolean @default(false)
}

model Tag {
  id            String   @default(cuid()) @id
  createdAt     DateTime @default(now())
  updatedAt     DateTime @updatedAt

  name          String
  content       String

  activities    Activity[]
  templates     Template[]

  organisation  Organisation
  domain        Domain?

  deleted       Boolean @default(false)
}

model ActivityType {
  id            String   @default(cuid()) @id
  createdAt     DateTime @default(now())
  updatedAt     DateTime @updatedAt

  name          String
  tags          Tag[]
  applicants    Applicant[]
  activities    Activity[]
  templates     Template[]

  organisation  Organisation
  domain        Domain?
  deleted       Boolean @default(false)
}

enum PriceType {
    ACTIVITY
    LESSON
}

model Lesson {
  id            String   @default(cuid()) @id
  createdAt     DateTime @default(now())
  updatedAt     DateTime @updatedAt

  start         DateTime
  end           DateTime

  activity      Activity?
  classroom     Classroom?
  teachers      Teacher[]
  domain        Domain?
  organisation  Organisation?
  department    Department?
  canceled      Boolean @default(false)
  notifyOnCancel Boolean @default(true)
  attendances   Attendance[] @relation(onDelete: CASCADE)

  deleted       Boolean @default(false)
}

model Attendance {
  id            String   @default(cuid()) @id
  createdAt     DateTime @default(now())
  updatedAt     DateTime @updatedAt

  present       Boolean @default(false)
  paid          Boolean @default(false)

  lesson        Lesson
  customer      Customer
  domain        Domain?
  organisation  Organisation?
  department    Department?

  deleted       Boolean @default(false)
}

model Teacher {
  id            String   @default(cuid()) @id
  createdAt     DateTime @default(now())
  updatedAt     DateTime @updatedAt
  
  firstname     String
  lastname      String
  email         String?
  mobile        String?

  lessons       Lesson[]
  domain        Domain?
  organisation  Organisation?
  department    Department?

  deleted       Boolean @default(false)
}

model Template {
  id                String   @default(cuid()) @id
  createdAt         DateTime @default(now())
  updatedAt         DateTime @updatedAt

  name          String
  abbreviation  String
  content       String
  tags          Tag[]
  remark        String?
  publicNote    String?
  
  price         Float
  priceVT       Float?
  priceAnt       Float? // Prijs niet antwerpenaar
  priceType     PriceType // price per unit (dus per les of activiteit)
  
  minParticipants Int
  maxParticipants Int
  
  canceled      Boolean @default(false)
  notifyOnCancel Boolean @default(true)

  published     Boolean @default(false)
  publicationTime DateTime?

  activityType  ActivityType
  notifications Notification[]
  organisation  Organisation?
  domain        Domain?
  department    Department

  deleted       Boolean @default(false)
}

model NotificationTemplate {
  id            String   @default(cuid()) @id
  createdAt     DateTime @default(now())
  updatedAt     DateTime @updatedAt

  message       String
  subject         String?
  event         NotificationEvent
  channel       ChannelType

  template      Template
  domain        Domain?
  organisation  Organisation?

  deleted       Boolean @default(false)
}

model Notification {
  id            String   @default(cuid()) @id
  createdAt     DateTime @default(now())
  updatedAt     DateTime @updatedAt

  message       String
  subject       String?
  event         NotificationEvent
  channel       ChannelType

  activity      Activity
  domain        Domain?
  organisation  Organisation?
  department    Department?

  deleted       Boolean @default(false)
}

enum ChannelType {
    EMAIL
    SMS
}

enum NotificationEvent {
    REMINDER
    CONFIRMATION
    ACTIVITY_CANCELED
    LESSON_CANCELED
}

model Applicant {
  id            String   @default(cuid()) @id
  createdAt     DateTime @default(now())
  updatedAt     DateTime @updatedAt

  activityType  ActivityType
  customer      Customer
  domain        Domain?
  organisation  Organisation?

  deleted       Boolean @default(false)
}

model MasterNode {
  id            String @id
  pid           Int
  createdAt     DateTime @default(now())
  updatedAt     DateTime @updatedAt
  changedAt     DateTime @default(now())
}

model EmailTask {
  id            String @default(cuid()) @id
  createdAt     DateTime @default(now())
  updatedAt     DateTime @updatedAt
  reference     String?
  subject       String
  message       String
  recipients    Customer[]
  cachedStatus  String?

  organisation  Organisation
  domain        Domain?

  deleted       Boolean @default(false)
}

model SmsTask {
  id            String @default(cuid()) @id
  createdAt     DateTime @default(now())
  updatedAt     DateTime @updatedAt
  reference     String?
  message       String
  recipients    Customer[]
  cachedStatus  String?

  organisation  Organisation
  domain        Domain?

  deleted       Boolean @default(false)
}

model OpeningSlot {
  id            String @default(cuid()) @id
  createdAt     DateTime @default(now())
  updatedAt     DateTime @updatedAt

  note          String?
  days          Day[]
  start         String
  end           String
  location      Location

  organisation  Organisation?
  domain        Domain?
  department    Department

  deleted       Boolean @default(false)
}

enum Day {
  MA
  DI
  WO
  DO
  VR
  ZA
  ZO
}
```

**Comment by janpio** [comment] 2020-01-31 19:21
The current `2.0.0-preview021` gives me:

```
λ prisma2 generate
Error: Schema parsing

error: No such argument.
  -->  schema.prisma:25
   |
24 |   address       DomainAddress?
25 |   organisations Organisation[] @relation(onDelete: CASCADE)

...
```

When I remove all the `onDelete: CASCADE` I can reproduce your error:

```
C:\Users\Jan\Documents\throwaway\1496
λ prisma2 generate
Error: Schema parsing

thread 'main' has overflowed its stack
```

with `DEBUG=*` set:

```
C:\Users\Jan\Documents\throwaway\1496
λ set DEBUG=*

C:\Users\Jan\Documents\throwaway\1496
λ prisma2 generate
  getos { platform: 'win32', libssl: undefined } +0ms
  cleanupCache Error: ENOENT: no such file or directory, scandir 'C:\Users\Jan\AppData\Roaming\Prisma\alpha' +0ms
  download Setting binary path for query-engine windows to C:\ProgramData\nvm\v12.6.0\node_modules\prisma2\query-engine-windows.exe +0ms
  download Setting binary path for migration-engine windows to C:\ProgramData\nvm\v12.6.0\node_modules\prisma2\migration-engine.exe +1ms
  download Setting binary path for introspection-engine windows to C:\ProgramData\nvm\v12.6.0\node_modules\prisma2\introspection-engine-windows.exe +1ms
  getos { platform: 'win32', libssl: undefined } +15ms
  getos { platform: 'win32', libssl: undefined } +1ms
  cleanupCache Error: ENOENT: no such file or directory, scandir 'C:\Users\Jan\AppData\Roaming\Prisma\alpha' +11ms
  download Setting binary path for query-engine windows to C:\ProgramData\nvm\v12.6.0\node_modules\prisma2\query-engine-windows.exe +9ms
  getGenerators {
  getGenerators   binaryPathsWithEngineType: {
  getGenerators     'query-engine': {
  getGenerators       windows: 'C:\\ProgramData\\nvm\\v12.6.0\\node_modules\\prisma2\\query-engine-windows.exe'
  getGenerators     }
  getGenerators   }
  getGenerators } +0ms
  engineCommands getDMMF, override prismaPath = C:\ProgramData\nvm\v12.6.0\node_modules\prisma2\query-engine-windows.exe +0ms
  engineCommands getDMMF failed Error: Command failed with exit code 3221225725: C:\ProgramData\nvm\v12.6.0\node_modules\prisma2\query-engine-windows.exe cli --dmmf
    at o (C:\ProgramData\nvm\v12.6.0\node_modules\prisma2\build\index.js:2:270394)
    at x (C:\ProgramData\nvm\v12.6.0\node_modules\prisma2\build\index.js:2:2254133)
    at processTicksAndRejections (internal/process/task_queues.js:85:5) {
  command: 'C:\\ProgramData\\nvm\\v12.6.0\\node_modules\\prisma2\\query-engine-windows.exe cli --dmmf',
  exitCode: 3221225725,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: "\nthread 'main' has overflowed its stack",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
} +106ms
Error: Error: Schema parsing

thread 'main' has overflowed its stack
    at Object.<anonymous> (C:\ProgramData\nvm\v12.6.0\node_modules\prisma2\build\index.js:2:2891166)
    at Generator.throw (<anonymous>)
    at rejected (C:\ProgramData\nvm\v12.6.0\node_modules\prisma2\build\index.js:2:2887426)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**Comment by maartenraes** [comment] 2020-01-31 19:26
Sorry about the `onDelete` statements, we still run on preview19 since 20 and 21 have some breaking bugs. Preview19 does not mind the `onDelete`s

**Comment by janpio** [comment] 2020-01-31 19:29
Yeah, could figure that out in 10 seconds so no harm done :)

**Comment by janpio** [comment] 2020-01-31 20:17
Ok, we have a plan: On Monday we will see if our current theory of problem and solution are correct, and if so provide an adapted binary for me and you to test out.

**Comment by maartenraes** [comment] 2020-02-01 07:35
> Ok, we have a plan: On Monday we will see if our current theory of problem and solution are correct, and if so provide an adapted binary for me and you to test out.

Great stuff, how do I get it and where do I put it?

**Comment by janpio** [comment] 2020-02-01 16:10
I do not know that yet, as it is not Monday yet. I will update this issue then.

**Comment by maartenraes** [comment] 2020-02-03 10:05
@janpio Friendly ping, any updates?

**Comment by janpio** [comment] 2020-02-03 12:30
We added this to the current sprint. Right now I do not know yet when we will have a new build with these problems fixed, sorry. We will update this issue as soon as we do.

**Comment by maartenraes** [comment] 2020-02-04 15:53
For people running into the same issue. You can run the project in docker and run generate command from there. 
To start a container from within your current working folder in powershell:
```powershell 
docker run -p 8080:8080  -it -v ${PWD}:/home/dev keymetrics/pm2:10-jessie /bin/bash 
``` 
or in bash 
```bash
docker run -p 8080:8080  -it -v /${PWD}:/home/dev keymetrics/pm2:10-jessie /bin/bash 
``` 

This launches a bash shell inside the container, you can then run any commands that you used to run from the folder `/home/dev`

For example: 
```bash
cd home/dev
yarn generate (-> prisma2 generate) 
yarn seed (-> ts-node prisma/seed)
yarn dev (-> cross-env NODE_ENV=development nodemon)
```

**Comment by janpio** [comment] 2020-02-04 18:46
To reproduce this on Windows without the CLI, but with the Query Engine directly:

1. Create a `schema.prisma` file by copy pasting this: https://github.com/prisma/prisma2/issues/1496#issuecomment-580868816 (in my case: `C:\Users\Jan\Documents\throwaway\1496\schema.prisma`)
2. Install `prisma2` from npm
3. Find the Query Engine binary path (in my case: `C:\ProgramData\nvm\v12.6.0\node_modules\prisma2\query-engine-windows.exe`) 
4. Set a bunch of ENV vars:
   - `set DEBUG=*`
   - ` set PRISMA_DML_PATH=C:\Users\Jan\Documents\throwaway\1496\schema.prisma`
5. Run the following command to see the crash: `C:\ProgramData\nvm\v12.6.0\node_modules\prisma2\query-engine-windows.exe cli --dmmf`

Output looks like this:

```
C:\Users\Jan\Documents\throwaway\1496
λ C:\ProgramData\nvm\v12.6.0\node_modules\prisma2\query-engine-windows.exe cli --dmmf

thread 'main' has overflowed its stack
```

**Comment by tomhoule** [comment] 2020-02-05 09:44
I have a convenient way to reproduce this on my machine, working on a fix now.

**Comment by tomhoule** [comment] 2020-02-05 12:40
I have a fix: https://github.com/prisma/prisma-engine/pull/454

With the schema posted above, DMMF rendering overflowed a 1MB stack, with these changes it doesn't overflow a 400kb stack.

**Comment by tomhoule** [comment] 2020-02-05 12:42
Once this is merged, it should be on alpha pretty fast for you to test.

**Comment by janpio** [comment] 2020-02-06 09:24
This is now merged and released in the current `alpha` - and it works:

![image](https://user-images.githubusercontent.com/183673/73922350-4dda4d00-48c9-11ea-9547-f87d46cf4db4.png)

```
C:\Users\Jan\Documents\throwaway\1496
λ prisma2 generate
Error: Schema parsing

thread 'main' has overflowed its stack

C:\Users\Jan\Documents\throwaway\1496
λ npx prisma2@alpha generate
Error: Oops! Photon has been renamed to Prisma Client. Please make the following adjustments:
  1. Rename provider = "photonjs" to provider = "prisma-client-js" in your schema.prisma file.
  2. Replace your package.json's @prisma/photon dependency to @prisma/client
  3. Replace import { Photon } from '@prisma/photon' with import { PrismaClient } from '@prisma/client' in your code.
  4. Run prisma2 generate again.
```

Instead of the stackoverflow I get a proper error message that I should update my `schema.prisma`, and if I do that it actually works:

```
C:\Users\Jan\Documents\throwaway\1496
λ npx prisma2@alpha generate
Generated Prisma Client to .\node_modules\@prisma\client
Done in 1.22s
```

**Comment by janpio** [comment] 2020-02-06 14:41
Can you confirm this works for you as well @maartenraes? Just running `npx prisma2@alpha generate` should be enough to test before updating your project to the alpha.

**Comment by maartenraes** [comment] 2020-02-10 12:06
@janpio just came around to updating to the newest preview and fix all breaking changes. 
Then upgrading to alpha indeed solves the issue. 

I would leave the issue open till it's in the preview22 release?

**Comment by janpio** [comment] 2020-02-10 14:53
Nah we usually close issues when they are fixed in the codebase as the changes become available in `alpha`. But yes, this will be included in `preview22` probably later this week.

**Closed** 2020-02-10 14:55 UTC
Labels: bug/2-confirmed, kind/bug, topic: schema, topic: windows
