### ISSUE TITLE
CLI 'prisma2 init' - 'Back' option doesn't work in multiple screens

### ISSUE THREAD

**Issue by thecodeah** [prisma/prisma2#1245] opened 2019-12-29 14:57 UTC
**1.** In the gif below you can see how the back button/option works on the "supported databases" screen, but doesn't work on the next screen ("Prisma framework tools")
>![Peek 2019-12-29 16-58](https://user-images.githubusercontent.com/21268739/71559284-88480300-2a5c-11ea-9089-496e611cbe14.gif)

**2.** On the "Database options" screen it just reloads the page when you try to go back
>![Peek 2019-12-29 17-01](https://user-images.githubusercontent.com/21268739/71559319-ef65b780-2a5c-11ea-8330-313869f7a998.gif)

Tested on :
 - `prisma2@2.0.0-preview019, binary version: e7579bd35e0938dbf773f1706c098a0d14a5a038`
 - `prisma2@2.0.0-preview018.2, binary version: 3c4da1d6caa0c40a0210a346ec982c77f74e18c7`

**Comment by pantharshit00** [comment] 2020-01-06 09:28
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of #723

**Closed by pantharshit00** 2020-01-06 09:28 UTC
