### ISSUE TITLE
Get config SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by thecodeah** [prisma/prisma2#1246] opened 2019-12-29 15:47 UTC
## Steps to reproduce bug
**1.** Run `prisma2 init`
**2.** Select Blank project
**3.** Select MySQL
**4.** Select Create new MySQL database (Use default db name)
**5.** Select Javascript
**6.** Select Minimal setup (If you choose the "demos" option it will automatically fail)
> ![image](https://user-images.githubusercontent.com/21268739/71559062-09ea6180-2a5a-11ea-8a66-252cefee8b2e.png)

**7.** Run `prisma2 dev`

**Ouput :**
```
Error: Get config SyntaxError: Unexpected end of JSON input
```

## Side notes
 - I've done this multiple times and one thing I notice is that despite selecting "Create new MySQL database" each time (Step 4) it keeps saying there are 4 databases, suggesting that it doesn't even create a database (This only happens when you leave the database name empty!)
![image](https://user-images.githubusercontent.com/21268739/71559047-ca237a00-2a59-11ea-9d82-091cd0897577.png)
 - The MySQL logs were unaffected
 - Prisma2 version : `prisma2@2.0.0-preview019, binary version: e7579bd35e0938dbf773f1706c098a0d14a5a038`
 - **Important!** - Doesn't work on current version `2.0.0-preview019`, but does work in older version `2.0.0-preview018.2`

**Comment by pantharshit00** [comment] 2020-01-06 09:25
I can confirm this bug. Indeed it looks like we are not using the defaults that were produced by this screen:
![image](https://user-images.githubusercontent.com/22195362/71808698-771e7800-3094-11ea-9259-3f1cbb4b0ac5.png)


The workaround would be to manully write the database name for now. Then it is working as expected.

**Comment by pantharshit00** [comment] 2020-01-06 09:26
Related: #471

**Comment by janpio** [comment] 2020-01-07 12:03
Thanks @thecodeah, the actual "Get config SyntaxError: Unexpected end of JSON input" bug you reported can not be reproduced unfortunately.

Can you please give some additional information about your environment?
Can you try re-installing `prisma2` and watching the output you are getting there?

**Comment by pantharshit00** [comment] 2020-01-07 13:12
Yes, sorry for the first comment, I misidentified the issue and got into #471 instead. 

Can you please list out the exact steps as mentioned by @janpio so that we can reproduce it? Also, you can run the command in debug mode using `export DEBUG=*` which may provide a more detailed log about the problem.

Related https://github.com/prisma/prisma2/issues/483 which was closed as it was not reproducable but it seems very related to your issue.

**Comment by timsuchanek** [comment] 2020-03-05 11:10
We don't have `prisma2 init` anymore and this is aging, so I close it.

**Closed by timsuchanek** 2020-03-05 11:10 UTC
Labels: bug/0-needs-info, kind/bug, topic: binaries
