### ISSUE TITLE
`prisma2 generate` Fails when Multiple Ids are Defined

### ISSUE THREAD

**Issue by seed-of-apricot** [prisma/prisma2#1441] opened 2020-01-26 22:09 UTC
I have models as the following:

```prisma
model game {
  id      String   @id @default(cuid())
  name    String
  leaders leader[]
}

model leader {
  id          String   @default(cuid())
  name        String
  displayName String
  isHuman     Boolean
  time        DateTime
  @@id([id, time]) // for use in timescaledb
}
```

And then `prisma2 generate` fails with the error:

```node
Error: Schema parsing
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "No id field 
defined! Model: leader"', src\libcore\result.rs:1165:5
stack backtrace:
   0: backtrace::backtrace::dbghelp::trace
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace/dbghelp.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src\libstd\sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src\libstd\sys_common/backtrace.rs:61
   4: core::fmt::write
             at src\libcore\fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src\libstd\io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src\libstd\sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src\libstd\sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src\libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src\libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src\libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src\libstd/panicking.rs:373
  12: rust_begin_unwind
             at src\libstd/panicking.rs:302
  13: core::panicking::panic_fmt
             at src\libcore/panicking.rs:139
  14: core::result::unwrap_failed
             at src\libcore/result.rs:1165
  15: once_cell::imp::OnceCell<T>::initialize::{{closure}}
  16: once_cell::imp::initialize_inner
  17: once_cell::imp::OnceCell<T>::initialize
  18: prisma_models::fields::Fields::id
  19: query_core::schema_builder::object_type_builder::ObjectTypeBuilder::many_records_arguments
  20: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
  21: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  22: query_core::schema_builder::object_type_builder::ObjectTypeBuilder::new        
  23: query_core::schema_builder::query_schema_builder::QuerySchemaBuilder::new      
  24: prisma::cli::CliCommand::execute
  25: std::future::set_task_context
  26: tokio::runtime::enter::Enter::block_on
  27: tokio::runtime::thread_pool::ThreadPool::block_on
  28: tokio::runtime::context::enter
  29: tokio::runtime::Runtime::block_on
  30: prisma::main
  31: std::rt::lang_start::{{closure}}
  32: std::rt::lang_start_internal::{{closure}}
             at src\libstd/rt.rs:48
  33: std::panicking::try::do_call
             at src\libstd/panicking.rs:287
  34: __rust_maybe_catch_panic
             at src\libpanic_unwind/lib.rs:78
  35: std::panicking::try
             at src\libstd/panicking.rs:265
  36: std::panic::catch_unwind
             at src\libstd/panic.rs:396
  37: std::rt::lang_start_internal
             at src\libstd/rt.rs:47
  38: main
  39: _tmainCRTStartup
  40: mainCRTStartup
  41: sqlite3GenerateConstraintChecks
  42: sqlite3GenerateConstraintChecks
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

My environment is:

|||
|---|---|
|OS|Windows 10 x64 18362|
|Node.js|12.4.0|
|prisma2|2.0.0-alpha.648|

I guess it is because of the multiple ids in the `leader` model. How could I solve this?

**Comment by pantharshit00** [comment] 2020-01-28 14:37
This is currently being implemented on the engine level, I am going to close this issue as a duplicate of https://github.com/prisma/prisma2/issues/1389

**Closed by pantharshit00** 2020-01-28 14:37 UTC

**Comment by seed-of-apricot** [comment] 2020-01-28 19:48
Understood, thanks!
