### ISSUE TITLE
prisma2 docker-compose up -d get error

### ISSUE THREAD

**Issue by Q00** [prisma/prisma2#1836] opened 2020-03-15 05:56 UTC
When I try to docker-compose up with my docker-compose.yml, I get error 

```
docker-compose up -d --build
Building server
Step 1/10 : FROM mhart/alpine-node:12
 ---> e0c094882982
Step 2/10 : ENV TZ="/usr/share/zoneinfo/Asia/Seoul"
 ---> Using cache
 ---> 25b531625aae
Step 3/10 : ENV HOST 0.0.0.0
 ---> Using cache
 ---> 0b6acf7fb27f
Step 4/10 : ARG PROJECT_DIR=/prisma-boilerplate/web
 ---> Using cache
 ---> ef90b6f00270
Step 5/10 : RUN npm install -g yarn
 ---> Using cache
 ---> 8491b157b238
Step 6/10 : WORKDIR ${PROJECT_DIR}
 ---> Using cache
 ---> a715765ee5cd
Step 7/10 : COPY . ${PROJECT_DIR}
 ---> 826d8434854f
Step 8/10 : RUN yarn install
 ---> Running in 764d86942de6
yarn install v1.22.4
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning " > graphql-shield@5.7.3" has unmet peer dependency "graphql-middleware@^2.0.0 || ^3.0.0".
warning "graphql-yoga > graphql-playground-middleware-lambda@1.7.12" has unmet peer dependency "aws-lambda@^0.1.2".
warning "graphql-yoga > graphql-subscriptions@0.5.8" has incorrect peer dependency "graphql@^0.10.5 || ^0.11.3 || ^0.12.0 || ^0.13.0".
warning "graphql-yoga > apollo-server-express > apollo-server-core@1.4.0" has incorrect peer dependency "graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
warning "graphql-yoga > apollo-server-express > apollo-server-core > apollo-cache-control@0.1.1" has incorrect peer dependency "graphql@0.10.x - 0.13.x".
warning "graphql-yoga > apollo-server-express > apollo-server-core > apollo-tracing@0.1.4" has incorrect peer dependency "graphql@0.10.x - 0.13.x".
warning "graphql-yoga > apollo-server-express > apollo-server-core > graphql-extensions@0.0.10" has incorrect peer dependency "graphql@0.10.x - 0.13.x".
warning " > nexus-prisma@0.11.1" has incorrect peer dependency "@prisma/client@2.0.0-preview023".
[5/5] Building fresh packages...
$ npm -s run generate
Error: Error: Command failed with ENOENT: /prisma-boilerplate/web/node_modules/prisma2/query-engine-debian-openssl-1.1.x --enable-raw-queries cli dmmf
spawn /prisma-boilerplate/web/node_modules/prisma2/query-engine-debian-openssl-1.1.x ENOENT
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR: Service 'server' failed to build: The command '/bin/sh -c yarn install' returned a non-zero code: 1
```

my docker-compose.yml file is

```yml
version: '3'
services:
  database:
    image: bitnami/postgresql:11-debian-9
    restart: on-failure
    ports:
      - '0.0.0.0:5432:5432'
    environment:
      - POSTGRESQL_PASSWORD=testpasswd
      - POSTGRESQL_USERNAME=testuser
      - POSTGRESQL_DATABASE=testdb
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repuser
      - POSTGRESQL_REPLICATION_PASSWORD=reppassword
    volumes:
      - ./db/conf.d # contains a custom postgresql.conf
    networks:
      coconet:
        ipv4_address: 172.16.25.2
  server:
    build:
      context: .
      dockerfile: ./dockerfile-dev
    environment:
      SENTRY_DSN: ''
    ports:
      - '3000:3000'
    volumes:
      - '.:/prisma-boilerplate/web'
    depends_on:
      - database
    command: 'yarn dev'
    networks:
      coconet:
        ipv4_address: 172.16.25.3
networks:
  coconet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.25.0/24

```

my package.json file
```json
{
  "name": "graphql-auth",
  "license": "MIT",
  "scripts": {
    "start": "node dist/server",
    "clean": "rm -rf dist",
    "build": "npm -s run clean && npm -s run generate && tsc",
    "generate": "npm -s run generate:prisma && npm -s run generate:nexus",
    "generate:prisma": "prisma2 generate",
    "generate:nexus": "ts-node --transpile-only src/schema",
    "postinstall": "npm -s run generate",
    "dev": "ts-node-dev --no-notify --respawn --transpileOnly src/server"
  },
  "dependencies": {
    "@prisma/client": "2.0.0-preview024",
    "bcryptjs": "2.4.3",
    "graphql": "14.6.0",
    "graphql-shield": "5.7.3",
    "graphql-yoga": "1.18.3",
    "jsonwebtoken": "8.5.1",
    "nexus": "0.12.0-rc.13",
    "nexus-prisma": "0.11.1"
  },
  "devDependencies": {
    "@types/bcryptjs": "2.4.2",
    "@types/jsonwebtoken": "8.3.8",
    "@types/node": "12.12.30",
    "@types/ws": "7.2.2",
    "prisma2": "2.0.0-preview024",
    "ts-node": "8.6.2",
    "ts-node-dev": "1.0.0-pre.44",
    "typescript": "3.8.3"
  },
  "prettier": {
    "singleQuote": true,
    "semi": false,
    "trailingComma": "all"
  },
  "engines": {
    "node": ">=10.0.0"
  }
}

```

my repo is https://github.com/Q00/prisma2-yoga-boilerplate.
What can I do?

**Comment by pantharshit00** [comment] 2020-03-17 17:12
Hey @Q00 

I checked your dockerfiles. We currently don't support alpine linux: #702 

So that is why Prisma is unable to download the binaries. So please use any other version of linux for now.

Closing this as a duplicate of #702. If you get any other issue, feel free to comment here.

**Closed by pantharshit00** 2020-03-17 17:12 UTC

**Comment by janpio** [comment] 2020-03-17 18:22
> Error: Error: Command failed with ENOENT: /prisma-boilerplate/web/node_modules/prisma2/query-engine-debian-openssl-1.1.x --enable-raw-queries cli dmmf
> spawn /prisma-boilerplate/web/node_modules/prisma2/query-engine-debian-openssl-1.1.x ENOENT
> error Command failed with exit code 1.

Doesn't that means that it is thinking it should download and run `query-engine-debian-openssl-1.1.x` - which does not exist for some reason? Shouldn't this be covered by a better error message earlier?

**Comment by pantharshit00** [comment] 2020-03-22 21:31
@janpio I think we fallback to debain if we don't detect the linux distro:
https://github.com/prisma/prisma-client-js/blob/ab201b4307203991d53f1709fa45b725974afded/packages/get-platform/src/getPlatform.ts#L158

Created a new issue to track the improvement of the error message: https://github.com/prisma/prisma2/issues/1898
