### ISSUE TITLE
error of filter with OR

### ISSUE THREAD

**Issue by sessionboy** [prisma/prisma2#877] opened 2019-11-03 10:46 UTC
This is my model:
```graphql
model Notification {
  id String @id @default(cuid())
  receivers User[] @relation(name: "User_Notification")
  sender User  @relation(name: "User_sendeNotifications")
  ...
}
```
This is my query, I want to query my notification list:
```graphql
const result = await ctx.photon.notifications.findMany({
   where:{
       OR:[
            {
              sender:{
                followers:{
                   some: { id: loginUserId }                  
                }
              }
            },
            {
              receivers:{
                 some: { id: loginUserId } 
              }
            }
       ]
   },
})
```
But I got an error: 
```js
Reason: Error occurred during query validation & transformation:
Query (object)
  ↳ findManyNotification (field)
    ↳ where (argument)
      ↳ NotificationWhereInput (object)
        ↳ OR (field)
          ↳ NotificationWhereInput (object)
            ↳ receivers_some_id (field)
              ↳ Field does not exist on enclosing type.
```
How should I solve it?

I can work when I try to use a single condition:
```graphql
const result = await ctx.photon.notifications.findMany({
   where:{
       OR:[
            {
              sender:{
                followers:{
                   some: { id: loginUserId }                  
                }
              }
            }
       ]
   },
})
```

Is there still no OR-based multi-conditional filtering?

**Comment by pantharshit00** [comment] 2019-11-05 16:53
Can you please share the full datamodel?

Or please share the User and the Notification model.

**Comment by sessionboy** [comment] 2019-11-06 03:00
ok!
The User model:
```graphql
model User {
  id    String  @id @default(cuid())
  name String? @unique
  nickname  String  @unique
  email String?  @unique
  password String
  followings User[]  @relation(name: "User_Follow") 
  followers  User[]  @relation(name: "User_Follow") 
  notifications Notification[] @relation(name: "User_Notification")
  sendeNotifications Notification[] @relation(name: "User_sendeNotifications")
  posts      Post[]  @relation(name: "User_Post", onDelete: CASCADE) 
  ....
  createdAt DateTime @default(now())
}
```
The Notification model:
```graphql
model Notification {
  id String @id @default(cuid())
  receivers User[] @relation(references: [id],name: "User_Notification")
  sender User  @relation(references: [id],name: "User_sendeNotifications")
  type NotificationType
  msg String?
  content String?
  post Post? 
  comment Comment?
  reply Reply?  @relation(references: [id])
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}
```

**Comment by pantharshit00** [comment] 2019-11-08 07:00
I am unable to reproduce this with `prisma2@2.0.0-preview015, binary version: 20b6dc13949cccccfef5be07c0be7a3d7c858abe`

Can you please make sure that you are using the latest version?
![image](https://user-images.githubusercontent.com/22195362/68456323-7b105400-0223-11ea-89be-781e60d92c46.png)

**Comment by sessionboy** [comment] 2019-11-08 07:42
@pantharshit00 Thank you for your help. I just upgraded to version 016 and now it works fine. The latest version seems to fix this problem. Now it work.

**Comment by pantharshit00** [comment] 2019-11-08 09:32
Awesome, I am going to close this then :)

**Closed by pantharshit00** 2019-11-08 09:32 UTC
Labels: bug/0-needs-info, kind/bug
