### ISSUE TITLE
Photon generation fails for a datamodel with back relations

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#34] opened 2019-06-06 13:54 UTC
```
model Todo {
  id: Int @id
  text: String
  author: Owner @relation(name: "AuthorTodo")
  delegatedTo: Owner? @relation(name: "DelegatedToTodo")
}

model Owner {
  id: Int @id
  name: String?
  todos: Todo[] @relation(name: "AuthorTodo")
}
```

Fails with the following trace: 
```
$ [todo-matrix]$ yarn prisma2 generate
yarn run v1.15.2
$ /Users/divyendusingh/Documents/prisma/support/feature/todo-matrix/node_modules/.bin/prisma2 generate

Generating Photon to /Users/divyendusingh/Documents/prisma/support/feature/todo-matrix/node_modules/@generated/photon
Engine path: /Users/divyendusingh/Documents/prisma/support/feature/todo-matrix/node_modules/@prisma/prototype/runtime/prisma
/Users/divyendusingh/Documents/prisma/support/feature/todo-matrix/node_modules/@prisma/prototype/build/index.js:17018
                    throw new Engine_1.PhotonError(`Error in query engine: ` + this.errorLogs, undefined, undefined, this.errorLogs);
                    ^

PhotonError: Error in query engine: thread 'main' panicked at 'Did not find a relation for those for model Owner and field todo', src/libcore/option.rs:1038:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

    at ChildProcess.<anonymous> (/Users/divyendusingh/Documents/prisma/support/feature/todo-matrix/node_modules/@prisma/prototype/build/index.js:17018:27)
    at ChildProcess.emit (events.js:200:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12) {
  query: undefined,
  error: undefined,
  logs: "thread 'main' panicked at 'Did not find a relation for those for " +
    "model Owner and field todo', src/libcore/option.rs:1038:5\nnote: Run " +
    'with `RUST_BACKTRACE=1` environment variable to display a backtrace.\n',
  isPanicked: undefined
```

**Comment by divyenduz** [comment] 2020-01-09 17:02
@pantharshit00 Can you please re-confirm this?

**Comment by pantharshit00** [comment] 2020-01-11 16:09
Unable to reproduce now, closing

**Closed by pantharshit00** 2020-01-11 16:09 UTC
Labels: bug/1-repro-available, kind/bug
