### ISSUE TITLE
Error in migration engine - no current timer when using prisma2 migrate

### ISSUE THREAD

**Issue by AlexanderProd** [prisma/prisma2#1395] opened 2020-01-21 18:16 UTC
I'm using the latest release `2.0.0-preview020` and I'm getting the following error when running `prisma2 migrate save --experimental` .

```
Error in migration engine.
Reason: [src/libcore/option.rs:1185:5] no current timer
```

Report id 1254

**Comment by tarazena** [comment] 2020-01-21 21:23
Same in here.

**Comment by andresggarcia** [comment] 2020-01-21 22:29
Having exact same issue just after upgrading to `2.0.0-preview020`. Previous version with `lift` command worked just fine.

**Comment by naveen-bharathi** [comment] 2020-01-21 23:08
same here. Is there any temporary solution or workaround?

**Comment by andresggarcia** [comment] 2020-01-22 02:00
As a workaround, you could use the previous API for migrations as follows:
`npx prisma2@2.0.0-preview019 lift save`
`npx prisma2@2.0.0-preview019 lift up`

**Comment by tomhoule** [comment] 2020-01-22 09:59
I can't reproduce the issue - what operating system and what database are you using? It would also be helpful to have a sample schema where this happens.

**Comment by AlexanderProd** [comment] 2020-01-22 10:01
@tomhoule I'm on macOS and using a MySQL database. 

this is the schema I'm using.

```
datasource sqlite {
  url      = "mysql://****:*****@*****/*****"
  provider = "mysql"
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id        String   @id @default(cuid())
  createdAt DateTime @default(now())
  email     String   @unique
  name      String?
  phone     String?
  role      Role     @default(USER)
  posts     Post[]
}

model Post {
  id         String     @id @default(cuid())
  createdAt  DateTime   @default(now())
  updatedAt  DateTime   @updatedAt
  author     User
  title      String
  categories Category[]
  published  Boolean    @default(false)
}

model Category {
  id    String  @id @default(cuid())
  name  String
}

enum Role {
  USER
  ADMIN
}
```

**Comment by tomhoule** [comment] 2020-01-22 10:03
Thanks a lot :) still investigating

**Comment by tomhoule** [comment] 2020-01-22 10:04
Ok I managed to reproduce the crash, will post an update here as soon as it's fixed.

**Comment by tomhoule** [comment] 2020-01-22 10:46
I have a fix - PR: https://github.com/prisma/prisma-engine/pull/405

Will keep updating this issue until the fix is released.

**Comment by tomhoule** [comment] 2020-01-22 17:32
preview 20.1 is being released right now - I will close this issue, thanks for reporting the bug and please continue giving feedback when things don't work :)

**Closed by tomhoule** 2020-01-22 17:32 UTC
Labels: bug/2-confirmed, kind/bug, process/candidate, topic: binaries

**Comment by yovanoc** [comment] 2020-01-22 17:54
![image](https://user-images.githubusercontent.com/7302317/72919906-92ea7500-3d48-11ea-93c5-82bd2ce5f1fd.png)

The new preview fix this issue but let us with a new one ^^

**Comment by PhilippSpo** [comment] 2020-01-22 17:56
@yovanoc Yup I have the same issue.

**Comment by AlexanderProd** [comment] 2020-01-22 18:12
Same here.

**Comment by AlexanderProd** [comment] 2020-01-22 18:23
opened #1419
